[<AutoOpen>]
module PureScript_Control_Comonad_Store_Class

open System
open System.Collections.Generic

let Control_Comonad_Store_Class_lower  = (sharpurs_apply (box ((box Control_Comonad_Trans_Class_lower))) (box ((box Control_Comonad_Env_Trans_comonadTransEnvT))))

let Control_Comonad_Store_Class_ComonadStoreusd_Dict  = (box (fun (x: obj) -> (box x)))

let Control_Comonad_Store_Class_pos  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "pos" (unbox<Map<string, obj>> ((box v))))))))

let Control_Comonad_Store_Class_peek  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "peek" (unbox<Map<string, obj>> ((box v))))))))

let Control_Comonad_Store_Class_peeks  = (box (fun (dictComonadStore: obj) -> (box (fun (f: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Store_Class_peek))) (box ((box dictComonadStore)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box f)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Store_Class_pos))) (box ((box dictComonadStore)))))) (box ((box x)))))))))))) (box ((box x))))))))))

let Control_Comonad_Store_Class_seeks  = (box (fun (dictComonadStore: obj) -> (let duplicate = (sharpurs_apply (box ((box Control_Extend_duplicate))) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadStore)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))) in (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Store_Class_peeks))) (box ((box dictComonadStore)))))) (box ((box f))))))))) (box ((box duplicate)))))))))

let Control_Comonad_Store_Class_seek  = (box (fun (dictComonadStore: obj) -> (let duplicate = (sharpurs_apply (box ((box Control_Extend_duplicate))) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadStore)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))) in (box (fun (s: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Store_Class_peek))) (box ((box dictComonadStore)))))) (box ((box s))))))))) (box ((box duplicate)))))))))

let Control_Comonad_Store_Class_experiment  = (box (fun (dictComonadStore: obj) -> (let peek1 = (sharpurs_apply (box ((box Control_Comonad_Store_Class_peek))) (box ((box dictComonadStore)))) in (box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((box peek1)))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Store_Class_pos))) (box ((box dictComonadStore)))))) (box ((box x)))))))))))))))))))

let Control_Comonad_Store_Class_comonadStoreTracedT  = (box (fun (dictComonadStore: obj) -> (let pos1 = (sharpurs_apply (box ((box Control_Comonad_Store_Class_pos))) (box ((box dictComonadStore)))) in let Comonad0 = (sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadStore)))))) (box ((box Prim_undefined)))) in let comonadTracedT = (sharpurs_apply (box ((box Control_Comonad_Traced_Trans_comonadTracedT))) (box ((box Comonad0)))) in (box (fun (dictMonoid: obj) -> (let lower1 = (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Trans_Class_lower))) (box ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_comonadTransTracedT))) (box ((box dictMonoid))))))))) (box ((box Comonad0)))) in let comonadTracedT1 = (sharpurs_apply (box ((box comonadTracedT))) (box ((box dictMonoid)))) in (sharpurs_apply (box ((box Control_Comonad_Store_Class_ComonadStoreusd_Dict))) (box ((box ((Map.add "pos" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box pos1)))))) (box ((box lower1)))))) (Map.add "peek" (box ((box (fun (s: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Store_Class_peek))) (box ((box dictComonadStore)))))) (box ((box s))))))))) (box ((box lower1)))))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadTracedT1))))) Map.empty))))))))))))))

let Control_Comonad_Store_Class_comonadStoreStoreT  = (box (fun (dictComonad: obj) -> (let comonadStoreT = (sharpurs_apply (box ((box Control_Comonad_Store_Trans_comonadStoreT))) (box ((box dictComonad)))) in (sharpurs_apply (box ((box Control_Comonad_Store_Class_ComonadStoreusd_Dict))) (box ((box ((Map.add "pos" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, s) -> ((box s))))))) (Map.add "peek" (box ((box (fun (s: obj) -> (box (fun (v: obj) -> (match (((unbox ((box s))), (unbox ((box v))))) with | (s1, Data_Tuple_Tupleusd_Ctor(f, _)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad)))))) (box ((box f)))))) (box ((box s1)))))))))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadStoreT))))) Map.empty)))))))))))

let Control_Comonad_Store_Class_comonadStoreEnvT  = (box (fun (dictComonadStore: obj) -> (let Comonad0 = (sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadStore)))))) (box ((box Prim_undefined)))) in let lower1 = (sharpurs_apply (box ((box Control_Comonad_Store_Class_lower))) (box ((box Comonad0)))) in let comonadEnvT = (sharpurs_apply (box ((box Control_Comonad_Env_Trans_comonadEnvT))) (box ((box Comonad0)))) in (sharpurs_apply (box ((box Control_Comonad_Store_Class_ComonadStoreusd_Dict))) (box ((box ((Map.add "pos" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Comonad_Store_Class_pos))) (box ((box dictComonadStore))))))))) (box ((box lower1)))))) (Map.add "peek" (box ((box (fun (s: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Store_Class_peek))) (box ((box dictComonadStore)))))) (box ((box s))))))))) (box ((box lower1)))))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadEnvT))))) Map.empty)))))))))))
