[<AutoOpen>]
module PureScript_Control_Monad_Error_Class

open System
open System.Collections.Generic

let Control_Monad_Error_Class_MonadThrowusd_Dict  = (box (fun (x: obj) -> (box x)))

let Control_Monad_Error_Class_MonadErrorusd_Dict  = (box (fun (x: obj) -> (box x)))

let Control_Monad_Error_Class_throwError  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "throwError" (unbox<Map<string, obj>> ((box v))))))))

let Control_Monad_Error_Class_monadThrowMaybe  = (sharpurs_apply (box ((box Control_Monad_Error_Class_MonadThrowusd_Dict))) (box ((box ((Map.add "throwError" (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box Data_Maybe_Nothingusd_Ctor)))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_monadMaybe))))) Map.empty)))))))

let Control_Monad_Error_Class_monadThrowEither  = (sharpurs_apply (box ((box Control_Monad_Error_Class_MonadThrowusd_Dict))) (box ((box ((Map.add "throwError" (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box Data_Either_monadEither))))) Map.empty)))))))

let Control_Monad_Error_Class_monadThrowEffect  = (sharpurs_apply (box ((box Control_Monad_Error_Class_MonadThrowusd_Dict))) (box ((box ((Map.add "throwError" (box ((box Effect_Exception_throwException))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box Effect_monadEffect))))) Map.empty)))))))

let Control_Monad_Error_Class_monadErrorMaybe  = (sharpurs_apply (box ((box Control_Monad_Error_Class_MonadErrorusd_Dict))) (box ((box ((Map.add "catchError" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Maybe_Nothingusd_Ctor, f) -> ((sharpurs_apply (box ((box f))) (box ((box Data_Unit_unit))))) | (Data_Maybe_Justusd_Ctor(a), _) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box a)))))))))))) (Map.add "MonadThrow0" (box ((box (fun (usd__unused: obj) -> (box Control_Monad_Error_Class_monadThrowMaybe))))) Map.empty)))))))

let Control_Monad_Error_Class_monadErrorEither  = (sharpurs_apply (box ((box Control_Monad_Error_Class_MonadErrorusd_Dict))) (box ((box ((Map.add "catchError" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Either_Leftusd_Ctor(e), h) -> ((sharpurs_apply (box ((box h))) (box ((box e))))) | (Data_Either_Rightusd_Ctor(x), _) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((box x)))))))))))) (Map.add "MonadThrow0" (box ((box (fun (usd__unused: obj) -> (box Control_Monad_Error_Class_monadThrowEither))))) Map.empty)))))))

let Control_Monad_Error_Class_monadErrorEffect  = (sharpurs_apply (box ((box Control_Monad_Error_Class_MonadErrorusd_Dict))) (box ((box ((Map.add "catchError" (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((box Effect_Exception_catchException)))))) (Map.add "MonadThrow0" (box ((box (fun (usd__unused: obj) -> (box Control_Monad_Error_Class_monadThrowEffect))))) Map.empty)))))))

let Control_Monad_Error_Class_liftMaybe  = (box (fun (dictMonadThrow: obj) -> (let pure_var = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadThrow)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))) in (box (fun (error: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Error_Class_throwError))) (box ((box dictMonadThrow)))))) (box ((box error))))))))) (box ((box pure_var)))))))))

let Control_Monad_Error_Class_liftEither  = (box (fun (dictMonadThrow: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((sharpurs_apply (box ((box Control_Monad_Error_Class_throwError))) (box ((box dictMonadThrow))))))))) (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadThrow)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))))))

let Control_Monad_Error_Class_catchError  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "catchError" (unbox<Map<string, obj>> ((box v))))))))

let Control_Monad_Error_Class_catchJust  = (box (fun (dictMonadError: obj) -> (let MonadThrow0 = (sharpurs_apply (box ((Map.find "MonadThrow0" (unbox<Map<string, obj>> ((box dictMonadError)))))) (box ((box Prim_undefined)))) in (box (fun (p: obj) -> (box (fun (act: obj) -> (box (fun (handler: obj) -> (let handle = (box (fun (e: obj) -> (let v = (sharpurs_apply (box ((box p))) (box ((box e)))) in (match ((unbox ((box v)))) with | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Error_Class_throwError))) (box ((box MonadThrow0)))))) (box ((box e))))) | Data_Maybe_Justusd_Ctor(b) -> ((sharpurs_apply (box ((box handler))) (box ((box b))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Error_Class_catchError))) (box ((box dictMonadError)))))) (box ((box act)))))) (box ((box handle))))))))))))))

let Control_Monad_Error_Class_try  = (box (fun (dictMonadError: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "MonadThrow0" (unbox<Map<string, obj>> ((box dictMonadError)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let pure_var = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))) in (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Error_Class_catchError))) (box ((box dictMonadError)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))))) (box ((box a))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box pure_var)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))))))))))))

let Control_Monad_Error_Class_withResource  = (box (fun (dictMonadError: obj) -> (let MonadThrow0 = (sharpurs_apply (box ((Map.find "MonadThrow0" (unbox<Map<string, obj>> ((box dictMonadError)))))) (box ((box Prim_undefined)))) in let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadThrow0)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in let try1 = (sharpurs_apply (box ((box Control_Monad_Error_Class_try))) (box ((box dictMonadError)))) in let throwError1 = (sharpurs_apply (box ((box Control_Monad_Error_Class_throwError))) (box ((box MonadThrow0)))) in let pure_var = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))) in (box (fun (acquire: obj) -> (box (fun (release: obj) -> (box (fun (kleisli: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((box acquire)))))) (box ((box (fun (resource: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box try1)))))) (box ((sharpurs_apply (box ((box kleisli))) (box ((box resource)))))))))))) (box ((box (fun (result: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_discard))) (box ((box Control_Bind_discardUnit)))))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((box release))) (box ((box resource))))))))) (box ((box (fun (usd__unused: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((box throwError1)))))) (box ((box pure_var)))))) (box ((box result))))))))))))))))))))))))))))
