[<AutoOpen>]
module PureScript_Control_Comonad_Traced_Class

open System
open System.Collections.Generic

let Control_Comonad_Traced_Class_ComonadTracedusd_Dict  = (box (fun (x: obj) -> (box x)))

let Control_Comonad_Traced_Class_track  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "track" (unbox<Map<string, obj>> ((box v))))))))

let Control_Comonad_Traced_Class_tracks  = (box (fun (dictComonadTraced: obj) -> (let Comonad0 = (sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadTraced)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (w: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Traced_Class_track))) (box ((box dictComonadTraced)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box f)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box Comonad0)))))) (box ((box w)))))))))))) (box ((box w)))))))))))

let Control_Comonad_Traced_Class_lowerTrack  = (box (fun (dictComonadTrans: obj) -> (let lower = (sharpurs_apply (box ((box Control_Comonad_Trans_Class_lower))) (box ((box dictComonadTrans)))) in (box (fun (dictComonadTraced: obj) -> (let lower1 = (sharpurs_apply (box ((box lower))) (box ((sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadTraced)))))) (box ((box Prim_undefined))))))) in (box (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Traced_Class_track))) (box ((box dictComonadTraced)))))) (box ((box m))))))))) (box ((box lower1))))))))))))

let Control_Comonad_Traced_Class_lowerTrack1  = (sharpurs_apply (box ((box Control_Comonad_Traced_Class_lowerTrack))) (box ((box Control_Comonad_Store_Trans_comonadTransStoreT))))

let Control_Comonad_Traced_Class_lowerTrack2  = (sharpurs_apply (box ((box Control_Comonad_Traced_Class_lowerTrack))) (box ((box Control_Comonad_Trans_Class_comonadTransIdentityT))))

let Control_Comonad_Traced_Class_lowerTrack3  = (sharpurs_apply (box ((box Control_Comonad_Traced_Class_lowerTrack))) (box ((box Control_Comonad_Env_Trans_comonadTransEnvT))))

let Control_Comonad_Traced_Class_listens  = (box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, tr) -> ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_TracedT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box (fun (g: obj) -> (box (fun (t: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((box g))) (box ((box t))))))))) (box ((sharpurs_apply (box ((box f1))) (box ((box t)))))))))))))))) (box ((box tr)))))))))))))))

let Control_Comonad_Traced_Class_listen  = (box (fun (dictFunctor: obj) -> (box (fun (v: obj) -> (match ((unbox ((box v)))) with | tr -> ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_TracedT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box (fun (f: obj) -> (box (fun (t: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((box f))) (box ((box t))))))))) (box ((box t))))))))))))) (box ((box tr)))))))))))))

let Control_Comonad_Traced_Class_comonadTracedTracedT  = (box (fun (dictComonad: obj) -> (let comonadTracedT = (sharpurs_apply (box ((box Control_Comonad_Traced_Trans_comonadTracedT))) (box ((box dictComonad)))) in (box (fun (dictMonoid: obj) -> (let comonadTracedT1 = (sharpurs_apply (box ((box comonadTracedT))) (box ((box dictMonoid)))) in (sharpurs_apply (box ((box Control_Comonad_Traced_Class_ComonadTracedusd_Dict))) (box ((box ((Map.add "track" (box ((box (fun (t: obj) -> (box (fun (v: obj) -> (match (((unbox ((box t))), (unbox ((box v))))) with | (t1, tr) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad)))))) (box ((box tr)))))) (box ((box t1)))))))))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadTracedT1))))) Map.empty)))))))))))))

let Control_Comonad_Traced_Class_comonadTracedStoreT  = (box (fun (dictComonadTraced: obj) -> (let comonadStoreT = (sharpurs_apply (box ((box Control_Comonad_Store_Trans_comonadStoreT))) (box ((sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadTraced)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Comonad_Traced_Class_ComonadTracedusd_Dict))) (box ((box ((Map.add "track" (box ((sharpurs_apply (box ((box Control_Comonad_Traced_Class_lowerTrack1))) (box ((box dictComonadTraced)))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadStoreT))))) Map.empty))))))))))

let Control_Comonad_Traced_Class_comonadTracedIdentityT  = (box (fun (dictComonadTraced: obj) -> (let comonadIdentityT = (sharpurs_apply (box ((box Control_Monad_Identity_Trans_comonadIdentityT))) (box ((sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadTraced)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Comonad_Traced_Class_ComonadTracedusd_Dict))) (box ((box ((Map.add "track" (box ((sharpurs_apply (box ((box Control_Comonad_Traced_Class_lowerTrack2))) (box ((box dictComonadTraced)))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadIdentityT))))) Map.empty))))))))))

let Control_Comonad_Traced_Class_comonadTracedEnvT  = (box (fun (dictComonadTraced: obj) -> (let comonadEnvT = (sharpurs_apply (box ((box Control_Comonad_Env_Trans_comonadEnvT))) (box ((sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadTraced)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Comonad_Traced_Class_ComonadTracedusd_Dict))) (box ((box ((Map.add "track" (box ((sharpurs_apply (box ((box Control_Comonad_Traced_Class_lowerTrack3))) (box ((box dictComonadTraced)))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadEnvT))))) Map.empty))))))))))

let Control_Comonad_Traced_Class_censor  = (box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, tr) -> ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_TracedT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box f1)))))) (box ((box v1))))))))))) (box ((box tr)))))))))))))))
