[<AutoOpen>]
module PureScript_Control_Parallel

open System
open System.Collections.Generic

let Control_Parallel_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Control_Parallel_parTraverse_  = (box (fun (dictParallel: obj) -> (let sequential = (sharpurs_apply (box ((box Control_Parallel_Class_sequential))) (box ((box dictParallel)))) in let parallel = (sharpurs_apply (box ((box Control_Parallel_Class_parallel))) (box ((box dictParallel)))) in (box (fun (dictApplicative: obj) -> (box (fun (dictFoldable: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box sequential)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_traverse_))) (box ((box dictApplicative)))))) (box ((box dictFoldable)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box parallel)))))) (box ((box f)))))))))))))))))))

let Control_Parallel_parTraverse  = (box (fun (dictParallel: obj) -> (let sequential = (sharpurs_apply (box ((box Control_Parallel_Class_sequential))) (box ((box dictParallel)))) in let parallel = (sharpurs_apply (box ((box Control_Parallel_Class_parallel))) (box ((box dictParallel)))) in (box (fun (dictApplicative: obj) -> (box (fun (dictTraversable: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box sequential)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Traversable_traverse))) (box ((box dictTraversable)))))) (box ((box dictApplicative)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box parallel)))))) (box ((box f)))))))))))))))))))

let Control_Parallel_parSequence_  = (box (fun (dictParallel: obj) -> (box (fun (dictApplicative: obj) -> (box (fun (dictFoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Parallel_parTraverse_))) (box ((box dictParallel)))))) (box ((box dictApplicative)))))) (box ((box dictFoldable)))))) (box ((box Control_Parallel_identity))))))))))

let Control_Parallel_parSequence  = (box (fun (dictParallel: obj) -> (box (fun (dictApplicative: obj) -> (box (fun (dictTraversable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Parallel_parTraverse))) (box ((box dictParallel)))))) (box ((box dictApplicative)))))) (box ((box dictTraversable)))))) (box ((box Control_Parallel_identity))))))))))

let Control_Parallel_parOneOfMap  = (box (fun (dictParallel: obj) -> (let sequential = (sharpurs_apply (box ((box Control_Parallel_Class_sequential))) (box ((box dictParallel)))) in let parallel = (sharpurs_apply (box ((box Control_Parallel_Class_parallel))) (box ((box dictParallel)))) in (box (fun (dictAlternative: obj) -> (let Plus1 = (sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined)))) in (box (fun (dictFoldable: obj) -> (box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box sequential)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_oneOfMap))) (box ((box dictFoldable)))))) (box ((box Plus1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box parallel)))))) (box ((box f))))))))))))))))))))))

let Control_Parallel_parOneOf  = (box (fun (dictParallel: obj) -> (let sequential = (sharpurs_apply (box ((box Control_Parallel_Class_sequential))) (box ((box dictParallel)))) in let parallel = (sharpurs_apply (box ((box Control_Parallel_Class_parallel))) (box ((box dictParallel)))) in (box (fun (dictAlternative: obj) -> (let Plus1 = (sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined)))) in (box (fun (dictFoldable: obj) -> (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box sequential)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_oneOfMap))) (box ((box dictFoldable)))))) (box ((box Plus1)))))) (box ((box parallel)))))))))))))))))

let Control_Parallel_parApply  = (box (fun (dictParallel: obj) -> (let Apply1 = (sharpurs_apply (box ((Map.find "Apply1" (unbox<Map<string, obj>> ((box dictParallel)))))) (box ((box Prim_undefined)))) in (box (fun (mf: obj) -> (box (fun (ma: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Parallel_Class_sequential))) (box ((box dictParallel)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Apply1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Parallel_Class_parallel))) (box ((box dictParallel)))))) (box ((box mf))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Parallel_Class_parallel))) (box ((box dictParallel)))))) (box ((box ma)))))))))))))))))
