[<AutoOpen>]
module PureScript_Data_Functor_Joker

open System
open System.Collections.Generic

let Data_Functor_Joker_Joker  = (box (fun (x: obj) -> (box x)))

let Data_Functor_Joker_showJoker  = (box (fun (dictShow: obj) -> (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | x -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(Joker ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow)))))) (box ((box x))))))))) (box ((box ")"))))))))))))) Map.empty))))))))

let Data_Functor_Joker_profunctorJoker  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Profunctor_Profunctorusd_Dict))) (box ((box ((Map.add "dimap" (box ((box (fun (v: obj) -> (box (fun (g: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box g))), (unbox ((box v1))))) with | (_, g1, a) -> ((sharpurs_apply (box ((box Data_Functor_Joker_Joker))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box g1)))))) (box ((box a))))))))))))))))) Map.empty))))))))

let Data_Functor_Joker_ordJoker  = (box (fun (dictOrd: obj) -> (box dictOrd)))

let Data_Functor_Joker_newtypeJoker  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Data_Functor_Joker_hoistJoker  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, a) -> ((sharpurs_apply (box ((box Data_Functor_Joker_Joker))) (box ((sharpurs_apply (box ((box f1))) (box ((box a)))))))))))))

let Data_Functor_Joker_functorJoker  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, a) -> ((sharpurs_apply (box ((box Data_Functor_Joker_Joker))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f1)))))) (box ((box a))))))))))))))) Map.empty))))))))

let Data_Functor_Joker_eqJoker  = (box (fun (dictEq: obj) -> (box dictEq)))

let Data_Functor_Joker_choiceJoker  = (box (fun (dictFunctor: obj) -> (let profunctorJoker1 = (sharpurs_apply (box ((box Data_Functor_Joker_profunctorJoker))) (box ((box dictFunctor)))) in (sharpurs_apply (box ((box Data_Profunctor_Choice_Choiceusd_Dict))) (box ((box ((Map.add "left" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Functor_Joker_Joker)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))) (box ((box f))))))))))))) (Map.add "right" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Functor_Joker_Joker)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))))) (box ((box f))))))))))))) (Map.add "Profunctor0" (box ((box (fun (usd__unused: obj) -> (box profunctorJoker1))))) Map.empty)))))))))))

let Data_Functor_Joker_bifunctorJoker  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Bifunctor_Bifunctorusd_Dict))) (box ((box ((Map.add "bimap" (box ((box (fun (v: obj) -> (box (fun (g: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box g))), (unbox ((box v1))))) with | (_, g1, a) -> ((sharpurs_apply (box ((box Data_Functor_Joker_Joker))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box g1)))))) (box ((box a))))))))))))))))) Map.empty))))))))

let Data_Functor_Joker_biapplyJoker  = (box (fun (dictApply: obj) -> (let bifunctorJoker1 = (sharpurs_apply (box ((box Data_Functor_Joker_bifunctorJoker))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Biapply_Biapplyusd_Dict))) (box ((box ((Map.add "biapply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (fg, xy) -> ((sharpurs_apply (box ((box Data_Functor_Joker_Joker))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box dictApply)))))) (box ((box fg)))))) (box ((box xy))))))))))))))) (Map.add "Bifunctor0" (box ((box (fun (usd__unused: obj) -> (box bifunctorJoker1))))) Map.empty))))))))))

let Data_Functor_Joker_biapplicativeJoker  = (box (fun (dictApplicative: obj) -> (let biapplyJoker1 = (sharpurs_apply (box ((box Data_Functor_Joker_biapplyJoker))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Biapplicative_Biapplicativeusd_Dict))) (box ((box ((Map.add "bipure" (box ((box (fun (v: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((box Data_Functor_Joker_Joker))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))))) (box ((box b))))))))))))) (Map.add "Biapply0" (box ((box (fun (usd__unused: obj) -> (box biapplyJoker1))))) Map.empty))))))))))

let Data_Functor_Joker_applyJoker  = (box (fun (dictApply: obj) -> (let functorJoker1 = (sharpurs_apply (box ((box Data_Functor_Joker_functorJoker))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, g) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Functor_Joker_Joker)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box dictApply)))))) (box ((box f)))))) (box ((box g))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorJoker1))))) Map.empty))))))))))

let Data_Functor_Joker_bindJoker  = (box (fun (dictBind: obj) -> (let applyJoker1 = (sharpurs_apply (box ((box Data_Functor_Joker_applyJoker))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictBind)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((box (fun (v: obj) -> (box (fun (amb: obj) -> (match (((unbox ((box v))), (unbox ((box amb))))) with | (ma, amb1) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Functor_Joker_Joker)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box dictBind)))))) (box ((box ma)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box amb1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_un))) (box ((box Prim_undefined)))))) (box ((box Data_Functor_Joker_Joker))))))))))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyJoker1))))) Map.empty))))))))))

let Data_Functor_Joker_applicativeJoker  = (box (fun (dictApplicative: obj) -> (let applyJoker1 = (sharpurs_apply (box ((box Data_Functor_Joker_applyJoker))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Functor_Joker_Joker)))))) (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyJoker1))))) Map.empty))))))))))

let Data_Functor_Joker_monadJoker  = (box (fun (dictMonad: obj) -> (let applicativeJoker1 = (sharpurs_apply (box ((box Data_Functor_Joker_applicativeJoker))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in let bindJoker1 = (sharpurs_apply (box ((box Data_Functor_Joker_bindJoker))) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box applicativeJoker1))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box bindJoker1))))) Map.empty))))))))))
