[<AutoOpen>]
module PureScript_Data_Array_ST_Iterator

open System
open System.Collections.Generic

type Data_Array_ST_Iterator_Iterator =
  | Data_Array_ST_Iterator_Iteratorusd_Ctor of obj * obj

let Data_Array_ST_Iterator_not  = (sharpurs_apply (box ((box Data_HeytingAlgebra_not))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean))))

let Data_Array_ST_Iterator_void  = (sharpurs_apply (box ((box Data_Functor_void))) (box ((box Control_Monad_ST_Internal_functorST))))

let Data_Array_ST_Iterator_void1  = (sharpurs_apply (box ((box Data_Functor_void))) (box ((box Control_Monad_ST_Internal_functorST))))

let Data_Array_ST_Iterator_Iterator  = (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Array_ST_Iterator_Iteratorusd_Ctor(usd__arg1, usd__arg2)))))))

let Data_Array_ST_Iterator_peek  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Array_ST_Iterator_Iteratorusd_Ctor(f, currentIndex) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Control_Monad_ST_Internal_bindST)))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_read))) (box ((box currentIndex))))))))) (box ((box (fun (i: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Control_Monad_ST_Internal_applicativeST)))))) (box ((sharpurs_apply (box ((box f))) (box ((box i))))))))))))))))

let Data_Array_ST_Iterator_next  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Array_ST_Iterator_Iteratorusd_Ctor(f, currentIndex) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Control_Monad_ST_Internal_bindST)))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_read))) (box ((box currentIndex))))))))) (box ((box (fun (i: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Control_Monad_ST_Internal_bindST)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_modify))) (box ((box (fun (v1: obj) -> (box ((unbox<int> (box ((box v1)))) + (unbox<int> (box ((box 1))))))))))))) (box ((box currentIndex))))))))) (box ((box (fun (usd__unused: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Control_Monad_ST_Internal_applicativeST)))))) (box ((sharpurs_apply (box ((box f))) (box ((box i)))))))))))))))))))))

let Data_Array_ST_Iterator_pushWhile  = (box (fun (p: obj) -> (box (fun (iter: obj) -> (box (fun (array: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Control_Monad_ST_Internal_bindST)))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_new))) (box ((box false))))))))) (box ((box (fun (break: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_while))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Control_Monad_ST_Internal_functorST)))))) (box ((box Data_Array_ST_Iterator_not)))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_read))) (box ((box break)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Control_Monad_ST_Internal_bindST)))))) (box ((sharpurs_apply (box ((box Data_Array_ST_Iterator_peek))) (box ((box iter))))))))) (box ((box (fun (mx: obj) -> (match ((unbox ((box mx)))) with | Data_Maybe_Justusd_Ctor(x) when (unbox (sharpurs_apply (box ((box p))) (box ((box x))))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Control_Monad_ST_Internal_bindST)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Array_ST_push))) (box ((box x)))))) (box ((box array))))))))) (box ((box (fun (usd__unused: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Array_ST_Iterator_void)))))) (box ((sharpurs_apply (box ((box Data_Array_ST_Iterator_next))) (box ((box iter))))))))))))) | _ -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Array_ST_Iterator_void1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_write))) (box ((box true)))))) (box ((box break))))))))))))))))))))))))))))

let Data_Array_ST_Iterator_pushAll  = (sharpurs_apply (box ((box Data_Array_ST_Iterator_pushWhile))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box true)))))))

let Data_Array_ST_Iterator_iterator  = (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Control_Monad_ST_Internal_functorST)))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Array_ST_Iterator_Iteratorusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box f))))))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_new))) (box ((box 0)))))))))

let Data_Array_ST_Iterator_iterate  = (box (fun (iter: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Control_Monad_ST_Internal_bindST)))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_new))) (box ((box false))))))))) (box ((box (fun (break: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_while))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Control_Monad_ST_Internal_functorST)))))) (box ((box Data_Array_ST_Iterator_not)))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_read))) (box ((box break)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Control_Monad_ST_Internal_bindST)))))) (box ((sharpurs_apply (box ((box Data_Array_ST_Iterator_next))) (box ((box iter))))))))) (box ((box (fun (mx: obj) -> (match ((unbox ((box mx)))) with | Data_Maybe_Justusd_Ctor(x) -> ((sharpurs_apply (box ((box f))) (box ((box x))))) | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Array_ST_Iterator_void1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_ST_Internal_write))) (box ((box true)))))) (box ((box break))))))))))))))))))))))))))

let Data_Array_ST_Iterator_exhausted  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Control_Monad_ST_Internal_functorST)))))) (box ((box Data_Maybe_isNothing))))))))) (box ((box Data_Array_ST_Iterator_peek))))
