[<AutoOpen>]
module PureScript_Data_Decide

open System
open System.Collections.Generic

let Data_Decide_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Decide_Decideusd_Dict  = (box (fun (x: obj) -> (box x)))

let Data_Decide_choosePredicate  = (sharpurs_apply (box ((box Data_Decide_Decideusd_Dict))) (box ((box ((Map.add "choose" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, g, h) -> ((sharpurs_apply (box ((box Data_Predicate_Predicate))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((box g)))))) (box ((box h))))))))) (box ((box f1))))))))))))))))) (Map.add "Divide0" (box ((box (fun (usd__unused: obj) -> (box Data_Divide_dividePredicate))))) Map.empty)))))))

let Data_Decide_chooseOp  = (box (fun (dictSemigroup: obj) -> (let divideOp = (sharpurs_apply (box ((box Data_Divide_divideOp))) (box ((box dictSemigroup)))) in (sharpurs_apply (box ((box Data_Decide_Decideusd_Dict))) (box ((box ((Map.add "choose" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, g, h) -> ((sharpurs_apply (box ((box Data_Op_Op))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((box g)))))) (box ((box h))))))))) (box ((box f1))))))))))))))))) (Map.add "Divide0" (box ((box (fun (usd__unused: obj) -> (box divideOp))))) Map.empty))))))))))

let Data_Decide_chooseEquivalence  = (sharpurs_apply (box ((box Data_Decide_Decideusd_Dict))) (box ((box ((Map.add "choose" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, g, h) -> ((sharpurs_apply (box ((box Data_Equivalence_Equivalence))) (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (let v2 = (sharpurs_apply (box ((box f1))) (box ((box a)))) in (match ((unbox ((box v2)))) with | Data_Either_Leftusd_Ctor(c) -> ((let v3 = (sharpurs_apply (box ((box f1))) (box ((box b)))) in (match ((unbox ((box v3)))) with | Data_Either_Leftusd_Ctor(d) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box g))) (box ((box c)))))) (box ((box d))))) | Data_Either_Rightusd_Ctor(_) -> ((box false))))) | Data_Either_Rightusd_Ctor(c) -> ((let v3 = (sharpurs_apply (box ((box f1))) (box ((box b)))) in (match ((unbox ((box v3)))) with | Data_Either_Leftusd_Ctor(_) -> ((box false)) | Data_Either_Rightusd_Ctor(d) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box h))) (box ((box c)))))) (box ((box d))))))))))))))))))))))))))) (Map.add "Divide0" (box ((box (fun (usd__unused: obj) -> (box Data_Divide_divideEquivalence))))) Map.empty)))))))

let Data_Decide_chooseComparison  = (sharpurs_apply (box ((box Data_Decide_Decideusd_Dict))) (box ((box ((Map.add "choose" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, g, h) -> ((sharpurs_apply (box ((box Data_Comparison_Comparison))) (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (let v2 = (sharpurs_apply (box ((box f1))) (box ((box a)))) in (match ((unbox ((box v2)))) with | Data_Either_Leftusd_Ctor(c) -> ((let v3 = (sharpurs_apply (box ((box f1))) (box ((box b)))) in (match ((unbox ((box v3)))) with | Data_Either_Leftusd_Ctor(d) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box g))) (box ((box c)))))) (box ((box d))))) | Data_Either_Rightusd_Ctor(_) -> ((box Data_Ordering_LTusd_Ctor))))) | Data_Either_Rightusd_Ctor(c) -> ((let v3 = (sharpurs_apply (box ((box f1))) (box ((box b)))) in (match ((unbox ((box v3)))) with | Data_Either_Leftusd_Ctor(_) -> ((box Data_Ordering_GTusd_Ctor)) | Data_Either_Rightusd_Ctor(d) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box h))) (box ((box c)))))) (box ((box d))))))))))))))))))))))))))) (Map.add "Divide0" (box ((box (fun (usd__unused: obj) -> (box Data_Divide_divideComparison))))) Map.empty)))))))

let Data_Decide_choose  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "choose" (unbox<Map<string, obj>> ((box v))))))))

let Data_Decide_chosen  = (box (fun (dictDecide: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Decide_choose))) (box ((box dictDecide)))))) (box ((box Data_Decide_identity))))))
