[<AutoOpen>]
module PureScript_Data_Semigroup_Traversable

open System
open System.Collections.Generic

let Data_Semigroup_Traversable_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Semigroup_Traversable_Traversable1usd_Dict  = (box (fun (x: obj) -> (box x)))

let Data_Semigroup_Traversable_traverse1  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "traverse1" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semigroup_Traversable_traversableTuple  = (sharpurs_apply (box ((box Data_Semigroup_Traversable_Traversable1usd_Dict))) (box ((box ((Map.add "traverse1" (box ((box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_Tuple_Tupleusd_Ctor(x, y)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((box f1))) (box ((box y)))))))))))))))))) (Map.add "sequence1" (box ((box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(x, y) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x))))))))) (box ((box y))))))))))))) (Map.add "Foldable10" (box ((box (fun (usd__unused: obj) -> (box Data_Semigroup_Foldable_foldableTuple))))) (Map.add "Traversable1" (box ((box (fun (usd__unused: obj) -> (box Data_Traversable_traversableTuple))))) Map.empty)))))))))

let Data_Semigroup_Traversable_traversableIdentity  = (sharpurs_apply (box ((box Data_Semigroup_Traversable_Traversable1usd_Dict))) (box ((box ((Map.add "traverse1" (box ((box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_Identity_Identity)))))) (box ((sharpurs_apply (box ((box f1))) (box ((box x)))))))))))))))))) (Map.add "sequence1" (box ((box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in (box (fun (v: obj) -> (match ((unbox ((box v)))) with | x -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_Identity_Identity)))))) (box ((box x))))))))))))) (Map.add "Foldable10" (box ((box (fun (usd__unused: obj) -> (box Data_Semigroup_Foldable_foldableIdentity))))) (Map.add "Traversable1" (box ((box (fun (usd__unused: obj) -> (box Data_Traversable_traversableIdentity))))) Map.empty)))))))))

let Data_Semigroup_Traversable_sequence1Default  = (box (fun (dictTraversable1: obj) -> (box (fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Traversable_traverse1))) (box ((box dictTraversable1)))))) (box ((box dictApply)))))) (box ((box Data_Semigroup_Traversable_identity))))))))

let rec Data_Semigroup_Traversable_traversableDual : obj = ((sharpurs_apply (box ((box Data_Semigroup_Traversable_Traversable1usd_Dict))) (box ((box ((Map.add "traverse1" (box ((box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_Monoid_Dual_Dual)))))) (box ((sharpurs_apply (box ((box f1))) (box ((box x)))))))))))))))))) (Map.add "sequence1" (box ((box (fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Traversable_sequence1Default))) (box ((box Data_Semigroup_Traversable_traversableDual)))))) (box ((box dictApply)))))))) (Map.add "Foldable10" (box ((box (fun (usd__unused: obj) -> (box Data_Semigroup_Foldable_foldableDual))))) (Map.add "Traversable1" (box ((box (fun (usd__unused: obj) -> (box Data_Traversable_traversableDual))))) Map.empty))))))))))


let rec Data_Semigroup_Traversable_traversableMultiplicative : obj = ((sharpurs_apply (box ((box Data_Semigroup_Traversable_Traversable1usd_Dict))) (box ((box ((Map.add "traverse1" (box ((box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_Monoid_Multiplicative_Multiplicative)))))) (box ((sharpurs_apply (box ((box f1))) (box ((box x)))))))))))))))))) (Map.add "sequence1" (box ((box (fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Traversable_sequence1Default))) (box ((box Data_Semigroup_Traversable_traversableMultiplicative)))))) (box ((box dictApply)))))))) (Map.add "Foldable10" (box ((box (fun (usd__unused: obj) -> (box Data_Semigroup_Foldable_foldableMultiplicative))))) (Map.add "Traversable1" (box ((box (fun (usd__unused: obj) -> (box Data_Traversable_traversableMultiplicative))))) Map.empty))))))))))


let Data_Semigroup_Traversable_sequence1  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "sequence1" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semigroup_Traversable_traverse1Default  = (box (fun (dictTraversable1: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Traversable1" (unbox<Map<string, obj>> ((box dictTraversable1)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (dictApply: obj) -> (box (fun (f: obj) -> (box (fun (ta: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Traversable_sequence1))) (box ((box dictTraversable1)))))) (box ((box dictApply)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box f)))))) (box ((box ta))))))))))))))))
