[<AutoOpen>]
module PureScript_Data_List_Lazy_NonEmpty

open System
open System.Collections.Generic

let Data_List_Lazy_NonEmpty_uncons  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | nel -> ((let v1 = (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box nel)))) in (match ((unbox ((box v1)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((box ((Map.add "head" (box ((box x))) (Map.add "tail" (box ((box xs))) Map.empty)))))))))))

let Data_List_Lazy_NonEmpty_toList  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | nel -> ((let v1 = (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box nel)))) in (match ((unbox ((box v1)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((box xs)))))))))))

let Data_List_Lazy_NonEmpty_toUnfoldable  = (box (fun (dictUnfoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Unfoldable_unfoldr))) (box ((box dictUnfoldable)))))) (box ((box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box (fun (rec_var: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((Map.find "head" (unbox<Map<string, obj>> ((box rec_var))))))))) (box ((Map.find "tail" (unbox<Map<string, obj>> ((box rec_var)))))))))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box xs))))))))))))))))) (box ((box Data_List_Lazy_NonEmpty_toList))))))

let Data_List_Lazy_NonEmpty_tail  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | nel -> ((let v1 = (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box nel)))) in (match ((unbox ((box v1)))) with | Data_NonEmpty_NonEmptyusd_Ctor(_, xs) -> ((box xs))))))))

let Data_List_Lazy_NonEmpty_singleton  = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Data_List_Lazy_Types_applicativeNonEmptyList))))

let Data_List_Lazy_NonEmpty_repeat  = (box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_List_Lazy_Types_NonEmptyList)))))) (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_repeat))) (box ((box x)))))))))))))))))

let Data_List_Lazy_NonEmpty_length  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | nel -> ((let v1 = (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box nel)))) in (match ((unbox ((box v1)))) with | Data_NonEmpty_NonEmptyusd_Ctor(_, xs) -> ((box ((unbox<int> (box ((box 1)))) + (unbox<int> (box ((sharpurs_apply (box ((box Data_List_Lazy_length))) (box ((box xs))))))))))))))))

let Data_List_Lazy_NonEmpty_last  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | nel -> ((let v1 = (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box nel)))) in (match ((unbox ((box v1)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_fromMaybe))) (box ((box x)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_last))) (box ((box xs))))))))))))))

let Data_List_Lazy_NonEmpty_iterate  = (box (fun (f: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_List_Lazy_Types_NonEmptyList)))))) (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_iterate))) (box ((box f)))))) (box ((sharpurs_apply (box ((box f))) (box ((box x))))))))))))))))))))))

let Data_List_Lazy_NonEmpty_init  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | nel -> ((let v1 = (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box nel)))) in (match ((unbox ((box v1)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe))) (box ((box Data_List_Lazy_Types_nil)))))) (box ((box (fun (v2: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((box v2))))))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_init))) (box ((box xs))))))))))))))

let Data_List_Lazy_NonEmpty_head  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | nel -> ((let v1 = (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box nel)))) in (match ((unbox ((box v1)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, _) -> ((box x))))))))

let Data_List_Lazy_NonEmpty_fromList  = (box (fun (l: obj) -> (let v = (sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box l)))) in (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((box Data_Maybe_Nothingusd_Ctor)) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_NonEmptyList))) (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs))))))))))))))))))))

let Data_List_Lazy_NonEmpty_fromFoldable  = (box (fun (dictFoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_NonEmpty_fromList)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_fromFoldable))) (box ((box dictFoldable)))))))))

let Data_List_Lazy_NonEmpty_cons  = (box (fun (y: obj) -> (box (fun (v: obj) -> (match (((unbox ((box y))), (unbox ((box v))))) with | (y1, nel) -> ((sharpurs_apply (box ((box Data_List_Lazy_Types_NonEmptyList))) (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v1: obj) -> (let v2 = (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box nel)))) in (match ((unbox ((box v2)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((box xs))))))))))))))))))))))))

let Data_List_Lazy_NonEmpty_concatMap  = (sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Data_List_Lazy_Types_bindNonEmptyList)))))))

let Data_List_Lazy_NonEmpty_appendFoldable  = (box (fun (dictFoldable: obj) -> (box (fun (nel: obj) -> (box (fun (ys: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_Types_NonEmptyList))) (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_NonEmpty_head))) (box ((box nel))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_List_Lazy_Types_semigroupList)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_NonEmpty_tail))) (box ((box nel))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_fromFoldable))) (box ((box dictFoldable)))))) (box ((box ys))))))))))))))))))))))))
