[<AutoOpen>]
module PureScript_Data_Divide

open System
open System.Collections.Generic

let Data_Divide_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Divide_Divideusd_Dict  = (box (fun (x: obj) -> (box x)))

let Data_Divide_dividePredicate  = (sharpurs_apply (box ((box Data_Divide_Divideusd_Dict))) (box ((box ((Map.add "divide" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, g, h) -> ((sharpurs_apply (box ((box Data_Predicate_Predicate))) (box ((box (fun (a: obj) -> (let v2 = (sharpurs_apply (box ((box f1))) (box ((box a)))) in (match ((unbox ((box v2)))) with | Data_Tuple_Tupleusd_Ctor(b, c) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_HeytingAlgebra_conj))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean)))))) (box ((sharpurs_apply (box ((box g))) (box ((box b))))))))) (box ((sharpurs_apply (box ((box h))) (box ((box c))))))))))))))))))))))))) (Map.add "Contravariant0" (box ((box (fun (usd__unused: obj) -> (box Data_Predicate_contravariantPredicate))))) Map.empty)))))))

let Data_Divide_divideOp  = (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((box Data_Divide_Divideusd_Dict))) (box ((box ((Map.add "divide" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, g, h) -> ((sharpurs_apply (box ((box Data_Op_Op))) (box ((box (fun (a: obj) -> (let v2 = (sharpurs_apply (box ((box f1))) (box ((box a)))) in (match ((unbox ((box v2)))) with | Data_Tuple_Tupleusd_Ctor(b, c) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))))) (box ((sharpurs_apply (box ((box g))) (box ((box b))))))))) (box ((sharpurs_apply (box ((box h))) (box ((box c))))))))))))))))))))))))) (Map.add "Contravariant0" (box ((box (fun (usd__unused: obj) -> (box Data_Op_contravariantOp))))) Map.empty)))))))))

let Data_Divide_divideEquivalence  = (sharpurs_apply (box ((box Data_Divide_Divideusd_Dict))) (box ((box ((Map.add "divide" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, g, h) -> ((sharpurs_apply (box ((box Data_Equivalence_Equivalence))) (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (let v2 = (sharpurs_apply (box ((box f1))) (box ((box a)))) in (match ((unbox ((box v2)))) with | Data_Tuple_Tupleusd_Ctor(a_prime, a_prime_prime) -> ((let v3 = (sharpurs_apply (box ((box f1))) (box ((box b)))) in (match ((unbox ((box v3)))) with | Data_Tuple_Tupleusd_Ctor(b_prime, b_prime_prime) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_HeytingAlgebra_conj))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box g))) (box ((box a_prime)))))) (box ((box b_prime))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box h))) (box ((box a_prime_prime)))))) (box ((box b_prime_prime)))))))))))))))))))))))))))))) (Map.add "Contravariant0" (box ((box (fun (usd__unused: obj) -> (box Data_Equivalence_contravariantEquivalence))))) Map.empty)))))))

let Data_Divide_divideComparison  = (sharpurs_apply (box ((box Data_Divide_Divideusd_Dict))) (box ((box ((Map.add "divide" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, g, h) -> ((sharpurs_apply (box ((box Data_Comparison_Comparison))) (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (let v2 = (sharpurs_apply (box ((box f1))) (box ((box a)))) in (match ((unbox ((box v2)))) with | Data_Tuple_Tupleusd_Ctor(a_prime, a_prime_prime) -> ((let v3 = (sharpurs_apply (box ((box f1))) (box ((box b)))) in (match ((unbox ((box v3)))) with | Data_Tuple_Tupleusd_Ctor(b_prime, b_prime_prime) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Ordering_semigroupOrdering)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box g))) (box ((box a_prime)))))) (box ((box b_prime))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box h))) (box ((box a_prime_prime)))))) (box ((box b_prime_prime)))))))))))))))))))))))))))))) (Map.add "Contravariant0" (box ((box (fun (usd__unused: obj) -> (box Data_Comparison_contravariantComparison))))) Map.empty)))))))

let Data_Divide_divide  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "divide" (unbox<Map<string, obj>> ((box v))))))))

let Data_Divide_divided  = (box (fun (dictDivide: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Divide_divide))) (box ((box dictDivide)))))) (box ((box Data_Divide_identity))))))
