[<AutoOpen>]
module PureScript_Data_Date_Gen

open System
open System.Collections.Generic

let Data_Date_Gen_bottom  = (sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Data_Date_Component_boundedMonth))))

let Data_Date_Gen_bottom1  = (sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Data_Date_Component_boundedDay))))

let Data_Date_Gen_genDate  = (box (fun (dictMonadGen: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let pure_var = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((box Data_Date_Component_Gen_genYear))) (box ((box dictMonadGen))))))))) (box ((box (fun (year: obj) -> (let maxDays = (match ((unbox ((sharpurs_apply (box ((box Data_Date_isLeapYear))) (box ((box year))))))) with | LitBool true () -> ((box 365)) | _ -> ((box 364))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Time_Duration_Days)))))) (box ((box Data_Int_toNumber))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 0)))))) (box ((box maxDays)))))))))))) (box ((box (fun (days: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box pure_var)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Partial_Unsafe_unsafePartial)))))) (box ((box (fun (usd__unused: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_fromJust))) (box ((box Prim_undefined)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Data_Maybe_bindMaybe)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Date_exactDate))) (box ((box year)))))) (box ((box Data_Date_Gen_bottom)))))) (box ((box Data_Date_Gen_bottom1))))))))) (box ((box (fun (janFirst: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Date_adjust))) (box ((box days)))))) (box ((box janFirst))))))))))))))))))))))))))))))))))
