[<AutoOpen>]
module PureScript_Data_Lazy

open System
open System.Collections.Generic

module Data_Lazy_FFI =
    open System
    
    let defer = fun (thunk: obj) ->
        let l = lazy (sharpurs_apply thunk undefined)
        box l
    
    let force = fun (l: obj) ->
        let lazyObj = unbox<Lazy<obj>> l
        lazyObj.Force()
    

let Data_Lazy_defer = box (Data_Lazy_FFI.``defer``)
let Data_Lazy_force = box (Data_Lazy_FFI.``force``)


let Data_Lazy_showLazy  = (box (fun (dictShow: obj) -> (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(defer \\_ -> ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box x)))))))))))) (box ((box ")"))))))))))) Map.empty))))))))

let Data_Lazy_semiringLazy  = (box (fun (dictSemiring: obj) -> (sharpurs_apply (box ((box Data_Semiring_Semiringusd_Dict))) (box ((box ((Map.add "add" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_add))) (box ((box dictSemiring)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box b)))))))))))))))))) (Map.add "zero" (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_Semiring_zero))) (box ((box dictSemiring))))))))))) (Map.add "mul" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_mul))) (box ((box dictSemiring)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box b)))))))))))))))))) (Map.add "one" (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_Semiring_one))) (box ((box dictSemiring))))))))))) Map.empty)))))))))))

let Data_Lazy_semigroupLazy  = (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((box Data_Semigroup_Semigroupusd_Dict))) (box ((box ((Map.add "append" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box b)))))))))))))))))) Map.empty))))))))

let Data_Lazy_ringLazy  = (box (fun (dictRing: obj) -> (let semiringLazy1 = (sharpurs_apply (box ((box Data_Lazy_semiringLazy))) (box ((sharpurs_apply (box ((Map.find "Semiring0" (unbox<Map<string, obj>> ((box dictRing)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ring_Ringusd_Dict))) (box ((box ((Map.add "sub" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ring_sub))) (box ((box dictRing)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box b)))))))))))))))))) (Map.add "Semiring0" (box ((box (fun (usd__unused: obj) -> (box semiringLazy1))))) Map.empty))))))))))

let Data_Lazy_monoidLazy  = (box (fun (dictMonoid: obj) -> (let semigroupLazy1 = (sharpurs_apply (box ((box Data_Lazy_semigroupLazy))) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid))))))))))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box semigroupLazy1))))) Map.empty))))))))))

let Data_Lazy_lazyLazy  = (sharpurs_apply (box ((box Control_Lazy_Lazyusd_Dict))) (box ((box ((Map.add "defer" (box ((box (fun (f: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_Lazy_force))) (box ((sharpurs_apply (box ((box f))) (box ((box Data_Unit_unit)))))))))))))))) Map.empty))))))

let Data_Lazy_functorLazy  = (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l)))))))))))))))))) Map.empty))))))

let Data_Lazy_map  = (sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy))))

let Data_Lazy_functorWithIndexLazy  = (sharpurs_apply (box ((box Data_FunctorWithIndex_FunctorWithIndexusd_Dict))) (box ((box ((Map.add "mapWithIndex" (box ((box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Lazy_map)))))) (box ((sharpurs_apply (box ((box f))) (box ((box Data_Unit_unit))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_functorLazy))))) Map.empty)))))))

let Data_Lazy_invariantLazy  = (sharpurs_apply (box ((box Data_Functor_Invariant_Invariantusd_Dict))) (box ((box ((Map.add "imap" (box ((sharpurs_apply (box ((box Data_Functor_Invariant_imapF))) (box ((box Data_Lazy_functorLazy)))))) Map.empty))))))

let Data_Lazy_foldableLazy  = (sharpurs_apply (box ((box Data_Foldable_Foldableusd_Dict))) (box ((box ((Map.add "foldr" (box ((box (fun (f: obj) -> (box (fun (z: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l))))))))) (box ((box z)))))))))))) (Map.add "foldl" (box ((box (fun (f: obj) -> (box (fun (z: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box z)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l))))))))))))))) (Map.add "foldMap" (box ((box (fun (dictMonoid: obj) -> (box (fun (f: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l))))))))))))))) Map.empty))))))))

let Data_Lazy_foldr  = (sharpurs_apply (box ((box Data_Foldable_foldr))) (box ((box Data_Lazy_foldableLazy))))

let Data_Lazy_foldl  = (sharpurs_apply (box ((box Data_Foldable_foldl))) (box ((box Data_Lazy_foldableLazy))))

let Data_Lazy_foldMap  = (sharpurs_apply (box ((box Data_Foldable_foldMap))) (box ((box Data_Lazy_foldableLazy))))

let Data_Lazy_foldableWithIndexLazy  = (sharpurs_apply (box ((box Data_FoldableWithIndex_FoldableWithIndexusd_Dict))) (box ((box ((Map.add "foldrWithIndex" (box ((box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Lazy_foldr)))))) (box ((sharpurs_apply (box ((box f))) (box ((box Data_Unit_unit))))))))))) (Map.add "foldlWithIndex" (box ((box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Lazy_foldl)))))) (box ((sharpurs_apply (box ((box f))) (box ((box Data_Unit_unit))))))))))) (Map.add "foldMapWithIndex" (box ((box (fun (dictMonoid: obj) -> (let foldMap1 = (sharpurs_apply (box ((box Data_Lazy_foldMap))) (box ((box dictMonoid)))) in (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box foldMap1)))))) (box ((sharpurs_apply (box ((box f))) (box ((box Data_Unit_unit)))))))))))))) (Map.add "Foldable0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_foldableLazy))))) Map.empty)))))))))

let Data_Lazy_traversableLazy  = (sharpurs_apply (box ((box Data_Traversable_Traversableusd_Dict))) (box ((box ((Map.add "traverse" (box ((box (fun (dictApplicative: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Lazy_defer)))))) (box ((box Data_Function_const))))))))) (box ((sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l))))))))))))))))))) (Map.add "sequence" (box ((box (fun (dictApplicative: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (l: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Lazy_defer)))))) (box ((box Data_Function_const))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l)))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_functorLazy))))) (Map.add "Foldable1" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_foldableLazy))))) Map.empty)))))))))

let Data_Lazy_traverse  = (sharpurs_apply (box ((box Data_Traversable_traverse))) (box ((box Data_Lazy_traversableLazy))))

let Data_Lazy_traversableWithIndexLazy  = (sharpurs_apply (box ((box Data_TraversableWithIndex_TraversableWithIndexusd_Dict))) (box ((box ((Map.add "traverseWithIndex" (box ((box (fun (dictApplicative: obj) -> (let traverse1 = (sharpurs_apply (box ((box Data_Lazy_traverse))) (box ((box dictApplicative)))) in (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box traverse1)))))) (box ((sharpurs_apply (box ((box f))) (box ((box Data_Unit_unit)))))))))))))) (Map.add "FunctorWithIndex0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_functorWithIndexLazy))))) (Map.add "FoldableWithIndex1" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_foldableWithIndexLazy))))) (Map.add "Traversable2" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_traversableLazy))))) Map.empty)))))))))

let Data_Lazy_foldable1Lazy  = (sharpurs_apply (box ((box Data_Semigroup_Foldable_Foldable1usd_Dict))) (box ((box ((Map.add "foldMap1" (box ((box (fun (dictSemigroup: obj) -> (box (fun (f: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l))))))))))))))) (Map.add "foldr1" (box ((box (fun (v: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l)))))))))) (Map.add "foldl1" (box ((box (fun (v: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l)))))))))) (Map.add "Foldable0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_foldableLazy))))) Map.empty)))))))))

let Data_Lazy_traversable1Lazy  = (sharpurs_apply (box ((box Data_Semigroup_Traversable_Traversable1usd_Dict))) (box ((box ((Map.add "traverse1" (box ((box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (l: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Lazy_defer)))))) (box ((box Data_Function_const))))))))) (box ((sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l))))))))))))))))))) (Map.add "sequence1" (box ((box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in (box (fun (l: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Lazy_defer)))))) (box ((box Data_Function_const))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l)))))))))))))) (Map.add "Foldable10" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_foldable1Lazy))))) (Map.add "Traversable1" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_traversableLazy))))) Map.empty)))))))))

let Data_Lazy_extendLazy  = (sharpurs_apply (box ((box Control_Extend_Extendusd_Dict))) (box ((box ((Map.add "extend" (box ((box (fun (f: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box f))) (box ((box x))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_functorLazy))))) Map.empty)))))))

let Data_Lazy_eqLazy  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box x))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box y))))))))))))) Map.empty))))))))

let Data_Lazy_ordLazy  = (box (fun (dictOrd: obj) -> (let eqLazy1 = (sharpurs_apply (box ((box Data_Lazy_eqLazy))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box x))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box y))))))))))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box eqLazy1))))) Map.empty))))))))))

let Data_Lazy_eq1Lazy  = (sharpurs_apply (box ((box Data_Eq_Eq1usd_Dict))) (box ((box ((Map.add "eq1" (box ((box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_Eq_eq))) (box ((sharpurs_apply (box ((box Data_Lazy_eqLazy))) (box ((box dictEq))))))))))) Map.empty))))))

let Data_Lazy_ord1Lazy  = (sharpurs_apply (box ((box Data_Ord_Ord1usd_Dict))) (box ((box ((Map.add "compare1" (box ((box (fun (dictOrd: obj) -> (sharpurs_apply (box ((box Data_Ord_compare))) (box ((sharpurs_apply (box ((box Data_Lazy_ordLazy))) (box ((box dictOrd))))))))))) (Map.add "Eq10" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_eq1Lazy))))) Map.empty)))))))

let Data_Lazy_comonadLazy  = (sharpurs_apply (box ((box Control_Comonad_Comonadusd_Dict))) (box ((box ((Map.add "extract" (box ((box Data_Lazy_force))) (Map.add "Extend0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_extendLazy))))) Map.empty)))))))

let Data_Lazy_commutativeRingLazy  = (box (fun (dictCommutativeRing: obj) -> (let ringLazy1 = (sharpurs_apply (box ((box Data_Lazy_ringLazy))) (box ((sharpurs_apply (box ((Map.find "Ring0" (unbox<Map<string, obj>> ((box dictCommutativeRing)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_CommutativeRing_CommutativeRingusd_Dict))) (box ((box ((Map.add "Ring0" (box ((box (fun (usd__unused: obj) -> (box ringLazy1))))) Map.empty)))))))))

let Data_Lazy_euclideanRingLazy  = (box (fun (dictEuclideanRing: obj) -> (let commutativeRingLazy1 = (sharpurs_apply (box ((box Data_Lazy_commutativeRingLazy))) (box ((sharpurs_apply (box ((Map.find "CommutativeRing0" (unbox<Map<string, obj>> ((box dictEuclideanRing)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_EuclideanRing_EuclideanRingusd_Dict))) (box ((box ((Map.add "degree" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_EuclideanRing_degree))) (box ((box dictEuclideanRing))))))))) (box ((box Data_Lazy_force)))))) (Map.add "div" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_EuclideanRing_div))) (box ((box dictEuclideanRing)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box b)))))))))))))))))) (Map.add "mod" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_EuclideanRing_mod))) (box ((box dictEuclideanRing)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box b)))))))))))))))))) (Map.add "CommutativeRing0" (box ((box (fun (usd__unused: obj) -> (box commutativeRingLazy1))))) Map.empty))))))))))))

let Data_Lazy_boundedLazy  = (box (fun (dictBounded: obj) -> (let ordLazy1 = (sharpurs_apply (box ((box Data_Lazy_ordLazy))) (box ((sharpurs_apply (box ((Map.find "Ord0" (unbox<Map<string, obj>> ((box dictBounded)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Bounded_Boundedusd_Dict))) (box ((box ((Map.add "top" (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_Bounded_top))) (box ((box dictBounded))))))))))) (Map.add "bottom" (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box dictBounded))))))))))) (Map.add "Ord0" (box ((box (fun (usd__unused: obj) -> (box ordLazy1))))) Map.empty)))))))))))

let Data_Lazy_applyLazy  = (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (f: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box f)))))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box x)))))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_functorLazy))))) Map.empty)))))))

let Data_Lazy_bindLazy  = (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((box (fun (l: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Lazy_force)))))) (box ((sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((box Data_Lazy_force))) (box ((box l))))))))))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_applyLazy))))) Map.empty)))))))

let Data_Lazy_heytingAlgebraLazy  = (box (fun (dictHeytingAlgebra: obj) -> (let implies = (sharpurs_apply (box ((box Data_HeytingAlgebra_implies))) (box ((box dictHeytingAlgebra)))) in let conj = (sharpurs_apply (box ((box Data_HeytingAlgebra_conj))) (box ((box dictHeytingAlgebra)))) in let disj = (sharpurs_apply (box ((box Data_HeytingAlgebra_disj))) (box ((box dictHeytingAlgebra)))) in let not_var = (sharpurs_apply (box ((box Data_HeytingAlgebra_not))) (box ((box dictHeytingAlgebra)))) in (sharpurs_apply (box ((box Data_HeytingAlgebra_HeytingAlgebrausd_Dict))) (box ((box ((Map.add "ff" (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_HeytingAlgebra_ff))) (box ((box dictHeytingAlgebra))))))))))) (Map.add "tt" (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_HeytingAlgebra_tt))) (box ((box dictHeytingAlgebra))))))))))) (Map.add "implies" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Data_Lazy_applyLazy)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box implies)))))) (box ((box a))))))))) (box ((box b)))))))))) (Map.add "conj" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Data_Lazy_applyLazy)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box conj)))))) (box ((box a))))))))) (box ((box b)))))))))) (Map.add "disj" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Data_Lazy_applyLazy)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box disj)))))) (box ((box a))))))))) (box ((box b)))))))))) (Map.add "not" (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box not_var)))))) (box ((box a)))))))) Map.empty))))))))))))))

let Data_Lazy_booleanAlgebraLazy  = (box (fun (dictBooleanAlgebra: obj) -> (let heytingAlgebraLazy1 = (sharpurs_apply (box ((box Data_Lazy_heytingAlgebraLazy))) (box ((sharpurs_apply (box ((Map.find "HeytingAlgebra0" (unbox<Map<string, obj>> ((box dictBooleanAlgebra)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_BooleanAlgebra_BooleanAlgebrausd_Dict))) (box ((box ((Map.add "HeytingAlgebra0" (box ((box (fun (usd__unused: obj) -> (box heytingAlgebraLazy1))))) Map.empty)))))))))

let Data_Lazy_applicativeLazy  = (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((box (fun (a: obj) -> (sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v: obj) -> (box a)))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_applyLazy))))) Map.empty)))))))

let Data_Lazy_monadLazy  = (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_applicativeLazy))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box Data_Lazy_bindLazy))))) Map.empty)))))))
