[<AutoOpen>]
module PureScript_Data_Either_Nested

open System
open System.Collections.Generic

let Data_Either_Nested_in9  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v))))))))))))))))))))))))))))))

let Data_Either_Nested_in8  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v)))))))))))))))))))))))))))

let Data_Either_Nested_in7  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v))))))))))))))))))))))))

let Data_Either_Nested_in6  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v)))))))))))))))))))))

let Data_Either_Nested_in5  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v))))))))))))))))))

let Data_Either_Nested_in4  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v)))))))))))))))

let Data_Either_Nested_in3  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v))))))))))))

let Data_Either_Nested_in2  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v)))))))))

let Data_Either_Nested_in10  = (box (fun (v: obj) -> (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box v)))))))))))))))))))))))))))))))))

let Data_Either_Nested_in1  = (box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))

let Data_Either_Nested_either9  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (h: obj) -> (box (fun (i: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((match ((unbox ((box _2)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box c))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_3) -> ((match ((unbox ((box _3)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box d))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_4) -> ((match ((unbox ((box _4)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box e))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_5) -> ((match ((unbox ((box _5)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_6) -> ((match ((unbox ((box _6)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box g))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_7) -> ((match ((unbox ((box _7)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box h))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_8) -> ((match ((unbox ((box _8)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box i))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_9) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _9))))))))))))))))))))))))))))))))))))))))))

let Data_Either_Nested_either8  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (h: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((match ((unbox ((box _2)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box c))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_3) -> ((match ((unbox ((box _3)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box d))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_4) -> ((match ((unbox ((box _4)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box e))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_5) -> ((match ((unbox ((box _5)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_6) -> ((match ((unbox ((box _6)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box g))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_7) -> ((match ((unbox ((box _7)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box h))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_8) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _8))))))))))))))))))))))))))))))))))))))

let Data_Either_Nested_either7  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((match ((unbox ((box _2)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box c))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_3) -> ((match ((unbox ((box _3)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box d))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_4) -> ((match ((unbox ((box _4)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box e))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_5) -> ((match ((unbox ((box _5)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_6) -> ((match ((unbox ((box _6)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box g))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_7) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _7))))))))))))))))))))))))))))))))))

let Data_Either_Nested_either6  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((match ((unbox ((box _2)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box c))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_3) -> ((match ((unbox ((box _3)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box d))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_4) -> ((match ((unbox ((box _4)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box e))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_5) -> ((match ((unbox ((box _5)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_6) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _6))))))))))))))))))))))))))))))

let Data_Either_Nested_either5  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((match ((unbox ((box _2)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box c))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_3) -> ((match ((unbox ((box _3)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box d))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_4) -> ((match ((unbox ((box _4)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box e))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_5) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _5))))))))))))))))))))))))))

let Data_Either_Nested_either4  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((match ((unbox ((box _2)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box c))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_3) -> ((match ((unbox ((box _3)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box d))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_4) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _4))))))))))))))))))))))

let Data_Either_Nested_either3  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((match ((unbox ((box _2)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box c))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_3) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _3))))))))))))))))))

let Data_Either_Nested_either2  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _2))))))))))))))

let Data_Either_Nested_either10  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (h: obj) -> (box (fun (i: obj) -> (box (fun (j: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box a))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_1) -> ((match ((unbox ((box _1)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box b))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_2) -> ((match ((unbox ((box _2)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box c))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_3) -> ((match ((unbox ((box _3)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box d))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_4) -> ((match ((unbox ((box _4)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box e))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_5) -> ((match ((unbox ((box _5)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_6) -> ((match ((unbox ((box _6)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box g))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_7) -> ((match ((unbox ((box _7)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box h))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_8) -> ((match ((unbox ((box _8)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box i))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_9) -> ((match ((unbox ((box _9)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box j))) (box ((box r))))) | Data_Either_Rightusd_Ctor(_10) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _10))))))))))))))))))))))))))))))))))))))))))))))

let Data_Either_Nested_either1  = (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((box r)) | Data_Either_Rightusd_Ctor(_1) -> ((sharpurs_apply (box ((box Data_Void_absurd))) (box ((box _1))))))))

let Data_Either_Nested_at9  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))))))))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at8  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))))))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at7  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at6  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at5  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at4  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at3  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at2  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at10  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Rightusd_Ctor(Unbox(Data_Either_Leftusd_Ctor(r))))))))))))))))))) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))

let Data_Either_Nested_at1  = (box (fun (b: obj) -> (box (fun (f: obj) -> (box (fun (y: obj) -> (match ((unbox ((box y)))) with | Data_Either_Leftusd_Ctor(r) -> ((sharpurs_apply (box ((box f))) (box ((box r))))) | _ -> ((box b)))))))))
