[<AutoOpen>]
module PureScript_Data_List_NonEmpty

open System
open System.Collections.Generic

let Data_List_NonEmpty_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_List_NonEmpty_zipWith  = (box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs), Data_NonEmpty_NonEmptyusd_Ctor(y, ys)) -> ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box f1))) (box ((box x)))))) (box ((box y))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_zipWith))) (box ((box f1)))))) (box ((box xs)))))) (box ((box ys))))))))))))))))))

let Data_List_NonEmpty_zipWithA  = (box (fun (dictApplicative: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (xs: obj) -> (box (fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Traversable_sequence1))) (box ((box Data_List_Types_traversable1NonEmptyList)))))) (box ((box Apply0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_zipWith))) (box ((box f)))))) (box ((box xs)))))) (box ((box ys))))))))))))))))

let Data_List_NonEmpty_zip  = (sharpurs_apply (box ((box Data_List_NonEmpty_zipWith))) (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))))

let Data_List_NonEmpty_wrappedOperation2  = (box (fun (name: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box name))), (unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (name1, f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs), Data_NonEmpty_NonEmptyusd_Ctor(y, ys)) -> ((let v2 = (sharpurs_apply (box ((sharpurs_apply (box ((box f1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y)))))) (box ((box ys))))))) in (match ((unbox ((box v2)))) with | Data_List_Types_Consusd_Ctor(x_prime, xs_prime) -> ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x_prime)))))) (box ((box xs_prime)))))))) | Data_List_Types_Nilusd_Ctor -> ((sharpurs_apply (box ((box Partial_Unsafe_unsafeCrashWith))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "Impossible: empty list in NonEmptyList ")))))) (box ((box name1))))))))))))))))))))

let Data_List_NonEmpty_wrappedOperation  = (box (fun (name: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box name))), (unbox ((box f))), (unbox ((box v))))) with | (name1, f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) -> ((let v1 = (sharpurs_apply (box ((box f1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs))))))) in (match ((unbox ((box v1)))) with | Data_List_Types_Consusd_Ctor(x_prime, xs_prime) -> ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x_prime)))))) (box ((box xs_prime)))))))) | Data_List_Types_Nilusd_Ctor -> ((sharpurs_apply (box ((box Partial_Unsafe_unsafeCrashWith))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "Impossible: empty list in NonEmptyList ")))))) (box ((box name1))))))))))))))))))

let Data_List_NonEmpty_updateAt  = (box (fun (i: obj) -> (box (fun (a: obj) -> (box (fun (v: obj) -> (match (((unbox ((box i))), (unbox ((box a))), (unbox ((box v))))) with | (i1, a1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Eq_eqInt)))))) (box ((box i1)))))) (box ((box 0))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box a1)))))) (box ((box xs))))))))))) | (i1, a1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) when (unbox (box Data_Boolean_otherwise)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Types_NonEmptyList)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box v1)))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_updateAt))) (box ((box ((unbox<int> (box ((box i1)))) - (unbox<int> (box ((box 1))))))))))) (box ((box a1)))))) (box ((box xs)))))))))))))))

let Data_List_NonEmpty_unzip  = (box (fun (ts: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_List_Types_functorNonEmptyList)))))) (box ((box Data_Tuple_fst)))))) (box ((box ts))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_List_Types_functorNonEmptyList)))))) (box ((box Data_Tuple_snd)))))) (box ((box ts)))))))))

let Data_List_NonEmpty_unsnoc  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((let v1 = (sharpurs_apply (box ((box Data_List_unsnoc))) (box ((box xs)))) in (match ((unbox ((box v1)))) with | Data_Maybe_Nothingusd_Ctor -> ((box ((Map.add "init" (box ((box Data_List_Types_Nilusd_Ctor))) (Map.add "last" (box ((box x))) Map.empty))))) | Data_Maybe_Justusd_Ctor(un) -> ((box ((Map.add "init" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((Map.find "init" (unbox<Map<string, obj>> ((box un))))))))) (Map.add "last" (box ((Map.find "last" (unbox<Map<string, obj>> ((box un)))))) Map.empty)))))))))))

let Data_List_NonEmpty_unionBy  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation2))) (box ((box "unionBy"))))))))) (box ((box Data_List_unionBy))))

let Data_List_NonEmpty_union  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation2))) (box ((box "union")))))) (box ((sharpurs_apply (box ((box Data_List_union))) (box ((box dictEq)))))))))

let Data_List_NonEmpty_uncons  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((box ((Map.add "head" (box ((box x))) (Map.add "tail" (box ((box xs))) Map.empty))))))))

let Data_List_NonEmpty_toList  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs))))))))

let Data_List_NonEmpty_toUnfoldable  = (box (fun (dictUnfoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Unfoldable_unfoldr))) (box ((box dictUnfoldable)))))) (box ((box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box (fun (rec_var: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((Map.find "head" (unbox<Map<string, obj>> ((box rec_var))))))))) (box ((Map.find "tail" (unbox<Map<string, obj>> ((box rec_var)))))))))))))) (box ((sharpurs_apply (box ((box Data_List_uncons))) (box ((box xs))))))))))))))))) (box ((box Data_List_NonEmpty_toList))))))

let Data_List_NonEmpty_tail  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_NonEmpty_NonEmptyusd_Ctor(_, xs) -> ((box xs)))))

let Data_List_NonEmpty_sortBy  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "sortBy"))))))))) (box ((box Data_List_sortBy))))

let Data_List_NonEmpty_sort  = (box (fun (dictOrd: obj) -> (let compare = (sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd)))) in (box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_sortBy))) (box ((box compare)))))) (box ((box xs)))))))))

let Data_List_NonEmpty_snoc  = (box (fun (v: obj) -> (box (fun (y: obj) -> (match (((unbox ((box v))), (unbox ((box y))))) with | (Data_NonEmpty_NonEmptyusd_Ctor(x, xs), y1) -> ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_snoc))) (box ((box xs)))))) (box ((box y1))))))))))))))))

let Data_List_NonEmpty_singleton  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Types_NonEmptyList)))))) (box ((sharpurs_apply (box ((box Data_NonEmpty_singleton))) (box ((box Data_List_Types_plusList)))))))

let Data_List_NonEmpty_snoc_prime  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_List_Types_Consusd_Ctor(x, xs), y) -> ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_snoc))) (box ((box xs)))))) (box ((box y))))))))))) | (Data_List_Types_Nilusd_Ctor, y) -> ((sharpurs_apply (box ((box Data_List_NonEmpty_singleton))) (box ((box y))))))))))

let Data_List_NonEmpty_reverse  = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "reverse")))))) (box ((box Data_List_reverse))))

let Data_List_NonEmpty_nubEq  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "nubEq")))))) (box ((sharpurs_apply (box ((box Data_List_nubEq))) (box ((box dictEq)))))))))

let Data_List_NonEmpty_nubByEq  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "nubByEq"))))))))) (box ((box Data_List_nubByEq))))

let Data_List_NonEmpty_nubBy  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "nubBy"))))))))) (box ((box Data_List_nubBy))))

let Data_List_NonEmpty_nub  = (box (fun (dictOrd: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "nub")))))) (box ((sharpurs_apply (box ((box Data_List_nub))) (box ((box dictOrd)))))))))

let Data_List_NonEmpty_modifyAt  = (box (fun (i: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box i))), (unbox ((box f))), (unbox ((box v))))) with | (i1, f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Eq_eqInt)))))) (box ((box i1)))))) (box ((box 0))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((box f1))) (box ((box x))))))))) (box ((box xs))))))))))) | (i1, f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) when (unbox (box Data_Boolean_otherwise)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Types_NonEmptyList)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box v1)))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_modifyAt))) (box ((box ((unbox<int> (box ((box i1)))) - (unbox<int> (box ((box 1))))))))))) (box ((box f1)))))) (box ((box xs)))))))))))))))

let Data_List_NonEmpty_lift  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) -> ((sharpurs_apply (box ((box f1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs)))))))))))))

let Data_List_NonEmpty_mapMaybe  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((box Data_List_mapMaybe))))

let Data_List_NonEmpty_partition  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((box Data_List_partition))))

let Data_List_NonEmpty_span  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((box Data_List_span))))

let Data_List_NonEmpty_take  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((box Data_List_take))))

let Data_List_NonEmpty_takeWhile  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((box Data_List_takeWhile))))

let Data_List_NonEmpty_length  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_NonEmpty_NonEmptyusd_Ctor(_, xs) -> ((box ((unbox<int> (box ((box 1)))) + (unbox<int> (box ((sharpurs_apply (box ((box Data_List_length))) (box ((box xs)))))))))))))

let Data_List_NonEmpty_last  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_fromMaybe))) (box ((box x)))))) (box ((sharpurs_apply (box ((box Data_List_last))) (box ((box xs)))))))))))

let Data_List_NonEmpty_intersectBy  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation2))) (box ((box "intersectBy"))))))))) (box ((box Data_List_intersectBy))))

let Data_List_NonEmpty_intersect  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation2))) (box ((box "intersect")))))) (box ((sharpurs_apply (box ((box Data_List_intersect))) (box ((box dictEq)))))))))

let Data_List_NonEmpty_insertAt  = (box (fun (i: obj) -> (box (fun (a: obj) -> (box (fun (v: obj) -> (match (((unbox ((box i))), (unbox ((box a))), (unbox ((box v))))) with | (i1, a1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Eq_eqInt)))))) (box ((box i1)))))) (box ((box 0))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box a1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs)))))))))))))) | (i1, a1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) when (unbox (box Data_Boolean_otherwise)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Types_NonEmptyList)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box v1)))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_insertAt))) (box ((box ((unbox<int> (box ((box i1)))) - (unbox<int> (box ((box 1))))))))))) (box ((box a1)))))) (box ((box xs)))))))))))))))

let Data_List_NonEmpty_init  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe))) (box ((box Data_List_Types_Nilusd_Ctor)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box v1))))))))))) (box ((sharpurs_apply (box ((box Data_List_init))) (box ((box xs)))))))))))

let Data_List_NonEmpty_index  = (box (fun (v: obj) -> (box (fun (i: obj) -> (match (((unbox ((box v))), (unbox ((box i))))) with | (Data_NonEmpty_NonEmptyusd_Ctor(x, xs), i1) when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Eq_eqInt)))))) (box ((box i1)))))) (box ((box 0))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box x))))) | (Data_NonEmpty_NonEmptyusd_Ctor(x, xs), i1) when (unbox (box Data_Boolean_otherwise)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_index))) (box ((box xs)))))) (box ((box ((unbox<int> (box ((box i1)))) - (unbox<int> (box ((box 1)))))))))))))))

let Data_List_NonEmpty_head  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_NonEmpty_NonEmptyusd_Ctor(x, _) -> ((box x)))))

let Data_List_NonEmpty_groupBy  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "groupBy"))))))))) (box ((box Data_List_groupBy))))

let Data_List_NonEmpty_groupAllBy  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "groupAllBy"))))))))) (box ((box Data_List_groupAllBy))))

let Data_List_NonEmpty_groupAll  = (box (fun (dictOrd: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "groupAll")))))) (box ((sharpurs_apply (box ((box Data_List_groupAll))) (box ((box dictOrd)))))))))

let Data_List_NonEmpty_group  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_NonEmpty_wrappedOperation))) (box ((box "group")))))) (box ((sharpurs_apply (box ((box Data_List_group))) (box ((box dictEq)))))))))

let Data_List_NonEmpty_fromList  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_List_Types_Nilusd_Ctor -> ((box Data_Maybe_Nothingusd_Ctor)) | Data_List_Types_Consusd_Ctor(x, xs) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs))))))))))))))

let Data_List_NonEmpty_fromFoldable  = (box (fun (dictFoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_fromList)))))) (box ((sharpurs_apply (box ((box Data_List_fromFoldable))) (box ((box dictFoldable)))))))))

let Data_List_NonEmpty_foldM  = (box (fun (dictMonad: obj) -> (let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (b: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box b))), (unbox ((box v))))) with | (f1, b1, Data_NonEmpty_NonEmptyusd_Ctor(a, as_var)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box f1))) (box ((box b1)))))) (box ((box a))))))))) (box ((box (fun (b_prime: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_foldM))) (box ((box dictMonad)))))) (box ((box f1)))))) (box ((box b_prime)))))) (box ((box as_var))))))))))))))))))))

let Data_List_NonEmpty_findLastIndex  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) -> ((let v1 = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_findLastIndex))) (box ((box f1)))))) (box ((box xs)))) in (match ((unbox ((box v1)))) with | Data_Maybe_Justusd_Ctor(i) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box ((unbox<int> (box ((box i)))) + (unbox<int> (box ((box 1)))))))))) | Data_Maybe_Nothingusd_Ctor when (unbox (sharpurs_apply (box ((box f1))) (box ((box x))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box 0))))) | Data_Maybe_Nothingusd_Ctor when (unbox (box Data_Boolean_otherwise)) -> ((box Data_Maybe_Nothingusd_Ctor))))))))))

let Data_List_NonEmpty_findIndex  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) when (unbox (sharpurs_apply (box ((box f1))) (box ((box x))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box 0))))) | (f1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) when (unbox (box Data_Boolean_otherwise)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box (fun (v1: obj) -> (box ((unbox<int> (box ((box v1)))) + (unbox<int> (box ((box 1))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_findIndex))) (box ((box f1)))))) (box ((box xs)))))))))))))

let Data_List_NonEmpty_filterM  = (box (fun (dictMonad: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((sharpurs_apply (box ((box Data_List_filterM))) (box ((box dictMonad)))))))))

let Data_List_NonEmpty_filter  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((box Data_List_filter))))

let Data_List_NonEmpty_elemLastIndex  = (box (fun (dictEq: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((box Data_List_NonEmpty_findLastIndex))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((box v)))))) (box ((box x)))))))))))))

let Data_List_NonEmpty_elemIndex  = (box (fun (dictEq: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((box Data_List_NonEmpty_findIndex))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((box v)))))) (box ((box x)))))))))))))

let Data_List_NonEmpty_dropWhile  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((box Data_List_dropWhile))))

let Data_List_NonEmpty_drop  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_NonEmpty_lift)))))) (box ((box Data_List_drop))))

let Data_List_NonEmpty_cons_prime  = (box (fun (x: obj) -> (box (fun (xs: obj) -> (sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs)))))))))))

let Data_List_NonEmpty_cons  = (box (fun (y: obj) -> (box (fun (v: obj) -> (match (((unbox ((box y))), (unbox ((box v))))) with | (y1, Data_NonEmpty_NonEmptyusd_Ctor(x, xs)) -> ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box xs))))))))))))))))

let Data_List_NonEmpty_concatMap  = (sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Data_List_Types_bindNonEmptyList)))))))

let Data_List_NonEmpty_concat  = (box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Data_List_Types_bindNonEmptyList)))))) (box ((box v)))))) (box ((box Data_List_NonEmpty_identity))))))

let Data_List_NonEmpty_catMaybes  = (sharpurs_apply (box ((box Data_List_NonEmpty_lift))) (box ((box Data_List_catMaybes))))

let Data_List_NonEmpty_appendFoldable  = (box (fun (dictFoldable: obj) -> (box (fun (v: obj) -> (box (fun (ys: obj) -> (match (((unbox ((box v))), (unbox ((box ys))))) with | (Data_NonEmpty_NonEmptyusd_Ctor(x, xs), ys1) -> ((sharpurs_apply (box ((box Data_List_Types_NonEmptyList))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_List_Types_semigroupList)))))) (box ((box xs)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_fromFoldable))) (box ((box dictFoldable)))))) (box ((box ys1)))))))))))))))))))))
