<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.0</LangVersion>
    <WarningsAsErrors>false</WarningsAsErrors>
    <NoWarn>40,25,46,58,66,67,3370</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="FFI.CSharp.csproj" />
    <Compile Include="Sharpurs_Prelude.fs" />
    <Compile Include="Control.Semigroupoid.fs" />
    <Compile Include="Control.Category.fs" />
    <Compile Include="Data.Boolean.fs" />
    <Compile Include="Type.Proxy.fs" />
    <Compile Include="Data.Symbol.fs" />
    <Compile Include="Data.Unit.fs" />
    <Compile Include="Record.Unsafe.fs" />
    <Compile Include="Data.HeytingAlgebra.fs" />
    <Compile Include="Data.Void.fs" />
    <Compile Include="Data.Eq.fs" />
    <Compile Include="Data.Semigroup.fs" />
    <Compile Include="Data.Show.fs" />
    <Compile Include="Data.Ordering.fs" />
    <Compile Include="Data.Semiring.fs" />
    <Compile Include="Data.Ring.fs" />
    <Compile Include="Data.Ord.fs" />
    <Compile Include="Data.Function.fs" />
    <Compile Include="Data.Functor.fs" />
    <Compile Include="Control.Apply.fs" />
    <Compile Include="Control.Applicative.fs" />
    <Compile Include="Control.Bind.fs" />
    <Compile Include="Control.Monad.fs" />
    <Compile Include="Data.BooleanAlgebra.fs" />
    <Compile Include="Data.CommutativeRing.fs" />
    <Compile Include="Data.EuclideanRing.fs" />
    <Compile Include="Data.Monoid.fs" />
    <Compile Include="Data.Bounded.fs" />
    <Compile Include="Data.DivisionRing.fs" />
    <Compile Include="Data.Field.fs" />
    <Compile Include="Data.NaturalTransformation.fs" />
    <Compile Include="Prelude.fs" />
    <Compile Include="Effect.fs" />
    <Compile Include="Effect.Console.fs" />
    <Compile Include="Bench.fs" />
    <Compile Include="Test.Ackermann.fs" />
    <Compile Include="Control.Alt.fs" />
    <Compile Include="Control.Plus.fs" />
    <Compile Include="Control.Alternative.fs" />
    <Compile Include="Control.Lazy.fs" />
    <Compile Include="Data.Monoid.Additive.fs" />
    <Compile Include="Control.Extend.fs" />
    <Compile Include="Control.Comonad.fs" />
    <Compile Include="Data.Monoid.Conj.fs" />
    <Compile Include="Data.Monoid.Disj.fs" />
    <Compile Include="Data.Monoid.Dual.fs" />
    <Compile Include="Data.Monoid.Endo.fs" />
    <Compile Include="Data.Monoid.Multiplicative.fs" />
    <Compile Include="Data.Semigroup.First.fs" />
    <Compile Include="Data.Semigroup.Last.fs" />
    <Compile Include="Unsafe.Coerce.fs" />
    <Compile Include="Safe.Coerce.fs" />
    <Compile Include="Data.Newtype.fs" />
    <Compile Include="Data.Monoid.Alternate.fs" />
    <Compile Include="Data.Functor.Invariant.fs" />
    <Compile Include="Data.Const.fs" />
    <Compile Include="Data.Generic.Rep.fs" />
    <Compile Include="Data.Maybe.fs" />
    <Compile Include="Data.Either.fs" />
    <Compile Include="Data.Tuple.fs" />
    <Compile Include="Data.Bifunctor.fs" />
    <Compile Include="Data.Identity.fs" />
    <Compile Include="Effect.Ref.fs" />
    <Compile Include="Partial.fs" />
    <Compile Include="Partial.Unsafe.fs" />
    <Compile Include="Control.Monad.Rec.Class.fs" />
    <Compile Include="Control.Monad.ST.Internal.fs" />
    <Compile Include="Control.Monad.ST.fs" />
    <Compile Include="Control.MonadPlus.fs" />
    <Compile Include="Data.Functor.App.fs" />
    <Compile Include="Data.Functor.Compose.fs" />
    <Compile Include="Data.Functor.Coproduct.fs" />
    <Compile Include="Data.Functor.Product.fs" />
    <Compile Include="Data.Maybe.First.fs" />
    <Compile Include="Data.Maybe.Last.fs" />
    <Compile Include="Data.Foldable.fs" />
    <Compile Include="Data.FunctorWithIndex.fs" />
    <Compile Include="Data.FoldableWithIndex.fs" />
    <Compile Include="Data.Function.Uncurried.fs" />
    <Compile Include="Data.Ord.Max.fs" />
    <Compile Include="Data.Ord.Min.fs" />
    <Compile Include="Data.Semigroup.Foldable.fs" />
    <Compile Include="Data.Traversable.Accum.fs" />
    <Compile Include="Data.Traversable.Accum.Internal.fs" />
    <Compile Include="Data.Traversable.fs" />
    <Compile Include="Data.Semigroup.Traversable.fs" />
    <Compile Include="Data.TraversableWithIndex.fs" />
    <Compile Include="Data.Unfoldable1.fs" />
    <Compile Include="Data.Array.NonEmpty.Internal.fs" />
    <Compile Include="Control.Monad.ST.Uncurried.fs" />
    <Compile Include="Data.Array.ST.fs" />
    <Compile Include="Control.Monad.ST.Ref.fs" />
    <Compile Include="Data.Array.ST.Iterator.fs" />
    <Compile Include="Data.Unfoldable.fs" />
    <Compile Include="Data.Array.fs" />
    <Compile Include="Test.ArrayOps.fs" />
    <Compile Include="Test.AstTree.fs" />
    <Compile Include="Test.Church.fs" />
    <Compile Include="Test.Fib.fs" />
    <Compile Include="Test.LazyEvaluation.fs" />
    <Compile Include="Test.ListOps.fs" />
    <Compile Include="Test.Polymorphism.fs" />
    <Compile Include="Test.Primes.fs" />
    <Compile Include="Test.RBTree.fs" />
    <Compile Include="Test.Records.fs" />
    <Compile Include="Test.RowToList.fs" />
    <Compile Include="Test.StateMonad.fs" />
    <Compile Include="Test.TCO.fs" />
    <Compile Include="App.fs" />
    <Compile Include="Test.AckermannFFI.fs" />
    <Compile Include="Test.AckermannFFICheatcode.fs" />
    <Compile Include="Test.ArrayOpsFFI.fs" />
    <Compile Include="Test.ArrayOpsFFICheatcode.fs" />
    <Compile Include="Test.AstTreeFFI.fs" />
    <Compile Include="Test.AstTreeFFICheatcode.fs" />
    <Compile Include="Test.ChurchFFI.fs" />
    <Compile Include="Test.ChurchFFICheatcode.fs" />
    <Compile Include="Test.FibFFI.fs" />
    <Compile Include="Test.FibFFICheatcode.fs" />
    <Compile Include="Test.LazyEvaluationFFI.fs" />
    <Compile Include="Test.LazyEvaluationFFICheatcode.fs" />
    <Compile Include="Test.ListOpsFFI.fs" />
    <Compile Include="Test.ListOpsFFICheatcode.fs" />
    <Compile Include="Test.PolymorphismFFI.fs" />
    <Compile Include="Test.PolymorphismFFICheatcode.fs" />
    <Compile Include="Test.PrimesFFI.fs" />
    <Compile Include="Test.PrimesFFICheatcode.fs" />
    <Compile Include="Test.RBTreeFFI.fs" />
    <Compile Include="Test.RBTreeFFICheatcode.fs" />
    <Compile Include="Test.RecordsFFI.fs" />
    <Compile Include="Test.RecordsFFICheatcode.fs" />
    <Compile Include="Test.RowToListFFI.fs" />
    <Compile Include="Test.RowToListFFICheatcode.fs" />
    <Compile Include="Test.StateMonadFFI.fs" />
    <Compile Include="Test.StateMonadFFICheatcode.fs" />
    <Compile Include="Test.TCOFFI.fs" />
    <Compile Include="Test.TCOFFICheatcode.fs" />
    <Compile Include="AppFFI.fs" />
    <Compile Include="AppFFICheatcode.fs" />
    <Compile Include="AppJavaFFI.fs" />
    <Compile Include="AppJavaFFICheatcode.fs" />
    <Compile Include="Control.Biapply.fs" />
    <Compile Include="Control.Biapplicative.fs" />
    <Compile Include="Control.Monad.Cont.Class.fs" />
    <Compile Include="Effect.Exception.fs" />
    <Compile Include="Control.Monad.Error.Class.fs" />
    <Compile Include="Control.Monad.Reader.Class.fs" />
    <Compile Include="Control.Monad.ST.Global.fs" />
    <Compile Include="Control.Monad.ST.Class.fs" />
    <Compile Include="Control.Monad.State.Class.fs" />
    <Compile Include="Control.Monad.Trans.Class.fs" />
    <Compile Include="Control.Monad.Writer.Class.fs" />
    <Compile Include="Effect.Class.fs" />
    <Compile Include="Control.Monad.Identity.Trans.fs" />
    <Compile Include="Control.Comonad.Trans.Class.fs" />
    <Compile Include="Control.Comonad.Env.Trans.fs" />
    <Compile Include="Control.Comonad.Store.Trans.fs" />
    <Compile Include="Control.Comonad.Traced.Trans.fs" />
    <Compile Include="Control.Comonad.Store.Class.fs" />
    <Compile Include="Control.Comonad.Store.fs" />
    <Compile Include="Control.Comonad.Env.Class.fs" />
    <Compile Include="Control.Comonad.Env.fs" />
    <Compile Include="Control.Comonad.Traced.Class.fs" />
    <Compile Include="Control.Comonad.Traced.fs" />
    <Compile Include="Control.Monad.Cont.Trans.fs" />
    <Compile Include="Control.Monad.Cont.fs" />
    <Compile Include="Control.Monad.Except.Trans.fs" />
    <Compile Include="Control.Monad.Except.fs" />
    <Compile Include="Control.Monad.Gen.Class.fs" />
    <Compile Include="Control.Monad.Gen.fs" />
    <Compile Include="Data.NonEmpty.fs" />
    <Compile Include="Control.Monad.Gen.Common.fs" />
    <Compile Include="Data.Lazy.fs" />
    <Compile Include="Control.Monad.List.Trans.fs" />
    <Compile Include="Control.Monad.Maybe.Trans.fs" />
    <Compile Include="Control.Monad.RWS.Trans.fs" />
    <Compile Include="Control.Monad.RWS.fs" />
    <Compile Include="Type.Equality.fs" />
    <Compile Include="Data.Distributive.fs" />
    <Compile Include="Control.Monad.Reader.Trans.fs" />
    <Compile Include="Control.Monad.Reader.fs" />
    <Compile Include="Control.Monad.State.Trans.fs" />
    <Compile Include="Control.Monad.State.fs" />
    <Compile Include="Control.Monad.Writer.Trans.fs" />
    <Compile Include="Control.Monad.Writer.fs" />
    <Compile Include="Data.Functor.Contravariant.fs" />
    <Compile Include="Data.Profunctor.fs" />
    <Compile Include="Data.Profunctor.Closed.fs" />
    <Compile Include="Data.Profunctor.Strong.fs" />
    <Compile Include="Data.Functor.Costar.fs" />
    <Compile Include="Data.Profunctor.Choice.fs" />
    <Compile Include="Data.Profunctor.Star.fs" />
    <Compile Include="Control.Parallel.Class.fs" />
    <Compile Include="Control.Parallel.fs" />
    <Compile Include="Data.Array.NonEmpty.fs" />
    <Compile Include="Data.Array.Partial.fs" />
    <Compile Include="Data.Array.ST.Partial.fs" />
    <Compile Include="Data.Functor.Clown.fs" />
    <Compile Include="Data.Functor.Flip.fs" />
    <Compile Include="Data.Functor.Joker.fs" />
    <Compile Include="Data.Functor.Product2.fs" />
    <Compile Include="Data.Bifoldable.fs" />
    <Compile Include="Data.Bifunctor.Join.fs" />
    <Compile Include="Data.Bitraversable.fs" />
    <Compile Include="Data.Bounded.Generic.fs" />
    <Compile Include="Data.Enum.fs" />
    <Compile Include="Data.Char.fs" />
    <Compile Include="Data.Char.Gen.fs" />
    <Compile Include="Data.Comparison.fs" />
    <Compile Include="Data.Date.Component.fs" />
    <Compile Include="Data.Int.Bits.fs" />
    <Compile Include="Data.Number.fs" />
    <Compile Include="Data.Int.fs" />
    <Compile Include="Data.Time.Duration.fs" />
    <Compile Include="Data.Date.fs" />
    <Compile Include="Data.Enum.Gen.fs" />
    <Compile Include="Data.Date.Component.Gen.fs" />
    <Compile Include="Data.Date.Gen.fs" />
    <Compile Include="Data.Time.Component.fs" />
    <Compile Include="Data.Time.fs" />
    <Compile Include="Data.DateTime.fs" />
    <Compile Include="Data.Time.Component.Gen.fs" />
    <Compile Include="Data.Time.Gen.fs" />
    <Compile Include="Data.DateTime.Gen.fs" />
    <Compile Include="Data.DateTime.Instant.fs" />
    <Compile Include="Data.Equivalence.fs" />
    <Compile Include="Data.Op.fs" />
    <Compile Include="Data.Predicate.fs" />
    <Compile Include="Data.Divide.fs" />
    <Compile Include="Data.Decide.fs" />
    <Compile Include="Data.Divisible.fs" />
    <Compile Include="Data.Decidable.fs" />
    <Compile Include="Data.Either.Inject.fs" />
    <Compile Include="Data.Either.Nested.fs" />
    <Compile Include="Data.Enum.Generic.fs" />
    <Compile Include="Data.Eq.Generic.fs" />
    <Compile Include="Data.Exists.fs" />
    <Compile Include="Data.Functor.Coproduct.Inject.fs" />
    <Compile Include="Data.Functor.Coproduct.Nested.fs" />
    <Compile Include="Data.Functor.Product.Nested.fs" />
    <Compile Include="Data.HeytingAlgebra.Generic.fs" />
    <Compile Include="Data.List.Types.fs" />
    <Compile Include="Data.List.Internal.fs" />
    <Compile Include="Data.List.fs" />
    <Compile Include="Data.Map.Internal.fs" />
    <Compile Include="Data.Set.fs" />
    <Compile Include="Data.Map.fs" />
    <Compile Include="Data.Interval.Duration.fs" />
    <Compile Include="Data.Interval.fs" />
    <Compile Include="Data.List.NonEmpty.fs" />
    <Compile Include="Data.Interval.Duration.Iso.fs" />
    <Compile Include="Data.List.Lazy.Types.fs" />
    <Compile Include="Data.List.Lazy.fs" />
    <Compile Include="Data.List.Lazy.NonEmpty.fs" />
    <Compile Include="Data.List.Partial.fs" />
    <Compile Include="Data.List.ZipList.fs" />
    <Compile Include="Data.Map.Gen.fs" />
    <Compile Include="Data.Monoid.Generic.fs" />
    <Compile Include="Data.Number.Approximate.fs" />
    <Compile Include="Data.Number.Format.fs" />
    <Compile Include="Data.Ord.Down.fs" />
    <Compile Include="Data.Ord.Generic.fs" />
    <Compile Include="Data.Profunctor.Cochoice.fs" />
    <Compile Include="Data.Profunctor.Costrong.fs" />
    <Compile Include="Data.Profunctor.Join.fs" />
    <Compile Include="Data.Profunctor.Split.fs" />
    <Compile Include="Data.Reflectable.fs" />
    <Compile Include="Data.Ring.Generic.fs" />
    <Compile Include="Data.Semigroup.Generic.fs" />
    <Compile Include="Data.Semiring.Generic.fs" />
    <Compile Include="Data.Set.NonEmpty.fs" />
    <Compile Include="Data.Show.Generic.fs" />
    <Compile Include="Data.String.Pattern.fs" />
    <Compile Include="Data.String.Unsafe.fs" />
    <Compile Include="Data.String.CodeUnits.fs" />
    <Compile Include="Data.String.Common.fs" />
    <Compile Include="Data.String.CodePoints.fs" />
    <Compile Include="Data.String.fs" />
    <Compile Include="Data.String.CaseInsensitive.fs" />
    <Compile Include="Data.String.Gen.fs" />
    <Compile Include="Data.String.NonEmpty.Internal.fs" />
    <Compile Include="Data.String.NonEmpty.CodePoints.fs" />
    <Compile Include="Data.String.NonEmpty.fs" />
    <Compile Include="Data.String.NonEmpty.CaseInsensitive.fs" />
    <Compile Include="Data.String.NonEmpty.CodeUnits.fs" />
    <Compile Include="Data.String.Regex.Flags.fs" />
    <Compile Include="Data.String.Regex.fs" />
    <Compile Include="Data.String.Regex.Unsafe.fs" />
    <Compile Include="Data.Time.Duration.Gen.fs" />
    <Compile Include="Data.Tuple.Nested.fs" />
    <Compile Include="Effect.Unsafe.fs" />
    <Compile Include="Effect.Aff.fs" />
    <Compile Include="Effect.Aff.Class.fs" />
    <Compile Include="Effect.Uncurried.fs" />
    <Compile Include="Effect.Aff.Compat.fs" />
    <Compile Include="Effect.Class.Console.fs" />
    <Compile Include="Effect.Exception.Unsafe.fs" />
    <Compile Include="Effect.Now.fs" />
    <Compile Include="Main.fs" />
    <Compile Include="Spago.Generated.BuildInfo.fs" />
    <Compile Include="Test.Main.fs" />
    <Compile Include="Test.TC.fs" />
    <Compile Include="EntryPoint.fs" />
  </ItemGroup>
</Project>
