<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Sharpurs_Prelude.fs" />
    <Compile Include="Test.Fib.fs" />
    <Compile Include="BenchFable.fs" />
    <PackageReference Include="Fable.Core" Version="4.3.0" />
  </ItemGroup>
</Project>
