#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Eq::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Record_Unsafe::*;
use Purs_Type_Proxy::*;
use Purs_Data_Eq::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semiring::*;
use Purs_Data_Symbol::*;
use Purs_Record_Unsafe::*;
use Purs_Type_Proxy::*;

// Code generated by purust for module Data_Ord


#[derive(Clone)]
pub struct OrdRecord {
    pub EqRecord0: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Eq::EqRecord>>,
    pub compareRecord: purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering>
}

#[derive(Clone)]
pub struct Ord {
    pub Eq0: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Eq::Eq>>,
    pub compare: purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering>
}

#[derive(Clone)]
pub struct Ord1 {
    pub Eq10: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Eq::Eq1>>,
    pub compare1: purust_core::Func3<std::rc::Rc<crate::Ord>, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering>
}

pub fn Data_Ord_ordVoid() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ordVoid", || {
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: purust_core::Void, mut _a1: purust_core::Void| -> Purs_Data_Ordering::Ordering {
    drop(_a1);
    drop(_a0);
    /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ
} as fn(purust_core::Void, purust_core::Void) -> Purs_Data_Ordering::Ordering)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_class::<purust_core::Void>().clone(), (_a1).unwrap_class::<purust_core::Void>().clone()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqVoid()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}

pub fn Data_Ord_ordUnit() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ordUnit", || {
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: (), mut _a1: ()| -> Purs_Data_Ordering::Ordering {
    drop(_a1);
    drop(_a0);
    /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ
} as fn((), ()) -> Purs_Data_Ordering::Ordering)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_unit(), (_a1).unwrap_unit()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqUnit()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}

pub fn Data_Ord_ordString() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ordString", || {
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<String, String, Purs_Data_Ordering::Ordering> <- purust_core::Func2<String, String, Purs_Data_Ordering::Ordering> : App(Var(...)) */{
        let mut eval_arg_0 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::LT;
        let mut eval_arg_1 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ;
        let mut eval_arg_2 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::GT;
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: String, mut eta_1: String| -> Purs_Data_Ordering::Ordering {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Ord_ordStringImpl(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone(), eta_1.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_string(), (_a1).unwrap_string()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqString()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}

pub fn Data_Ord_ordRecordNil() -> std::rc::Rc<crate::OrdRecord> {
    // AST: Typed(Typed(Typed(Typed(Lit))))
std::rc::Rc::new(crate::OrdRecord { compareRecord: /* Typed Abs */purust_core::Func3::Static(|mut _a0: Purs_Type_Proxy::Proxy, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> Purs_Data_Ordering::Ordering {
    drop(_a2);
    drop(_a1);
    drop(_a0);
    /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ
} as fn(Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType) -> Purs_Data_Ordering::Ordering), EqRecord0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::EqRecord> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::EqRecord> <- std::rc::Rc<Purs_Data_Eq::EqRecord> : Var(...) */Data_Eq_eqRowNil()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::EqRecord>) })
}

pub fn Data_Ord_ordProxy() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Typed(Lit))))
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: Purs_Type_Proxy::Proxy, mut _a1: Purs_Type_Proxy::Proxy| -> Purs_Data_Ordering::Ordering {
    drop(_a1);
    drop(_a0);
    /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ
} as fn(Purs_Type_Proxy::Proxy, Purs_Type_Proxy::Proxy) -> Purs_Data_Ordering::Ordering)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_class::<Purs_Type_Proxy::Proxy>().clone(), (_a1).unwrap_class::<Purs_Type_Proxy::Proxy>().clone()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqProxy()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}

pub fn Data_Ord_ordOrdering() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ordOrdering", || {
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: Purs_Data_Ordering::Ordering, mut _a1: Purs_Data_Ordering::Ordering| -> Purs_Data_Ordering::Ordering {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Branch(...) */if /* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_0.clone()), Purs_Data_Ordering::Ordering::LT) {
        if /* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_1), Purs_Data_Ordering::Ordering::LT) {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ
    } else {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::LT
    }
    } else if /* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_0.clone()), Purs_Data_Ordering::Ordering::EQ) {
        if /* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_1.clone()), Purs_Data_Ordering::Ordering::EQ) {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ
    } else if /* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_1.clone()), Purs_Data_Ordering::Ordering::LT) {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::GT
    } else if /* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_1), Purs_Data_Ordering::Ordering::GT) {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::LT
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
    } else if /* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_0), Purs_Data_Ordering::Ordering::GT) {
        if /* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_1), Purs_Data_Ordering::Ordering::GT) {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ
    } else {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::GT
    }
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
} as fn(Purs_Data_Ordering::Ordering, Purs_Data_Ordering::Ordering) -> Purs_Data_Ordering::Ordering)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_class::<Purs_Data_Ordering::Ordering>().clone(), (_a1).unwrap_class::<Purs_Data_Ordering::Ordering>().clone()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Ordering_eqOrdering()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}

pub fn Data_Ord_ordNumber() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ordNumber", || {
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<f64, f64, Purs_Data_Ordering::Ordering> <- purust_core::Func2<f64, f64, Purs_Data_Ordering::Ordering> : App(Var(...)) */{
        let mut eval_arg_0 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::LT;
        let mut eval_arg_1 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ;
        let mut eval_arg_2 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::GT;
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: f64, mut eta_1: f64| -> Purs_Data_Ordering::Ordering {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Ord_ordNumberImpl(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone(), eta_1.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_number(), (_a1).unwrap_number()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqNumber()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}

pub fn Data_Ord_ordInt() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ordInt", || {
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<i64, i64, Purs_Data_Ordering::Ordering> <- purust_core::Func2<i64, i64, Purs_Data_Ordering::Ordering> : App(Var(...)) */{
        let mut eval_arg_0 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::LT;
        let mut eval_arg_1 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ;
        let mut eval_arg_2 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::GT;
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: i64, mut eta_1: i64| -> Purs_Data_Ordering::Ordering {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Ord_ordIntImpl(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone(), eta_1.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_int(), (_a1).unwrap_int()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqInt()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}

pub fn Data_Ord_ordChar() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ordChar", || {
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<char, char, Purs_Data_Ordering::Ordering> <- purust_core::Func2<char, char, Purs_Data_Ordering::Ordering> : App(Var(...)) */{
        let mut eval_arg_0 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::LT;
        let mut eval_arg_1 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ;
        let mut eval_arg_2 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::GT;
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: char, mut eta_1: char| -> Purs_Data_Ordering::Ordering {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Ord_ordCharImpl(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone(), eta_1.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_char(), (_a1).unwrap_char()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqChar()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}

pub fn Data_Ord_ordBoolean() -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ordBoolean", || {
std::rc::Rc::new(crate::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<bool, bool, Purs_Data_Ordering::Ordering> <- purust_core::Func2<bool, bool, Purs_Data_Ordering::Ordering> : App(Var(...)) */{
        let mut eval_arg_0 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::LT;
        let mut eval_arg_1 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ;
        let mut eval_arg_2 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::GT;
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: bool, mut eta_1: bool| -> Purs_Data_Ordering::Ordering {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Ord_ordBooleanImpl(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone(), eta_1.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_bool(), (_a1).unwrap_bool()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqBoolean()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}

pub fn Data_Ord_compareRecord(mut a0: std::rc::Rc<crate::OrdRecord>, mut a1: Purs_Type_Proxy::Proxy, mut a2: crate::UnknownType, mut a3: crate::UnknownType) -> Purs_Data_Ordering::Ordering {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func4::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::OrdRecord>| -> purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compareRecord.clone()
} as fn(std::rc::Rc<crate::OrdRecord>) -> purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering>)).clone(); move |mut _a0: std::rc::Rc<crate::OrdRecord>, mut _a1: Purs_Type_Proxy::Proxy, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> Purs_Data_Ordering::Ordering { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone(), _a3.clone()) } })))(a0.clone(), a1.clone(), a2.clone(), a3.clone())
}

pub fn Data_Ord_ordRecord(mut purs_local_0: crate::UnknownType, mut purs_local_1: std::rc::Rc<crate::OrdRecord>) -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : App(Var(...)) */Data_Eq_eqRec(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), ((purs_local_1.clone()).EqRecord0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::Ord { compare: /* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : App(Typed(Accessor(Local(...)))) */{
        let mut _fn_eval = (/* Typed purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_1).compareRecord.clone());
        let mut eval_arg_0 = /* Typed Purs_Type_Proxy::Proxy <- Purs_Type_Proxy::Proxy : CtorSaturated(...) */Purs_Type_Proxy::Proxy::Proxy;
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType, mut eta_1: crate::UnknownType| -> Purs_Data_Ordering::Ordering {
    let mut _fn_ptr = _fn_eval.clone();
    let mut eval_arg_0 = eval_arg_0.clone();
    _fn_ptr(eval_arg_0, eta_0.clone(), eta_1.clone())
}))
}, Eq0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}

pub fn Data_Ord_compare1(mut a0: std::rc::Rc<crate::Ord1>, mut a1: std::rc::Rc<crate::Ord>, mut a2: crate::UnknownType, mut a3: crate::UnknownType) -> Purs_Data_Ordering::Ordering {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func4::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Ord1>| -> purust_core::Func3<std::rc::Rc<crate::Ord>, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func3<std::rc::Rc<crate::Ord>, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func3<std::rc::Rc<crate::Ord>, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare1.clone()
} as fn(std::rc::Rc<crate::Ord1>) -> purust_core::Func3<std::rc::Rc<crate::Ord>, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering>)).clone(); move |mut _a0: std::rc::Rc<crate::Ord1>, mut _a1: std::rc::Rc<crate::Ord>, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> Purs_Data_Ordering::Ordering { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone(), _a3.clone()) } })))(a0.clone(), a1.clone(), a2.clone(), a3.clone())
}

pub fn Data_Ord_compare(mut a0: std::rc::Rc<crate::Ord>, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> Purs_Data_Ordering::Ordering {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Ord>| -> purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone()
} as fn(std::rc::Rc<crate::Ord>) -> purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering>)).clone(); move |mut _a0: std::rc::Rc<crate::Ord>, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> Purs_Data_Ordering::Ordering { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Data_Ord_comparing(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut purs_local_2: crate::UnknownType, mut purs_local_3: crate::UnknownType) -> Purs_Data_Ordering::Ordering {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(Typed(Accessor(Local(...)))))))))))))))
/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_1)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2), /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_1)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3))
}

pub fn Data_Ord_greaterThan(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(PrimOp(...)))))))))
/* Typed bool <- bool : PrimOp(...) *//* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2)), Purs_Data_Ordering::Ordering::GT)
}

pub fn Data_Ord_greaterThanOrEq(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(PrimOp(...)))))))))
/* Typed bool <- bool : PrimOp(...) */!(/* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2)), Purs_Data_Ordering::Ordering::LT) /* aTy: bool, a is PrimOp(...), fn ty is not app */)
}

pub fn Data_Ord_lessThan(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(PrimOp(...)))))))))
/* Typed bool <- bool : PrimOp(...) *//* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2)), Purs_Data_Ordering::Ordering::LT)
}

pub fn Data_Ord_signum(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: std::rc::Rc<Purs_Data_Ring::Ring>, mut purs_local_6: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut purs_local_2 = ((purs_local_1.clone()).Semiring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut purs_local_3 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Semiring_zero(purs_local_2.clone());
    {
    let mut purs_local_4 = /* Typed std::rc::Rc<Purs_Data_Semiring::Semiring> <- std::rc::Rc<Purs_Data_Semiring::Semiring> : App(Accessor(Local(...))) */((purs_local_1.clone()).Semiring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    {
    let mut purs_local_5 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Semiring_one(purs_local_2);
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* Typed bool <- bool : PrimOp(...) *//* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0.clone()).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_6.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3.clone())), Purs_Data_Ordering::Ordering::LT) {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_1.clone()).sub.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(App(Accessor(Local(...)))) */(((purs_local_1).Semiring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))).zero.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */(purs_local_4).one.clone())
    } else {
        /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* Typed bool <- bool : PrimOp(...) *//* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_6.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3)), Purs_Data_Ordering::Ordering::GT) {
        purs_local_5
    } else {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_6
    }
    }
}
}
}
}
}

pub fn Data_Ord_lessThanOrEq(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(PrimOp(...)))))))))
/* Typed bool <- bool : PrimOp(...) */!(/* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2)), Purs_Data_Ordering::Ordering::GT) /* aTy: bool, a is PrimOp(...), fn ty is not app */)
}

pub fn Data_Ord_max(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Let(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut purs_local_3 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2.clone());
    if /* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((purs_local_3.clone()), Purs_Data_Ordering::Ordering::LT) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2
    } else if /* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((purs_local_3.clone()), Purs_Data_Ordering::Ordering::EQ) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1
    } else if /* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((purs_local_3), Purs_Data_Ordering::Ordering::GT) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
}
}

pub fn Data_Ord_min(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Let(...)))))))))
/* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut purs_local_3 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2.clone());
    if /* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((purs_local_3.clone()), Purs_Data_Ordering::Ordering::LT) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1
    } else if /* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((purs_local_3.clone()), Purs_Data_Ordering::Ordering::EQ) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1
    } else if /* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((purs_local_3), Purs_Data_Ordering::Ordering::GT) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
}
}

pub fn Data_Ord_ordArray(mut purs_local_0: std::rc::Rc<crate::Ord>) -> std::rc::Rc<crate::Ord> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : App(Var(...)) */Data_Eq_eqArray(((purs_local_0.clone()).Eq0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::Ord { compare: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Var(...)) */Data_Ord_ordIntImpl(/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::LT, /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::EQ, /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : CtorSaturated(...) */Purs_Data_Ordering::Ordering::GT, /* Typed i64 <- i64 : Lit */0, /* Typed i64 <- i64 : App(TypeApp(Var(...))) */Data_Ord_ordArrayImpl(/* Typed Abs */{
    let mut purs_local_0 = purs_local_0.clone();
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> i64 {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    {
    let mut purs_local_6 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0.clone()).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_4, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_5);
    /* Typed i64 <- i64 : Branch(...) */if /* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((purs_local_6.clone()), Purs_Data_Ordering::Ordering::EQ) {
        /* Typed i64 <- i64 : Lit */0
    } else if /* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((purs_local_6.clone()), Purs_Data_Ordering::Ordering::LT) {
        /* Typed i64 <- i64 : Lit */1
    } else if /* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((purs_local_6), Purs_Data_Ordering::Ordering::GT) {
        /* Typed i64 <- i64 : Lit */-1
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
}
}))
}, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3))
})), Eq0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    purs_local_1.clone()
})) })
}
}

pub fn Data_Ord_ord1Array() -> std::rc::Rc<crate::Ord1> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ord1>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ord_ord1Array", || {
std::rc::Rc::new(crate::Ord1 { compare1: /* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Ord>| -> purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : App(Var(...)) */{
        let mut eval_arg_0 = Data_Ord_ordArray(purs_local_0);
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType, mut eta_1: crate::UnknownType| -> Purs_Data_Ordering::Ordering {
    let mut eval_arg_0 = eval_arg_0.clone();
    Data_Ord_compare(eval_arg_0, eta_0.clone(), eta_1.clone())
}))
}
} as fn(std::rc::Rc<crate::Ord>) -> purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering>)).clone(); move |mut _a0: std::rc::Rc<crate::Ord>, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> Purs_Data_Ordering::Ordering { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })), Eq10: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq1> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq1> <- std::rc::Rc<Purs_Data_Eq::Eq1> : Var(...) */Data_Eq_eq1Array()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq1>) })
}).clone())
}

pub fn Data_Ord_ordRecordCons(mut purs_local_0: std::rc::Rc<crate::OrdRecord>, mut purs_local_2: crate::UnknownType, mut purs_local_3: std::rc::Rc<Purs_Data_Symbol::IsSymbol>, mut purs_local_5: std::rc::Rc<crate::Ord>) -> std::rc::Rc<crate::OrdRecord> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = {
        let mut eval_arg_0 = ((purs_local_0.clone()).EqRecord0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
        let mut eval_arg_1 = purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }));
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: std::rc::Rc<Purs_Data_Symbol::IsSymbol>, mut eta_1: std::rc::Rc<Purs_Data_Eq::Eq>| -> std::rc::Rc<Purs_Data_Eq::EqRecord> {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    Data_Eq_eqRowCons(eval_arg_0, eval_arg_1, eta_0.clone(), eta_1.clone())
}))
};
    {
    let mut purs_local_4 = {
        let mut _fn_eval = (purs_local_1);
        let mut eval_arg_0 = purs_local_3.clone();
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: std::rc::Rc<Purs_Data_Eq::Eq>| -> std::rc::Rc<Purs_Data_Eq::EqRecord> {
    let mut _fn_ptr = _fn_eval.clone();
    let mut eval_arg_0 = eval_arg_0.clone();
    _fn_ptr(eval_arg_0, eta_0.clone())
}))
};
    {
    let mut purs_local_6 = /* Typed std::rc::Rc<Purs_Data_Eq::EqRecord> <- std::rc::Rc<Purs_Data_Eq::EqRecord> : App(Local(...)) */(purs_local_4)(((purs_local_5.clone()).Eq0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::OrdRecord { compareRecord: /* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new(move |mut _a0: Purs_Type_Proxy::Proxy, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> Purs_Data_Ordering::Ordering {
    let mut purs_local_8 = _a1;
    let mut purs_local_9 = _a2;
    drop(_a0);
    {
    let mut purs_local_10 = /* Typed String <- String : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func1<Purs_Type_Proxy::Proxy, String> <- purust_core::Func1<Purs_Type_Proxy::Proxy, String> : Accessor(Local(...)) */(purs_local_3.clone()).reflectSymbol.clone())(/* Typed Purs_Type_Proxy::Proxy <- Purs_Type_Proxy::Proxy : CtorSaturated(...) */Purs_Type_Proxy::Proxy::Proxy);
    {
    let mut purs_local_11 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_5.clone()).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Record_Unsafe_unsafeGet(/* Typed String <- String : Local(...) */purs_local_10.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_8.clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Record_Unsafe_unsafeGet(/* Typed String <- String : Local(...) */purs_local_10, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_9.clone()));
    /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Branch(...) */if /* Typed bool <- bool : PrimOp(...) */!(/* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((purs_local_11.clone()), Purs_Data_Ordering::Ordering::EQ) /* aTy: bool, a is PrimOp(...), fn ty is not app */) {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : Local(...) */purs_local_11
    } else {
        /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0.clone()).compareRecord.clone())(/* Typed Purs_Type_Proxy::Proxy <- Purs_Type_Proxy::Proxy : CtorSaturated(...) */Purs_Type_Proxy::Proxy::Proxy, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_8, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_9)
    }
}
}
})), EqRecord0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::EqRecord> {
    drop(_a0);
    purs_local_6.clone()
})) })
}
}
}
}

pub fn Data_Ord_clamp(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType, mut purs_local_3: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Let(...))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut purs_local_4 = /* Typed crate::UnknownType <- crate::UnknownType : Let(...) */{
    let mut purs_local_4 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0.clone()).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3.clone());
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((purs_local_4.clone()), Purs_Data_Ordering::Ordering::LT) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3
    } else if /* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((purs_local_4.clone()), Purs_Data_Ordering::Ordering::EQ) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1
    } else if /* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((purs_local_4.clone()), Purs_Data_Ordering::Ordering::GT) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
};
    {
    let mut purs_local_5 = /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_4.clone());
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((purs_local_5.clone()), Purs_Data_Ordering::Ordering::LT) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2
    } else if /* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((purs_local_5.clone()), Purs_Data_Ordering::Ordering::EQ) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2
    } else if /* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((purs_local_5), Purs_Data_Ordering::Ordering::GT) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_4
    } else {
        unimplemented!() /* Unsupported Expr: Fail */
    }
}
}
}

pub fn Data_Ord_between(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType, mut purs_local_3: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Branch(...)))))))))))
/* Typed bool <- bool : Branch(...) */if /* Typed bool <- bool : PrimOp(...) *//* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0.clone()).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1)), Purs_Data_Ordering::Ordering::LT) {
        /* Typed bool <- bool : Lit */false
    } else {
        !(/* Typed bool <- bool : PrimOp(...) *//* OpIsTag Debug: Data_Ordering_GT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2)), Purs_Data_Ordering::Ordering::GT) /* aTy: bool, a is Typed(Typed(Typed(PrimOp(...)))), fn ty is not app */)
    }
}

pub fn Data_Ord_abs(mut purs_local_0: std::rc::Rc<crate::Ord>, mut purs_local_1: std::rc::Rc<Purs_Data_Ring::Ring>, mut purs_local_3: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut purs_local_2 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Semiring_zero(((purs_local_1.clone()).Semiring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    /* Typed crate::UnknownType <- crate::UnknownType : Branch(...) */if /* Typed bool <- bool : PrimOp(...) */!(/* OpIsTag Debug: Data_Ordering_LT -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Accessor(Local(...)) */(purs_local_0).compare.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2)), Purs_Data_Ordering::Ordering::LT) /* aTy: bool, a is PrimOp(...), fn ty is not app */) {
        /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3
    } else {
        /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_1.clone()).sub.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(App(Accessor(Local(...)))) */(((purs_local_1).Semiring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))).zero.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3)
    }
}
}



pub fn Data_Ord_ordIntImpl(mut lt: Purs_Data_Ordering::Ordering, mut eq: Purs_Data_Ordering::Ordering, mut gt: Purs_Data_Ordering::Ordering, mut a: i64, mut b: i64) -> Purs_Data_Ordering::Ordering {
    match a.cmp(&b) {
        std::cmp::Ordering::Less => lt,
        std::cmp::Ordering::Equal => eq,
        std::cmp::Ordering::Greater => gt,
    }
}

pub fn Data_Ord_ordNumberImpl(mut lt: Purs_Data_Ordering::Ordering, mut eq: Purs_Data_Ordering::Ordering, mut gt: Purs_Data_Ordering::Ordering, mut a: f64, mut b: f64) -> Purs_Data_Ordering::Ordering {
    if a < b { lt }
    else if a > b { gt }
    else { eq }
}

pub fn Data_Ord_ordCharImpl(mut lt: Purs_Data_Ordering::Ordering, mut eq: Purs_Data_Ordering::Ordering, mut gt: Purs_Data_Ordering::Ordering, mut a: char, mut b: char) -> Purs_Data_Ordering::Ordering {
    match a.cmp(&b) {
        std::cmp::Ordering::Less => lt,
        std::cmp::Ordering::Equal => eq,
        std::cmp::Ordering::Greater => gt,
    }
}

pub fn Data_Ord_ordStringImpl(mut lt: Purs_Data_Ordering::Ordering, mut eq: Purs_Data_Ordering::Ordering, mut gt: Purs_Data_Ordering::Ordering, mut a: String, mut b: String) -> Purs_Data_Ordering::Ordering {
    match a.cmp(&b) {
        std::cmp::Ordering::Less => lt,
        std::cmp::Ordering::Equal => eq,
        std::cmp::Ordering::Greater => gt,
    }
}

pub fn Data_Ord_ordBooleanImpl(mut lt: Purs_Data_Ordering::Ordering, mut eq: Purs_Data_Ordering::Ordering, mut gt: Purs_Data_Ordering::Ordering, mut a: bool, mut b: bool) -> Purs_Data_Ordering::Ordering {
    match a.cmp(&b) {
        std::cmp::Ordering::Less => lt,
        std::cmp::Ordering::Equal => eq,
        std::cmp::Ordering::Greater => gt,
    }
}

pub fn Data_Ord_ordArrayImpl(mut f: purust_core::Func2<crate::UnknownType, crate::UnknownType, i64>, mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> i64 {
    let arr1 = a0.unwrap_array();
    let arr2 = a1.unwrap_array();
    let len = std::cmp::min(arr1.len(), arr2.len());
    for i in 0..len {
        let cmp = f(arr1[i].clone(), arr2[i].clone());
        if cmp != 0 {
            return cmp;
        }
    }
    match arr1.len().cmp(&arr2.len()) {
        std::cmp::Ordering::Less => -1,
        std::cmp::Ordering::Equal => 0,
        std::cmp::Ordering::Greater => 1,
    }
}




