#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Alt::*;
use Purs_Control_Alternative::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Comonad::*;
use Purs_Control_Extend::*;
use Purs_Control_Lazy::*;
use Purs_Control_Monad::*;
use Purs_Control_MonadPlus::*;
use Purs_Control_Plus::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Bifunctor::*;
use Purs_Data_Boolean::*;
use Purs_Data_BooleanAlgebra::*;
use Purs_Data_Bounded::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Const::*;
use Purs_Data_Either::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Foldable::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_Functor_App::*;
use Purs_Data_Functor_Compose::*;
use Purs_Data_Functor_Coproduct::*;
use Purs_Data_Functor_Invariant::*;
use Purs_Data_Functor_Product::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Identity::*;
use Purs_Data_Maybe::*;
use Purs_Data_Maybe_First::*;
use Purs_Data_Maybe_Last::*;
use Purs_Data_Monoid::*;
use Purs_Data_Monoid_Additive::*;
use Purs_Data_Monoid_Alternate::*;
use Purs_Data_Monoid_Conj::*;
use Purs_Data_Monoid_Disj::*;
use Purs_Data_Monoid_Dual::*;
use Purs_Data_Monoid_Endo::*;
use Purs_Data_Monoid_Multiplicative::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ord::*;
use Purs_Data_Ord_Max::*;
use Purs_Data_Ord_Min::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semigroup_Foldable::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_String_CodeUnits::*;
use Purs_Data_String_Common::*;
use Purs_Data_String_NonEmpty_Internal::*;
use Purs_Data_String_Pattern::*;
use Purs_Data_String_Unsafe::*;
use Purs_Data_Symbol::*;
use Purs_Data_Tuple::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Record_Unsafe::*;
use Purs_Safe_Coerce::*;
use Purs_Type_Proxy::*;
use Purs_Unsafe_Coerce::*;
use Purs_Data_Eq::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ord::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Show::*;
use Purs_Data_String_NonEmpty_Internal::*;
use Purs_Data_Ordering::*;

// Code generated by purust for module Data_String_NonEmpty_CaseInsensitive



pub fn Data_String_NonEmpty_CaseInsensitive_CaseInsensitiveNonEmptyString(mut purs_local_0: String) -> String {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_String_NonEmpty_CaseInsensitive_showCaseInsensitiveNonEmptyString() -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Show::Show>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_CaseInsensitive_showCaseInsensitiveNonEmptyString", || {
std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: String| -> String {
    let mut purs_local_0 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(CaseInsensitiveNonEmptyString (NonEmptyString.unsafeFromString "), Data_Show_showStringImpl(/* Typed String <- String : Local(...) */purs_local_0)), String::from("))"))
} as fn(String) -> String)).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_string()) } })) })
}).clone())
}

pub fn Data_String_NonEmpty_CaseInsensitive_newtypeCaseInsensitiveNonEmptyString() -> std::rc::Rc<Purs_Data_Newtype::Newtype> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Newtype::Newtype>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_CaseInsensitive_newtypeCaseInsensitiveNonEmptyString", || {
std::rc::Rc::new(Purs_Data_Newtype::Newtype { Coercible0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
} as fn(crate::UnknownType) -> crate::UnknownType) })
}).clone())
}

pub fn Data_String_NonEmpty_CaseInsensitive_eqCaseInsensitiveNonEmptyString() -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Eq::Eq>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_CaseInsensitive_eqCaseInsensitiveNonEmptyString", || {
std::rc::Rc::new(Purs_Data_Eq::Eq { eq: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: String, mut _a1: String| -> bool {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed bool <- bool : PrimOp(...) */(Data_String_Common_toLower(/* Typed String <- String : Local(...) */purs_local_0) == /* Typed String <- String : App(Var(...)) */Data_String_Common_toLower(/* Typed String <- String : Local(...) */purs_local_1))
} as fn(String, String) -> bool)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> bool { _f((_a0).unwrap_string(), (_a1).unwrap_string()) } })) })
}).clone())
}

pub fn Data_String_NonEmpty_CaseInsensitive_ordCaseInsensitiveNonEmptyString() -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Ord::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_CaseInsensitive_ordCaseInsensitiveNonEmptyString", || {
std::rc::Rc::new(Purs_Data_Ord::Ord { compare: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: String, mut _a1: String| -> Purs_Data_Ordering::Ordering {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Accessor(Var(...))) */((Data_Ord_ordString()).compare.clone())(purust_core::Value::String(/* Typed String <- String : App(Var(...)) */Data_String_Common_toLower(/* Typed String <- String : Local(...) */purs_local_0)), purust_core::Value::String(/* Typed String <- String : App(Var(...)) */Data_String_Common_toLower(/* Typed String <- String : Local(...) */purs_local_1)))
} as fn(String, String) -> Purs_Data_Ordering::Ordering)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> Purs_Data_Ordering::Ordering { _f((_a0).unwrap_string(), (_a1).unwrap_string()) } })), Eq0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Eq::Eq> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_String_NonEmpty_CaseInsensitive_eqCaseInsensitiveNonEmptyString()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Eq::Eq>) })
}).clone())
}





