let AdtMultiConsumer_viaReturned  = (box AdtMulti_returned)

let AdtMultiConsumer_orderedPartial  = (box (fun (tree: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box AdtMulti_assemble))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackColor))) (box ((box 1)))))) (box ((box (AdtMulti_Onyx_adt_native)))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackTree))) (box ((box 2)))))) (box ((box tree)))))))))

let AdtMultiConsumer_ordered  = (box (fun (tree: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMulti_assemble))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackColor))) (box ((box 1)))))) (box ((box (AdtMulti_Onyx_adt_native)))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackTree))) (box ((box 2)))))) (box ((box tree))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackInt))) (box ((box 3)))))) (box ((box 7))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackTree))) (box ((box 4)))))) (box ((box tree)))))))))

let AdtMultiConsumer_lastArgumentFailure  = (box (fun (tree: obj) -> (box (fun (bad: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box AdtMulti_readNonEmpty))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackTree))) (box ((box 1)))))) (box ((box tree))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackInt))) (box ((box 2)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMulti_readNonEmpty))) (box ((box bad)))))) (box ((box 0))))))))))))))

let AdtMultiConsumer_firstArgumentFailure  = (box (fun (bad: obj) -> (box (fun (tree: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMulti_choose))) (box ((box true)))))) (box ((box tree)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackInt))) (box ((box 1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMulti_readNonEmpty))) (box ((box bad)))))) (box ((box 0)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box AdtMultiConsumer_trackTree))) (box ((box 2)))))) (box ((box tree)))))))))))

let AdtMultiConsumer_captured  = (box AdtMulti_insert)