(library (Test.ArrayOpsFFI foreign)
  (export runArrayOpsFFI)
  (import (chezscheme))
  (define (range-from-one limit)
    (let* ([size (+ 1 (abs (- limit 1)))]
           [step (if (>= limit 1) 1 -1)]
           [input (make-vector size)])
      (do ([i 0 (+ i 1)]) ((= i size))
        (vector-set! input i (+ 1 (* i step))))
      input))
  (define (filter-array predicate input)
    (let* ([size (vector-length input)] [buffer (make-vector size)])
      (let filter-loop ([i 0] [j 0])
        (if (= i size)
            (let ([result (make-vector j)])
              (do ([k 0 (+ k 1)]) ((= k j))
                (vector-set! result k (vector-ref buffer k)))
              result)
            (let ([value (vector-ref input i)])
              (if (predicate value)
                  (begin (vector-set! buffer j value) (filter-loop (+ i 1) (+ j 1)))
                  (filter-loop (+ i 1) j)))))))
  (define (fold-array combine initial input)
    (let loop ([i 0] [acc initial])
      (if (= i (vector-length input)) acc
          (loop (+ i 1) (combine acc (vector-ref input i))))))
  (define (runArrayOpsFFI limit)
    (fold-array + 0 (filter-array (lambda (value) (= (modulo value 2) 0))
                                 (range-from-one limit)))))
