(library (Test.ChurchFFI foreign)
  (export runChurchFFI)
  (import (chezscheme))
  (define (zero-c f) (lambda (x) x))
  (define (succ-c n) (lambda (f) (lambda (x) (f ((n f) x)))))
  (define (mul-c m n) (lambda (f) (lambda (x) ((m (n f)) x))))
  (define (from-int n)
    (if (= n 0) zero-c (succ-c (from-int (- n 1)))))
  (define (c100 n) (mul-c (from-int n) (from-int n)))
  (define (c10k n) (mul-c (c100 n) (c100 n)))
  (define (runChurchFFI n)
    (((mul-c (c10k n) (from-int n)) (lambda (x) (+ x 1))) 0)))
