(library (Test.PrimesFFICheatcode foreign)
  (export runPrimesFFICheatcode)
  (import (chezscheme))

  (define (runPrimesFFICheatcode limit)
    (if (< limit 2)
        0
        (let ([sieve (make-vector (+ limit 1) #t)]
              [sum 0])
          (let loop ([p 2])
            (when (<= (* p p) limit)
              (when (vector-ref sieve p)
                (let inner ([i (* p p)])
                  (when (<= i limit)
                    (vector-set! sieve i #f)
                    (inner (+ i p)))))
              (loop (+ p 1))))
          (let sum-loop ([p 2])
            (when (<= p limit)
              (when (vector-ref sieve p)
                (set! sum (+ sum p)))
              (sum-loop (+ p 1))))
          sum)))
)
