#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Alt::*;
use Purs_Control_Alternative::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Biapply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Comonad::*;
use Purs_Control_Extend::*;
use Purs_Control_Lazy::*;
use Purs_Control_Monad::*;
use Purs_Control_Plus::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Bifunctor::*;
use Purs_Data_Boolean::*;
use Purs_Data_BooleanAlgebra::*;
use Purs_Data_Bounded::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Const::*;
use Purs_Data_Either::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_Functor_Invariant::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Maybe::*;
use Purs_Data_Monoid::*;
use Purs_Data_Monoid_Additive::*;
use Purs_Data_Monoid_Alternate::*;
use Purs_Data_Monoid_Conj::*;
use Purs_Data_Monoid_Disj::*;
use Purs_Data_Monoid_Dual::*;
use Purs_Data_Monoid_Endo::*;
use Purs_Data_Monoid_Multiplicative::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ord::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Tuple::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Record_Unsafe::*;
use Purs_Safe_Coerce::*;
use Purs_Type_Proxy::*;
use Purs_Unsafe_Coerce::*;
use Purs_Control_Biapply::*;
use Purs_Data_Tuple::*;
use Purs_Record_Unsafe::*;

// Code generated by purust for module Control_Biapplicative


#[derive(Clone)]
pub struct Biapplicative {
    pub Biapply0: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Control_Biapply::Biapply>>,
    pub bipure: purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType>
}

pub fn Control_Biapplicative_bipure(mut a0: std::rc::Rc<crate::Biapplicative>, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Biapplicative>| -> purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_0).bipure.clone()
} as fn(std::rc::Rc<crate::Biapplicative>) -> purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType>)).clone(); move |mut _a0: std::rc::Rc<crate::Biapplicative>, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Control_Biapplicative_biapplicativeTuple() -> std::rc::Rc<crate::Biapplicative> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Biapplicative>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Control_Biapplicative_biapplicativeTuple", || {
std::rc::Rc::new(crate::Biapplicative { bipure: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, std::rc::Rc<Purs_Data_Tuple::Tuple>> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, std::rc::Rc<Purs_Data_Tuple::Tuple>> : Var(...) */purust_core::Func2::Static(Data_Tuple_Tuple)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f(_a0, _a1))) } })), Biapply0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Control_Biapply::Biapply> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Control_Biapply::Biapply> <- std::rc::Rc<Purs_Control_Biapply::Biapply> : Var(...) */Control_Biapply_biapplyTuple()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Control_Biapply::Biapply>) })
}).clone())
}





