% Generated by purerl version 0.0.24
-module(data_ring@ps).
-export([subRecord/0, subRecord/4, subRecord/1, sub/0, sub/3, sub/1, ringUnit/0, ringRecordNil/0, ringRecordCons/0, ringRecord/0, ringProxy3/0, ringProxy2/0, ringProxy/0, ringNumber/0, ringInt/0, ringFn/0, negate/0, negate/2, negate/1]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./data_ring.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 0).
-spec semiringRecord() -> any().
semiringRecord() -> ((data_semiring@ps:semiringRecord())(undefined)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 0).
-spec semiringRecord(any()) -> any().
semiringRecord(_@1) -> ((semiringRecord())(_@1)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 63).
-spec subRecord() -> fun((any()) -> fun((any()) -> fun((map()) -> fun((map()) -> map())))).
subRecord() -> fun (Dict) ->
  case Dict of
    (_@2) -> (maps:get(subRecord, _@2))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 63).
-spec subRecord(any(),any(),map(),map()) -> map().
subRecord(_@8,_@9,_@10,_@11) -> (((((subRecord())(_@8))(_@9))(_@10))(_@11)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 63).
-spec subRecord(any()) -> any().
subRecord(_@3) -> case _@3 of
  (_@7) -> (maps:get(subRecord, _@7))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 24).
-spec sub() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
sub() -> fun (Dict) ->
  case Dict of
    (_@12) -> (maps:get(sub, _@12))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 24).
-spec sub(any(),any(),any()) -> any().
sub(_@17,_@18,_@19) -> ((((sub())(_@17))(_@18))(_@19)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 24).
-spec sub(any()) -> any().
sub(_@13) -> case _@13 of
  (_@16) -> (maps:get(sub, _@16))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 34).
-spec ringUnit() -> any().
ringUnit() -> #{sub=>fun (V) ->
  fun (V1) ->
    unit
  end
end, 'Semiring0'=>fun (_) ->
  (data_semiring@ps:semiringUnit())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 65).
-spec ringRecordNil() -> any().
ringRecordNil() -> #{subRecord=>fun (V) ->
  fun (V1) ->
    fun (V2) ->
      #{}
    end
  end
end, 'SemiringRecord0'=>fun (_) ->
  (data_semiring@ps:semiringRecordNil())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 68).
-spec ringRecordCons() -> any().
ringRecordCons() -> fun (DictIsSymbol) ->
  ReflectSymbol@38 = (?MEMOIZE((data_symbol@ps:reflectSymbol(DictIsSymbol)))),
  SemiringRecordCons@39 = (((data_semiring@ps:semiringRecordCons())(DictIsSymbol))(undefined)),
  fun (_) ->
    fun (DictRingRecord) ->
      SubRecord1@40 = (?MEMOIZE((subRecord(DictRingRecord)))),
      SemiringRecordCons1@41 = (SemiringRecordCons@39(((maps:get('SemiringRecord0', DictRingRecord))(undefined)))),
      fun (DictRing) ->
        Sub1@42 = (?MEMOIZE((sub(DictRing)))),
        SemiringRecordCons2@43 = (SemiringRecordCons1@41(((maps:get('Semiring0', DictRing))(undefined)))),
        #{subRecord=>fun (V) ->
          fun (Ra) ->
            fun (Rb) ->
              Tail@44 = (((SubRecord1@40({ proxy }))(Ra))(Rb)),
              Key@45 = (ReflectSymbol@38({ proxy })),
              Insert@46 = ((record_unsafe@ps:unsafeSet())(Key@45)),
              Get@47 = ((record_unsafe@ps:unsafeGet())(Key@45)),
              ((Insert@46(((Sub1@42((Get@47(Ra))))((Get@47(Rb))))))(Tail@44))
            end
          end
        end, 'SemiringRecord0'=>fun (_) ->
          SemiringRecordCons2@43
        end}
      end
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 49).
-spec ringRecord() -> any().
ringRecord() -> fun (_) ->
  fun (DictRingRecord) ->
    SemiringRecord1@48 = (?MEMOIZE((semiringRecord(((maps:get('SemiringRecord0', DictRingRecord))(undefined)))))),
    #{sub=>((subRecord(DictRingRecord))({ proxy })), 'Semiring0'=>fun (_) ->
      SemiringRecord1@48
    end}
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 46).
-spec ringProxy3() -> any().
ringProxy3() -> #{sub=>fun (V) ->
  fun (V1) ->
    { proxy3 }
  end
end, 'Semiring0'=>fun (_) ->
  (data_semiring@ps:semiringProxy3())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 43).
-spec ringProxy2() -> any().
ringProxy2() -> #{sub=>fun (V) ->
  fun (V1) ->
    { proxy2 }
  end
end, 'Semiring0'=>fun (_) ->
  (data_semiring@ps:semiringProxy2())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 40).
-spec ringProxy() -> any().
ringProxy() -> #{sub=>fun (V) ->
  fun (V1) ->
    { proxy }
  end
end, 'Semiring0'=>fun (_) ->
  (data_semiring@ps:semiringProxy())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 31).
-spec ringNumber() -> any().
ringNumber() -> #{sub=>(numSub()), 'Semiring0'=>fun (_) ->
  (data_semiring@ps:semiringNumber())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 28).
-spec ringInt() -> any().
ringInt() -> #{sub=>(intSub()), 'Semiring0'=>fun (_) ->
  (data_semiring@ps:semiringInt())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 37).
-spec ringFn() -> any().
ringFn() -> fun (DictRing) ->
  Sub1@49 = (?MEMOIZE((sub(DictRing)))),
  SemiringFn@50 = ((data_semiring@ps:semiringFn())(((maps:get('Semiring0', DictRing))(undefined)))),
  #{sub=>fun (F) ->
    fun (G) ->
      fun (X) ->
        ((Sub1@49((F(X))))((G(X))))
      end
    end
  end, 'Semiring0'=>fun (_) ->
    SemiringFn@50
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 53).
-spec negate() -> fun((any()) -> fun((any()) -> any())).
negate() -> fun (DictRing) ->
  Sub1@51 = (?MEMOIZE((sub(DictRing)))),
  Zero@52 = (?MEMOIZE((data_semiring@ps:zero(((maps:get('Semiring0', DictRing))(undefined)))))),
  fun (A) ->
    ((Sub1@51(Zero@52))(A))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 53).
-spec negate(any(),any()) -> any().
negate(_@22,_@23) -> (((negate())(_@22))(_@23)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Ring.purs", 53).
-spec negate(any()) -> any().
negate(_@20) -> 
  Sub1@53 = (?MEMOIZE((sub(_@20)))),
  Zero@54 = (?MEMOIZE((data_semiring@ps:zero(((maps:get('Semiring0', _@20))(undefined)))))),
  fun (A) ->
    ((Sub1@53(Zero@54))(A))
  end
.
-spec intSub() -> any().
intSub() -> fun (_@24) ->
  fun (_@25) ->
    (data_ring@foreign:intSub(_@24, _@25))
  end
end.
-spec numSub() -> any().
numSub() -> fun (_@31) ->
  fun (_@32) ->
    (data_ring@foreign:numSub(_@31, _@32))
  end
end.
