% Generated by purerl version 0.0.24
-module(data_show@ps).
-export([showString/0, showRecordFieldsNil/0, showRecordFields/0, showRecordFields/3, showRecordFields/1, showRecord/0, showProxy3/0, showProxy2/0, showProxy/0, showNumber/0, showInt/0, showChar/0, showBoolean/0, show/0, show/2, show/1, showArray/0, showRecordFieldsCons/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./data_show.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 33).
-spec showString() -> any().
showString() -> #{show=>fun showStringImpl/1}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 59).
-spec showRecordFieldsNil() -> any().
showRecordFieldsNil() -> #{showRecordFields=>fun (V) ->
  fun (V1) ->
    (array:from_list([]))
  end
end}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 57).
-spec showRecordFields() -> fun((any()) -> fun((any()) -> fun((map()) -> array:array(binary())))).
showRecordFields() -> fun (Dict) ->
  case Dict of
    (_@0) -> (maps:get(showRecordFields, _@0))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 57).
-spec showRecordFields(any(),any(),map()) -> array:array(binary()).
showRecordFields(_@5,_@6,_@7) -> ((((showRecordFields())(_@5))(_@6))(_@7)).
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 57).
-spec showRecordFields(any()) -> any().
showRecordFields(_@1) -> case _@1 of
  (_@4) -> (maps:get(showRecordFields, _@4))
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 48).
-spec showRecord() -> any().
showRecord() -> fun (_) ->
  fun (DictShowRecordFields) ->
    ShowRecordFields1@54 = (?MEMOIZE((showRecordFields(DictShowRecordFields)))),
    #{show=>fun (Record) ->
      V@55 = ((ShowRecordFields1@54({ proxy }))(Record)),
      _@9@56 = (array:to_list(V@55)),
      (fun
        Case(_@8, []) -> 
        <<"{}"/utf8>>;
        Case(_@10, _) -> 
        (data_show@foreign:join(<<" "/utf8>>, (array:from_list([<<"{"/utf8>>, (data_show@foreign:join(<<", "/utf8>>, _@10)), <<"}"/utf8>>]))))
      end(V@55, _@9@56))
    end}
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 45).
-spec showProxy3() -> any().
showProxy3() -> #{show=>fun (V) ->
  <<"Proxy3"/utf8>>
end}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 42).
-spec showProxy2() -> any().
showProxy2() -> #{show=>fun (V) ->
  <<"Proxy2"/utf8>>
end}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 39).
-spec showProxy() -> any().
showProxy() -> #{show=>fun (V) ->
  <<"Proxy"/utf8>>
end}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 27).
-spec showNumber() -> any().
showNumber() -> #{show=>fun showNumberImpl/1}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 24).
-spec showInt() -> any().
showInt() -> #{show=>fun showIntImpl/1}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 30).
-spec showChar() -> any().
showChar() -> #{show=>fun showCharImpl/1}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 20).
-spec showBoolean() -> any().
showBoolean() -> #{show=>fun (V) ->
  case V of
    (true) -> <<"true"/utf8>>;
    (false) -> <<"false"/utf8>>
  end
end}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 18).
-spec show() -> fun((any()) -> fun((any()) -> binary())).
show() -> fun (Dict) ->
  case Dict of
    (_@11) -> (maps:get(show, _@11))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 18).
-spec show(any(),any()) -> binary().
show(_@15,_@16) -> (((show())(_@15))(_@16)).
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 18).
-spec show(any()) -> any().
show(_@12) -> case _@12 of
  (_@14) -> (maps:get(show, _@14))
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 36).
-spec showArray() -> any().
showArray() -> fun (DictShow) ->
  #{show=>((showArrayImpl())((?MEMOIZE((show(DictShow))))))}
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Show.purs", 62).
-spec showRecordFieldsCons() -> any().
showRecordFieldsCons() -> fun (DictIsSymbol) ->
  ReflectSymbol@57 = (?MEMOIZE((data_symbol@ps:reflectSymbol(DictIsSymbol)))),
  fun (DictShowRecordFields) ->
    ShowRecordFields1@58 = (?MEMOIZE((showRecordFields(DictShowRecordFields)))),
    fun (DictShow) ->
      Show1@59 = (?MEMOIZE((show(DictShow)))),
      #{showRecordFields=>fun (V) ->
        fun (Record) ->
          Tail@60 = ((ShowRecordFields1@58({ proxy }))(Record)),
          Key@61 = (ReflectSymbol@57({ proxy })),
          Focus@62 = (record_unsafe@ps:unsafeGet(Key@61, Record)),
          (data_show@foreign:cons((data_show@foreign:join(<<": "/utf8>>, (array:from_list([Key@61, (Show1@59(Focus@62))])))), Tail@60))
        end
      end}
    end
  end
end.
-spec showIntImpl() -> any().
showIntImpl() -> fun (_@17) ->
  (data_show@foreign:showIntImpl(_@17))
end.
-spec showIntImpl(any()) -> any().
showIntImpl(_@20) -> ((showIntImpl())(_@20)).
-spec showNumberImpl() -> any().
showNumberImpl() -> fun (_@21) ->
  (data_show@foreign:showNumberImpl(_@21))
end.
-spec showNumberImpl(any()) -> any().
showNumberImpl(_@24) -> ((showNumberImpl())(_@24)).
-spec showCharImpl() -> any().
showCharImpl() -> fun (_@25) ->
  (data_show@foreign:showCharImpl(_@25))
end.
-spec showCharImpl(any()) -> any().
showCharImpl(_@28) -> ((showCharImpl())(_@28)).
-spec showStringImpl() -> any().
showStringImpl() -> fun (_@29) ->
  (data_show@foreign:showStringImpl(_@29))
end.
-spec showStringImpl(any()) -> any().
showStringImpl(_@32) -> ((showStringImpl())(_@32)).
-spec showArrayImpl() -> any().
showArrayImpl() -> fun (_@33) ->
  fun (_@34) ->
    (data_show@foreign:showArrayImpl(_@33, _@34))
  end
end.
