#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Bench::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Monad::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Boolean::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Monoid::*;
use Purs_Data_Ord::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Effect::*;
use Purs_Effect_Console::*;
use Purs_Record_Unsafe::*;
use Purs_Test_AckermannFFICheatcode::*;
use Purs_Test_ArrayOpsFFICheatcode::*;
use Purs_Test_AstTreeFFICheatcode::*;
use Purs_Test_ChurchFFICheatcode::*;
use Purs_Test_FibFFICheatcode::*;
use Purs_Test_LazyEvaluationFFICheatcode::*;
use Purs_Test_ListOpsFFICheatcode::*;
use Purs_Test_PolymorphismFFICheatcode::*;
use Purs_Test_PrimesFFICheatcode::*;
use Purs_Test_RBTreeFFICheatcode::*;
use Purs_Test_RecordsFFICheatcode::*;
use Purs_Test_RowToListFFICheatcode::*;
use Purs_Test_StateMonadFFICheatcode::*;
use Purs_Test_TCOFFICheatcode::*;
use Purs_Type_Proxy::*;
use Purs_Bench::*;
use Purs_Control_Bind::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Effect::*;
use Purs_Effect_Console::*;
use Purs_Test_AckermannFFICheatcode::*;
use Purs_Test_ArrayOpsFFICheatcode::*;
use Purs_Test_AstTreeFFICheatcode::*;
use Purs_Test_ChurchFFICheatcode::*;
use Purs_Test_FibFFICheatcode::*;
use Purs_Test_LazyEvaluationFFICheatcode::*;
use Purs_Test_ListOpsFFICheatcode::*;
use Purs_Test_PolymorphismFFICheatcode::*;
use Purs_Test_PrimesFFICheatcode::*;
use Purs_Test_RBTreeFFICheatcode::*;
use Purs_Test_RecordsFFICheatcode::*;
use Purs_Test_RowToListFFICheatcode::*;
use Purs_Test_StateMonadFFICheatcode::*;
use Purs_Test_TCOFFICheatcode::*;

// Code generated by purust for module AppFFICheatcode



pub fn AppFFICheatcode_warmup() -> crate::UnknownType {
    // AST: Typed(Typed(App(Var(...))))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<crate::UnknownType> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("AppFFICheatcode_warmup", || {
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_AstTreeFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_FibFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ListOpsFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_TCOFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RecordsFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_AckermannFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ChurchFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_PrimesFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RBTreeFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_PolymorphismFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_StateMonadFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_LazyEvaluationFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ArrayOpsFFICheatcode_act()), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Var(...))) */((Effect_functorEffect()).map.clone())(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> () {
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn(crate::UnknownType) -> ())).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f(_a0)) } })), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RowToListFFICheatcode_act())
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
}).clone())
}

pub fn AppFFICheatcode_main() -> crate::UnknownType {
    // AST: Typed(Typed(App(Var(...))))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<crate::UnknownType> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("AppFFICheatcode_main", || {
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_log(/* Typed String <- String : Lit */String::from("Global warm-up in progress (this may take a moment)...\u{a}")), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */AppFFICheatcode_warmup(), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */AppFFICheatcode_warmup(), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */AppFFICheatcode_warmup(), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Control_Bind_bind(Effect_bindEffect(), /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_log(/* Typed String <- String : Lit */String::from("Global warm-up complete. Starting benchmarks...\u{a}")), /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    {
    purust_core::Value::Func1(purust_core::Func1::Static(|mut _u: crate::UnknownType| -> crate::UnknownType {
        {
    let mut purs_local_5 = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_AstTreeFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_AstTreeFFICheatcode_act());
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_6 = ({
        let _val_eval = purs_local_5;
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_7 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_FibFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_FibFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_8 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ListOpsFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ListOpsFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_9 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_TCOFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_TCOFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_10 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RecordsFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RecordsFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_11 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_AckermannFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_AckermannFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_12 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ChurchFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ChurchFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_13 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_PrimesFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_PrimesFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_14 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RBTreeFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RBTreeFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_15 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_PolymorphismFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_PolymorphismFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_16 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_StateMonadFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_StateMonadFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_17 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_LazyEvaluationFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_LazyEvaluationFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_18 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ArrayOpsFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_ArrayOpsFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_19 = ({
        let _val_eval = Bench_runBench(/* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RowToListFFICheatcode_describe(), /* Typed crate::UnknownType <- crate::UnknownType : Var(...) */Test_RowToListFFICheatcode_act());
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }).unwrap_number();
    {
        let _val_eval = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_log(/* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("\u{a}==================================================\u{a}\u{a}Total exec time: "), Bench_formatNumber(/* Typed f64 <- f64 : PrimOp(...) */((((((((((((((purs_local_6 / /* Typed f64 <- f64 : Lit */1000.0) + (purs_local_7 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_8 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_9 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_10 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_11 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_12 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_13 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_14 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_15 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_16 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_17 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_18 / /* Typed f64 <- f64 : Lit */1000.0)) + (purs_local_19 / /* Typed f64 <- f64 : Lit */1000.0)))), String::from(" ms\u{a}")));
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    }
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
    } as fn(crate::UnknownType) -> crate::UnknownType))
}
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
} as fn(crate::UnknownType) -> crate::UnknownType))
}).clone())
}

pub use AppFFICheatcode_main as main;





