package main

// Generated by backend-go (Phase 2, optimizer IR). Module: Data.Ring

var Data_Ring_ringNumber any
func init() {
Data_Ring_ringNumber = _lazy(func() any { return map[string]any{"sub": _force(Data_Ring_numSub), "Semiring0": func(v0_unused any) any {
return _force(Data_Semiring_semiringNumber)
}} })
}