package main

// Generated by backend-go (Phase 2, optimizer IR). Module: Test.Ackermann

var Test_Ackermann_describe any
var Test_Ackermann_ackermann any
var Test_Ackermann_act any
func init() {
Test_Ackermann_describe = _lazy(func() any { return (_force(Effect_Console_log)).(func(any) any)("Ackermann (3, 4):") })
Test_Ackermann_ackermann = _lazy(func() any { return func(v0_v any) any {
return func(v1_v1 any) any {
return func() any {
if _truthy(_intEq(v0_v, 0)) { return _intAdd(v1_v1, 1) }
if _truthy(_intEq(v1_v1, 0)) { return ((_force(Test_Ackermann_ackermann)).(func(any) any)(_intSub(v0_v, 1))).(func(any) any)(1) }
return ((_force(Test_Ackermann_ackermann)).(func(any) any)(_intSub(v0_v, 1))).(func(any) any)(((_force(Test_Ackermann_ackermann)).(func(any) any)(v0_v)).(func(any) any)(_intSub(v1_v1, 1)))
}()
}
} })
Test_Ackermann_act = _lazy(func() any { return (((_force(Effect_bindEffect)).(map[string]any)["bind"]).(func(any) any)((_force(Bench_opaque)).(func(any) any)(3))).(func(any) any)(func(v0_dummy any) any {
return (_force(Effect_Console_log)).(func(any) any)(((_force(Data_Show_showInt)).(map[string]any)["show"]).(func(any) any)(((_force(Test_Ackermann_ackermann)).(func(any) any)(v0_dummy)).(func(any) any)(4)))
}) })
}