package main

// Generated by backend-go (Phase 2, optimizer IR). Module: Test.ListOps

var Test_ListOps_lessThan any
var Test_ListOps_range_ any
var Test_ListOps_foldl any
var Test_ListOps_filterEvens any
var Test_ListOps_describe any
var Test_ListOps_act any
func init() {
Test_ListOps_lessThan = _lazy(func() any { return func() any {
var v0 any = (((_force(Data_Ord_ordIntImpl)).(func(any) any)(V{Tag: "LT", Fields: []any{}})).(func(any) any)(V{Tag: "EQ", Fields: []any{}})).(func(any) any)(V{Tag: "GT", Fields: []any{}})
_ = v0
return func(v1_a1 any) any {
return func(v2_a2 any) any {
return func() any {
if _truthy(_isTag(((v0).(func(any) any)(v1_a1)).(func(any) any)(v2_a2), "LT")) { return true }
return false
}()
}
}
}() })
Test_ListOps_range_ = _lazy(func() any { return func(v0_start any) any {
return func(v1_end any) any {
return func() any {
var v2_go any
v2_go = func(v3_curr any) any {
return func(v4_acc any) any {
return func() any {
if _truthy(((_force(Test_ListOps_lessThan)).(func(any) any)(v3_curr)).(func(any) any)(v0_start)) { return v4_acc }
return ((v2_go).(func(any) any)(_intSub(v3_curr, 1))).(func(any) any)(V{Tag: "Cons", Fields: []any{v3_curr, v4_acc}})
}()
}
}
_ = v2_go
return ((v2_go).(func(any) any)(v1_end)).(func(any) any)(V{Tag: "Nil", Fields: []any{}})
}()
}
} })
Test_ListOps_foldl = _lazy(func() any { return func(v0_v any) any {
return func(v1_v1 any) any {
return func(v2_v2 any) any {
return func() any {
if _truthy(_isTag(v2_v2, "Nil")) { return v1_v1 }
if _truthy(_isTag(v2_v2, "Cons")) { return (((_force(Test_ListOps_foldl)).(func(any) any)(v0_v)).(func(any) any)(((v0_v).(func(any) any)(v1_v1)).(func(any) any)((v2_v2).(V).Fields[0]))).(func(any) any)((v2_v2).(V).Fields[1]) }
return _fail("Failed pattern match")
}()
}
}
} })
Test_ListOps_filterEvens = _lazy(func() any { return func(v0_lst any) any {
return func() any {
var v1_go any
v1_go = func(v2_v any) any {
return func(v3_v1 any) any {
return func() any {
if _truthy(_isTag(v2_v, "Nil")) { return v3_v1 }
if _truthy(_isTag(v2_v, "Cons")) { return func() any {
if _truthy(_intEq((((_force(Data_EuclideanRing_euclideanRingInt)).(map[string]any)["mod"]).(func(any) any)((v2_v).(V).Fields[0])).(func(any) any)(2), 0)) { return ((v1_go).(func(any) any)((v2_v).(V).Fields[1])).(func(any) any)(V{Tag: "Cons", Fields: []any{(v2_v).(V).Fields[0], v3_v1}}) }
return ((v1_go).(func(any) any)((v2_v).(V).Fields[1])).(func(any) any)(v3_v1)
}() }
return _fail("Failed pattern match")
}()
}
}
_ = v1_go
return ((v1_go).(func(any) any)(v0_lst)).(func(any) any)(V{Tag: "Nil", Fields: []any{}})
}()
} })
Test_ListOps_describe = _lazy(func() any { return (_force(Effect_Console_log)).(func(any) any)("List Processing (900 elements):") })
Test_ListOps_act = _lazy(func() any { return (((_force(Effect_bindEffect)).(map[string]any)["bind"]).(func(any) any)((_force(Bench_opaque)).(func(any) any)(900))).(func(any) any)(func(v0_dummy any) any {
return (_force(Effect_Console_log)).(func(any) any)(((_force(Data_Show_showInt)).(map[string]any)["show"]).(func(any) any)((((_force(Test_ListOps_foldl)).(func(any) any)(_force(Data_Semiring_intAdd))).(func(any) any)(0)).(func(any) any)((_force(Test_ListOps_filterEvens)).(func(any) any)(((_force(Test_ListOps_range_)).(func(any) any)(1)).(func(any) any)(v0_dummy)))))
}) })
}