#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Alt::*;
use Purs_Control_Alternative::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Comonad::*;
use Purs_Control_Extend::*;
use Purs_Control_Lazy::*;
use Purs_Control_Monad::*;
use Purs_Control_MonadPlus::*;
use Purs_Control_Plus::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Bifunctor::*;
use Purs_Data_Boolean::*;
use Purs_Data_BooleanAlgebra::*;
use Purs_Data_Bounded::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Const::*;
use Purs_Data_Either::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Foldable::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_Functor_App::*;
use Purs_Data_Functor_Compose::*;
use Purs_Data_Functor_Coproduct::*;
use Purs_Data_Functor_Invariant::*;
use Purs_Data_Functor_Product::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Identity::*;
use Purs_Data_Maybe::*;
use Purs_Data_Maybe_First::*;
use Purs_Data_Maybe_Last::*;
use Purs_Data_Monoid::*;
use Purs_Data_Monoid_Additive::*;
use Purs_Data_Monoid_Alternate::*;
use Purs_Data_Monoid_Conj::*;
use Purs_Data_Monoid_Disj::*;
use Purs_Data_Monoid_Dual::*;
use Purs_Data_Monoid_Endo::*;
use Purs_Data_Monoid_Multiplicative::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ord::*;
use Purs_Data_Ord_Max::*;
use Purs_Data_Ord_Min::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semigroup_Foldable::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_String_CodeUnits::*;
use Purs_Data_String_Common::*;
use Purs_Data_String_Pattern::*;
use Purs_Data_String_Unsafe::*;
use Purs_Data_Symbol::*;
use Purs_Data_Tuple::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Record_Unsafe::*;
use Purs_Safe_Coerce::*;
use Purs_Type_Proxy::*;
use Purs_Unsafe_Coerce::*;
use Purs_Control_Bind::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Eq::*;
use Purs_Data_Foldable::*;
use Purs_Data_Maybe::*;
use Purs_Data_Monoid::*;
use Purs_Data_Ord::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Show::*;
use Purs_Data_String_CodeUnits::*;
use Purs_Data_String_Common::*;
use Purs_Data_String_Pattern::*;
use Purs_Data_Symbol::*;
use Purs_Record_Unsafe::*;
use Purs_Unsafe_Coerce::*;
use Purs_Type_Proxy::*;
use Purs_Data_Ordering::*;
use Purs_Data_Semigroup_Foldable::*;

// Code generated by purust for module Data_String_NonEmpty_Internal


#[derive(Clone)]
pub struct MakeNonEmpty {
    pub nes: purust_core::Func1<Purs_Type_Proxy::Proxy, String>
}

pub fn Data_String_NonEmpty_Internal_NonEmptyString(mut purs_local_0: String) -> String {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_String_NonEmpty_Internal_NonEmptyReplacement(mut purs_local_0: String) -> String {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_String_NonEmpty_Internal_toUpper(mut purs_local_0: String) -> String {
    // AST: Typed(Abs(..., Typed(Typed(Typed(Typed(App(Var(...))))))))
/* Typed String <- String : App(Var(...)) */Data_String_Common_toUpper(/* Typed String <- String : Local(...) */purs_local_0)
}

pub fn Data_String_NonEmpty_Internal_toString(mut purs_local_0: String) -> String {
    // AST: Typed(Abs(..., Typed(Typed(Typed(Local(...))))))
/* Typed String <- String : Local(...) */purs_local_0
}

pub fn Data_String_NonEmpty_Internal_toLower(mut purs_local_0: String) -> String {
    // AST: Typed(Abs(..., Typed(Typed(Typed(Typed(App(Var(...))))))))
/* Typed String <- String : App(Var(...)) */Data_String_Common_toLower(/* Typed String <- String : Local(...) */purs_local_0)
}

pub fn Data_String_NonEmpty_Internal_showNonEmptyString() -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Show::Show>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_Internal_showNonEmptyString", || {
std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: String| -> String {
    let mut purs_local_0 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(NonEmptyString.unsafeFromString "), Data_Show_showStringImpl(/* Typed String <- String : Local(...) */purs_local_0)), String::from(")"))
} as fn(String) -> String)).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_string()) } })) })
}).clone())
}

pub fn Data_String_NonEmpty_Internal_showNonEmptyReplacement() -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Show::Show>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_Internal_showNonEmptyReplacement", || {
std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: String| -> String {
    let mut purs_local_0 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(NonEmptyReplacement (NonEmptyString.unsafeFromString "), Data_Show_showStringImpl(/* Typed String <- String : Local(...) */purs_local_0)), String::from("))"))
} as fn(String) -> String)).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_string()) } })) })
}).clone())
}

pub fn Data_String_NonEmpty_Internal_semigroupNonEmptyString() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Semigroup::Semigroup>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_Internal_semigroupNonEmptyString", || {
/* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_Semigroup_semigroupString()
}).clone())
}

pub fn Data_String_NonEmpty_Internal_semigroupNonEmptyReplacement() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Var(...)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Semigroup::Semigroup>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_Internal_semigroupNonEmptyReplacement", || {
/* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_Semigroup_semigroupString()
}).clone())
}

pub fn Data_String_NonEmpty_Internal_replaceAll(mut purs_local_0: String, mut purs_local_1: String, mut purs_local_2: String) -> String {
    // AST: Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(App(Var(...))))))))))))
/* Typed String <- String : App(Var(...)) */Data_String_Common_replaceAll(/* Typed String <- String : Local(...) */purs_local_0, /* Typed String <- String : Local(...) */purs_local_1, /* Typed String <- String : Local(...) */purs_local_2)
}

pub fn Data_String_NonEmpty_Internal_replace(mut purs_local_0: String, mut purs_local_1: String, mut purs_local_2: String) -> String {
    // AST: Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(App(Var(...))))))))))))
/* Typed String <- String : App(Var(...)) */Data_String_Common_replace(/* Typed String <- String : Local(...) */purs_local_0, /* Typed String <- String : Local(...) */purs_local_1, /* Typed String <- String : Local(...) */purs_local_2)
}

pub fn Data_String_NonEmpty_Internal_prependString(mut purs_local_0: String, mut purs_local_1: String) -> String {
    // AST: Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(PrimOp(...)))))))))
/* Typed String <- String : PrimOp(...) */format!("{}{}", purs_local_0, purs_local_1)
}

pub fn Data_String_NonEmpty_Internal_ordNonEmptyString() -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Ord::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_Internal_ordNonEmptyString", || {
/* Typed std::rc::Rc<Purs_Data_Ord::Ord> <- std::rc::Rc<Purs_Data_Ord::Ord> : Var(...) */Data_Ord_ordString()
}).clone())
}

pub fn Data_String_NonEmpty_Internal_ordNonEmptyReplacement() -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Typed(Var(...)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Ord::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_Internal_ordNonEmptyReplacement", || {
/* Typed std::rc::Rc<Purs_Data_Ord::Ord> <- std::rc::Rc<Purs_Data_Ord::Ord> : Var(...) */Data_Ord_ordString()
}).clone())
}

pub fn Data_String_NonEmpty_Internal_nonEmptyNonEmpty(mut purs_local_0: std::rc::Rc<Purs_Data_Symbol::IsSymbol>) -> std::rc::Rc<crate::MakeNonEmpty> {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Lit))))))
std::rc::Rc::new(crate::MakeNonEmpty { nes: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: Purs_Type_Proxy::Proxy| -> String {
    let mut purs_local_1 = _a0;
    /* Typed String <- String : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func1<Purs_Type_Proxy::Proxy, String> <- purust_core::Func1<Purs_Type_Proxy::Proxy, String> : Accessor(Local(...)) */(purs_local_0.clone()).reflectSymbol.clone())(/* Typed Purs_Type_Proxy::Proxy <- Purs_Type_Proxy::Proxy : Local(...) */purs_local_1)
})) })
}

pub fn Data_String_NonEmpty_Internal_nes(mut a0: std::rc::Rc<crate::MakeNonEmpty>, mut a1: Purs_Type_Proxy::Proxy) -> String {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::MakeNonEmpty>| -> purust_core::Func1<Purs_Type_Proxy::Proxy, String> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func1<Purs_Type_Proxy::Proxy, String> <- purust_core::Func1<Purs_Type_Proxy::Proxy, String> : Accessor(Local(...)) */(purs_local_0).nes.clone()
} as fn(std::rc::Rc<crate::MakeNonEmpty>) -> purust_core::Func1<Purs_Type_Proxy::Proxy, String>)).clone(); move |mut _a0: std::rc::Rc<crate::MakeNonEmpty>, mut _a1: Purs_Type_Proxy::Proxy| -> String { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Data_String_NonEmpty_Internal_makeNonEmptyBad(mut purs_local_0: crate::UnknownType) -> std::rc::Rc<crate::MakeNonEmpty> {
    // AST: Typed(Abs(..., Typed(Typed(Typed(Lit)))))
std::rc::Rc::new(crate::MakeNonEmpty { nes: /* Typed Abs */purust_core::Func1::Static(|mut _a0: Purs_Type_Proxy::Proxy| -> String {
    drop(_a0);
    /* Typed String <- String : Lit */String::from("")
} as fn(Purs_Type_Proxy::Proxy) -> String) })
}

pub fn Data_String_NonEmpty_Internal_localeCompare(mut purs_local_0: String, mut purs_local_1: String) -> Purs_Data_Ordering::Ordering {
    // AST: Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(App(Var(...)))))))))
/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Var(...)) */Data_String_Common_localeCompare(/* Typed String <- String : Local(...) */purs_local_0, /* Typed String <- String : Local(...) */purs_local_1)
}

pub fn Data_String_NonEmpty_Internal_liftS(mut purs_local_0: purust_core::Func1<String, crate::UnknownType>, mut purs_local_1: String) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(App(Typed(Local(...))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<String, crate::UnknownType> <- purust_core::Func1<String, crate::UnknownType> : Local(...) */purs_local_0)(/* Typed String <- String : Local(...) */purs_local_1)
}

pub fn Data_String_NonEmpty_Internal_startsWith(mut a0: String, mut a1: String) -> bool {
    // AST: Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...)))))))))
(/* Typed purust_core::Func2<String, String, bool> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<purust_core::Func1<String, bool>, String, bool> <- purust_core::Func2<purust_core::Func1<String, crate::UnknownType>, String, crate::UnknownType> : Var(...) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func2::Static(Data_String_NonEmpty_Internal_liftS)).clone(); move |mut _a0: purust_core::Func1<String, bool>, mut _a1: String| -> bool { (_f(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0).clone(); move |mut _a0: String| -> crate::UnknownType { crate::mk_bool(_f(_a0)) } })), _a1)).unwrap_bool() } }))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0).unwrap_func1(); move |mut _a0: String| -> bool { (_f(purust_core::Value::String(_a0))).unwrap_bool() } })), (_a1).unwrap_string())) } }))), purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<String, String, bool> <- purust_core::Func2<String, String, bool> : Var(...) */purust_core::Func2::Static(Data_String_CodeUnits_startsWith)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f((_a0).unwrap_string(), (_a1).unwrap_string())) } }))))).unwrap_func2(); move |mut _a0: String, mut _a1: String| -> bool { (_f(purust_core::Value::String(_a0), purust_core::Value::String(_a1))).unwrap_bool() } })))(a0.clone(), a1.clone())
}

pub fn Data_String_NonEmpty_Internal_joinWith1(mut a0: std::rc::Rc<Purs_Data_Semigroup_Foldable::Foldable1>, mut a1: String, mut a2: crate::UnknownType) -> String {
    // AST: Typed(Typed(Abs(..., Let(...))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<Purs_Data_Semigroup_Foldable::Foldable1>| -> purust_core::Func2<String, crate::UnknownType, String> {
    let mut purs_local_0 = _a0;
    {
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Foldable::Foldable> <- std::rc::Rc<Purs_Data_Foldable::Foldable> : App(Accessor(Local(...))) */((purs_local_0).Foldable0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: String| -> purust_core::Func1<crate::UnknownType, String> {
    let mut purs_local_2 = _a0;
    /* Typed purust_core::Func1<crate::UnknownType, String> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: String| -> String {
    let mut purs_local_3 = _a0;
    purs_local_3
} as fn(String) -> String)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::String(_f((_a0).unwrap_string())) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, String> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : App(TypeApp(TypeApp(Var(...)))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = purs_local_1.clone();
        let mut eval_arg_1 = /* Typed std::rc::Rc<Purs_Data_Monoid::Monoid> <- std::rc::Rc<Purs_Data_Monoid::Monoid> : Var(...) */Data_Monoid_monoidString();
        let mut eval_arg_2 = purust_core::Value::String(/* Typed String <- String : Local(...) */purs_local_2);
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Foldable_intercalate(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType| -> String { (_f(_a0)).unwrap_string() } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::String(_f(_a0)) } }))))).unwrap_func1(); move |mut _a0: crate::UnknownType| -> String { (_f(_a0)).unwrap_string() } }))
}))).clone(); move |mut _a0: String, mut _a1: crate::UnknownType| -> String { ((_f)(_a0.clone()))(_a1.clone()) } }))
}
} as fn(std::rc::Rc<Purs_Data_Semigroup_Foldable::Foldable1>) -> purust_core::Func2<String, crate::UnknownType, String>)).clone(); move |mut _a0: std::rc::Rc<Purs_Data_Semigroup_Foldable::Foldable1>, mut _a1: String, mut _a2: crate::UnknownType| -> String { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Data_String_NonEmpty_Internal_joinWith(mut a0: std::rc::Rc<Purs_Data_Foldable::Foldable>, mut a1: String, mut a2: crate::UnknownType) -> String {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...)))))))))))))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<Purs_Data_Foldable::Foldable>| -> purust_core::Func2<String, crate::UnknownType, String> {
    let mut purs_local_0 = _a0;
    /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: String| -> purust_core::Func1<crate::UnknownType, String> {
    let mut purs_local_1 = _a0;
    /* Typed purust_core::Func1<crate::UnknownType, String> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, String> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : App(TypeApp(TypeApp(Var(...)))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed std::rc::Rc<Purs_Data_Foldable::Foldable> <- std::rc::Rc<Purs_Data_Foldable::Foldable> : Local(...) */purs_local_0.clone();
        let mut eval_arg_1 = /* Typed std::rc::Rc<Purs_Data_Monoid::Monoid> <- std::rc::Rc<Purs_Data_Monoid::Monoid> : Var(...) */Data_Monoid_monoidString();
        let mut eval_arg_2 = purust_core::Value::String(/* Typed String <- String : Local(...) */purs_local_1);
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Foldable_intercalate(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType| -> String { (_f(_a0)).unwrap_string() } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::String(_f(_a0)) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Var(...) */purust_core::Func1::Static(Unsafe_Coerce_unsafeCoerce)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))))).unwrap_func1(); move |mut _a0: crate::UnknownType| -> String { (_f(_a0)).unwrap_string() } }))
}))).clone(); move |mut _a0: String, mut _a1: crate::UnknownType| -> String { ((_f)(_a0.clone()))(_a1.clone()) } }))
} as fn(std::rc::Rc<Purs_Data_Foldable::Foldable>) -> purust_core::Func2<String, crate::UnknownType, String>)).clone(); move |mut _a0: std::rc::Rc<Purs_Data_Foldable::Foldable>, mut _a1: String, mut _a2: crate::UnknownType| -> String { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Data_String_NonEmpty_Internal_join1With(mut a0: std::rc::Rc<Purs_Data_Semigroup_Foldable::Foldable1>, mut a1: String, mut a2: crate::UnknownType) -> String {
    // AST: Typed(Typed(Abs(..., Let(...))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<Purs_Data_Semigroup_Foldable::Foldable1>| -> purust_core::Func2<String, crate::UnknownType, String> {
    let mut purs_local_0 = _a0;
    {
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Foldable::Foldable> <- std::rc::Rc<Purs_Data_Foldable::Foldable> : App(Accessor(Local(...))) */((purs_local_0).Foldable0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: String| -> purust_core::Func1<crate::UnknownType, String> {
    let mut purs_local_2 = _a0;
    /* Typed purust_core::Func1<crate::UnknownType, String> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: String| -> String {
    let mut purs_local_3 = _a0;
    purs_local_3
} as fn(String) -> String)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::String(_f((_a0).unwrap_string())) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, String> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, String> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : App(TypeApp(TypeApp(Var(...)))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed std::rc::Rc<Purs_Data_Foldable::Foldable> <- std::rc::Rc<Purs_Data_Foldable::Foldable> : Local(...) */purs_local_1.clone();
        let mut eval_arg_1 = /* Typed std::rc::Rc<Purs_Data_Monoid::Monoid> <- std::rc::Rc<Purs_Data_Monoid::Monoid> : Var(...) */Data_Monoid_monoidString();
        let mut eval_arg_2 = purust_core::Value::String(/* Typed String <- String : Local(...) */purs_local_2);
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Foldable_intercalate(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType| -> String { (_f(_a0)).unwrap_string() } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::String(_f(_a0)) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Var(...) */purust_core::Func1::Static(Unsafe_Coerce_unsafeCoerce)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))))).unwrap_func1(); move |mut _a0: crate::UnknownType| -> String { (_f(_a0)).unwrap_string() } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::String(_f(_a0)) } }))))).unwrap_func1(); move |mut _a0: crate::UnknownType| -> String { (_f(_a0)).unwrap_string() } }))
}))).clone(); move |mut _a0: String, mut _a1: crate::UnknownType| -> String { ((_f)(_a0.clone()))(_a1.clone()) } }))
}
} as fn(std::rc::Rc<Purs_Data_Semigroup_Foldable::Foldable1>) -> purust_core::Func2<String, crate::UnknownType, String>)).clone(); move |mut _a0: std::rc::Rc<Purs_Data_Semigroup_Foldable::Foldable1>, mut _a1: String, mut _a2: crate::UnknownType| -> String { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Data_String_NonEmpty_Internal_fromString(mut purs_local_0: String) -> std::rc::Rc<Purs_Data_Maybe::Maybe> {
    // AST: Typed(Abs(..., Typed(Branch(...))))
/* Typed std::rc::Rc<Purs_Data_Maybe::Maybe> <- std::rc::Rc<Purs_Data_Maybe::Maybe> : Branch(...) */if (/* Typed String <- String : Local(...) */purs_local_0.clone() == String::from("")) {
        /* Typed std::rc::Rc<Purs_Data_Maybe::Maybe> <- std::rc::Rc<Purs_Data_Maybe::Maybe> : CtorSaturated(...) */std::rc::Rc::new(Purs_Data_Maybe::Maybe::Nothing)
    } else {
        /* Typed std::rc::Rc<Purs_Data_Maybe::Maybe> <- std::rc::Rc<Purs_Data_Maybe::Maybe> : CtorSaturated(...) */std::rc::Rc::new(Purs_Data_Maybe::Maybe::Just(purust_core::Value::String(/* Typed String <- String : Local(...) */purs_local_0)))
    }
}

pub fn Data_String_NonEmpty_Internal_stripPrefix(mut a0: String, mut a1: String) -> std::rc::Rc<Purs_Data_Maybe::Maybe> {
    // AST: Typed(Abs(..., Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))))))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: String| -> purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : App(TypeApp(TypeApp(TypeApp(TypeApp(Var(...)))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed std::rc::Rc<Purs_Control_Bind::Bind> <- std::rc::Rc<Purs_Control_Bind::Bind> : Var(...) */Data_Maybe_bindMaybe();
        let mut eval_arg_1 = purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> <- purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> : Var(...) */purust_core::Func1::Static(Data_String_NonEmpty_Internal_fromString)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_string()))) } }));
        let mut eval_arg_2 = purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: String| -> std::rc::Rc<Purs_Data_Maybe::Maybe> {
    let mut purs_local_1 = _a0;
    /* Typed std::rc::Rc<Purs_Data_Maybe::Maybe> <- std::rc::Rc<Purs_Data_Maybe::Maybe> : App(Var(...)) */Data_String_CodeUnits_stripPrefix(/* Typed String <- String : Local(...) */purs_local_0.clone(), /* Typed String <- String : Local(...) */purs_local_1)
}))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_string()))) } }));
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Control_Bind_composeKleisliFlipped(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone())
}))
}).clone(); move |mut _a0: String| -> std::rc::Rc<Purs_Data_Maybe::Maybe> { (_f(purust_core::Value::String(_a0))).unwrap_class::<std::rc::Rc<Purs_Data_Maybe::Maybe>>().clone() } }))
} as fn(String) -> purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>>)).clone(); move |mut _a0: String, mut _a1: String| -> std::rc::Rc<Purs_Data_Maybe::Maybe> { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Data_String_NonEmpty_Internal_stripSuffix(mut a0: String, mut a1: String) -> std::rc::Rc<Purs_Data_Maybe::Maybe> {
    // AST: Typed(Abs(..., Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))))))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: String| -> purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : App(TypeApp(TypeApp(TypeApp(TypeApp(Var(...)))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = /* Typed std::rc::Rc<Purs_Control_Bind::Bind> <- std::rc::Rc<Purs_Control_Bind::Bind> : Var(...) */Data_Maybe_bindMaybe();
        let mut eval_arg_1 = purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> <- purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> : Var(...) */purust_core::Func1::Static(Data_String_NonEmpty_Internal_fromString)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_string()))) } }));
        let mut eval_arg_2 = purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: String| -> std::rc::Rc<Purs_Data_Maybe::Maybe> {
    let mut purs_local_1 = _a0;
    /* Typed std::rc::Rc<Purs_Data_Maybe::Maybe> <- std::rc::Rc<Purs_Data_Maybe::Maybe> : App(Var(...)) */Data_String_CodeUnits_stripSuffix(/* Typed String <- String : Local(...) */purs_local_0.clone(), /* Typed String <- String : Local(...) */purs_local_1)
}))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_string()))) } }));
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Control_Bind_composeKleisliFlipped(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone())
}))
}).clone(); move |mut _a0: String| -> std::rc::Rc<Purs_Data_Maybe::Maybe> { (_f(purust_core::Value::String(_a0))).unwrap_class::<std::rc::Rc<Purs_Data_Maybe::Maybe>>().clone() } }))
} as fn(String) -> purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>>)).clone(); move |mut _a0: String, mut _a1: String| -> std::rc::Rc<Purs_Data_Maybe::Maybe> { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Data_String_NonEmpty_Internal_trim(mut purs_local_0: String) -> std::rc::Rc<Purs_Data_Maybe::Maybe> {
    // AST: Typed(Abs(..., Typed(Typed(Let(...)))))
{
    let mut purs_local_1 = Data_String_Common_trim(/* Typed String <- String : Local(...) */purs_local_0);
    /* Typed std::rc::Rc<Purs_Data_Maybe::Maybe> <- std::rc::Rc<Purs_Data_Maybe::Maybe> : Branch(...) */if (/* Typed String <- String : Local(...) */purs_local_1.clone() == String::from("")) {
        /* Typed std::rc::Rc<Purs_Data_Maybe::Maybe> <- std::rc::Rc<Purs_Data_Maybe::Maybe> : CtorSaturated(...) */std::rc::Rc::new(Purs_Data_Maybe::Maybe::Nothing)
    } else {
        /* Typed std::rc::Rc<Purs_Data_Maybe::Maybe> <- std::rc::Rc<Purs_Data_Maybe::Maybe> : CtorSaturated(...) */std::rc::Rc::new(Purs_Data_Maybe::Maybe::Just(purust_core::Value::String(/* Typed String <- String : Local(...) */purs_local_1)))
    }
}
}

pub fn Data_String_NonEmpty_Internal_unsafeFromString(mut a0: crate::UnknownType, mut a1: String) -> String {
    // AST: Typed(Abs(..., Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...)))))))))))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> purust_core::Func1<String, String> {
    drop(_a0);
    /* Typed purust_core::Func1<String, String> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<std::rc::Rc<Purs_Data_Maybe::Maybe>, String> <- purust_core::Func1<std::rc::Rc<Purs_Data_Maybe::Maybe>, crate::UnknownType> : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }));
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: std::rc::Rc<Purs_Data_Maybe::Maybe>| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Data_Maybe_fromJust(eval_arg_0, eta_0.clone())
}))
}).clone(); move |mut _a0: std::rc::Rc<Purs_Data_Maybe::Maybe>| -> String { (_f(_a0)).unwrap_string() } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::String(_f((_a0).unwrap_class::<std::rc::Rc<Purs_Data_Maybe::Maybe>>().clone())) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> <- purust_core::Func1<String, std::rc::Rc<Purs_Data_Maybe::Maybe>> : Var(...) */purust_core::Func1::Static(Data_String_NonEmpty_Internal_fromString)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_string()))) } }))))).unwrap_func1(); move |mut _a0: String| -> String { (_f(purust_core::Value::String(_a0))).unwrap_string() } }))
} as fn(crate::UnknownType) -> purust_core::Func1<String, String>)).clone(); move |mut _a0: crate::UnknownType, mut _a1: String| -> String { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Data_String_NonEmpty_Internal_eqNonEmptyString() -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Eq::Eq>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_Internal_eqNonEmptyString", || {
/* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqString()
}).clone())
}

pub fn Data_String_NonEmpty_Internal_eqNonEmptyReplacement() -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Typed(Var(...)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Eq::Eq>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_String_NonEmpty_Internal_eqNonEmptyReplacement", || {
/* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqString()
}).clone())
}

pub fn Data_String_NonEmpty_Internal_endsWith(mut a0: String, mut a1: String) -> bool {
    // AST: Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...)))))))))
(/* Typed purust_core::Func2<String, String, bool> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<purust_core::Func1<String, bool>, String, bool> <- purust_core::Func2<purust_core::Func1<String, crate::UnknownType>, String, crate::UnknownType> : Var(...) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func2::Static(Data_String_NonEmpty_Internal_liftS)).clone(); move |mut _a0: purust_core::Func1<String, bool>, mut _a1: String| -> bool { (_f(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0).clone(); move |mut _a0: String| -> crate::UnknownType { crate::mk_bool(_f(_a0)) } })), _a1)).unwrap_bool() } }))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0).unwrap_func1(); move |mut _a0: String| -> bool { (_f(purust_core::Value::String(_a0))).unwrap_bool() } })), (_a1).unwrap_string())) } }))), purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<String, String, bool> <- purust_core::Func2<String, String, bool> : Var(...) */purust_core::Func2::Static(Data_String_CodeUnits_endsWith)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f((_a0).unwrap_string(), (_a1).unwrap_string())) } }))))).unwrap_func2(); move |mut _a0: String, mut _a1: String| -> bool { (_f(purust_core::Value::String(_a0), purust_core::Value::String(_a1))).unwrap_bool() } })))(a0.clone(), a1.clone())
}

pub fn Data_String_NonEmpty_Internal_contains(mut a0: String, mut a1: String) -> bool {
    // AST: Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...)))))))))
(/* Typed purust_core::Func2<String, String, bool> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<purust_core::Func1<String, bool>, String, bool> <- purust_core::Func2<purust_core::Func1<String, crate::UnknownType>, String, crate::UnknownType> : Var(...) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func2::Static(Data_String_NonEmpty_Internal_liftS)).clone(); move |mut _a0: purust_core::Func1<String, bool>, mut _a1: String| -> bool { (_f(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0).clone(); move |mut _a0: String| -> crate::UnknownType { crate::mk_bool(_f(_a0)) } })), _a1)).unwrap_bool() } }))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0).unwrap_func1(); move |mut _a0: String| -> bool { (_f(purust_core::Value::String(_a0))).unwrap_bool() } })), (_a1).unwrap_string())) } }))), purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<String, String, bool> <- purust_core::Func2<String, String, bool> : Var(...) */purust_core::Func2::Static(Data_String_CodeUnits_contains)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f((_a0).unwrap_string(), (_a1).unwrap_string())) } }))))).unwrap_func2(); move |mut _a0: String, mut _a1: String| -> bool { (_f(purust_core::Value::String(_a0), purust_core::Value::String(_a1))).unwrap_bool() } })))(a0.clone(), a1.clone())
}

pub fn Data_String_NonEmpty_Internal_appendString(mut purs_local_0: String, mut purs_local_1: String) -> String {
    // AST: Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(PrimOp(...)))))))))
/* Typed String <- String : PrimOp(...) */format!("{}{}", purs_local_0, purs_local_1)
}





