% Generated by purerl version 0.0.24
-module(data_comparison@ps).
-export(['Comparison'/0, semigroupComparison/0, newtypeComparison/0, monoidComparison/0, defaultComparison/1, defaultComparison/0, contravariantComparison/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./data_comparison.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 0).
-spec append() -> any().
append() -> (?MEMOIZE((data_semigroup@ps:append(((data_semigroup@ps:semigroupFn())(((data_semigroup@ps:semigroupFn())((data_ordering@ps:semigroupOrdering()))))))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 0).
-spec append(any(),any()) -> any().
append(_@2,_@3) -> (((append())(_@2))(_@3)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 10).
-spec 'Comparison'() -> any().
'Comparison'() -> fun (X) ->
  X
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 17).
-spec semigroupComparison() -> any().
semigroupComparison() -> #{append=>fun (V) ->
  fun (V1) ->
    case { V, V1 } of
      ({ _@4, _@5 }) -> (append(_@4, _@5))
    end
  end
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 12).
-spec newtypeComparison() -> any().
newtypeComparison() -> #{'Coercible0'=>fun (_) ->
  undefined
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 20).
-spec monoidComparison() -> any().
monoidComparison() -> #{mempty=>fun (V) ->
  fun (V1) ->
    { eQ }
  end
end, 'Semigroup0'=>fun (_) ->
  (semigroupComparison())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 24).
-spec defaultComparison(any()) -> data_comparison_Comparison(any()).
defaultComparison(_@6) -> (?MEMOIZE((data_ord@ps:compare(_@6)))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 24).
-spec defaultComparison() -> fun((any()) -> data_comparison_Comparison(any())).
defaultComparison() -> fun (_@7) ->
  (defaultComparison(_@7))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Comparison.purs", 14).
-spec contravariantComparison() -> any().
contravariantComparison() -> #{cmap=>fun (F) ->
  fun (V) ->
    case { F, V } of
      ({ _@8, _@9 }) -> (((data_function@ps:on())(_@9))(_@8))
    end
  end
end}.
