[package]
name = "Purs_Control_Monad_Identity_Trans"
version = "0.1.0"
edition = "2021"

[dependencies]
purust_core = { path = "../purust_core" }
perceus_ptr = { path = "../perceus_ptr" }
fancy-regex = "0.13"
Purs_Control_Alt = { path = "../Purs_Control_Alt" }
Purs_Control_Alternative = { path = "../Purs_Control_Alternative" }
Purs_Control_Applicative = { path = "../Purs_Control_Applicative" }
Purs_Control_Apply = { path = "../Purs_Control_Apply" }
Purs_Control_Bind = { path = "../Purs_Control_Bind" }
Purs_Control_Category = { path = "../Purs_Control_Category" }
Purs_Control_Comonad = { path = "../Purs_Control_Comonad" }
Purs_Control_Extend = { path = "../Purs_Control_Extend" }
Purs_Control_Lazy = { path = "../Purs_Control_Lazy" }
Purs_Control_Monad = { path = "../Purs_Control_Monad" }
Purs_Control_MonadPlus = { path = "../Purs_Control_MonadPlus" }
Purs_Control_Monad_Cont_Class = { path = "../Purs_Control_Monad_Cont_Class" }
Purs_Control_Monad_Error_Class = { path = "../Purs_Control_Monad_Error_Class" }
Purs_Control_Monad_Reader_Class = { path = "../Purs_Control_Monad_Reader_Class" }
Purs_Control_Monad_Rec_Class = { path = "../Purs_Control_Monad_Rec_Class" }
Purs_Control_Monad_ST_Class = { path = "../Purs_Control_Monad_ST_Class" }
Purs_Control_Monad_ST_Global = { path = "../Purs_Control_Monad_ST_Global" }
Purs_Control_Monad_ST_Internal = { path = "../Purs_Control_Monad_ST_Internal" }
Purs_Control_Monad_State_Class = { path = "../Purs_Control_Monad_State_Class" }
Purs_Control_Monad_Trans_Class = { path = "../Purs_Control_Monad_Trans_Class" }
Purs_Control_Monad_Writer_Class = { path = "../Purs_Control_Monad_Writer_Class" }
Purs_Control_Plus = { path = "../Purs_Control_Plus" }
Purs_Control_Semigroupoid = { path = "../Purs_Control_Semigroupoid" }
Purs_Data_Bifunctor = { path = "../Purs_Data_Bifunctor" }
Purs_Data_Boolean = { path = "../Purs_Data_Boolean" }
Purs_Data_BooleanAlgebra = { path = "../Purs_Data_BooleanAlgebra" }
Purs_Data_Bounded = { path = "../Purs_Data_Bounded" }
Purs_Data_CommutativeRing = { path = "../Purs_Data_CommutativeRing" }
Purs_Data_Const = { path = "../Purs_Data_Const" }
Purs_Data_Either = { path = "../Purs_Data_Either" }
Purs_Data_Eq = { path = "../Purs_Data_Eq" }
Purs_Data_EuclideanRing = { path = "../Purs_Data_EuclideanRing" }
Purs_Data_Foldable = { path = "../Purs_Data_Foldable" }
Purs_Data_Function = { path = "../Purs_Data_Function" }
Purs_Data_Functor = { path = "../Purs_Data_Functor" }
Purs_Data_Functor_App = { path = "../Purs_Data_Functor_App" }
Purs_Data_Functor_Compose = { path = "../Purs_Data_Functor_Compose" }
Purs_Data_Functor_Coproduct = { path = "../Purs_Data_Functor_Coproduct" }
Purs_Data_Functor_Invariant = { path = "../Purs_Data_Functor_Invariant" }
Purs_Data_Functor_Product = { path = "../Purs_Data_Functor_Product" }
Purs_Data_Generic_Rep = { path = "../Purs_Data_Generic_Rep" }
Purs_Data_HeytingAlgebra = { path = "../Purs_Data_HeytingAlgebra" }
Purs_Data_Identity = { path = "../Purs_Data_Identity" }
Purs_Data_Maybe = { path = "../Purs_Data_Maybe" }
Purs_Data_Maybe_First = { path = "../Purs_Data_Maybe_First" }
Purs_Data_Maybe_Last = { path = "../Purs_Data_Maybe_Last" }
Purs_Data_Monoid = { path = "../Purs_Data_Monoid" }
Purs_Data_Monoid_Additive = { path = "../Purs_Data_Monoid_Additive" }
Purs_Data_Monoid_Alternate = { path = "../Purs_Data_Monoid_Alternate" }
Purs_Data_Monoid_Conj = { path = "../Purs_Data_Monoid_Conj" }
Purs_Data_Monoid_Disj = { path = "../Purs_Data_Monoid_Disj" }
Purs_Data_Monoid_Dual = { path = "../Purs_Data_Monoid_Dual" }
Purs_Data_Monoid_Endo = { path = "../Purs_Data_Monoid_Endo" }
Purs_Data_Monoid_Multiplicative = { path = "../Purs_Data_Monoid_Multiplicative" }
Purs_Data_Newtype = { path = "../Purs_Data_Newtype" }
Purs_Data_Ord = { path = "../Purs_Data_Ord" }
Purs_Data_Ordering = { path = "../Purs_Data_Ordering" }
Purs_Data_Ring = { path = "../Purs_Data_Ring" }
Purs_Data_Semigroup = { path = "../Purs_Data_Semigroup" }
Purs_Data_Semiring = { path = "../Purs_Data_Semiring" }
Purs_Data_Show = { path = "../Purs_Data_Show" }
Purs_Data_Symbol = { path = "../Purs_Data_Symbol" }
Purs_Data_Traversable = { path = "../Purs_Data_Traversable" }
Purs_Data_Traversable_Accum_Internal = { path = "../Purs_Data_Traversable_Accum_Internal" }
Purs_Data_Tuple = { path = "../Purs_Data_Tuple" }
Purs_Data_Unit = { path = "../Purs_Data_Unit" }
Purs_Data_Void = { path = "../Purs_Data_Void" }
Purs_Effect = { path = "../Purs_Effect" }
Purs_Effect_Class = { path = "../Purs_Effect_Class" }
Purs_Effect_Exception = { path = "../Purs_Effect_Exception" }
Purs_Effect_Ref = { path = "../Purs_Effect_Ref" }
Purs_Partial = { path = "../Purs_Partial" }
Purs_Partial_Unsafe = { path = "../Purs_Partial_Unsafe" }
Purs_Record_Unsafe = { path = "../Purs_Record_Unsafe" }
Purs_Safe_Coerce = { path = "../Purs_Safe_Coerce" }
Purs_Type_Proxy = { path = "../Purs_Type_Proxy" }
Purs_Unsafe_Coerce = { path = "../Purs_Unsafe_Coerce" }