#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Record_Unsafe::*;
use Purs_Record_Unsafe::*;

// Code generated by purust for module Control_Semigroupoid


#[derive(Clone)]
pub struct Semigroupoid {
    pub compose: purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType>
}

pub fn Control_Semigroupoid_semigroupoidFn() -> std::rc::Rc<crate::Semigroupoid> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Semigroupoid>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Control_Semigroupoid_semigroupoidFn", || {
std::rc::Rc::new(crate::Semigroupoid { compose: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func3::Static(|mut _a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut _a1: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut _a2: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    let mut purs_local_2 = _a2;
    /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_0)(/* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_1)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2))
} as fn(purust_core::Func1<crate::UnknownType, crate::UnknownType>, purust_core::Func1<crate::UnknownType, crate::UnknownType>, crate::UnknownType) -> crate::UnknownType)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Shared(std::rc::Rc::new({ let _f2 = _f.clone(); let mut _a0 = _a0.clone(); let mut _a1 = _a1.clone(); move |mut _a2: crate::UnknownType| -> crate::UnknownType { _f2(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0.clone()).unwrap_func1(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } })), purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a1.clone()).unwrap_func1(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } })), _a2.clone()) } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))) } })) })
}).clone())
}

pub fn Control_Semigroupoid_compose(mut a0: std::rc::Rc<crate::Semigroupoid>, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Semigroupoid>| -> purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_0).compose.clone()
} as fn(std::rc::Rc<crate::Semigroupoid>) -> purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType>)).clone(); move |mut _a0: std::rc::Rc<crate::Semigroupoid>, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Control_Semigroupoid_composeFlipped(mut purs_local_0: std::rc::Rc<crate::Semigroupoid>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */Control_Semigroupoid_compose(/* Typed std::rc::Rc<crate::Semigroupoid> <- std::rc::Rc<crate::Semigroupoid> : Local(...) */purs_local_0, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1)
}





