import * as Test$dAckermann from "../Test.Ackermann/index.js";
import * as Test$dAstTree from "../Test.AstTree/index.js";
import * as Test$dAsync from "../Test.Async/index.js";
import * as Test$dChurch from "../Test.Church/index.js";
import * as Test$dFib from "../Test.Fib/index.js";
import * as Test$dFileOps from "../Test.FileOps/index.js";
import * as Test$dLazyEvaluation from "../Test.LazyEvaluation/index.js";
import * as Test$dListOps from "../Test.ListOps/index.js";
import * as Test$dPolymorphism from "../Test.Polymorphism/index.js";
import * as Test$dPrimes from "../Test.Primes/index.js";
import * as Test$dRBTree from "../Test.RBTree/index.js";
import * as Test$dRecords from "../Test.Records/index.js";
import * as Test$dStateMonad from "../Test.StateMonad/index.js";
import * as Test$dTCO from "../Test.TCO/index.js";
const main = () => {
  Test$dAstTree.describe();
  Test$dAstTree.act();
  Test$dFib.describe();
  Test$dFib.act();
  Test$dListOps.describe();
  Test$dListOps.act();
  Test$dTCO.describe();
  Test$dTCO.act();
  Test$dRecords.describe();
  Test$dRecords.act();
  Test$dAckermann.describe();
  Test$dAckermann.act();
  Test$dChurch.describe();
  Test$dChurch.act();
  Test$dPrimes.describe();
  Test$dPrimes.act();
  Test$dRBTree.describe();
  Test$dRBTree.act();
  Test$dPolymorphism.describe();
  Test$dPolymorphism.act();
  Test$dStateMonad.describe();
  Test$dStateMonad.act();
  Test$dLazyEvaluation.describe();
  Test$dLazyEvaluation.act();
  Test$dFileOps.describe();
  Test$dFileOps.act();
  Test$dAsync.describe();
  return Test$dAsync.act();
};
export {main};
