[<AutoOpen>]
module PureScript_Control_Monad_Reader_Trans

open System
open System.Collections.Generic

let Control_Monad_Reader_Trans_ReaderT  = (box (fun (x: obj) -> (box x)))

let Control_Monad_Reader_Trans_withReaderT  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, m) -> ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box m)))))) (box ((box f1)))))))))))))

let Control_Monad_Reader_Trans_runReaderT  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | x -> ((box x)))))

let Control_Monad_Reader_Trans_newtypeReaderT  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Control_Monad_Reader_Trans_monadTransReaderT  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_MonadTransusd_Dict))) (box ((box ((Map.add "lift" (box ((box (fun (dictMonad: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Control_Monad_Reader_Trans_ReaderT)))))) (box ((box Data_Function_const)))))))) Map.empty))))))

let Control_Monad_Reader_Trans_lift  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_Reader_Trans_monadTransReaderT))))

let Control_Monad_Reader_Trans_mapReaderT  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, m) -> ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box f1)))))) (box ((box m)))))))))))))

let Control_Monad_Reader_Trans_functorReaderT  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Control_Monad_Reader_Trans_mapReaderT)))))) (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor))))))))) Map.empty))))))))

let rec Control_Monad_Reader_Trans_distributiveReaderT_tco (dictDistributive: obj) : obj = ((let functorReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_functorReaderT))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictDistributive)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Distributive_Distributiveusd_Dict))) (box ((box ((Map.add "distribute" (box ((box (fun (dictFunctor: obj) -> (box (fun (a: obj) -> (sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((box (fun (e: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Distributive_collect))) (box ((box dictDistributive)))))) (box ((box dictFunctor)))))) (box ((box (fun (r: obj) -> (match ((unbox ((box r)))) with | r_prime -> ((sharpurs_apply (box ((box r_prime))) (box ((box e))))))))))))) (box ((box a))))))))))))))) (Map.add "collect" (box ((box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Distributive_distribute))) (box ((Control_Monad_Reader_Trans_distributiveReaderT_tco ((box dictDistributive)))))))) (box ((box dictFunctor))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorReaderT1))))) Map.empty))))))))))
and Control_Monad_Reader_Trans_distributiveReaderT = box (fun (dictDistributive: obj) -> Control_Monad_Reader_Trans_distributiveReaderT_tco dictDistributive)


let Control_Monad_Reader_Trans_applyReaderT  = (box (fun (dictApply: obj) -> (let functorReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_functorReaderT))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, v2) -> ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((box (fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box dictApply)))))) (box ((sharpurs_apply (box ((box f))) (box ((box r))))))))) (box ((sharpurs_apply (box ((box v2))) (box ((box r)))))))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_bindReaderT  = (box (fun (dictBind: obj) -> (let applyReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_applyReaderT))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictBind)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((box (fun (v: obj) -> (box (fun (k: obj) -> (match (((unbox ((box v))), (unbox ((box k))))) with | (m, k1) -> ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((box (fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box dictBind)))))) (box ((sharpurs_apply (box ((box m))) (box ((box r))))))))) (box ((box (fun (a: obj) -> (let v1 = (sharpurs_apply (box ((box k1))) (box ((box a)))) in (match ((unbox ((box v1)))) with | f -> ((sharpurs_apply (box ((box f))) (box ((box r))))))))))))))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_semigroupReaderT  = (box (fun (dictApply: obj) -> (let applyReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_applyReaderT))) (box ((box dictApply)))) in (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((box Data_Semigroup_Semigroupusd_Dict))) (box ((box ((Map.add "append" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_lift2))) (box ((box applyReaderT1)))))) (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup))))))))) Map.empty)))))))))))

let Control_Monad_Reader_Trans_applicativeReaderT  = (box (fun (dictApplicative: obj) -> (let applyReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_applyReaderT))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Control_Monad_Reader_Trans_ReaderT)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Function_const)))))) (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadReaderT  = (box (fun (dictMonad: obj) -> (let applicativeReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_applicativeReaderT))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in let bindReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_bindReaderT))) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box applicativeReaderT1))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box bindReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadAskReaderT  = (box (fun (dictMonad: obj) -> (let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((box dictMonad)))) in (sharpurs_apply (box ((box Control_Monad_Reader_Class_MonadAskusd_Dict))) (box ((box ((Map.add "ask" (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadReaderReaderT  = (box (fun (dictMonad: obj) -> (let monadAskReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadAskReaderT))) (box ((box dictMonad)))) in (sharpurs_apply (box ((box Control_Monad_Reader_Class_MonadReaderusd_Dict))) (box ((box ((Map.add "local" (box ((box Control_Monad_Reader_Trans_withReaderT))) (Map.add "MonadAsk0" (box ((box (fun (usd__unused: obj) -> (box monadAskReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadContReaderT  = (box (fun (dictMonadCont: obj) -> (let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadCont)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Cont_Class_MonadContusd_Dict))) (box ((box ((Map.add "callCC" (box ((box (fun (f: obj) -> (sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((box (fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Cont_Class_callCC))) (box ((box dictMonadCont)))))) (box ((box (fun (c: obj) -> (let v = (sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Control_Monad_Reader_Trans_ReaderT)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Function_const)))))) (box ((box c)))))))))) in (match ((unbox ((box v)))) with | f_prime -> ((sharpurs_apply (box ((box f_prime))) (box ((box r))))))))))))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadEffectReader  = (box (fun (dictMonadEffect: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadEffect)))))) (box ((box Prim_undefined)))) in let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((box Monad0)))) in (sharpurs_apply (box ((box Effect_Class_MonadEffectusd_Dict))) (box ((box ((Map.add "liftEffect" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_lift))) (box ((box Monad0))))))))) (box ((sharpurs_apply (box ((box Effect_Class_liftEffect))) (box ((box dictMonadEffect))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadRecReaderT  = (box (fun (dictMonadRec: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadRec)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in let pure_var = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))) in let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((box Monad0)))) in (sharpurs_apply (box ((box Control_Monad_Rec_Class_MonadRecusd_Dict))) (box ((box ((Map.add "tailRecM" (box ((box (fun (k: obj) -> (box (fun (a: obj) -> (let k_prime = (box (fun (r: obj) -> (box (fun (a_prime: obj) -> (let v = (sharpurs_apply (box ((box k))) (box ((box a_prime)))) in (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bindFlipped))) (box ((box Bind1)))))) (box ((box pure_var)))))) (box ((sharpurs_apply (box ((box f))) (box ((box r)))))))))))))) in (sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((box (fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRecM))) (box ((box dictMonadRec)))))) (box ((sharpurs_apply (box ((box k_prime))) (box ((box r))))))))) (box ((box a)))))))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadStateReaderT  = (box (fun (dictMonadState: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadState)))))) (box ((box Prim_undefined)))) in let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((box Monad0)))) in (sharpurs_apply (box ((box Control_Monad_State_Class_MonadStateusd_Dict))) (box ((box ((Map.add "state" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_lift))) (box ((box Monad0))))))))) (box ((sharpurs_apply (box ((box Control_Monad_State_Class_state))) (box ((box dictMonadState))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadTellReaderT  = (box (fun (dictMonadTell: obj) -> (let Monad1 = (sharpurs_apply (box ((Map.find "Monad1" (unbox<Map<string, obj>> ((box dictMonadTell)))))) (box ((box Prim_undefined)))) in let Semigroup0 = (sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonadTell)))))) (box ((box Prim_undefined)))) in let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((box Monad1)))) in (sharpurs_apply (box ((box Control_Monad_Writer_Class_MonadTellusd_Dict))) (box ((box ((Map.add "tell" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_lift))) (box ((box Monad1))))))))) (box ((sharpurs_apply (box ((box Control_Monad_Writer_Class_tell))) (box ((box dictMonadTell))))))))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box Semigroup0))))) (Map.add "Monad1" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) Map.empty)))))))))))

let Control_Monad_Reader_Trans_monadWriterReaderT  = (box (fun (dictMonadWriter: obj) -> (let Monoid0 = (sharpurs_apply (box ((Map.find "Monoid0" (unbox<Map<string, obj>> ((box dictMonadWriter)))))) (box ((box Prim_undefined)))) in let monadTellReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadTellReaderT))) (box ((sharpurs_apply (box ((Map.find "MonadTell1" (unbox<Map<string, obj>> ((box dictMonadWriter)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Writer_Class_MonadWriterusd_Dict))) (box ((box ((Map.add "listen" (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_mapReaderT))) (box ((sharpurs_apply (box ((box Control_Monad_Writer_Class_listen))) (box ((box dictMonadWriter))))))))) (Map.add "pass" (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_mapReaderT))) (box ((sharpurs_apply (box ((box Control_Monad_Writer_Class_pass))) (box ((box dictMonadWriter))))))))) (Map.add "Monoid0" (box ((box (fun (usd__unused: obj) -> (box Monoid0))))) (Map.add "MonadTell1" (box ((box (fun (usd__unused: obj) -> (box monadTellReaderT1))))) Map.empty))))))))))))

let Control_Monad_Reader_Trans_monadThrowReaderT  = (box (fun (dictMonadThrow: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadThrow)))))) (box ((box Prim_undefined)))) in let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((box Monad0)))) in (sharpurs_apply (box ((box Control_Monad_Error_Class_MonadThrowusd_Dict))) (box ((box ((Map.add "throwError" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_lift))) (box ((box Monad0))))))))) (box ((sharpurs_apply (box ((box Control_Monad_Error_Class_throwError))) (box ((box dictMonadThrow))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadErrorReaderT  = (box (fun (dictMonadError: obj) -> (let monadThrowReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadThrowReaderT))) (box ((sharpurs_apply (box ((Map.find "MonadThrow0" (unbox<Map<string, obj>> ((box dictMonadError)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Error_Class_MonadErrorusd_Dict))) (box ((box ((Map.add "catchError" (box ((box (fun (v: obj) -> (box (fun (h: obj) -> (match (((unbox ((box v))), (unbox ((box h))))) with | (m, h1) -> ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((box (fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Error_Class_catchError))) (box ((box dictMonadError)))))) (box ((sharpurs_apply (box ((box m))) (box ((box r))))))))) (box ((box (fun (e: obj) -> (let v1 = (sharpurs_apply (box ((box h1))) (box ((box e)))) in (match ((unbox ((box v1)))) with | f -> ((sharpurs_apply (box ((box f))) (box ((box r))))))))))))))))))))))))) (Map.add "MonadThrow0" (box ((box (fun (usd__unused: obj) -> (box monadThrowReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadSTReaderT  = (box (fun (dictMonadST: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadST)))))) (box ((box Prim_undefined)))) in let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((box Monad0)))) in (sharpurs_apply (box ((box Control_Monad_ST_Class_MonadSTusd_Dict))) (box ((box ((Map.add "liftST" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_lift))) (box ((box Monad0))))))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Class_liftST))) (box ((box dictMonadST))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monoidReaderT  = (box (fun (dictApplicative: obj) -> (let applicativeReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_applicativeReaderT))) (box ((box dictApplicative)))) in let semigroupReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_semigroupReaderT))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (box (fun (dictMonoid: obj) -> (let semigroupReaderT2 = (sharpurs_apply (box ((box semigroupReaderT1))) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box applicativeReaderT1)))))) (box ((sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid))))))))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box semigroupReaderT2))))) Map.empty)))))))))))))

let Control_Monad_Reader_Trans_altReaderT  = (box (fun (dictAlt: obj) -> (let functorReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_functorReaderT))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictAlt)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Alt_Altusd_Dict))) (box ((box ((Map.add "alt" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (m, n) -> ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((box (fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Alt_alt))) (box ((box dictAlt)))))) (box ((sharpurs_apply (box ((box m))) (box ((box r))))))))) (box ((sharpurs_apply (box ((box n))) (box ((box r)))))))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_plusReaderT  = (box (fun (dictPlus: obj) -> (let altReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_altReaderT))) (box ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> ((box dictPlus)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Plus_Plususd_Dict))) (box ((box ((Map.add "empty" (box ((sharpurs_apply (box ((box Control_Monad_Reader_Trans_ReaderT))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((sharpurs_apply (box ((box Control_Plus_empty))) (box ((box dictPlus)))))))))))) (Map.add "Alt0" (box ((box (fun (usd__unused: obj) -> (box altReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_alternativeReaderT  = (box (fun (dictAlternative: obj) -> (let applicativeReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_applicativeReaderT))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))) in let plusReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_plusReaderT))) (box ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Alternative_Alternativeusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box applicativeReaderT1))))) (Map.add "Plus1" (box ((box (fun (usd__unused: obj) -> (box plusReaderT1))))) Map.empty))))))))))

let Control_Monad_Reader_Trans_monadPlusReaderT  = (box (fun (dictMonadPlus: obj) -> (let monadReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadReaderT))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadPlus)))))) (box ((box Prim_undefined))))))) in let alternativeReaderT1 = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_alternativeReaderT))) (box ((sharpurs_apply (box ((Map.find "Alternative1" (unbox<Map<string, obj>> ((box dictMonadPlus)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_MonadPlus_MonadPlususd_Dict))) (box ((box ((Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadReaderT1))))) (Map.add "Alternative1" (box ((box (fun (usd__unused: obj) -> (box alternativeReaderT1))))) Map.empty))))))))))
