[<AutoOpen>]
module PureScript_Control_Comonad_Env_Class

open System
open System.Collections.Generic

let Control_Comonad_Env_Class_lower  = (sharpurs_apply (box ((box Control_Comonad_Trans_Class_lower))) (box ((box Control_Comonad_Store_Trans_comonadTransStoreT))))

let Control_Comonad_Env_Class_ComonadAskusd_Dict  = (box (fun (x: obj) -> (box x)))

let Control_Comonad_Env_Class_ComonadEnvusd_Dict  = (box (fun (x: obj) -> (box x)))

let Control_Comonad_Env_Class_local  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "local" (unbox<Map<string, obj>> ((box v))))))))

let Control_Comonad_Env_Class_comonadAskTuple  = (sharpurs_apply (box ((box Control_Comonad_Env_Class_ComonadAskusd_Dict))) (box ((box ((Map.add "ask" (box ((box Data_Tuple_fst))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box Data_Tuple_comonadTuple))))) Map.empty)))))))

let Control_Comonad_Env_Class_comonadEnvTuple  = (sharpurs_apply (box ((box Control_Comonad_Env_Class_ComonadEnvusd_Dict))) (box ((box ((Map.add "local" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_Tuple_Tupleusd_Ctor(x, y)) -> ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((box f1))) (box ((box x)))), (box y)))))))))))) (Map.add "ComonadAsk0" (box ((box (fun (usd__unused: obj) -> (box Control_Comonad_Env_Class_comonadAskTuple))))) Map.empty)))))))

let Control_Comonad_Env_Class_comonadAskEnvT  = (box (fun (dictComonad: obj) -> (let comonadEnvT = (sharpurs_apply (box ((box Control_Comonad_Env_Trans_comonadEnvT))) (box ((box dictComonad)))) in (sharpurs_apply (box ((box Control_Comonad_Env_Class_ComonadAskusd_Dict))) (box ((box ((Map.add "ask" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | x -> ((sharpurs_apply (box ((box Data_Tuple_fst))) (box ((box x)))))))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadEnvT))))) Map.empty))))))))))

let Control_Comonad_Env_Class_comonadEnvEnvT  = (box (fun (dictComonad: obj) -> (let comonadAskEnvT1 = (sharpurs_apply (box ((box Control_Comonad_Env_Class_comonadAskEnvT))) (box ((box dictComonad)))) in (sharpurs_apply (box ((box Control_Comonad_Env_Class_ComonadEnvusd_Dict))) (box ((box ((Map.add "local" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, x) -> ((sharpurs_apply (box ((box Control_Comonad_Env_Trans_EnvT))) (box ((match ((unbox ((box x)))) with | Data_Tuple_Tupleusd_Ctor(y, z) -> ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((box f1))) (box ((box y)))), (box z))))))))))))))))) (Map.add "ComonadAsk0" (box ((box (fun (usd__unused: obj) -> (box comonadAskEnvT1))))) Map.empty))))))))))

let Control_Comonad_Env_Class_ask  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "ask" (unbox<Map<string, obj>> ((box v))))))))

let Control_Comonad_Env_Class_asks  = (box (fun (dictComonadAsk: obj) -> (box (fun (f: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Env_Class_ask))) (box ((box dictComonadAsk)))))) (box ((box x)))))))))))))

let Control_Comonad_Env_Class_comonadAskStoreT  = (box (fun (dictComonadAsk: obj) -> (let Comonad0 = (sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadAsk)))))) (box ((box Prim_undefined)))) in let comonadStoreT = (sharpurs_apply (box ((box Control_Comonad_Store_Trans_comonadStoreT))) (box ((box Comonad0)))) in (sharpurs_apply (box ((box Control_Comonad_Env_Class_ComonadAskusd_Dict))) (box ((box ((Map.add "ask" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Comonad_Env_Class_ask))) (box ((box dictComonadAsk))))))))) (box ((sharpurs_apply (box ((box Control_Comonad_Env_Class_lower))) (box ((box Comonad0))))))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadStoreT))))) Map.empty))))))))))

let Control_Comonad_Env_Class_comonadEnvStoreT  = (box (fun (dictComonadEnv: obj) -> (let comonadAskStoreT1 = (sharpurs_apply (box ((box Control_Comonad_Env_Class_comonadAskStoreT))) (box ((sharpurs_apply (box ((Map.find "ComonadAsk0" (unbox<Map<string, obj>> ((box dictComonadEnv)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Comonad_Env_Class_ComonadEnvusd_Dict))) (box ((box ((Map.add "local" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_Tuple_Tupleusd_Ctor(w, s)) -> ((sharpurs_apply (box ((box Control_Comonad_Store_Trans_StoreT))) (box ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Env_Class_local))) (box ((box dictComonadEnv)))))) (box ((box f1)))))) (box ((box w)))), (box s))))))))))))))) (Map.add "ComonadAsk0" (box ((box (fun (usd__unused: obj) -> (box comonadAskStoreT1))))) Map.empty))))))))))

let Control_Comonad_Env_Class_comonadAskTracedT  = (box (fun (dictComonadAsk: obj) -> (let ask1 = (sharpurs_apply (box ((box Control_Comonad_Env_Class_ask))) (box ((box dictComonadAsk)))) in let Comonad0 = (sharpurs_apply (box ((Map.find "Comonad0" (unbox<Map<string, obj>> ((box dictComonadAsk)))))) (box ((box Prim_undefined)))) in let comonadTracedT = (sharpurs_apply (box ((box Control_Comonad_Traced_Trans_comonadTracedT))) (box ((box Comonad0)))) in (box (fun (dictMonoid: obj) -> (let comonadTracedT1 = (sharpurs_apply (box ((box comonadTracedT))) (box ((box dictMonoid)))) in (sharpurs_apply (box ((box Control_Comonad_Env_Class_ComonadAskusd_Dict))) (box ((box ((Map.add "ask" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box ask1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Trans_Class_lower))) (box ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_comonadTransTracedT))) (box ((box dictMonoid))))))))) (box ((box Comonad0))))))))) (Map.add "Comonad0" (box ((box (fun (usd__unused: obj) -> (box comonadTracedT1))))) Map.empty)))))))))))))

let Control_Comonad_Env_Class_comonadEnvTracedT  = (box (fun (dictComonadEnv: obj) -> (let comonadAskTracedT1 = (sharpurs_apply (box ((box Control_Comonad_Env_Class_comonadAskTracedT))) (box ((sharpurs_apply (box ((Map.find "ComonadAsk0" (unbox<Map<string, obj>> ((box dictComonadEnv)))))) (box ((box Prim_undefined))))))) in (box (fun (dictMonoid: obj) -> (let comonadAskTracedT2 = (sharpurs_apply (box ((box comonadAskTracedT1))) (box ((box dictMonoid)))) in (sharpurs_apply (box ((box Control_Comonad_Env_Class_ComonadEnvusd_Dict))) (box ((box ((Map.add "local" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, w) -> ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_TracedT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_Env_Class_local))) (box ((box dictComonadEnv)))))) (box ((box f1)))))) (box ((box w))))))))))))))) (Map.add "ComonadAsk0" (box ((box (fun (usd__unused: obj) -> (box comonadAskTracedT2))))) Map.empty)))))))))))))
