[<AutoOpen>]
module PureScript_Control_Comonad_Traced_Trans

open System
open System.Collections.Generic

let Control_Comonad_Traced_Trans_TracedT  = (box (fun (x: obj) -> (box x)))

let Control_Comonad_Traced_Trans_runTracedT  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | w -> ((box w)))))

let Control_Comonad_Traced_Trans_newtypeTracedT  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Control_Comonad_Traced_Trans_functorTracedT  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, w) -> ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_TracedT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box (fun (g: obj) -> (box (fun (t: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box f1)))))) (box ((sharpurs_apply (box ((box g))) (box ((box t)))))))))))))))) (box ((box w))))))))))))))) Map.empty))))))))

let Control_Comonad_Traced_Trans_extendTracedT  = (box (fun (dictExtend: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictExtend)))))) (box ((box Prim_undefined)))) in let functorTracedT1 = (sharpurs_apply (box ((box Control_Comonad_Traced_Trans_functorTracedT))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictExtend)))))) (box ((box Prim_undefined))))))) in (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((box Control_Extend_Extendusd_Dict))) (box ((box ((Map.add "extend" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, w) -> ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_TracedT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Extend_extend))) (box ((box dictExtend)))))) (box ((box (fun (w_prime: obj) -> (box (fun (t: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box f1)))))) (box ((sharpurs_apply (box ((box Control_Comonad_Traced_Trans_TracedT))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box (fun (h: obj) -> (box (fun (t_prime: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box h)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))))) (box ((box t)))))) (box ((box t_prime)))))))))))))))) (box ((box w_prime))))))))))))))))))) (box ((box w))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorTracedT1))))) Map.empty))))))))))))

let Control_Comonad_Traced_Trans_comonadTransTracedT  = (box (fun (dictMonoid: obj) -> (sharpurs_apply (box ((box Control_Comonad_Trans_Class_ComonadTransusd_Dict))) (box ((box ((Map.add "lower" (box ((box (fun (dictComonad: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((box dictComonad)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (v: obj) -> (match ((unbox ((box v)))) with | w -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box (fun (f: obj) -> (sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid)))))))))))))) (box ((box w))))))))))))) Map.empty))))))))

let Control_Comonad_Traced_Trans_comonadTracedT  = (box (fun (dictComonad: obj) -> (let extendTracedT1 = (sharpurs_apply (box ((box Control_Comonad_Traced_Trans_extendTracedT))) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((box dictComonad)))))) (box ((box Prim_undefined))))))) in (box (fun (dictMonoid: obj) -> (let extendTracedT2 = (sharpurs_apply (box ((box extendTracedT1))) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Comonad_Comonadusd_Dict))) (box ((box ((Map.add "extract" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | w -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad)))))) (box ((box w)))))) (box ((sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid))))))))))))) (Map.add "Extend0" (box ((box (fun (usd__unused: obj) -> (box extendTracedT2))))) Map.empty)))))))))))))
