[<AutoOpen>]
module PureScript_Control_Monad_Cont_Trans

open System
open System.Collections.Generic

let Control_Monad_Cont_Trans_ContT  = (box (fun (x: obj) -> (box x)))

let Control_Monad_Cont_Trans_withContT  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, m) -> ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k: obj) -> (sharpurs_apply (box ((box m))) (box ((sharpurs_apply (box ((box f1))) (box ((box k))))))))))))))))))

let Control_Monad_Cont_Trans_runContT  = (box (fun (v: obj) -> (box (fun (k: obj) -> (match (((unbox ((box v))), (unbox ((box k))))) with | (f, k1) -> ((sharpurs_apply (box ((box f))) (box ((box k1))))))))))

let Control_Monad_Cont_Trans_newtypeContT  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Control_Monad_Cont_Trans_monadTransContT  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_MonadTransusd_Dict))) (box ((box ((Map.add "lift" (box ((box (fun (dictMonad: obj) -> (let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))) in (box (fun (m: obj) -> (sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((box m)))))) (box ((box k)))))))))))))))) Map.empty))))))

let Control_Monad_Cont_Trans_lift  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_Cont_Trans_monadTransContT))))

let Control_Monad_Cont_Trans_mapContT  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, m) -> ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k: obj) -> (sharpurs_apply (box ((box f1))) (box ((sharpurs_apply (box ((box m))) (box ((box k))))))))))))))))))

let Control_Monad_Cont_Trans_functorContT  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, m) -> ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k: obj) -> (sharpurs_apply (box ((box m))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box k)))))) (box ((sharpurs_apply (box ((box f1))) (box ((box a))))))))))))))))))))))))) Map.empty))))))))

let Control_Monad_Cont_Trans_applyContT  = (box (fun (dictApply: obj) -> (let functorContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_functorContT))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, v2) -> ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k: obj) -> (sharpurs_apply (box ((box f))) (box ((box (fun (g: obj) -> (sharpurs_apply (box ((box v2))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((box k))) (box ((sharpurs_apply (box ((box g))) (box ((box a)))))))))))))))))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_bindContT  = (box (fun (dictBind: obj) -> (let applyContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_applyContT))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictBind)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((box (fun (v: obj) -> (box (fun (k: obj) -> (match (((unbox ((box v))), (unbox ((box k))))) with | (m, k1) -> ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k_prime: obj) -> (sharpurs_apply (box ((box m))) (box ((box (fun (a: obj) -> (let v1 = (sharpurs_apply (box ((box k1))) (box ((box a)))) in (match ((unbox ((box v1)))) with | m_prime -> ((sharpurs_apply (box ((box m_prime))) (box ((box k_prime))))))))))))))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_semigroupContT  = (box (fun (dictApply: obj) -> (let applyContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_applyContT))) (box ((box dictApply)))) in (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((box Data_Semigroup_Semigroupusd_Dict))) (box ((box ((Map.add "append" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_lift2))) (box ((box applyContT1)))))) (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup))))))))) Map.empty)))))))))))

let Control_Monad_Cont_Trans_applicativeContT  = (box (fun (dictApplicative: obj) -> (let applyContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_applyContT))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((box (fun (a: obj) -> (sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k: obj) -> (sharpurs_apply (box ((box k))) (box ((box a))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_monadContT  = (box (fun (dictMonad: obj) -> (let applicativeContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_applicativeContT))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in let bindContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_bindContT))) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box applicativeContT1))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box bindContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_monadAskContT  = (box (fun (dictMonadAsk: obj) -> (let monadContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_monadContT))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadAsk)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Reader_Class_MonadAskusd_Dict))) (box ((box ((Map.add "ask" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_Cont_Trans_monadTransContT)))))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadAsk)))))) (box ((box Prim_undefined))))))))) (box ((sharpurs_apply (box ((box Control_Monad_Reader_Class_ask))) (box ((box dictMonadAsk))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_monadReaderContT  = (box (fun (dictMonadReader: obj) -> (let MonadAsk0 = (sharpurs_apply (box ((Map.find "MonadAsk0" (unbox<Map<string, obj>> ((box dictMonadReader)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadAsk0)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let ask = (sharpurs_apply (box ((box Control_Monad_Reader_Class_ask))) (box ((box MonadAsk0)))) in let monadAskContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_monadAskContT))) (box ((box MonadAsk0)))) in (sharpurs_apply (box ((box Control_Monad_Reader_Class_MonadReaderusd_Dict))) (box ((box ((Map.add "local" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, c) -> ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((box ask)))))) (box ((box (fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Reader_Class_local))) (box ((box dictMonadReader)))))) (box ((box f1)))))) (box ((sharpurs_apply (box ((box c))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Reader_Class_local))) (box ((box dictMonadReader)))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box r)))))))))))) (box ((box k)))))))))))))))))))))))))))) (Map.add "MonadAsk0" (box ((box (fun (usd__unused: obj) -> (box monadAskContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_monadContContT  = (box (fun (dictMonad: obj) -> (let monadContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_monadContT))) (box ((box dictMonad)))) in (sharpurs_apply (box ((box Control_Monad_Cont_Class_MonadContusd_Dict))) (box ((box ((Map.add "callCC" (box ((box (fun (f: obj) -> (sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (k: obj) -> (let v = (sharpurs_apply (box ((box f))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((box Control_Monad_Cont_Trans_ContT))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((box k))) (box ((box a)))))))))))))) in (match ((unbox ((box v)))) with | f_prime -> ((sharpurs_apply (box ((box f_prime))) (box ((box k)))))))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_monadEffectContT  = (box (fun (dictMonadEffect: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadEffect)))))) (box ((box Prim_undefined)))) in let monadContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_monadContT))) (box ((box Monad0)))) in (sharpurs_apply (box ((box Effect_Class_MonadEffectusd_Dict))) (box ((box ((Map.add "liftEffect" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_lift))) (box ((box Monad0))))))))) (box ((sharpurs_apply (box ((box Effect_Class_liftEffect))) (box ((box dictMonadEffect))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_monadStateContT  = (box (fun (dictMonadState: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadState)))))) (box ((box Prim_undefined)))) in let monadContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_monadContT))) (box ((box Monad0)))) in (sharpurs_apply (box ((box Control_Monad_State_Class_MonadStateusd_Dict))) (box ((box ((Map.add "state" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_lift))) (box ((box Monad0))))))))) (box ((sharpurs_apply (box ((box Control_Monad_State_Class_state))) (box ((box dictMonadState))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_monadSTContT  = (box (fun (dictMonadST: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadST)))))) (box ((box Prim_undefined)))) in let monadContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_monadContT))) (box ((box Monad0)))) in (sharpurs_apply (box ((box Control_Monad_ST_Class_MonadSTusd_Dict))) (box ((box ((Map.add "liftST" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Control_Monad_Cont_Trans_lift))) (box ((box Monad0))))))))) (box ((sharpurs_apply (box ((box Control_Monad_ST_Class_liftST))) (box ((box dictMonadST))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadContT1))))) Map.empty))))))))))

let Control_Monad_Cont_Trans_monoidContT  = (box (fun (dictApplicative: obj) -> (let applicativeContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_applicativeContT))) (box ((box dictApplicative)))) in let semigroupContT1 = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_semigroupContT))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (box (fun (dictMonoid: obj) -> (let semigroupContT2 = (sharpurs_apply (box ((box semigroupContT1))) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box applicativeContT1)))))) (box ((sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid))))))))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box semigroupContT2))))) Map.empty)))))))))))))
