[<AutoOpen>]
module PureScript_Data_String_Gen

open System
open System.Collections.Generic

let Data_String_Gen_genString  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (genChar: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_sized))) (box ((box dictMonadGen)))))) (box ((box (fun (size: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_max))) (box ((box Data_Ord_ordInt)))))) (box ((box 1)))))) (box ((box size)))))))))))) (box ((box (fun (newSize: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_resize))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box newSize)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_String_CodeUnits_fromCharArray)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_unfoldable))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((box Data_Unfoldable_unfoldableArray)))))) (box ((box genChar)))))))))))))))))))))))))))

let Data_String_Gen_genUnicodeString  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_String_Gen_genString))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Char_Gen_genUnicodeChar))) (box ((box dictMonadGen)))))))))))

let Data_String_Gen_genDigitString  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_String_Gen_genString))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Char_Gen_genDigitChar))) (box ((box dictMonadGen)))))))))))

let Data_String_Gen_genAsciiString_prime  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_String_Gen_genString))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Char_Gen_genAsciiChar_prime))) (box ((box dictMonadGen)))))))))))

let Data_String_Gen_genAsciiString  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_String_Gen_genString))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Char_Gen_genAsciiChar))) (box ((box dictMonadGen)))))))))))

let Data_String_Gen_genAlphaUppercaseString  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_String_Gen_genString))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Char_Gen_genAlphaUppercase))) (box ((box dictMonadGen)))))))))))

let Data_String_Gen_genAlphaString  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_String_Gen_genString))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Char_Gen_genAlpha))) (box ((box dictMonadGen)))))))))))

let Data_String_Gen_genAlphaLowercaseString  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_String_Gen_genString))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((box Data_Char_Gen_genAlphaLowercase))) (box ((box dictMonadGen)))))))))))
