[<AutoOpen>]
module PureScript_Data_Semigroup_Foldable

open System
open System.Collections.Generic

type Data_Semigroup_Foldable_FoldRight1 =
  | Data_Semigroup_Foldable_FoldRight1usd_Ctor of obj * obj

let Data_Semigroup_Foldable_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Semigroup_Foldable_identity1  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Semigroup_Foldable_JoinWith  = (box (fun (x: obj) -> (box x)))

let Data_Semigroup_Foldable_Foldable1usd_Dict  = (box (fun (x: obj) -> (box x)))

let Data_Semigroup_Foldable_FoldRight1  = (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Semigroup_Foldable_FoldRight1usd_Ctor(usd__arg1, usd__arg2)))))))

let Data_Semigroup_Foldable_Act  = (box (fun (x: obj) -> (box x)))

let Data_Semigroup_Foldable_semigroupJoinWith  = (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((box Data_Semigroup_Semigroupusd_Dict))) (box ((box ((Map.add "append" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (a, b) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Semigroup_Foldable_JoinWith)))))) (box ((box (fun (j: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))))) (box ((sharpurs_apply (box ((box a))) (box ((box j))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))))) (box ((box j)))))) (box ((sharpurs_apply (box ((box b))) (box ((box j))))))))))))))))))))))) Map.empty))))))))

let Data_Semigroup_Foldable_semigroupAct  = (box (fun (dictApply: obj) -> (sharpurs_apply (box ((box Data_Semigroup_Semigroupusd_Dict))) (box ((box ((Map.add "append" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (a, b) -> ((sharpurs_apply (box ((box Data_Semigroup_Foldable_Act))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_applySecond))) (box ((box dictApply)))))) (box ((box a)))))) (box ((box b))))))))))))))) Map.empty))))))))

let Data_Semigroup_Foldable_runFoldRight1  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Semigroup_Foldable_FoldRight1usd_Ctor(f, a) -> ((sharpurs_apply (box ((box f))) (box ((box a))))))))

let Data_Semigroup_Foldable_mkFoldRight1  = (sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Semigroup_Foldable_FoldRight1usd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box Data_Function_const))))

let Data_Semigroup_Foldable_joinee  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | x -> ((box x)))))

let Data_Semigroup_Foldable_getAct  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((box f)))))

let Data_Semigroup_Foldable_foldr1  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "foldr1" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semigroup_Foldable_foldl1  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "foldl1" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semigroup_Foldable_maximumBy  = (box (fun (dictFoldable1: obj) -> (box (fun (cmp: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldl1))) (box ((box dictFoldable1)))))) (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Ordering_eqOrdering)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box cmp))) (box ((box x)))))) (box ((box y))))))))) (box ((box Data_Ordering_GTusd_Ctor))))))) with | LitBool true () -> ((box x)) | _ -> ((box y))))))))))))))

let Data_Semigroup_Foldable_minimumBy  = (box (fun (dictFoldable1: obj) -> (box (fun (cmp: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldl1))) (box ((box dictFoldable1)))))) (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Ordering_eqOrdering)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box cmp))) (box ((box x)))))) (box ((box y))))))))) (box ((box Data_Ordering_LTusd_Ctor))))))) with | LitBool true () -> ((box x)) | _ -> ((box y))))))))))))))

let Data_Semigroup_Foldable_foldableTuple  = (sharpurs_apply (box ((box Data_Semigroup_Foldable_Foldable1usd_Dict))) (box ((box ((Map.add "foldMap1" (box ((box (fun (dictSemigroup: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_Tuple_Tupleusd_Ctor(_, x)) -> ((sharpurs_apply (box ((box f1))) (box ((box x)))))))))))))) (Map.add "foldr1" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_Tuple_Tupleusd_Ctor(_, x)) -> ((box x))))))))) (Map.add "foldl1" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_Tuple_Tupleusd_Ctor(_, x)) -> ((box x))))))))) (Map.add "Foldable0" (box ((box (fun (usd__unused: obj) -> (box Data_Foldable_foldableTuple))))) Map.empty)))))))))

let Data_Semigroup_Foldable_foldableMultiplicative  = (sharpurs_apply (box ((box Data_Semigroup_Foldable_Foldable1usd_Dict))) (box ((box ((Map.add "foldr1" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, x) -> ((box x))))))))) (Map.add "foldl1" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, x) -> ((box x))))))))) (Map.add "foldMap1" (box ((box (fun (dictSemigroup: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, x) -> ((sharpurs_apply (box ((box f1))) (box ((box x)))))))))))))) (Map.add "Foldable0" (box ((box (fun (usd__unused: obj) -> (box Data_Foldable_foldableMultiplicative))))) Map.empty)))))))))

let Data_Semigroup_Foldable_foldableIdentity  = (sharpurs_apply (box ((box Data_Semigroup_Foldable_Foldable1usd_Dict))) (box ((box ((Map.add "foldMap1" (box ((box (fun (dictSemigroup: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, x) -> ((sharpurs_apply (box ((box f1))) (box ((box x)))))))))))))) (Map.add "foldl1" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, x) -> ((box x))))))))) (Map.add "foldr1" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, x) -> ((box x))))))))) (Map.add "Foldable0" (box ((box (fun (usd__unused: obj) -> (box Data_Foldable_foldableIdentity))))) Map.empty)))))))))

let Data_Semigroup_Foldable_foldableDual  = (sharpurs_apply (box ((box Data_Semigroup_Foldable_Foldable1usd_Dict))) (box ((box ((Map.add "foldr1" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, x) -> ((box x))))))))) (Map.add "foldl1" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, x) -> ((box x))))))))) (Map.add "foldMap1" (box ((box (fun (dictSemigroup: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, x) -> ((sharpurs_apply (box ((box f1))) (box ((box x)))))))))))))) (Map.add "Foldable0" (box ((box (fun (usd__unused: obj) -> (box Data_Foldable_foldableDual))))) Map.empty)))))))))

let Data_Semigroup_Foldable_foldRight1Semigroup  = (sharpurs_apply (box ((box Data_Semigroup_Semigroupusd_Dict))) (box ((box ((Map.add "append" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Semigroup_Foldable_FoldRight1usd_Ctor(lf, lr), Data_Semigroup_Foldable_FoldRight1usd_Ctor(rf, rr)) -> ((box (Data_Semigroup_Foldable_FoldRight1usd_Ctor((box (fun (a: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box lf))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box lr)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box rf))) (box ((box a)))))) (box ((box f)))))))))))) (box ((box f)))))))), (box rr)))))))))))) Map.empty))))))

let Data_Semigroup_Foldable_semigroupDual  = (sharpurs_apply (box ((box Data_Monoid_Dual_semigroupDual))) (box ((box Data_Semigroup_Foldable_foldRight1Semigroup))))

let Data_Semigroup_Foldable_foldMap1DefaultR  = (box (fun (dictFoldable1: obj) -> (box (fun (dictFunctor: obj) -> (box (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))) in (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldr1))) (box ((box dictFoldable1)))))) (box ((box append))))))))))))))))

let Data_Semigroup_Foldable_foldMap1DefaultL  = (box (fun (dictFoldable1: obj) -> (box (fun (dictFunctor: obj) -> (box (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))) in (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldl1))) (box ((box dictFoldable1)))))) (box ((box append))))))))))))))))

let Data_Semigroup_Foldable_foldMap1  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "foldMap1" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semigroup_Foldable_foldl1Default  = (box (fun (dictFoldable1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Semigroup_Foldable_runFoldRight1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_alaF))) (box ((box Prim_undefined)))))) (box ((box Prim_undefined)))))) (box ((box Prim_undefined)))))) (box ((box Prim_undefined)))))) (box ((box Data_Monoid_Dual_Dual)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldMap1))) (box ((box dictFoldable1)))))) (box ((box Data_Semigroup_Foldable_semigroupDual))))))))) (box ((box Data_Semigroup_Foldable_mkFoldRight1))))))))))))))) (box ((box Data_Function_flip))))))

let Data_Semigroup_Foldable_foldr1Default  = (box (fun (dictFoldable1: obj) -> (sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Semigroup_Foldable_runFoldRight1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldMap1))) (box ((box dictFoldable1)))))) (box ((box Data_Semigroup_Foldable_foldRight1Semigroup)))))) (box ((box Data_Semigroup_Foldable_mkFoldRight1))))))))))))

let Data_Semigroup_Foldable_intercalateMap  = (box (fun (dictFoldable1: obj) -> (box (fun (dictSemigroup: obj) -> (let semigroupJoinWith1 = (sharpurs_apply (box ((box Data_Semigroup_Foldable_semigroupJoinWith))) (box ((box dictSemigroup)))) in (box (fun (j: obj) -> (box (fun (f: obj) -> (box (fun (foldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_joinee))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldMap1))) (box ((box dictFoldable1)))))) (box ((box semigroupJoinWith1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Semigroup_Foldable_JoinWith)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Function_const)))))) (box ((box f)))))))))))) (box ((box foldable))))))))) (box ((box j)))))))))))))))

let Data_Semigroup_Foldable_intercalate  = (box (fun (dictFoldable1: obj) -> (let intercalateMap1 = (sharpurs_apply (box ((box Data_Semigroup_Foldable_intercalateMap))) (box ((box dictFoldable1)))) in (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((box intercalateMap1))) (box ((box dictSemigroup))))))))) (box ((box Data_Semigroup_Foldable_identity)))))))))

let Data_Semigroup_Foldable_maximum  = (box (fun (dictOrd: obj) -> (let semigroupMax = (sharpurs_apply (box ((box Data_Ord_Max_semigroupMax))) (box ((box dictOrd)))) in (box (fun (dictFoldable1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_ala))) (box ((box Prim_undefined)))))) (box ((box Prim_undefined)))))) (box ((box Prim_undefined)))))) (box ((box Data_Ord_Max_Max)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldMap1))) (box ((box dictFoldable1)))))) (box ((box semigroupMax))))))))))))

let Data_Semigroup_Foldable_minimum  = (box (fun (dictOrd: obj) -> (let semigroupMin = (sharpurs_apply (box ((box Data_Ord_Min_semigroupMin))) (box ((box dictOrd)))) in (box (fun (dictFoldable1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_ala))) (box ((box Prim_undefined)))))) (box ((box Prim_undefined)))))) (box ((box Prim_undefined)))))) (box ((box Data_Ord_Min_Min)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldMap1))) (box ((box dictFoldable1)))))) (box ((box semigroupMin))))))))))))

let Data_Semigroup_Foldable_traverse1_  = (box (fun (dictFoldable1: obj) -> (box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in let semigroupAct1 = (sharpurs_apply (box ((box Data_Semigroup_Foldable_semigroupAct))) (box ((box dictApply)))) in (box (fun (f: obj) -> (box (fun (t: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_voidRight))) (box ((box Functor0)))))) (box ((box Data_Unit_unit)))))) (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_getAct))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldMap1))) (box ((box dictFoldable1)))))) (box ((box semigroupAct1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Semigroup_Foldable_Act)))))) (box ((box f))))))))) (box ((box t)))))))))))))))))))

let Data_Semigroup_Foldable_for1_  = (box (fun (dictFoldable1: obj) -> (let traverse1_1 = (sharpurs_apply (box ((box Data_Semigroup_Foldable_traverse1_))) (box ((box dictFoldable1)))) in (box (fun (dictApply: obj) -> (sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((box traverse1_1))) (box ((box dictApply))))))))))))

let Data_Semigroup_Foldable_sequence1_  = (box (fun (dictFoldable1: obj) -> (box (fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_traverse1_))) (box ((box dictFoldable1)))))) (box ((box dictApply)))))) (box ((box Data_Semigroup_Foldable_identity1))))))))

let Data_Semigroup_Foldable_fold1  = (box (fun (dictFoldable1: obj) -> (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_Foldable_foldMap1))) (box ((box dictFoldable1)))))) (box ((box dictSemigroup)))))) (box ((box Data_Semigroup_Foldable_identity))))))))
