[<AutoOpen>]
module PureScript_Data_Functor_Compose

open System
open System.Collections.Generic

let Data_Functor_Compose_Compose  = (box (fun (x: obj) -> (box x)))

let Data_Functor_Compose_showCompose  = (box (fun (dictShow: obj) -> (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | fga -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(Compose ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow)))))) (box ((box fga))))))))) (box ((box ")"))))))))))))) Map.empty))))))))

let Data_Functor_Compose_newtypeCompose  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Data_Functor_Compose_functorCompose  = (box (fun (dictFunctor: obj) -> (box (fun (dictFunctor1: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, fga) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Functor_Compose_Compose)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor1)))))) (box ((box f1))))))))) (box ((box fga))))))))))))))) Map.empty))))))))))

let Data_Functor_Compose_eqCompose  = (box (fun (dictEq1: obj) -> (box (fun (dictEq11: obj) -> (let eqApp = (sharpurs_apply (box ((box Data_Functor_App_eqApp))) (box ((box dictEq11)))) in (box (fun (dictEq: obj) -> (let eqApp1 = (sharpurs_apply (box ((box eqApp))) (box ((box dictEq)))) in (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (fga1, fga2) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq1))) (box ((box dictEq1)))))) (box ((box eqApp1)))))) (box ((sharpurs_apply (box ((box Data_Functor_App_hoistLiftApp))) (box ((box fga1))))))))) (box ((sharpurs_apply (box ((box Data_Functor_App_hoistLiftApp))) (box ((box fga2))))))))))))))) Map.empty))))))))))))))

let Data_Functor_Compose_ordCompose  = (box (fun (dictOrd1: obj) -> (let eqCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_eqCompose))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd1)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd11: obj) -> (let ordApp = (sharpurs_apply (box ((box Data_Functor_App_ordApp))) (box ((box dictOrd11)))) in let eqCompose2 = (sharpurs_apply (box ((box eqCompose1))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd11)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd: obj) -> (let ordApp1 = (sharpurs_apply (box ((box ordApp))) (box ((box dictOrd)))) in let eqCompose3 = (sharpurs_apply (box ((box eqCompose2))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (fga1, fga2) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare1))) (box ((box dictOrd1)))))) (box ((box ordApp1)))))) (box ((sharpurs_apply (box ((box Data_Functor_App_hoistLiftApp))) (box ((box fga1))))))))) (box ((sharpurs_apply (box ((box Data_Functor_App_hoistLiftApp))) (box ((box fga2))))))))))))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box eqCompose3))))) Map.empty))))))))))))))))

let Data_Functor_Compose_eq1Compose  = (box (fun (dictEq1: obj) -> (let eqCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_eqCompose))) (box ((box dictEq1)))) in (box (fun (dictEq11: obj) -> (let eqCompose2 = (sharpurs_apply (box ((box eqCompose1))) (box ((box dictEq11)))) in (sharpurs_apply (box ((box Data_Eq_Eq1usd_Dict))) (box ((box ((Map.add "eq1" (box ((box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_Eq_eq))) (box ((sharpurs_apply (box ((box eqCompose2))) (box ((box dictEq))))))))))) Map.empty))))))))))))

let Data_Functor_Compose_ord1Compose  = (box (fun (dictOrd1: obj) -> (let ordCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_ordCompose))) (box ((box dictOrd1)))) in let eq1Compose1 = (sharpurs_apply (box ((box Data_Functor_Compose_eq1Compose))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd1)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd11: obj) -> (let ordCompose2 = (sharpurs_apply (box ((box ordCompose1))) (box ((box dictOrd11)))) in let eq1Compose2 = (sharpurs_apply (box ((box eq1Compose1))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd11)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ord1usd_Dict))) (box ((box ((Map.add "compare1" (box ((box (fun (dictOrd: obj) -> (sharpurs_apply (box ((box Data_Ord_compare))) (box ((sharpurs_apply (box ((box ordCompose2))) (box ((box dictOrd))))))))))) (Map.add "Eq10" (box ((box (fun (usd__unused: obj) -> (box eq1Compose2))))) Map.empty)))))))))))))

let Data_Functor_Compose_bihoistCompose  = (box (fun (dictFunctor: obj) -> (box (fun (natF: obj) -> (box (fun (natG: obj) -> (box (fun (v: obj) -> (match (((unbox ((box natF))), (unbox ((box natG))), (unbox ((box v))))) with | (natF1, natG1, fga) -> ((sharpurs_apply (box ((box Data_Functor_Compose_Compose))) (box ((sharpurs_apply (box ((box natF1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box natG1)))))) (box ((box fga))))))))))))))))))))

let Data_Functor_Compose_applyCompose  = (box (fun (dictApply: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined)))) in let functorCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_functorCompose))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined))))))) in (box (fun (dictApply1: obj) -> (let apply = (sharpurs_apply (box ((box Control_Apply_apply))) (box ((box dictApply1)))) in let functorCompose2 = (sharpurs_apply (box ((box functorCompose1))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Functor_Compose_Compose)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box dictApply)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box apply)))))) (box ((box f))))))))) (box ((box x))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorCompose2))))) Map.empty)))))))))))))

let Data_Functor_Compose_applicativeCompose  = (box (fun (dictApplicative: obj) -> (let pure_var = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))) in let applyCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_applyCompose))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (box (fun (dictApplicative1: obj) -> (let applyCompose2 = (sharpurs_apply (box ((box applyCompose1))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Functor_Compose_Compose)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box pure_var)))))) (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative1)))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyCompose2))))) Map.empty)))))))))))))

let Data_Functor_Compose_altCompose  = (box (fun (dictAlt: obj) -> (let functorCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_functorCompose))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictAlt)))))) (box ((box Prim_undefined))))))) in (box (fun (dictFunctor: obj) -> (let functorCompose2 = (sharpurs_apply (box ((box functorCompose1))) (box ((box dictFunctor)))) in (sharpurs_apply (box ((box Control_Alt_Altusd_Dict))) (box ((box ((Map.add "alt" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (a, b) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Functor_Compose_Compose)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Alt_alt))) (box ((box dictAlt)))))) (box ((box a)))))) (box ((box b))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorCompose2))))) Map.empty)))))))))))))

let Data_Functor_Compose_plusCompose  = (box (fun (dictPlus: obj) -> (let empty = (sharpurs_apply (box ((box Control_Plus_empty))) (box ((box dictPlus)))) in let altCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_altCompose))) (box ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> ((box dictPlus)))))) (box ((box Prim_undefined))))))) in (box (fun (dictFunctor: obj) -> (let altCompose2 = (sharpurs_apply (box ((box altCompose1))) (box ((box dictFunctor)))) in (sharpurs_apply (box ((box Control_Plus_Plususd_Dict))) (box ((box ((Map.add "empty" (box ((sharpurs_apply (box ((box Data_Functor_Compose_Compose))) (box ((box empty)))))) (Map.add "Alt0" (box ((box (fun (usd__unused: obj) -> (box altCompose2))))) Map.empty)))))))))))))

let Data_Functor_Compose_alternativeCompose  = (box (fun (dictAlternative: obj) -> (let applicativeCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_applicativeCompose))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))) in let plusCompose1 = (sharpurs_apply (box ((box Data_Functor_Compose_plusCompose))) (box ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))) in (box (fun (dictApplicative: obj) -> (let applicativeCompose2 = (sharpurs_apply (box ((box applicativeCompose1))) (box ((box dictApplicative)))) in let plusCompose2 = (sharpurs_apply (box ((box plusCompose1))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Alternative_Alternativeusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box applicativeCompose2))))) (Map.add "Plus1" (box ((box (fun (usd__unused: obj) -> (box plusCompose2))))) Map.empty)))))))))))))
