[<AutoOpen>]
module PureScript_Data_Functor_Product_Nested

open System
open System.Collections.Generic

let Data_Functor_Product_Nested_product9  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (h: obj) -> (box (fun (i: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box c)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box d)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box e)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box f)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box g)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box h)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box i)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit)))))))))))))))))))))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product8  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (h: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box c)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box d)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box e)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box f)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box g)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box h)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit))))))))))))))))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product7  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box c)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box d)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box e)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box f)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box g)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit)))))))))))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product6  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box c)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box d)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box e)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box f)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit))))))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product5  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box c)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box d)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box e)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit)))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product4  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box c)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box d)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit))))))))))))))))))))))))

let Data_Functor_Product_Nested_product3  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box c)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit)))))))))))))))))))

let Data_Functor_Product_Nested_product2  = (box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit))))))))))))))

let Data_Functor_Product_Nested_product10  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (fun (d: obj) -> (box (fun (e: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (h: obj) -> (box (fun (i: obj) -> (box (fun (j: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box b)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box c)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box d)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box e)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box f)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box g)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box h)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box i)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box j)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit))))))))))))))))))))))))))))))))))))))))))))))))))))))

let Data_Functor_Product_Nested_product1  = (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((box a)))))) (box ((sharpurs_apply (box ((box Data_Const_Const))) (box ((box Data_Unit_unit)))))))))

let Data_Functor_Product_Nested_get9  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(i, _))))))))))))))))) -> ((box i)))))

let Data_Functor_Product_Nested_get8  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(h, _))))))))))))))) -> ((box h)))))

let Data_Functor_Product_Nested_get7  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(g, _))))))))))))) -> ((box g)))))

let Data_Functor_Product_Nested_get6  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(f, _))))))))))) -> ((box f)))))

let Data_Functor_Product_Nested_get5  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(e, _))))))))) -> ((box e)))))

let Data_Functor_Product_Nested_get4  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(d, _))))))) -> ((box d)))))

let Data_Functor_Product_Nested_get3  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(c, _))))) -> ((box c)))))

let Data_Functor_Product_Nested_get2  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(b, _))) -> ((box b)))))

let Data_Functor_Product_Nested_get10  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(_, Unbox(Data_Tuple_Tupleusd_Ctor(j, _))))))))))))))))))) -> ((box j)))))

let Data_Functor_Product_Nested_get1  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(a, _) -> ((box a)))))
