[<AutoOpen>]
module PureScript_Data_Bifoldable

open System
open System.Collections.Generic

let Data_Bifoldable_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Bifoldable_identity1  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Bifoldable_monoidDual  = (sharpurs_apply (box ((box Data_Monoid_Dual_monoidDual))) (box ((sharpurs_apply (box ((box Data_Monoid_Endo_monoidEndo))) (box ((box Control_Category_categoryFn)))))))

let Data_Bifoldable_monoidEndo  = (sharpurs_apply (box ((box Data_Monoid_Endo_monoidEndo))) (box ((box Control_Category_categoryFn))))

let Data_Bifoldable_identity2  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Bifoldable_unwrap  = (sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined))))

let Data_Bifoldable_Bifoldableusd_Dict  = (box (fun (x: obj) -> (box x)))

let Data_Bifoldable_bifoldr  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "bifoldr" (unbox<Map<string, obj>> ((box v))))))))

let Data_Bifoldable_bitraverse_  = (box (fun (dictBifoldable: obj) -> (box (fun (dictApplicative: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined)))) in let applySecond = (sharpurs_apply (box ((box Control_Apply_applySecond))) (box ((box Apply0)))) in let applySecond1 = (sharpurs_apply (box ((box Control_Apply_applySecond))) (box ((box Apply0)))) in (box (fun (f: obj) -> (box (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldr))) (box ((box dictBifoldable)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box applySecond)))))) (box ((box f))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box applySecond1)))))) (box ((box g))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))))) (box ((box Data_Unit_unit))))))))))))))))

let Data_Bifoldable_bifor_  = (box (fun (dictBifoldable: obj) -> (box (fun (dictApplicative: obj) -> (box (fun (t: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bitraverse_))) (box ((box dictBifoldable)))))) (box ((box dictApplicative)))))) (box ((box f)))))) (box ((box g)))))) (box ((box t))))))))))))))

let Data_Bifoldable_bisequence_  = (box (fun (dictBifoldable: obj) -> (box (fun (dictApplicative: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bitraverse_))) (box ((box dictBifoldable)))))) (box ((box dictApplicative)))))) (box ((box Data_Bifoldable_identity)))))) (box ((box Data_Bifoldable_identity1))))))))

let Data_Bifoldable_bifoldl  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "bifoldl" (unbox<Map<string, obj>> ((box v))))))))

let Data_Bifoldable_bifoldableTuple  = (sharpurs_apply (box ((box Data_Bifoldable_Bifoldableusd_Dict))) (box ((box ((Map.add "bifoldMap" (box ((box (fun (dictMonoid: obj) -> (let Semigroup0 = (sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box v))))) with | (f1, g1, Data_Tuple_Tupleusd_Ctor(a, b)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Semigroup0)))))) (box ((sharpurs_apply (box ((box f1))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box g1))) (box ((box b)))))))))))))))))))) (Map.add "bifoldr" (box ((box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (z: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box z))), (unbox ((box v))))) with | (f1, g1, z1, Data_Tuple_Tupleusd_Ctor(a, b)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box f1))) (box ((box a)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box g1))) (box ((box b)))))) (box ((box z1))))))))))))))))))) (Map.add "bifoldl" (box ((box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (z: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box z))), (unbox ((box v))))) with | (f1, g1, z1, Data_Tuple_Tupleusd_Ctor(a, b)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box g1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box f1))) (box ((box z1)))))) (box ((box a))))))))) (box ((box b)))))))))))))))) Map.empty))))))))

let Data_Bifoldable_bifoldableJoker  = (box (fun (dictFoldable: obj) -> (sharpurs_apply (box ((box Data_Bifoldable_Bifoldableusd_Dict))) (box ((box ((Map.add "bifoldr" (box ((box (fun (v: obj) -> (box (fun (r: obj) -> (box (fun (u: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box r))), (unbox ((box u))), (unbox ((box v1))))) with | (_, r1, u1, f) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldr))) (box ((box dictFoldable)))))) (box ((box r1)))))) (box ((box u1)))))) (box ((box f)))))))))))))))) (Map.add "bifoldl" (box ((box (fun (v: obj) -> (box (fun (r: obj) -> (box (fun (u: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box r))), (unbox ((box u))), (unbox ((box v1))))) with | (_, r1, u1, f) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldl))) (box ((box dictFoldable)))))) (box ((box r1)))))) (box ((box u1)))))) (box ((box f)))))))))))))))) (Map.add "bifoldMap" (box ((box (fun (dictMonoid: obj) -> (box (fun (v: obj) -> (box (fun (r: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box r))), (unbox ((box v1))))) with | (_, r1, f) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldMap))) (box ((box dictFoldable)))))) (box ((box dictMonoid)))))) (box ((box r1)))))) (box ((box f)))))))))))))))) Map.empty))))))))))

let Data_Bifoldable_bifoldableEither  = (sharpurs_apply (box ((box Data_Bifoldable_Bifoldableusd_Dict))) (box ((box ((Map.add "bifoldr" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (box (fun (v2: obj) -> (box (fun (v3: obj) -> (match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))), (unbox ((box v3))))) with | (f, _, z, Data_Either_Leftusd_Ctor(a)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box a)))))) (box ((box z))))) | (_, g, z, Data_Either_Rightusd_Ctor(b)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box g))) (box ((box b)))))) (box ((box z)))))))))))))))) (Map.add "bifoldl" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (box (fun (v2: obj) -> (box (fun (v3: obj) -> (match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))), (unbox ((box v3))))) with | (f, _, z, Data_Either_Leftusd_Ctor(a)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box z)))))) (box ((box a))))) | (_, g, z, Data_Either_Rightusd_Ctor(b)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box g))) (box ((box z)))))) (box ((box b)))))))))))))))) (Map.add "bifoldMap" (box ((box (fun (dictMonoid: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (box (fun (v2: obj) -> (match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))))) with | (f, _, Data_Either_Leftusd_Ctor(a)) -> ((sharpurs_apply (box ((box f))) (box ((box a))))) | (_, g, Data_Either_Rightusd_Ctor(b)) -> ((sharpurs_apply (box ((box g))) (box ((box b)))))))))))))))) Map.empty))))))))

let Data_Bifoldable_bifoldableConst  = (sharpurs_apply (box ((box Data_Bifoldable_Bifoldableusd_Dict))) (box ((box ((Map.add "bifoldr" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (z: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box z))), (unbox ((box v1))))) with | (f1, _, z1, a) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box f1))) (box ((box a)))))) (box ((box z1)))))))))))))))) (Map.add "bifoldl" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (z: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box z))), (unbox ((box v1))))) with | (f1, _, z1, a) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box f1))) (box ((box z1)))))) (box ((box a)))))))))))))))) (Map.add "bifoldMap" (box ((box (fun (dictMonoid: obj) -> (box (fun (f: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box f))), (unbox ((box v))), (unbox ((box v1))))) with | (f1, _, a) -> ((sharpurs_apply (box ((box f1))) (box ((box a)))))))))))))))) Map.empty))))))))

let Data_Bifoldable_bifoldableClown  = (box (fun (dictFoldable: obj) -> (sharpurs_apply (box ((box Data_Bifoldable_Bifoldableusd_Dict))) (box ((box ((Map.add "bifoldr" (box ((box (fun (l: obj) -> (box (fun (v: obj) -> (box (fun (u: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box l))), (unbox ((box v))), (unbox ((box u))), (unbox ((box v1))))) with | (l1, _, u1, f) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldr))) (box ((box dictFoldable)))))) (box ((box l1)))))) (box ((box u1)))))) (box ((box f)))))))))))))))) (Map.add "bifoldl" (box ((box (fun (l: obj) -> (box (fun (v: obj) -> (box (fun (u: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box l))), (unbox ((box v))), (unbox ((box u))), (unbox ((box v1))))) with | (l1, _, u1, f) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldl))) (box ((box dictFoldable)))))) (box ((box l1)))))) (box ((box u1)))))) (box ((box f)))))))))))))))) (Map.add "bifoldMap" (box ((box (fun (dictMonoid: obj) -> (box (fun (l: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box l))), (unbox ((box v))), (unbox ((box v1))))) with | (l1, _, f) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldMap))) (box ((box dictFoldable)))))) (box ((box dictMonoid)))))) (box ((box l1)))))) (box ((box f)))))))))))))))) Map.empty))))))))))

let Data_Bifoldable_bifoldMapDefaultR  = (box (fun (dictBifoldable: obj) -> (box (fun (dictMonoid: obj) -> (let append = (sharpurs_apply (box ((box Data_Semigroup_append))) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined))))))) in let mempty = (sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid)))) in (box (fun (f: obj) -> (box (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldr))) (box ((box dictBifoldable)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box append)))))) (box ((box f))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box append)))))) (box ((box g))))))))) (box ((box mempty)))))))))))))

let Data_Bifoldable_bifoldMapDefaultL  = (box (fun (dictBifoldable: obj) -> (box (fun (dictMonoid: obj) -> (let Semigroup0 = (sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined)))) in let mempty = (sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid)))) in (box (fun (f: obj) -> (box (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldl))) (box ((box dictBifoldable)))))) (box ((box (fun (m: obj) -> (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Semigroup0)))))) (box ((box m)))))) (box ((sharpurs_apply (box ((box f))) (box ((box a)))))))))))))))) (box ((box (fun (m: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Semigroup0)))))) (box ((box m)))))) (box ((sharpurs_apply (box ((box g))) (box ((box b)))))))))))))))) (box ((box mempty)))))))))))))

let Data_Bifoldable_bifoldMap  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "bifoldMap" (unbox<Map<string, obj>> ((box v))))))))

let Data_Bifoldable_bifoldableFlip  = (box (fun (dictBifoldable: obj) -> (sharpurs_apply (box ((box Data_Bifoldable_Bifoldableusd_Dict))) (box ((box ((Map.add "bifoldr" (box ((box (fun (r: obj) -> (box (fun (l: obj) -> (box (fun (u: obj) -> (box (fun (v: obj) -> (match (((unbox ((box r))), (unbox ((box l))), (unbox ((box u))), (unbox ((box v))))) with | (r1, l1, u1, p) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldr))) (box ((box dictBifoldable)))))) (box ((box l1)))))) (box ((box r1)))))) (box ((box u1)))))) (box ((box p)))))))))))))))) (Map.add "bifoldl" (box ((box (fun (r: obj) -> (box (fun (l: obj) -> (box (fun (u: obj) -> (box (fun (v: obj) -> (match (((unbox ((box r))), (unbox ((box l))), (unbox ((box u))), (unbox ((box v))))) with | (r1, l1, u1, p) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldl))) (box ((box dictBifoldable)))))) (box ((box l1)))))) (box ((box r1)))))) (box ((box u1)))))) (box ((box p)))))))))))))))) (Map.add "bifoldMap" (box ((box (fun (dictMonoid: obj) -> (box (fun (r: obj) -> (box (fun (l: obj) -> (box (fun (v: obj) -> (match (((unbox ((box r))), (unbox ((box l))), (unbox ((box v))))) with | (r1, l1, p) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldMap))) (box ((box dictBifoldable)))))) (box ((box dictMonoid)))))) (box ((box l1)))))) (box ((box r1)))))) (box ((box p)))))))))))))))) Map.empty))))))))))

let Data_Bifoldable_bifoldlDefault  = (box (fun (dictBifoldable: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (z: obj) -> (box (fun (p: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldMap))) (box ((box dictBifoldable)))))) (box ((box Data_Bifoldable_monoidDual)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Dual_Dual)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Endo_Endo)))))) (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((box f))))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Dual_Dual)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Endo_Endo)))))) (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((box g))))))))))))))) (box ((box p)))))))))))) (box ((box z))))))))))))))

let Data_Bifoldable_bifoldrDefault  = (box (fun (dictBifoldable: obj) -> (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (z: obj) -> (box (fun (p: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldMap))) (box ((box dictBifoldable)))))) (box ((box Data_Bifoldable_monoidEndo)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Endo_Endo)))))) (box ((box f))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Endo_Endo)))))) (box ((box g))))))))) (box ((box p))))))))) (box ((box z))))))))))))))

let rec Data_Bifoldable_bifoldableProduct2_tco (dictBifoldable: obj) (dictBifoldable1: obj) : obj = ((sharpurs_apply (box ((box Data_Bifoldable_Bifoldableusd_Dict))) (box ((box ((Map.add "bifoldr" (box ((box (fun (l: obj) -> (box (fun (r: obj) -> (box (fun (u: obj) -> (box (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldrDefault))) (box ((Data_Bifoldable_bifoldableProduct2_tco ((box dictBifoldable)) ((box dictBifoldable1)))))))) (box ((box l)))))) (box ((box r)))))) (box ((box u)))))) (box ((box m)))))))))))))) (Map.add "bifoldl" (box ((box (fun (l: obj) -> (box (fun (r: obj) -> (box (fun (u: obj) -> (box (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldlDefault))) (box ((Data_Bifoldable_bifoldableProduct2_tco ((box dictBifoldable)) ((box dictBifoldable1)))))))) (box ((box l)))))) (box ((box r)))))) (box ((box u)))))) (box ((box m)))))))))))))) (Map.add "bifoldMap" (box ((box (fun (dictMonoid: obj) -> (let Semigroup0 = (sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined)))) in (box (fun (l: obj) -> (box (fun (r: obj) -> (box (fun (v: obj) -> (match (((unbox ((box l))), (unbox ((box r))), (unbox ((box v))))) with | (l1, r1, Data_Functor_Product2_Product2usd_Ctor(f, g)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Semigroup0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldMap))) (box ((box dictBifoldable)))))) (box ((box dictMonoid)))))) (box ((box l1)))))) (box ((box r1)))))) (box ((box f))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldMap))) (box ((box dictBifoldable1)))))) (box ((box dictMonoid)))))) (box ((box l1)))))) (box ((box r1)))))) (box ((box g)))))))))))))))))))) Map.empty)))))))))
and Data_Bifoldable_bifoldableProduct2 = box (fun (dictBifoldable: obj) ->  (fun (dictBifoldable1: obj) -> Data_Bifoldable_bifoldableProduct2_tco dictBifoldable dictBifoldable1))


let Data_Bifoldable_bifold  = (box (fun (dictBifoldable: obj) -> (box (fun (dictMonoid: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldMap))) (box ((box dictBifoldable)))))) (box ((box dictMonoid)))))) (box ((box Data_Bifoldable_identity2)))))) (box ((box Data_Bifoldable_identity2))))))))

let Data_Bifoldable_biany  = (box (fun (dictBifoldable: obj) -> (box (fun (dictBooleanAlgebra: obj) -> (let monoidDisj = (sharpurs_apply (box ((box Data_Monoid_Disj_monoidDisj))) (box ((sharpurs_apply (box ((Map.find "HeytingAlgebra0" (unbox<Map<string, obj>> ((box dictBooleanAlgebra)))))) (box ((box Prim_undefined))))))) in (box (fun (p: obj) -> (box (fun (q: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Bifoldable_unwrap)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldMap))) (box ((box dictBifoldable)))))) (box ((box monoidDisj)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Disj_Disj)))))) (box ((box p))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Disj_Disj)))))) (box ((box q)))))))))))))))))))

let Data_Bifoldable_biall  = (box (fun (dictBifoldable: obj) -> (box (fun (dictBooleanAlgebra: obj) -> (let monoidConj = (sharpurs_apply (box ((box Data_Monoid_Conj_monoidConj))) (box ((sharpurs_apply (box ((Map.find "HeytingAlgebra0" (unbox<Map<string, obj>> ((box dictBooleanAlgebra)))))) (box ((box Prim_undefined))))))) in (box (fun (p: obj) -> (box (fun (q: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Bifoldable_unwrap)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifoldable_bifoldMap))) (box ((box dictBifoldable)))))) (box ((box monoidConj)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Conj_Conj)))))) (box ((box p))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Monoid_Conj_Conj)))))) (box ((box q)))))))))))))))))))
