[<AutoOpen>]
module PureScript_Effect_Aff_Compat

open System
open System.Collections.Generic

let Effect_Aff_Compat_pure  = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Effect_applicativeEffect))))

let Effect_Aff_Compat_EffectFnCanceler  = (box (fun (x: obj) -> (box x)))

let Effect_Aff_Compat_EffectFnAff  = (box (fun (x: obj) -> (box x)))

let Effect_Aff_Compat_fromEffectFnAff  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | eff -> ((sharpurs_apply (box ((box Effect_Aff_makeAff))) (box ((box (fun (k: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Effect_bindEffect)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Effect_Uncurried_runEffectFn2))) (box ((box eff)))))) (box ((sharpurs_apply (box ((box Effect_Uncurried_mkEffectFn1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box k)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))))))))) (box ((sharpurs_apply (box ((box Effect_Uncurried_mkEffectFn1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box k)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))))))))))))))) (box ((box (fun (v1: obj) -> (match ((unbox ((box v1)))) with | canceler -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Effect_Aff_Compat_pure)))))) (box ((sharpurs_apply (box ((box Effect_Aff_Canceler))) (box ((box (fun (e: obj) -> (sharpurs_apply (box ((box Effect_Aff_makeAff))) (box ((box (fun (k2: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_discard))) (box ((box Control_Bind_discardUnit)))))) (box ((box Effect_bindEffect)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Effect_Uncurried_runEffectFn3))) (box ((box canceler)))))) (box ((box e)))))) (box ((sharpurs_apply (box ((box Effect_Uncurried_mkEffectFn1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box k2)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))))))))) (box ((sharpurs_apply (box ((box Effect_Uncurried_mkEffectFn1))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box k2)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))))))))))))))) (box ((box (fun (usd__unused: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Effect_applicativeEffect)))))) (box ((box Effect_Aff_nonCanceler))))))))))))))))))))))))))))))))))))))
