% Generated by purerl version 0.0.24
-module(control_monad@ps).
-export([whenM/0, whenM/3, whenM/1, unlessM/0, unlessM/3, unlessM/1, monadProxy/0, monadFn/0, monadArray/0, liftM1/0, liftM1/3, liftM1/1, ap/0, ap/3, ap/1]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./control_monad.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 57).
-spec whenM() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
whenM() -> fun (DictMonad) ->
  Bind@24 = (?MEMOIZE((control_bind@ps:bind(((maps:get('Bind1', DictMonad))(undefined)))))),
  When@25 = (?MEMOIZE((control_applicative@ps:'when'(((maps:get('Applicative0', DictMonad))(undefined)))))),
  fun (Mb) ->
    fun (M) ->
      ((Bind@24(Mb))(fun (B) ->
        ((When@25(B))(M))
      end))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 57).
-spec whenM(any(),any(),any()) -> any().
whenM(_@3,_@4,_@5) -> ((((whenM())(_@3))(_@4))(_@5)).
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 57).
-spec whenM(any()) -> any().
whenM(_@0) -> 
  Bind@26 = (?MEMOIZE((control_bind@ps:bind(((maps:get('Bind1', _@0))(undefined)))))),
  When@27 = (?MEMOIZE((control_applicative@ps:'when'(((maps:get('Applicative0', _@0))(undefined)))))),
  fun (Mb) ->
    fun (M) ->
      ((Bind@26(Mb))(fun (B) ->
        ((When@27(B))(M))
      end))
    end
  end
.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 64).
-spec unlessM() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
unlessM() -> fun (DictMonad) ->
  Bind@28 = (?MEMOIZE((control_bind@ps:bind(((maps:get('Bind1', DictMonad))(undefined)))))),
  Unless@29 = (?MEMOIZE((control_applicative@ps:unless(((maps:get('Applicative0', DictMonad))(undefined)))))),
  fun (Mb) ->
    fun (M) ->
      ((Bind@28(Mb))(fun (B) ->
        ((Unless@29(B))(M))
      end))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 64).
-spec unlessM(any(),any(),any()) -> any().
unlessM(_@9,_@10,_@11) -> ((((unlessM())(_@9))(_@10))(_@11)).
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 64).
-spec unlessM(any()) -> any().
unlessM(_@6) -> 
  Bind@30 = (?MEMOIZE((control_bind@ps:bind(((maps:get('Bind1', _@6))(undefined)))))),
  Unless@31 = (?MEMOIZE((control_applicative@ps:unless(((maps:get('Applicative0', _@6))(undefined)))))),
  fun (Mb) ->
    fun (M) ->
      ((Bind@30(Mb))(fun (B) ->
        ((Unless@31(B))(M))
      end))
    end
  end
.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 37).
-spec monadProxy() -> any().
monadProxy() -> #{'Applicative0'=>fun (_) ->
  (control_applicative@ps:applicativeProxy())
end, 'Bind1'=>fun (_) ->
  (control_bind@ps:bindProxy())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 33).
-spec monadFn() -> any().
monadFn() -> #{'Applicative0'=>fun (_) ->
  (control_applicative@ps:applicativeFn())
end, 'Bind1'=>fun (_) ->
  (control_bind@ps:bindFn())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 35).
-spec monadArray() -> any().
monadArray() -> #{'Applicative0'=>fun (_) ->
  (control_applicative@ps:applicativeArray())
end, 'Bind1'=>fun (_) ->
  (control_bind@ps:bindArray())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 50).
-spec liftM1() -> fun((any()) -> fun((fun((any()) -> any())) -> fun((any()) -> any()))).
liftM1() -> fun (DictMonad) ->
  Bind@32 = (?MEMOIZE((control_bind@ps:bind(((maps:get('Bind1', DictMonad))(undefined)))))),
  Pure@33 = (?MEMOIZE((control_applicative@ps:pure(((maps:get('Applicative0', DictMonad))(undefined)))))),
  fun (F) ->
    fun (A) ->
      ((Bind@32(A))(fun (A@prime) ->
        (Pure@33((F(A@prime))))
      end))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 50).
-spec liftM1(any(),fun((any()) -> any()),any()) -> any().
liftM1(_@15,_@16,_@17) -> ((((liftM1())(_@15))(_@16))(_@17)).
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 50).
-spec liftM1(any()) -> any().
liftM1(_@12) -> 
  Bind@34 = (?MEMOIZE((control_bind@ps:bind(((maps:get('Bind1', _@12))(undefined)))))),
  Pure@35 = (?MEMOIZE((control_applicative@ps:pure(((maps:get('Applicative0', _@12))(undefined)))))),
  fun (F) ->
    fun (A) ->
      ((Bind@34(A))(fun (A@prime) ->
        (Pure@35((F(A@prime))))
      end))
    end
  end
.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 82).
-spec ap() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
ap() -> fun (DictMonad) ->
  Bind@36 = (?MEMOIZE((control_bind@ps:bind(((maps:get('Bind1', DictMonad))(undefined)))))),
  Pure@37 = (?MEMOIZE((control_applicative@ps:pure(((maps:get('Applicative0', DictMonad))(undefined)))))),
  fun (F) ->
    fun (A) ->
      ((Bind@36(F))(fun (F@prime) ->
        ((Bind@36(A))(fun (A@prime) ->
          (Pure@37((F@prime(A@prime))))
        end))
      end))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 82).
-spec ap(any(),any(),any()) -> any().
ap(_@21,_@22,_@23) -> ((((ap())(_@21))(_@22))(_@23)).
%-file("/Users/0x1/Documents/htdocs/altbak/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Control/Monad.purs", 82).
-spec ap(any()) -> any().
ap(_@18) -> 
  Bind@38 = (?MEMOIZE((control_bind@ps:bind(((maps:get('Bind1', _@18))(undefined)))))),
  Pure@39 = (?MEMOIZE((control_applicative@ps:pure(((maps:get('Applicative0', _@18))(undefined)))))),
  fun (F) ->
    fun (A) ->
      ((Bind@38(F))(fun (F@prime) ->
        ((Bind@38(A))(fun (A@prime) ->
          (Pure@39((F@prime(A@prime))))
        end))
      end))
    end
  end
.
