% Generated by purerl version 0.0.24
-module(test_church@ps).
-export([zeroC/2, zeroC/0, toInt/1, toInt/0, succC/3, succC/0, mulC/4, mulC/0, fromInt/0, fromInt/3, describe/0, c10/0, c10/2, c100/0, c100/2, c10k/0, c10k/2, c100k/0, c100k/2, addC/4, addC/0, act/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./test_church.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 12).
-spec zeroC(fun((any()) -> any()),any()) -> any().
zeroC(_@8,_@9) -> _@9.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 12).
-spec zeroC() -> fun((fun((any()) -> any())) -> fun((any()) -> any())).
zeroC() -> fun (_@10) ->
  fun (_@11) ->
    (zeroC(_@10, _@11))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 28).
-spec toInt(fun((fun((integer()) -> integer())) -> fun((integer()) -> integer()))) -> integer().
toInt(_@12) -> ((_@12(fun (X) ->
  X + 1
end))(0)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 28).
-spec toInt() -> fun((fun((fun((integer()) -> integer())) -> fun((integer()) -> integer()))) -> integer()).
toInt() -> fun (_@13) ->
  (toInt(_@13))
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 15).
-spec succC(fun((fun((any()) -> any())) -> fun((any()) -> any())),fun((any()) -> any()),any()) -> any().
succC(_@14,_@15,_@16) -> (_@15(((_@14(_@15))(_@16)))).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 15).
-spec succC() -> fun((fun((fun((any()) -> any())) -> fun((any()) -> any()))) -> fun((fun((any()) -> any())) -> fun((any()) -> any()))).
succC() -> fun (_@17) ->
  fun (_@18) ->
    fun (_@19) ->
      (succC(_@17, _@18, _@19))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 21).
-spec mulC(fun((fun((any()) -> any())) -> fun((any()) -> any())),fun((fun((any()) -> any())) -> fun((any()) -> any())),fun((any()) -> any()),any()) -> any().
mulC(_@20,_@21,_@22,_@23) -> ((_@20((_@21(_@22))))(_@23)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 21).
-spec mulC() -> fun((fun((fun((any()) -> any())) -> fun((any()) -> any()))) -> fun((fun((fun((any()) -> any())) -> fun((any()) -> any()))) -> fun((fun((any()) -> any())) -> fun((any()) -> any())))).
mulC() -> fun (_@24) ->
  fun (_@25) ->
    fun (_@26) ->
      fun (_@27) ->
        (mulC(_@24, _@25, _@26, _@27))
      end
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 24).
-spec fromInt() -> fun((integer()) -> fun((fun((integer()) -> integer())) -> fun((integer()) -> integer()))).
fromInt() -> fun (V) ->
  case V of
    (0) -> (zeroC());
    (_@28) -> ((succC())(((fromInt())(_@28 - 1))))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 24).
-spec fromInt(integer(),fun((integer()) -> integer()),integer()) -> integer().
fromInt(_@32,_@33,_@34) -> ((((fromInt())(_@32))(_@33))(_@34)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 44).
-spec describe() -> fun(() -> any()).
describe() -> (effect_console@ps:log(<<"Church Numerals (100k Closure Applications):"/utf8>>)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 32).
-spec c10() -> fun((fun((integer()) -> integer())) -> fun((integer()) -> integer())).
c10() -> ((fromInt())(10)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 32).
-spec c10(fun((integer()) -> integer()),integer()) -> integer().
c10(_@37,_@38) -> (((c10())(_@37))(_@38)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 35).
-spec c100() -> fun((fun((integer()) -> integer())) -> fun((integer()) -> integer())).
c100() -> (((mulC())((c10())))((c10()))).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 35).
-spec c100(fun((integer()) -> integer()),integer()) -> integer().
c100(_@41,_@42) -> (((c100())(_@41))(_@42)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 38).
-spec c10k() -> fun((fun((integer()) -> integer())) -> fun((integer()) -> integer())).
c10k() -> (((mulC())((c100())))((c100()))).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 38).
-spec c10k(fun((integer()) -> integer()),integer()) -> integer().
c10k(_@45,_@46) -> (((c10k())(_@45))(_@46)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 41).
-spec c100k() -> fun((fun((integer()) -> integer())) -> fun((integer()) -> integer())).
c100k() -> (((mulC())((c10k())))((c10()))).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 41).
-spec c100k(fun((integer()) -> integer()),integer()) -> integer().
c100k(_@49,_@50) -> (((c100k())(_@49))(_@50)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 18).
-spec addC(fun((fun((any()) -> any())) -> fun((any()) -> any())),fun((fun((any()) -> any())) -> fun((any()) -> any())),fun((any()) -> any()),any()) -> any().
addC(_@51,_@52,_@53,_@54) -> ((_@51(_@53))(((_@52(_@53))(_@54)))).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 18).
-spec addC() -> fun((fun((fun((any()) -> any())) -> fun((any()) -> any()))) -> fun((fun((fun((any()) -> any())) -> fun((any()) -> any()))) -> fun((fun((any()) -> any())) -> fun((any()) -> any())))).
addC() -> fun (_@55) ->
  fun (_@56) ->
    fun (_@57) ->
      fun (_@58) ->
        (addC(_@55, _@56, _@57, _@58))
      end
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/Church.purs", 47).
-spec act() -> fun(() -> any()).
act() -> (effect_console@ps:logShow((data_show@ps:showInt()), (toInt((c100k()))))).
