#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Unsafe_Coerce::*;
use Purs_Unsafe_Coerce::*;

// Code generated by purust for module Data_Exists



pub fn Data_Exists_runExists(mut a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Var(...)))
(/* Typed purust_core::Func2<purust_core::Func1<crate::UnknownType, crate::UnknownType>, crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Var(...) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(Unsafe_Coerce_unsafeCoerce)).clone(); move |mut _a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut _a1: crate::UnknownType| -> crate::UnknownType { ((_f)(purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0.clone()).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))))).unwrap_func1()(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Data_Exists_mkExists(mut a0: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Var(...)))
(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Var(...) */purust_core::Func1::Static(Unsafe_Coerce_unsafeCoerce))(a0.clone())
}





// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum Exists {}
