% Generated by purerl version 0.0.24
-module(test_rBTree@ps).
-export(['R'/0, 'B'/0, 'E'/0, 'T'/0, max/2, max/0, describe/0, depth/1, depth/0, balance/4, balance/0, insert/2, insert/0, buildTree/2, buildTree/0, act/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./test_rBTree.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 11).
-spec 'R'() -> any().
'R'() -> { r }.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 11).
-spec 'B'() -> any().
'B'() -> { b }.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 12).
-spec 'E'() -> any().
'E'() -> { e }.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 12).
-spec 'T'() -> any().
'T'() -> fun (Value0) ->
  fun (Value1) ->
    fun (Value2) ->
      fun (Value3) ->
        { t, Value0, Value1, Value2, Value3 }
      end
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 43).
-spec max(integer(),integer()) -> integer().
max(_@16,_@17) -> case _@16 > _@17 of
  (true) -> _@16;
  (_) -> _@17
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 43).
-spec max() -> fun((integer()) -> fun((integer()) -> integer())).
max() -> fun (_@18) ->
  fun (_@19) ->
    (max(_@18, _@19))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 46).
-spec describe() -> fun(() -> any()).
describe() -> (effect_console@ps:log(<<"Red-Black Tree (100k Worst-Case Insertions):"/utf8>>)).
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 39).
-spec depth(any()) -> integer().
depth(_@22) -> case _@22 of
  ({ e }) -> 0;
  ({ t, _, _@23, _, _@24 }) -> 1 + (max((depth(_@23)), (depth(_@24))))
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 39).
-spec depth() -> fun((any()) -> integer()).
depth() -> fun (_@25) ->
  (depth(_@25))
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 14).
-spec balance(any(),any(),integer(),any()) -> any().
balance(_@58,_@59,_@60,_@61) -> case { _@58, _@59, _@60, _@61 } of
  ({ { b }, { t, { r }, { t, { r }, _@62, _@63, _@64 }, _@65, _@66 }, _@67, _@68 }) -> { t, { r }, { t, { b }, _@62, _@63, _@64 }, _@65, { t, { b }, _@66, _@67, _@68 } };
  ({ { b }, { t, { r }, _@69, _@70, { t, { r }, _@71, _@72, _@73 } }, _@74, _@75 }) -> { t, { r }, { t, { b }, _@69, _@70, _@71 }, _@72, { t, { b }, _@73, _@74, _@75 } };
  ({ { b }, _@76, _@77, { t, { r }, { t, { r }, _@78, _@79, _@80 }, _@81, _@82 } }) -> { t, { r }, { t, { b }, _@76, _@77, _@78 }, _@79, { t, { b }, _@80, _@81, _@82 } };
  ({ { b }, _@83, _@84, { t, { r }, _@85, _@86, { t, { r }, _@87, _@88, _@89 } } }) -> { t, { r }, { t, { b }, _@83, _@84, _@85 }, _@86, { t, { b }, _@87, _@88, _@89 } };
  ({ _@90, _@91, _@92, _@93 }) -> { t, _@90, _@91, _@92, _@93 }
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 14).
-spec balance() -> fun((any()) -> fun((any()) -> fun((integer()) -> fun((any()) -> any())))).
balance() -> fun (_@94) ->
  fun (_@95) ->
    fun (_@96) ->
      fun (_@97) ->
        (balance(_@94, _@95, _@96, _@97))
      end
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 21).
-spec insert(integer(),any()) -> any().
insert(_@106,_@107) -> 
  MakeBlack@128@131 = fun MakeBlack(V) ->
    case V of
      ({ t, _, _@108, _@109, _@110 }) -> { t, { b }, _@108, _@109, _@110 };
      ({ e }) -> { e }
    end
  end,
  Ins@f@129@132 = fun
    Reccase({ Ins@f }) -> 
    fun (V) ->
      case V of
        ({ e }) -> { t, { r }, { e }, _@106, { e } };
        ({ t, _@112, _@113, _@114, _@115 }) -> case _@106 < _@114 of
          (true) -> (balance(_@112, ((Ins@f({ Ins@f }))(_@113)), _@114, _@115));
          (_) -> case _@106 > _@114 of
            (true) -> (balance(_@112, _@113, _@114, ((Ins@f({ Ins@f }))(_@115))));
            (_) -> { t, _@112, _@113, _@114, _@115 }
          end
        end
      end
    end
  end,
  Ins@130@133 = (Ins@f@129@132({ Ins@f@129@132 })),
  (MakeBlack@128@131((Ins@130@133(_@107))))
.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 21).
-spec insert() -> fun((integer()) -> fun((any()) -> any())).
insert() -> fun (_@116) ->
  fun (_@117) ->
    (insert(_@116, _@117))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 34).
-spec buildTree(integer(),any()) -> any().
buildTree(_@121,_@122) -> case { _@121, _@122 } of
  ({ 0, _@123 }) -> _@123;
  ({ _@124, _@125 }) -> (buildTree(_@124 - 1, (insert(_@124, _@125))))
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 34).
-spec buildTree() -> fun((integer()) -> fun((any()) -> any())).
buildTree() -> fun (_@126) ->
  fun (_@127) ->
    (buildTree(_@126, _@127))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak/src/Test/RBTree.purs", 49).
-spec act() -> fun(() -> any()).
act() -> (effect_console@ps:logShow((data_show@ps:showInt()), (depth((buildTree(100000, { e })))))).
