#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Category::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Boolean::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Monoid::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ord::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Record_Unsafe::*;
use Purs_Safe_Coerce::*;
use Purs_Type_Proxy::*;
use Purs_Unsafe_Coerce::*;
use Purs_Control_Category::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Monoid::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ord::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Record_Unsafe::*;

// Code generated by purust for module Data_Time_Duration


#[derive(Clone)]
pub struct Duration {
    pub fromDuration: purust_core::Func1<crate::UnknownType, f64>,
    pub toDuration: purust_core::Func1<f64, crate::UnknownType>
}

pub fn Data_Time_Duration_Seconds(mut purs_local_0: f64) -> f64 {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_Time_Duration_Minutes(mut purs_local_0: f64) -> f64 {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_Time_Duration_Milliseconds(mut purs_local_0: f64) -> f64 {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_Time_Duration_Hours(mut purs_local_0: f64) -> f64 {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_Time_Duration_Days(mut purs_local_0: f64) -> f64 {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_Time_Duration_toDuration(mut a0: std::rc::Rc<crate::Duration>, mut a1: f64) -> crate::UnknownType {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Duration>| -> purust_core::Func1<f64, crate::UnknownType> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func1<f64, crate::UnknownType> <- purust_core::Func1<f64, crate::UnknownType> : Accessor(Local(...)) */(purs_local_0).toDuration.clone()
} as fn(std::rc::Rc<crate::Duration>) -> purust_core::Func1<f64, crate::UnknownType>)).clone(); move |mut _a0: std::rc::Rc<crate::Duration>, mut _a1: f64| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Data_Time_Duration_showSeconds() -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Show::Show>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_showSeconds", || {
std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> String {
    let mut purs_local_0 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(Seconds "), Data_Show_showNumberImpl(/* Typed f64 <- f64 : Local(...) */purs_local_0)), String::from(")"))
} as fn(f64) -> String)).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_number()) } })) })
}).clone())
}

pub fn Data_Time_Duration_showMinutes() -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Show::Show>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_showMinutes", || {
std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> String {
    let mut purs_local_0 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(Minutes "), Data_Show_showNumberImpl(/* Typed f64 <- f64 : Local(...) */purs_local_0)), String::from(")"))
} as fn(f64) -> String)).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_number()) } })) })
}).clone())
}

pub fn Data_Time_Duration_showMilliseconds() -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Show::Show>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_showMilliseconds", || {
std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> String {
    let mut purs_local_0 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(Milliseconds "), Data_Show_showNumberImpl(/* Typed f64 <- f64 : Local(...) */purs_local_0)), String::from(")"))
} as fn(f64) -> String)).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_number()) } })) })
}).clone())
}

pub fn Data_Time_Duration_showHours() -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Show::Show>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_showHours", || {
std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> String {
    let mut purs_local_0 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(Hours "), Data_Show_showNumberImpl(/* Typed f64 <- f64 : Local(...) */purs_local_0)), String::from(")"))
} as fn(f64) -> String)).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_number()) } })) })
}).clone())
}

pub fn Data_Time_Duration_showDays() -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Show::Show>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_showDays", || {
std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> String {
    let mut purs_local_0 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(Days "), Data_Show_showNumberImpl(/* Typed f64 <- f64 : Local(...) */purs_local_0)), String::from(")"))
} as fn(f64) -> String)).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_number()) } })) })
}).clone())
}

pub fn Data_Time_Duration_semigroupSeconds() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Semigroup::Semigroup>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_semigroupSeconds", || {
std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: f64, mut _a1: f64| -> f64 {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 + purs_local_1)
} as fn(f64, f64) -> f64)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number(), (_a1).unwrap_number())) } })) })
}).clone())
}

pub fn Data_Time_Duration_semigroupMinutes() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Semigroup::Semigroup>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_semigroupMinutes", || {
std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: f64, mut _a1: f64| -> f64 {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 + purs_local_1)
} as fn(f64, f64) -> f64)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number(), (_a1).unwrap_number())) } })) })
}).clone())
}

pub fn Data_Time_Duration_semigroupMilliseconds() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Semigroup::Semigroup>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_semigroupMilliseconds", || {
std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: f64, mut _a1: f64| -> f64 {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 + purs_local_1)
} as fn(f64, f64) -> f64)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number(), (_a1).unwrap_number())) } })) })
}).clone())
}

pub fn Data_Time_Duration_semigroupHours() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Semigroup::Semigroup>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_semigroupHours", || {
std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: f64, mut _a1: f64| -> f64 {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 + purs_local_1)
} as fn(f64, f64) -> f64)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number(), (_a1).unwrap_number())) } })) })
}).clone())
}

pub fn Data_Time_Duration_semigroupDays() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Semigroup::Semigroup>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_semigroupDays", || {
std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: f64, mut _a1: f64| -> f64 {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 + purs_local_1)
} as fn(f64, f64) -> f64)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number(), (_a1).unwrap_number())) } })) })
}).clone())
}

pub fn Data_Time_Duration_ordSeconds() -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Ord::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_ordSeconds", || {
/* Typed std::rc::Rc<Purs_Data_Ord::Ord> <- std::rc::Rc<Purs_Data_Ord::Ord> : Var(...) */Data_Ord_ordNumber()
}).clone())
}

pub fn Data_Time_Duration_ordMinutes() -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Ord::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_ordMinutes", || {
/* Typed std::rc::Rc<Purs_Data_Ord::Ord> <- std::rc::Rc<Purs_Data_Ord::Ord> : Var(...) */Data_Ord_ordNumber()
}).clone())
}

pub fn Data_Time_Duration_ordMilliseconds() -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Ord::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_ordMilliseconds", || {
/* Typed std::rc::Rc<Purs_Data_Ord::Ord> <- std::rc::Rc<Purs_Data_Ord::Ord> : Var(...) */Data_Ord_ordNumber()
}).clone())
}

pub fn Data_Time_Duration_ordHours() -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Ord::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_ordHours", || {
/* Typed std::rc::Rc<Purs_Data_Ord::Ord> <- std::rc::Rc<Purs_Data_Ord::Ord> : Var(...) */Data_Ord_ordNumber()
}).clone())
}

pub fn Data_Time_Duration_ordDays() -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Ord::Ord>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_ordDays", || {
/* Typed std::rc::Rc<Purs_Data_Ord::Ord> <- std::rc::Rc<Purs_Data_Ord::Ord> : Var(...) */Data_Ord_ordNumber()
}).clone())
}

pub fn Data_Time_Duration_newtypeSeconds() -> std::rc::Rc<Purs_Data_Newtype::Newtype> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Newtype::Newtype>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_newtypeSeconds", || {
std::rc::Rc::new(Purs_Data_Newtype::Newtype { Coercible0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
} as fn(crate::UnknownType) -> crate::UnknownType) })
}).clone())
}

pub fn Data_Time_Duration_newtypeMinutes() -> std::rc::Rc<Purs_Data_Newtype::Newtype> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Newtype::Newtype>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_newtypeMinutes", || {
std::rc::Rc::new(Purs_Data_Newtype::Newtype { Coercible0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
} as fn(crate::UnknownType) -> crate::UnknownType) })
}).clone())
}

pub fn Data_Time_Duration_newtypeMilliseconds() -> std::rc::Rc<Purs_Data_Newtype::Newtype> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Newtype::Newtype>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_newtypeMilliseconds", || {
std::rc::Rc::new(Purs_Data_Newtype::Newtype { Coercible0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
} as fn(crate::UnknownType) -> crate::UnknownType) })
}).clone())
}

pub fn Data_Time_Duration_newtypeHours() -> std::rc::Rc<Purs_Data_Newtype::Newtype> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Newtype::Newtype>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_newtypeHours", || {
std::rc::Rc::new(Purs_Data_Newtype::Newtype { Coercible0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
} as fn(crate::UnknownType) -> crate::UnknownType) })
}).clone())
}

pub fn Data_Time_Duration_newtypeDays() -> std::rc::Rc<Purs_Data_Newtype::Newtype> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Newtype::Newtype>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_newtypeDays", || {
std::rc::Rc::new(Purs_Data_Newtype::Newtype { Coercible0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
} as fn(crate::UnknownType) -> crate::UnknownType) })
}).clone())
}

pub fn Data_Time_Duration_monoidSeconds() -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Monoid::Monoid>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_monoidSeconds", || {
std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: crate::mk_number(/* Typed f64 <- f64 : Lit */0.0), Semigroup0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_Time_Duration_semigroupSeconds()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup>) })
}).clone())
}

pub fn Data_Time_Duration_monoidMinutes() -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Monoid::Monoid>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_monoidMinutes", || {
std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: crate::mk_number(/* Typed f64 <- f64 : Lit */0.0), Semigroup0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_Time_Duration_semigroupMinutes()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup>) })
}).clone())
}

pub fn Data_Time_Duration_monoidMilliseconds() -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Monoid::Monoid>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_monoidMilliseconds", || {
std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: crate::mk_number(/* Typed f64 <- f64 : Lit */0.0), Semigroup0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_Time_Duration_semigroupMilliseconds()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup>) })
}).clone())
}

pub fn Data_Time_Duration_monoidHours() -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Monoid::Monoid>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_monoidHours", || {
std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: crate::mk_number(/* Typed f64 <- f64 : Lit */0.0), Semigroup0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_Time_Duration_semigroupHours()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup>) })
}).clone())
}

pub fn Data_Time_Duration_monoidDays() -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Lit))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Monoid::Monoid>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_monoidDays", || {
std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: crate::mk_number(/* Typed f64 <- f64 : Lit */0.0), Semigroup0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_Time_Duration_semigroupDays()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup>) })
}).clone())
}

pub fn Data_Time_Duration_fromDuration(mut a0: std::rc::Rc<crate::Duration>, mut a1: crate::UnknownType) -> f64 {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Duration>| -> purust_core::Func1<crate::UnknownType, f64> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func1<crate::UnknownType, f64> <- purust_core::Func1<crate::UnknownType, f64> : Accessor(Local(...)) */(purs_local_0).fromDuration.clone()
} as fn(std::rc::Rc<crate::Duration>) -> purust_core::Func1<crate::UnknownType, f64>)).clone(); move |mut _a0: std::rc::Rc<crate::Duration>, mut _a1: crate::UnknownType| -> f64 { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Data_Time_Duration_negateDuration(mut a0: std::rc::Rc<crate::Duration>, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))))))))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Duration>| -> purust_core::Func1<crate::UnknownType, crate::UnknownType> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, crate::UnknownType> <- purust_core::Func1<f64, crate::UnknownType> : App(Var(...)) */{
        let mut eval_arg_0 = purs_local_0.clone();
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: f64| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Data_Time_Duration_toDuration(eval_arg_0, eta_0.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f((_a0).unwrap_number()) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, f64> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_1 = _a0;
    -(purs_local_1)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, f64> <- purust_core::Func1<crate::UnknownType, f64> : App(Var(...)) */{
        let mut eval_arg_0 = purs_local_0;
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> f64 {
    let mut eval_arg_0 = eval_arg_0.clone();
    Data_Time_Duration_fromDuration(eval_arg_0, eta_0.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f(_a0)) } }))))).unwrap_func1(); move |mut _a0: crate::UnknownType| -> f64 { (_f(_a0)).unwrap_number() } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f(_a0)) } }))))).unwrap_func1(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))
} as fn(std::rc::Rc<crate::Duration>) -> purust_core::Func1<crate::UnknownType, crate::UnknownType>)).clone(); move |mut _a0: std::rc::Rc<crate::Duration>, mut _a1: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Data_Time_Duration_eqSeconds() -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Eq::Eq>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_eqSeconds", || {
/* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqNumber()
}).clone())
}

pub fn Data_Time_Duration_eqMinutes() -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Eq::Eq>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_eqMinutes", || {
/* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqNumber()
}).clone())
}

pub fn Data_Time_Duration_eqMilliseconds() -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Eq::Eq>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_eqMilliseconds", || {
/* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqNumber()
}).clone())
}

pub fn Data_Time_Duration_eqHours() -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Eq::Eq>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_eqHours", || {
/* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqNumber()
}).clone())
}

pub fn Data_Time_Duration_eqDays() -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Var(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<Purs_Data_Eq::Eq>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_eqDays", || {
/* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : Var(...) */Data_Eq_eqNumber()
}).clone())
}

pub fn Data_Time_Duration_durationSeconds() -> std::rc::Rc<crate::Duration> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Duration>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_durationSeconds", || {
std::rc::Rc::new(crate::Duration { fromDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_0 = _a0;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 * 1000.0)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: crate::UnknownType| -> f64 { _f((_a0).unwrap_number()) } })), toDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_0 = _a0;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 / /* Typed f64 <- f64 : Lit */1000.0)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: f64| -> crate::UnknownType { crate::mk_number(_f(_a0)) } })) })
}).clone())
}

pub fn Data_Time_Duration_durationMinutes() -> std::rc::Rc<crate::Duration> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Duration>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_durationMinutes", || {
std::rc::Rc::new(crate::Duration { fromDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_0 = _a0;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 * 60000.0)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: crate::UnknownType| -> f64 { _f((_a0).unwrap_number()) } })), toDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_0 = _a0;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 / /* Typed f64 <- f64 : Lit */60000.0)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: f64| -> crate::UnknownType { crate::mk_number(_f(_a0)) } })) })
}).clone())
}

pub fn Data_Time_Duration_durationMilliseconds() -> std::rc::Rc<crate::Duration> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Duration>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_durationMilliseconds", || {
std::rc::Rc::new(crate::Duration { fromDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Category_identity(Control_Category_categoryFn())).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: crate::UnknownType| -> f64 { _f((_a0).unwrap_number()) } })), toDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Category_identity(Control_Category_categoryFn())).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: f64| -> crate::UnknownType { crate::mk_number(_f(_a0)) } })) })
}).clone())
}

pub fn Data_Time_Duration_durationHours() -> std::rc::Rc<crate::Duration> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Duration>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_durationHours", || {
std::rc::Rc::new(crate::Duration { fromDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_0 = _a0;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 * 3600000.0)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: crate::UnknownType| -> f64 { _f((_a0).unwrap_number()) } })), toDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_0 = _a0;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 / /* Typed f64 <- f64 : Lit */3600000.0)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: f64| -> crate::UnknownType { crate::mk_number(_f(_a0)) } })) })
}).clone())
}

pub fn Data_Time_Duration_durationDays() -> std::rc::Rc<crate::Duration> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Duration>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Time_Duration_durationDays", || {
std::rc::Rc::new(crate::Duration { fromDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_0 = _a0;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 * 86400000.0)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: crate::UnknownType| -> f64 { _f((_a0).unwrap_number()) } })), toDuration: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, f64> <- crate::UnknownType : App(Var(...)) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Safe_Coerce_coerce(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: f64| -> f64 {
    let mut purs_local_0 = _a0;
    /* Typed f64 <- f64 : PrimOp(...) */(purs_local_0 / /* Typed f64 <- f64 : Lit */86400000.0)
} as fn(f64) -> f64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number())) } }))))).unwrap_func1(); move |mut _a0: f64| -> f64 { (_f(crate::mk_number(_a0))).unwrap_number() } }))).clone(); move |mut _a0: f64| -> crate::UnknownType { crate::mk_number(_f(_a0)) } })) })
}).clone())
}

pub fn Data_Time_Duration_convertDuration(mut a0: std::rc::Rc<crate::Duration>, mut a1: std::rc::Rc<crate::Duration>, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Duration>| -> purust_core::Func2<std::rc::Rc<crate::Duration>, crate::UnknownType, crate::UnknownType> {
    let mut purs_local_0 = _a0;
    {
    let mut purs_local_1 = /* Typed purust_core::Func1<crate::UnknownType, f64> <- purust_core::Func1<crate::UnknownType, f64> : App(Var(...)) */{
        let mut eval_arg_0 = purs_local_0;
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> f64 {
    let mut eval_arg_0 = eval_arg_0.clone();
    Data_Time_Duration_fromDuration(eval_arg_0, eta_0.clone())
}))
};
    /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: std::rc::Rc<crate::Duration>| -> purust_core::Func1<crate::UnknownType, crate::UnknownType> {
    let mut purs_local_2 = _a0;
    /* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<f64, crate::UnknownType> <- purust_core::Func1<f64, crate::UnknownType> : App(Var(...)) */{
        let mut eval_arg_0 = purs_local_2;
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: f64| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Data_Time_Duration_toDuration(eval_arg_0, eta_0.clone())
}))
}).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f((_a0).unwrap_number()) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (purs_local_1.clone()).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f(_a0)) } }))))).unwrap_func1(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))
}))).clone(); move |mut _a0: std::rc::Rc<crate::Duration>, mut _a1: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone()) } }))
}
} as fn(std::rc::Rc<crate::Duration>) -> purust_core::Func2<std::rc::Rc<crate::Duration>, crate::UnknownType, crate::UnknownType>)).clone(); move |mut _a0: std::rc::Rc<crate::Duration>, mut _a1: std::rc::Rc<crate::Duration>, mut _a2: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}





