#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Ring::*;
use Purs_Data_Semiring::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Record_Unsafe::*;
use Purs_Type_Proxy::*;
use Purs_Data_Ring::*;
use Purs_Record_Unsafe::*;
use Purs_Data_Symbol::*;

// Code generated by purust for module Data_CommutativeRing


#[derive(Clone)]
pub struct CommutativeRingRecord {
    pub RingRecord0: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Ring::RingRecord>>
}

#[derive(Clone)]
pub struct CommutativeRing {
    pub Ring0: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Ring::Ring>>
}

pub fn Data_CommutativeRing_commutativeRingUnit() -> std::rc::Rc<crate::CommutativeRing> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::CommutativeRing>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_CommutativeRing_commutativeRingUnit", || {
std::rc::Rc::new(crate::CommutativeRing { Ring0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Ring::Ring> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Ring::Ring> <- std::rc::Rc<Purs_Data_Ring::Ring> : Var(...) */Data_Ring_ringUnit()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Ring::Ring>) })
}).clone())
}

pub fn Data_CommutativeRing_commutativeRingRecordNil() -> std::rc::Rc<crate::CommutativeRingRecord> {
    // AST: Typed(Typed(Typed(Typed(Lit))))
std::rc::Rc::new(crate::CommutativeRingRecord { RingRecord0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Ring::RingRecord> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Ring::RingRecord> <- std::rc::Rc<Purs_Data_Ring::RingRecord> : Var(...) */Data_Ring_ringRecordNil()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Ring::RingRecord>) })
}

pub fn Data_CommutativeRing_commutativeRingRecordCons(mut purs_local_0: std::rc::Rc<Purs_Data_Symbol::IsSymbol>, mut purs_local_1: crate::UnknownType, mut purs_local_2: std::rc::Rc<crate::CommutativeRingRecord>, mut purs_local_4: std::rc::Rc<crate::CommutativeRing>) -> std::rc::Rc<crate::CommutativeRingRecord> {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Let(...))))))))
{
    let mut purs_local_3 = {
        let mut eval_arg_0 = purs_local_0;
        let mut eval_arg_1 = purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }));
        let mut eval_arg_2 = ((purs_local_2).RingRecord0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: std::rc::Rc<Purs_Data_Ring::Ring>| -> std::rc::Rc<Purs_Data_Ring::RingRecord> {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Ring_ringRecordCons(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone())
}))
};
    {
    let mut purs_local_5 = /* Typed std::rc::Rc<Purs_Data_Ring::RingRecord> <- std::rc::Rc<Purs_Data_Ring::RingRecord> : App(Local(...)) */(purs_local_3)(((purs_local_4).Ring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::CommutativeRingRecord { RingRecord0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Ring::RingRecord> {
    drop(_a0);
    purs_local_5.clone()
})) })
}
}
}

pub fn Data_CommutativeRing_commutativeRingRecord(mut purs_local_0: crate::UnknownType, mut purs_local_1: std::rc::Rc<crate::CommutativeRingRecord>) -> std::rc::Rc<crate::CommutativeRing> {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Ring::Ring> <- std::rc::Rc<Purs_Data_Ring::Ring> : App(Var(...)) */Data_Ring_ringRecord(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), ((purs_local_1).RingRecord0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::CommutativeRing { Ring0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Ring::Ring> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}

pub fn Data_CommutativeRing_commutativeRingProxy() -> std::rc::Rc<crate::CommutativeRing> {
    // AST: Typed(Typed(Typed(Typed(Lit))))
std::rc::Rc::new(crate::CommutativeRing { Ring0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Ring::Ring> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Ring::Ring> <- std::rc::Rc<Purs_Data_Ring::Ring> : Var(...) */Data_Ring_ringProxy()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Ring::Ring>) })
}

pub fn Data_CommutativeRing_commutativeRingNumber() -> std::rc::Rc<crate::CommutativeRing> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::CommutativeRing>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_CommutativeRing_commutativeRingNumber", || {
std::rc::Rc::new(crate::CommutativeRing { Ring0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Ring::Ring> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Ring::Ring> <- std::rc::Rc<Purs_Data_Ring::Ring> : Var(...) */Data_Ring_ringNumber()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Ring::Ring>) })
}).clone())
}

pub fn Data_CommutativeRing_commutativeRingInt() -> std::rc::Rc<crate::CommutativeRing> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::CommutativeRing>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_CommutativeRing_commutativeRingInt", || {
std::rc::Rc::new(crate::CommutativeRing { Ring0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Ring::Ring> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Ring::Ring> <- std::rc::Rc<Purs_Data_Ring::Ring> : Var(...) */Data_Ring_ringInt()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Ring::Ring>) })
}).clone())
}

pub fn Data_CommutativeRing_commutativeRingFn(mut purs_local_0: std::rc::Rc<crate::CommutativeRing>) -> std::rc::Rc<crate::CommutativeRing> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Ring::Ring> <- std::rc::Rc<Purs_Data_Ring::Ring> : App(Var(...)) */Data_Ring_ringFn(((purs_local_0).Ring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::CommutativeRing { Ring0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Ring::Ring> {
    drop(_a0);
    purs_local_1.clone()
})) })
}
}





