#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Monad::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Boolean::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Monoid::*;
use Purs_Data_Ord::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Effect::*;
use Purs_Record_Unsafe::*;
use Purs_Type_Proxy::*;
use Purs_Data_Monoid::*;
use Purs_Data_Semigroup::*;
use Purs_Effect::*;
use Purs_Record_Unsafe::*;

// Code generated by purust for module Effect_Uncurried



pub fn Effect_Uncurried_semigroupEffectFn9(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func9(purust_core::Func9::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func9::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType, mut _a8: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    let mut purs_local_6 = _a2;
    let mut purs_local_7 = _a3;
    let mut purs_local_8 = _a4;
    let mut purs_local_9 = _a5;
    let mut purs_local_10 = _a6;
    let mut purs_local_11 = _a7;
    let mut purs_local_12 = _a8;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_12 = purs_local_12.clone();
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_10, purs_local_11, purs_local_12, purs_local_2, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_12 = purs_local_12.clone();
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(((((((((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())).unwrap_func1()(purs_local_10.clone())).unwrap_func1()(purs_local_11.clone())).unwrap_func1()(purs_local_12.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_10, purs_local_11, purs_local_12, purs_local_3, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_12 = purs_local_12.clone();
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(((((((((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())).unwrap_func1()(purs_local_10.clone())).unwrap_func1()(purs_local_11.clone())).unwrap_func1()(purs_local_12.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType, mut _a8: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn8(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func8(purust_core::Func8::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func8::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    let mut purs_local_6 = _a2;
    let mut purs_local_7 = _a3;
    let mut purs_local_8 = _a4;
    let mut purs_local_9 = _a5;
    let mut purs_local_10 = _a6;
    let mut purs_local_11 = _a7;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_10, purs_local_11, purs_local_2, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((((((((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())).unwrap_func1()(purs_local_10.clone())).unwrap_func1()(purs_local_11.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_10, purs_local_11, purs_local_3, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((((((((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())).unwrap_func1()(purs_local_10.clone())).unwrap_func1()(purs_local_11.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn7(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func7(purust_core::Func7::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func7::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    let mut purs_local_6 = _a2;
    let mut purs_local_7 = _a3;
    let mut purs_local_8 = _a4;
    let mut purs_local_9 = _a5;
    let mut purs_local_10 = _a6;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_10, purs_local_2, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(((((((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())).unwrap_func1()(purs_local_10.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_10, purs_local_3, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(((((((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())).unwrap_func1()(purs_local_10.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5, _a6) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn6(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func6(purust_core::Func6::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func6::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    let mut purs_local_6 = _a2;
    let mut purs_local_7 = _a3;
    let mut purs_local_8 = _a4;
    let mut purs_local_9 = _a5;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_2, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((((((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_3, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((((((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn5(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func5(purust_core::Func5::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func5::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    let mut purs_local_6 = _a2;
    let mut purs_local_7 = _a3;
    let mut purs_local_8 = _a4;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_2, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(((((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_3, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(((((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn4(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func4(purust_core::Func4::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func4::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    let mut purs_local_6 = _a2;
    let mut purs_local_7 = _a3;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_2, purs_local_4, purs_local_5, purs_local_6, purs_local_7
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_3, purs_local_4, purs_local_5, purs_local_6, purs_local_7
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn3(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func3(purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func3::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    let mut purs_local_6 = _a2;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_2, purs_local_4, purs_local_5, purs_local_6
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_3, purs_local_4, purs_local_5, purs_local_6
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn2(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_2, purs_local_4, purs_local_5
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_3, purs_local_4, purs_local_5
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn10(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func10(purust_core::Func10::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func10::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType, mut _a8: crate::UnknownType, mut _a9: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    let mut purs_local_5 = _a1;
    let mut purs_local_6 = _a2;
    let mut purs_local_7 = _a3;
    let mut purs_local_8 = _a4;
    let mut purs_local_9 = _a5;
    let mut purs_local_10 = _a6;
    let mut purs_local_11 = _a7;
    let mut purs_local_12 = _a8;
    let mut purs_local_13 = _a9;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_12 = purs_local_12.clone();
    let mut purs_local_13 = purs_local_13.clone();
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_10, purs_local_11, purs_local_12, purs_local_13, purs_local_2, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_12 = purs_local_12.clone();
    let mut purs_local_13 = purs_local_13.clone();
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((((((((((purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())).unwrap_func1()(purs_local_10.clone())).unwrap_func1()(purs_local_11.clone())).unwrap_func1()(purs_local_12.clone())).unwrap_func1()(purs_local_13.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_10, purs_local_11, purs_local_12, purs_local_13, purs_local_3, purs_local_4, purs_local_5, purs_local_6, purs_local_7, purs_local_8, purs_local_9
    let mut purs_local_10 = purs_local_10.clone();
    let mut purs_local_11 = purs_local_11.clone();
    let mut purs_local_12 = purs_local_12.clone();
    let mut purs_local_13 = purs_local_13.clone();
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
    let mut purs_local_5 = purs_local_5.clone();
    let mut purs_local_6 = purs_local_6.clone();
    let mut purs_local_7 = purs_local_7.clone();
    let mut purs_local_8 = purs_local_8.clone();
    let mut purs_local_9 = purs_local_9.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */((((((((((purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())).unwrap_func1()(purs_local_5.clone())).unwrap_func1()(purs_local_6.clone())).unwrap_func1()(purs_local_7.clone())).unwrap_func1()(purs_local_8.clone())).unwrap_func1()(purs_local_9.clone())).unwrap_func1()(purs_local_10.clone())).unwrap_func1()(purs_local_11.clone())).unwrap_func1()(purs_local_12.clone())).unwrap_func1()(purs_local_13.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType, mut _a8: crate::UnknownType, mut _a9: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8, _a9) } })))
})) })
}
}

pub fn Effect_Uncurried_semigroupEffectFn1(mut purs_local_0: std::rc::Rc<Purs_Data_Semigroup::Semigroup>) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_semigroupEffect(purs_local_0);
    std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: /* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */{
    let mut purs_local_1 = purs_local_1.clone();
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_4 = _a0;
    (/* Typed crate::UnknownType <- crate::UnknownType : App(Accessor(Local(...))) */((purs_local_1.clone()).append.clone())({
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_2, purs_local_4
    let mut purs_local_2 = purs_local_2.clone();
    let mut purs_local_4 = purs_local_4.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(purs_local_2.clone()).unwrap_func1()(purs_local_4.clone())
    })))
}, {
    let mut purs_local_3 = purs_local_3.clone();
    purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {
// FREEVARS: purs_local_3, purs_local_4
    let mut purs_local_3 = purs_local_3.clone();
    let mut purs_local_4 = purs_local_4.clone();
        /* Typed crate::UnknownType <- crate::UnknownType : UncurriedEffectApp(Local(...)) */(purs_local_3.clone()).unwrap_func1()(purs_local_4.clone())
    })))
})).unwrap_func1()(purust_core::Value::Unit)
}))
}).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } })))
})) })
}
}

pub fn Effect_Uncurried_monoidEffectFn9(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn9(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func9(purust_core::Func9::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func9::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType, mut _a8: crate::UnknownType| -> crate::UnknownType {
    drop(_a8);
    drop(_a7);
    drop(_a6);
    drop(_a5);
    drop(_a4);
    drop(_a3);
    drop(_a2);
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType, mut _a8: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn8(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn8(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func8(purust_core::Func8::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func8::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType| -> crate::UnknownType {
    drop(_a7);
    drop(_a6);
    drop(_a5);
    drop(_a4);
    drop(_a3);
    drop(_a2);
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn7(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn7(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func7(purust_core::Func7::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func7::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType| -> crate::UnknownType {
    drop(_a6);
    drop(_a5);
    drop(_a4);
    drop(_a3);
    drop(_a2);
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5, _a6) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn6(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn6(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func6(purust_core::Func6::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func6::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType| -> crate::UnknownType {
    drop(_a5);
    drop(_a4);
    drop(_a3);
    drop(_a2);
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn5(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn5(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func5(purust_core::Func5::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func5::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType| -> crate::UnknownType {
    drop(_a4);
    drop(_a3);
    drop(_a2);
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn4(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn4(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func4(purust_core::Func4::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func4::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> crate::UnknownType {
    drop(_a3);
    drop(_a2);
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn3(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn3(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func3(purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func3::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType {
    drop(_a2);
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn2(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn2(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func2::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType {
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn10(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn10(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func10(purust_core::Func10::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func10::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType, mut _a8: crate::UnknownType, mut _a9: crate::UnknownType| -> crate::UnknownType {
    drop(_a9);
    drop(_a8);
    drop(_a7);
    drop(_a6);
    drop(_a5);
    drop(_a4);
    drop(_a3);
    drop(_a2);
    drop(_a1);
    drop(_a0);
    (/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType, mut _a4: crate::UnknownType, mut _a5: crate::UnknownType, mut _a6: crate::UnknownType, mut _a7: crate::UnknownType, mut _a8: crate::UnknownType, mut _a9: crate::UnknownType| -> crate::UnknownType { _f(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8, _a9) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}

pub fn Effect_Uncurried_monoidEffectFn1(mut purs_local_0: std::rc::Rc<Purs_Data_Monoid::Monoid>) -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Data_Monoid_mempty(Effect_monoidEffect(purs_local_0.clone()));
    {
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : App(Var(...)) */Effect_Uncurried_semigroupEffectFn1(((purs_local_0).Semigroup0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed UncurriedEffectAbs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    (purs_local_1.clone()).unwrap_func1()(purust_core::Value::Unit)
}))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}
}



pub fn Effect_Uncurried_mkEffectFn1(
    callback: purust_core::Func1<UnknownType, UnknownType>,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |a| {
        callback(a).unwrap_func1()(Value::Unit)
    })))
}

pub fn Effect_Uncurried_runEffectFn1(callback: UnknownType, a: UnknownType) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func1()(a.clone())
    })))
}

pub fn Effect_Uncurried_mkEffectFn2(
    callback: purust_core::Func2<UnknownType, UnknownType, UnknownType>,
) -> UnknownType {
    Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new(move |a, b| {
        callback(a, b).unwrap_func1()(Value::Unit)
    })))
}

pub fn Effect_Uncurried_runEffectFn2(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func2()(a.clone(), b.clone())
    })))
}

pub fn Effect_Uncurried_mkEffectFn3(
    callback: purust_core::Func3<UnknownType, UnknownType, UnknownType, UnknownType>,
) -> UnknownType {
    Value::Func3(purust_core::Func3::Shared(std::rc::Rc::new(
        move |a, b, c| callback(a, b, c).unwrap_func1()(Value::Unit),
    )))
}

pub fn Effect_Uncurried_runEffectFn3(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
    c: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func3()(a.clone(), b.clone(), c.clone())
    })))
}

pub fn Effect_Uncurried_mkEffectFn4(
    callback: purust_core::Func4<UnknownType, UnknownType, UnknownType, UnknownType, UnknownType>,
) -> UnknownType {
    Value::Func4(purust_core::Func4::Shared(std::rc::Rc::new(
        move |a, b, c, d| callback(a, b, c, d).unwrap_func1()(Value::Unit),
    )))
}

pub fn Effect_Uncurried_runEffectFn4(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
    c: UnknownType,
    d: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func4()(a.clone(), b.clone(), c.clone(), d.clone())
    })))
}

pub fn Effect_Uncurried_mkEffectFn5(
    callback: purust_core::Func5<
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
    >,
) -> UnknownType {
    Value::Func5(purust_core::Func5::Shared(std::rc::Rc::new(
        move |a, b, c, d, e| callback(a, b, c, d, e).unwrap_func1()(Value::Unit),
    )))
}

pub fn Effect_Uncurried_runEffectFn5(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
    c: UnknownType,
    d: UnknownType,
    e: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func5()(a.clone(), b.clone(), c.clone(), d.clone(), e.clone())
    })))
}

pub fn Effect_Uncurried_mkEffectFn6(
    callback: purust_core::Func6<
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
    >,
) -> UnknownType {
    Value::Func6(purust_core::Func6::Shared(std::rc::Rc::new(
        move |a, b, c, d, e, f| callback(a, b, c, d, e, f).unwrap_func1()(Value::Unit),
    )))
}

pub fn Effect_Uncurried_runEffectFn6(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
    c: UnknownType,
    d: UnknownType,
    e: UnknownType,
    f: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func6()(
            a.clone(),
            b.clone(),
            c.clone(),
            d.clone(),
            e.clone(),
            f.clone(),
        )
    })))
}

pub fn Effect_Uncurried_mkEffectFn7(
    callback: purust_core::Func7<
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
    >,
) -> UnknownType {
    Value::Func7(purust_core::Func7::Shared(std::rc::Rc::new(
        move |a, b, c, d, e, f, g| callback(a, b, c, d, e, f, g).unwrap_func1()(Value::Unit),
    )))
}

pub fn Effect_Uncurried_runEffectFn7(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
    c: UnknownType,
    d: UnknownType,
    e: UnknownType,
    f: UnknownType,
    g: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func7()(
            a.clone(),
            b.clone(),
            c.clone(),
            d.clone(),
            e.clone(),
            f.clone(),
            g.clone(),
        )
    })))
}

pub fn Effect_Uncurried_mkEffectFn8(
    callback: purust_core::Func8<
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
    >,
) -> UnknownType {
    Value::Func8(purust_core::Func8::Shared(std::rc::Rc::new(
        move |a, b, c, d, e, f, g, h| callback(a, b, c, d, e, f, g, h).unwrap_func1()(Value::Unit),
    )))
}

pub fn Effect_Uncurried_runEffectFn8(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
    c: UnknownType,
    d: UnknownType,
    e: UnknownType,
    f: UnknownType,
    g: UnknownType,
    h: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func8()(
            a.clone(),
            b.clone(),
            c.clone(),
            d.clone(),
            e.clone(),
            f.clone(),
            g.clone(),
            h.clone(),
        )
    })))
}

pub fn Effect_Uncurried_mkEffectFn9(
    callback: purust_core::Func9<
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
    >,
) -> UnknownType {
    Value::Func9(purust_core::Func9::Shared(std::rc::Rc::new(
        move |a, b, c, d, e, f, g, h, i| {
            callback(a, b, c, d, e, f, g, h, i).unwrap_func1()(Value::Unit)
        },
    )))
}

pub fn Effect_Uncurried_runEffectFn9(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
    c: UnknownType,
    d: UnknownType,
    e: UnknownType,
    f: UnknownType,
    g: UnknownType,
    h: UnknownType,
    i: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func9()(
            a.clone(),
            b.clone(),
            c.clone(),
            d.clone(),
            e.clone(),
            f.clone(),
            g.clone(),
            h.clone(),
            i.clone(),
        )
    })))
}

pub fn Effect_Uncurried_mkEffectFn10(
    callback: purust_core::Func10<
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
        UnknownType,
    >,
) -> UnknownType {
    Value::Func10(purust_core::Func10::Shared(std::rc::Rc::new(
        move |a, b, c, d, e, f, g, h, i, j| {
            callback(a, b, c, d, e, f, g, h, i, j).unwrap_func1()(Value::Unit)
        },
    )))
}

pub fn Effect_Uncurried_runEffectFn10(
    callback: UnknownType,
    a: UnknownType,
    b: UnknownType,
    c: UnknownType,
    d: UnknownType,
    e: UnknownType,
    f: UnknownType,
    g: UnknownType,
    h: UnknownType,
    i: UnknownType,
    j: UnknownType,
) -> UnknownType {
    Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new(move |_| {
        callback.unwrap_func10()(
            a.clone(),
            b.clone(),
            c.clone(),
            d.clone(),
            e.clone(),
            f.clone(),
            g.clone(),
            h.clone(),
            i.clone(),
            j.clone(),
        )
    })))
}




// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn1 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn2 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn3 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn4 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn5 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn6 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn7 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn8 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn9 {}

// Opaque FFI declaration only: no native values can be constructed.
#[derive(Clone, Debug)]
pub enum EffectFn10 {}
