% Generated by purerl version 0.0.24
-module(data_monoid_dual@ps).
-export(['Dual'/0, showDual/0, semigroupDual/1, semigroupDual/0, ordDual/1, ordDual/0, monoidDual/0, functorDual/0, eqDual/1, eqDual/0, eq1Dual/0, ord1Dual/0, boundedDual/0, applyDual/0, bindDual/0, applicativeDual/0, monadDual/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./data_monoid_dual.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 0).
-spec append() -> any().
append() -> (?MEMOIZE((data_semigroup@ps:append((data_semigroup@ps:semigroupString()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 0).
-spec append(any(),any()) -> any().
append(_@2,_@3) -> (((append())(_@2))(_@3)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 14).
-spec 'Dual'() -> any().
'Dual'() -> fun (X) ->
  X
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 24).
-spec showDual() -> any().
showDual() -> fun (DictShow) ->
  Show@20 = (?MEMOIZE((data_show@ps:show(DictShow)))),
  #{show=>fun (V) ->
    case V of
      (_@4) -> (append(<<"(Dual "/utf8>>, (append((Show@20(_@4)), <<")"/utf8>>))))
    end
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 40).
-spec semigroupDual(any()) -> any().
semigroupDual(_@7) -> 
  Append1@21 = (?MEMOIZE((data_semigroup@ps:append(_@7)))),
  #{append=>fun (V) ->
    fun (V1) ->
      case { V, V1 } of
        ({ _@8, _@9 }) -> ((Append1@21(_@9))(_@8))
      end
    end
  end}
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 40).
-spec semigroupDual() -> any().
semigroupDual() -> fun (_@10) ->
  (semigroupDual(_@10))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 19).
-spec ordDual(any()) -> any().
ordDual(_@11) -> _@11.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 19).
-spec ordDual() -> any().
ordDual() -> fun (_@12) ->
  (ordDual(_@12))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 43).
-spec monoidDual() -> any().
monoidDual() -> fun (DictMonoid) ->
  SemigroupDual1@22 = (?MEMOIZE((semigroupDual(((maps:get('Semigroup0', DictMonoid))(undefined)))))),
  #{mempty=>(?MEMOIZE((data_monoid@ps:mempty(DictMonoid)))), 'Semigroup0'=>fun (_) ->
    SemigroupDual1@22
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 27).
-spec functorDual() -> any().
functorDual() -> #{map=>fun (F) ->
  fun (M) ->
    case M of
      (_@13) -> (F(_@13))
    end
  end
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 16).
-spec eqDual(any()) -> any().
eqDual(_@14) -> _@14.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 16).
-spec eqDual() -> any().
eqDual() -> fun (_@15) ->
  (eqDual(_@15))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 17).
-spec eq1Dual() -> any().
eq1Dual() -> #{eq1=>fun (DictEq) ->
  (?MEMOIZE((data_eq@ps:eq((?MEMOIZE((eqDual(DictEq))))))))
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 20).
-spec ord1Dual() -> any().
ord1Dual() -> #{compare1=>fun (DictOrd) ->
  (?MEMOIZE((data_ord@ps:compare((?MEMOIZE((ordDual(DictOrd))))))))
end, 'Eq10'=>fun (_) ->
  (eq1Dual())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 22).
-spec boundedDual() -> any().
boundedDual() -> fun (DictBounded) ->
  DictBounded
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 29).
-spec applyDual() -> any().
applyDual() -> #{apply=>fun (V) ->
  fun (V1) ->
    case { V, V1 } of
      ({ _@16, _@17 }) -> (_@16(_@17))
    end
  end
end, 'Functor0'=>fun (_) ->
  (functorDual())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 35).
-spec bindDual() -> any().
bindDual() -> #{bind=>fun (V) ->
  fun (F) ->
    case { V, F } of
      ({ _@18, _@19 }) -> (_@19(_@18))
    end
  end
end, 'Apply0'=>fun (_) ->
  (applyDual())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 32).
-spec applicativeDual() -> any().
applicativeDual() -> #{pure=>('Dual'()), 'Apply0'=>fun (_) ->
  (applyDual())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Monoid/Dual.purs", 38).
-spec monadDual() -> any().
monadDual() -> #{'Applicative0'=>fun (_) ->
  (applicativeDual())
end, 'Bind1'=>fun (_) ->
  (bindDual())
end}.
