#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Bench::*;
use Purs_Control_Alt::*;
use Purs_Control_Alternative::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Comonad::*;
use Purs_Control_Extend::*;
use Purs_Control_Lazy::*;
use Purs_Control_Monad::*;
use Purs_Control_MonadPlus::*;
use Purs_Control_Monad_Rec_Class::*;
use Purs_Control_Monad_ST_Internal::*;
use Purs_Control_Monad_ST_Uncurried::*;
use Purs_Control_Plus::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Array::*;
use Purs_Data_Array_NonEmpty_Internal::*;
use Purs_Data_Array_ST::*;
use Purs_Data_Array_ST_Iterator::*;
use Purs_Data_Bifunctor::*;
use Purs_Data_Boolean::*;
use Purs_Data_BooleanAlgebra::*;
use Purs_Data_Bounded::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Const::*;
use Purs_Data_Either::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Foldable::*;
use Purs_Data_FoldableWithIndex::*;
use Purs_Data_Function::*;
use Purs_Data_Function_Uncurried::*;
use Purs_Data_Functor::*;
use Purs_Data_FunctorWithIndex::*;
use Purs_Data_Functor_App::*;
use Purs_Data_Functor_Compose::*;
use Purs_Data_Functor_Coproduct::*;
use Purs_Data_Functor_Invariant::*;
use Purs_Data_Functor_Product::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Identity::*;
use Purs_Data_Maybe::*;
use Purs_Data_Maybe_First::*;
use Purs_Data_Maybe_Last::*;
use Purs_Data_Monoid::*;
use Purs_Data_Monoid_Additive::*;
use Purs_Data_Monoid_Alternate::*;
use Purs_Data_Monoid_Conj::*;
use Purs_Data_Monoid_Disj::*;
use Purs_Data_Monoid_Dual::*;
use Purs_Data_Monoid_Endo::*;
use Purs_Data_Monoid_Multiplicative::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ord::*;
use Purs_Data_Ord_Max::*;
use Purs_Data_Ord_Min::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semigroup_Foldable::*;
use Purs_Data_Semigroup_Traversable::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Traversable::*;
use Purs_Data_TraversableWithIndex::*;
use Purs_Data_Traversable_Accum_Internal::*;
use Purs_Data_Tuple::*;
use Purs_Data_Unfoldable::*;
use Purs_Data_Unfoldable1::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Effect::*;
use Purs_Effect_Console::*;
use Purs_Effect_Ref::*;
use Purs_Partial::*;
use Purs_Partial_Unsafe::*;
use Purs_Record_Unsafe::*;
use Purs_Safe_Coerce::*;
use Purs_Type_Proxy::*;
use Purs_Unsafe_Coerce::*;
use Purs_Bench::*;
use Purs_Control_Applicative::*;
use Purs_Control_Bind::*;
use Purs_Data_Array::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Effect::*;
use Purs_Effect_Console::*;

// Code generated by purust for module Test_ArrayOps



pub fn Test_ArrayOps_range(mut purs_local_0: i64, mut purs_local_1: i64) -> crate::UnknownType {
    // AST: Typed(Abs(..., Typed(Abs(..., Typed(Typed(UncurriedApp(Var(...))))))))
/* Typed crate::UnknownType <- crate::UnknownType : UncurriedApp(Var(...)) */((Data_Array_rangeImpl()).unwrap_func1()(crate::mk_int(purs_local_0))).unwrap_func1()(crate::mk_int(purs_local_1))
}

pub fn Test_ArrayOps_filterEvens(mut purs_local_0: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Abs(..., Typed(Typed(Typed(UncurriedApp(Var(...)))))))
/* Typed crate::UnknownType <- crate::UnknownType : UncurriedApp(Var(...)) */((Data_Array_filterImpl()).unwrap_func1()(purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_1 = _a0;
    crate::mk_bool(/* Typed bool <- bool : PrimOp(...) */(/* Typed i64 <- i64 : PrimOp(...) */{ let _mod_l: i64 = (purs_local_1).unwrap_int(); let _mod_r: i64 = /* Typed i64 <- i64 : Lit */2; _mod_l.checked_rem_euclid(_mod_r).unwrap_or(0_i64) } == /* Typed i64 <- i64 : Lit */0))
} as fn(crate::UnknownType) -> crate::UnknownType)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))))).unwrap_func1()(purs_local_0)
}

pub fn Test_ArrayOps_sumEvens(mut purs_local_0: i64) -> i64 {
    // AST: Typed(Abs(..., Typed(Typed(App(Var(...))))))
/* Typed i64 <- crate::UnknownType : App(Var(...)) */(Data_Foldable_foldl(Data_Foldable_foldableArray(), purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<i64, i64, i64> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : App(Var(...)) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = ({
        let mut eval_arg_0 = Data_Semiring_semiringInt();
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType, mut eta_1: crate::UnknownType| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Data_Semiring_add(eval_arg_0, eta_0.clone(), eta_1.clone())
}))
}).clone(); move |mut _a0: i64, mut _a1: i64| -> i64 { (_f(crate::mk_int(_a0), crate::mk_int(_a1))).unwrap_int() } }))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_int(_f((_a0).unwrap_int(), (_a1).unwrap_int())) } })), crate::mk_int(/* Typed i64 <- i64 : Lit */0), /* Typed crate::UnknownType <- crate::UnknownType : UncurriedApp(Var(...)) */((Data_Array_filterImpl()).unwrap_func1()(purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_1 = _a0;
    crate::mk_bool(/* Typed bool <- bool : PrimOp(...) */(/* Typed i64 <- i64 : PrimOp(...) */{ let _mod_l: i64 = (purs_local_1).unwrap_int(); let _mod_r: i64 = /* Typed i64 <- i64 : Lit */2; _mod_l.checked_rem_euclid(_mod_r).unwrap_or(0_i64) } == /* Typed i64 <- i64 : Lit */0))
} as fn(crate::UnknownType) -> crate::UnknownType)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))))).unwrap_func1()(((Data_Array_rangeImpl()).unwrap_func1()(crate::mk_int(1))).unwrap_func1()(crate::mk_int(purs_local_0))))).unwrap_int()
}

pub fn Test_ArrayOps_describe() -> crate::UnknownType {
    // AST: Typed(Typed(App(Var(...))))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<crate::UnknownType> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Test_ArrayOps_describe", || {
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_log(/* Typed String <- String : Lit */String::from("Array Processing (900 elements):"))
}).clone())
}

pub fn Test_ArrayOps_act() -> crate::UnknownType {
    // AST: Typed(Let(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<crate::UnknownType> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Test_ArrayOps_act", || {
{
    purust_core::Value::Func1(purust_core::Func1::Static(|mut _u: crate::UnknownType| -> crate::UnknownType {
        {
    let mut purs_local_0 = Bench_opaque(crate::mk_int(/* Typed i64 <- i64 : Lit */900));
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_1 = {
        let _val_eval = purs_local_0;
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    };
    /* Typed crate::UnknownType <- crate::UnknownType : EffectPure */purust_core::Value::String(Data_Show_showIntImpl(/* Typed i64 <- i64 : App(Var(...)) */Test_ArrayOps_sumEvens(/* Typed i64 <- crate::UnknownType : Local(...) */(purs_local_1).unwrap_int())))
}
}
    } as fn(crate::UnknownType) -> crate::UnknownType))
}
}).clone())
}





