pub mod PureScript_Data_Time_Duration_Gen {
    use super::*;
    use fable_library_rust::Map_::find;
    use fable_library_rust::Native_::Any;
    use fable_library_rust::Native_::Func1;
    use fable_library_rust::Native_::MutCell;
    use fable_library_rust::String_::string;
    use crate::module_851afbc9::PureScript_Control_Monad_Gen_Class;
    use crate::module_b38d0a2::PureScript_Data_Functor;
    use crate::module_c4b34810::PureScript_Data_Time_Duration;
    use crate::module_aa21d1e7::Sharpurs_Prelude;
    pub fn Data_Time_Duration_Gen_genSeconds() -> &dyn Any {
        static Data_Time_Duration_Gen_genSeconds: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Time_Duration_Gen_genSeconds.get_or_init(||
                                                          &Func1::new(move
                                                                          |dictMonadGen|
                                                                          Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                                 &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                           Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                            Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                             Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                              Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                       &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                      &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                     &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                    &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                              &&&PureScript_Data_Time_Duration::Data_Time_Duration_Seconds()),
                                                                                                           &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseFloat(),
                                                                                                                                                                                                                    dictMonadGen),
                                                                                                                                                                                 &&&0.0_f64),
                                                                                                                                              &&&600.0_f64))))
    }
    pub fn Data_Time_Duration_Gen_genMinutes() -> &dyn Any {
        static Data_Time_Duration_Gen_genMinutes: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Time_Duration_Gen_genMinutes.get_or_init(||
                                                          &Func1::new(move
                                                                          |dictMonadGen|
                                                                          Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                                 &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                           Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                            Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                             Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                              Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                       &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                      &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                     &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                    &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                              &&&PureScript_Data_Time_Duration::Data_Time_Duration_Minutes()),
                                                                                                           &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseFloat(),
                                                                                                                                                                                                                    dictMonadGen),
                                                                                                                                                                                 &&&0.0_f64),
                                                                                                                                              &&&600.0_f64))))
    }
    pub fn Data_Time_Duration_Gen_genMilliseconds() -> &dyn Any {
        static Data_Time_Duration_Gen_genMilliseconds:
         MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Time_Duration_Gen_genMilliseconds.get_or_init(||
                                                               &Func1::new(move
                                                                               |dictMonadGen|
                                                                               Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                                      &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                                Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                                 Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                                  Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                                   Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                            &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                           &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                          &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                         &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                                   &&&PureScript_Data_Time_Duration::Data_Time_Duration_Milliseconds()),
                                                                                                                &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseFloat(),
                                                                                                                                                                                                                         dictMonadGen),
                                                                                                                                                                                      &&&0.0_f64),
                                                                                                                                                   &&&600000.0_f64))))
    }
    pub fn Data_Time_Duration_Gen_genHours() -> &dyn Any {
        static Data_Time_Duration_Gen_genHours: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Time_Duration_Gen_genHours.get_or_init(||
                                                        &Func1::new(move
                                                                        |dictMonadGen|
                                                                        Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                         Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                          Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                           Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                            Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                     &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                    &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                   &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                  &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                            &&&PureScript_Data_Time_Duration::Data_Time_Duration_Hours()),
                                                                                                         &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseFloat(),
                                                                                                                                                                                                                  dictMonadGen),
                                                                                                                                                                               &&&0.0_f64),
                                                                                                                                            &&&240.0_f64))))
    }
    pub fn Data_Time_Duration_Gen_genDays() -> &dyn Any {
        static Data_Time_Duration_Gen_genDays: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Time_Duration_Gen_genDays.get_or_init(||
                                                       &Func1::new(move
                                                                       |dictMonadGen|
                                                                       Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                              &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                        Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                         Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                          Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                           Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                    &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                   &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                  &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                 &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                           &&&PureScript_Data_Time_Duration::Data_Time_Duration_Days()),
                                                                                                        &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseFloat(),
                                                                                                                                                                                                                 dictMonadGen),
                                                                                                                                                                              &&&0.0_f64),
                                                                                                                                           &&&42.0_f64))))
    }
}
