pub mod PureScript_Data_Char_Gen {
    use super::*;
    use fable_library_rust::Map_::find;
    use fable_library_rust::Native_::Any;
    use fable_library_rust::Native_::Func1;
    use fable_library_rust::Native_::LrcPtr;
    use fable_library_rust::Native_::MutCell;
    use fable_library_rust::NativeArray_::new_array;
    use fable_library_rust::String_::string;
    use crate::module_851afbc9::PureScript_Control_Monad_Gen_Class;
    use crate::module_e72de349::PureScript_Control_Monad_Gen;
    use crate::module_d89c2f46::PureScript_Data_Bounded;
    use crate::module_6a1c5ce6::PureScript_Data_Enum;
    use crate::module_419ece9e::PureScript_Data_Foldable;
    use crate::module_b38d0a2::PureScript_Data_Functor;
    use crate::module_d6a130cf::PureScript_Data_NonEmpty;
    use crate::module_d6a130cf::PureScript_Data_NonEmpty::Data_NonEmpty_NonEmpty;
    use crate::module_aa21d1e7::Sharpurs_Prelude;
    pub fn Data_Char_Gen_foldable1NonEmpty() -> &dyn Any {
        static Data_Char_Gen_foldable1NonEmpty: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Char_Gen_foldable1NonEmpty.get_or_init(||
                                                        Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_NonEmpty::Data_NonEmpty_foldable1NonEmpty(),
                                                                                         &&&PureScript_Data_Foldable::Data_Foldable_foldableArray()))
    }
    pub fn Data_Char_Gen_genUnicodeChar() -> &dyn Any {
        static Data_Char_Gen_genUnicodeChar: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Char_Gen_genUnicodeChar.get_or_init(||
                                                     &Func1::new(move
                                                                     |dictMonadGen|
                                                                     Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                            &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                      Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                       Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                        Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                         Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                  &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                 &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                               &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                         &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Enum::Data_Enum_toEnumWithDefaults(),
                                                                                                                                                                                                                                                  &&&PureScript_Data_Enum::Data_Enum_boundedEnumChar()),
                                                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_bottom(),
                                                                                                                                                                                                                                                  &&&PureScript_Data_Bounded::Data_Bounded_boundedChar())),
                                                                                                                                                                            &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_top(),
                                                                                                                                                                                                               &&&PureScript_Data_Bounded::Data_Bounded_boundedChar()))),
                                                                                                      &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseInt(),
                                                                                                                                                                                                               dictMonadGen),
                                                                                                                                                                            &&&0_i32),
                                                                                                                                         &&&65536_i32))))
    }
    pub fn Data_Char_Gen_genDigitChar() -> &dyn Any {
        static Data_Char_Gen_genDigitChar: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Char_Gen_genDigitChar.get_or_init(||
                                                   &Func1::new(move
                                                                   |dictMonadGen|
                                                                   Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                          &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                    Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                     Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                      Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                       Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                               &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                              &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                             &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                       &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Enum::Data_Enum_toEnumWithDefaults(),
                                                                                                                                                                                                                                                &&&PureScript_Data_Enum::Data_Enum_boundedEnumChar()),
                                                                                                                                                                                                             &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_bottom(),
                                                                                                                                                                                                                                                &&&PureScript_Data_Bounded::Data_Bounded_boundedChar())),
                                                                                                                                                                          &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_top(),
                                                                                                                                                                                                             &&&PureScript_Data_Bounded::Data_Bounded_boundedChar()))),
                                                                                                    &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseInt(),
                                                                                                                                                                                                             dictMonadGen),
                                                                                                                                                                          &&&48_i32),
                                                                                                                                       &&&57_i32))))
    }
    pub fn Data_Char_Gen_genAsciiChar_prime() -> &dyn Any {
        static Data_Char_Gen_genAsciiChar_prime: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Char_Gen_genAsciiChar_prime.get_or_init(||
                                                         &Func1::new(move
                                                                         |dictMonadGen|
                                                                         Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                                &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                          Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                           Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                            Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                             Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                      &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                     &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                    &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                   &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                             &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Enum::Data_Enum_toEnumWithDefaults(),
                                                                                                                                                                                                                                                      &&&PureScript_Data_Enum::Data_Enum_boundedEnumChar()),
                                                                                                                                                                                                                   &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_bottom(),
                                                                                                                                                                                                                                                      &&&PureScript_Data_Bounded::Data_Bounded_boundedChar())),
                                                                                                                                                                                &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_top(),
                                                                                                                                                                                                                   &&&PureScript_Data_Bounded::Data_Bounded_boundedChar()))),
                                                                                                          &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseInt(),
                                                                                                                                                                                                                   dictMonadGen),
                                                                                                                                                                                &&&0_i32),
                                                                                                                                             &&&127_i32))))
    }
    pub fn Data_Char_Gen_genAsciiChar() -> &dyn Any {
        static Data_Char_Gen_genAsciiChar: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Char_Gen_genAsciiChar.get_or_init(||
                                                   &Func1::new(move
                                                                   |dictMonadGen|
                                                                   Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                          &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                    Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                     Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                      Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                       Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                               &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                              &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                             &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                       &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Enum::Data_Enum_toEnumWithDefaults(),
                                                                                                                                                                                                                                                &&&PureScript_Data_Enum::Data_Enum_boundedEnumChar()),
                                                                                                                                                                                                             &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_bottom(),
                                                                                                                                                                                                                                                &&&PureScript_Data_Bounded::Data_Bounded_boundedChar())),
                                                                                                                                                                          &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_top(),
                                                                                                                                                                                                             &&&PureScript_Data_Bounded::Data_Bounded_boundedChar()))),
                                                                                                    &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseInt(),
                                                                                                                                                                                                             dictMonadGen),
                                                                                                                                                                          &&&32_i32),
                                                                                                                                       &&&127_i32))))
    }
    pub fn Data_Char_Gen_genAlphaUppercase() -> &dyn Any {
        static Data_Char_Gen_genAlphaUppercase: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Char_Gen_genAlphaUppercase.get_or_init(||
                                                        &Func1::new(move
                                                                        |dictMonadGen|
                                                                        Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                         Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                          Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                           Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                            Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                     &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                    &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                   &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                  &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                            &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Enum::Data_Enum_toEnumWithDefaults(),
                                                                                                                                                                                                                                                     &&&PureScript_Data_Enum::Data_Enum_boundedEnumChar()),
                                                                                                                                                                                                                  &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_bottom(),
                                                                                                                                                                                                                                                     &&&PureScript_Data_Bounded::Data_Bounded_boundedChar())),
                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_top(),
                                                                                                                                                                                                                  &&&PureScript_Data_Bounded::Data_Bounded_boundedChar()))),
                                                                                                         &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseInt(),
                                                                                                                                                                                                                  dictMonadGen),
                                                                                                                                                                               &&&65_i32),
                                                                                                                                            &&&90_i32))))
    }
    pub fn Data_Char_Gen_genAlphaLowercase() -> &dyn Any {
        static Data_Char_Gen_genAlphaLowercase: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Char_Gen_genAlphaLowercase.get_or_init(||
                                                        &Func1::new(move
                                                                        |dictMonadGen|
                                                                        Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                                                                                                         Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                                                                                                          Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                                                                                                                                                                                                                                           Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                                                                                                                                                                                                                                                                                                            Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                                                                                                                                                                                                                                                                                                                     &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                                                                                    &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                                                                                   &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                                                                                                                  &&&Sharpurs_Prelude::Prim_undefined())),
                                                                                                                                            &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Enum::Data_Enum_toEnumWithDefaults(),
                                                                                                                                                                                                                                                     &&&PureScript_Data_Enum::Data_Enum_boundedEnumChar()),
                                                                                                                                                                                                                  &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_bottom(),
                                                                                                                                                                                                                                                     &&&PureScript_Data_Bounded::Data_Bounded_boundedChar())),
                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Bounded::Data_Bounded_top(),
                                                                                                                                                                                                                  &&&PureScript_Data_Bounded::Data_Bounded_boundedChar()))),
                                                                                                         &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseInt(),
                                                                                                                                                                                                                  dictMonadGen),
                                                                                                                                                                               &&&97_i32),
                                                                                                                                            &&&122_i32))))
    }
    pub fn Data_Char_Gen_genAlpha() -> &dyn Any {
        static Data_Char_Gen_genAlpha: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Char_Gen_genAlpha.get_or_init(||
                                               &Func1::new(move |dictMonadGen|
                                                               Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen::Control_Monad_Gen_oneOf(),
                                                                                                                                                                      dictMonadGen),
                                                                                                                                   &&&PureScript_Data_Char_Gen::Data_Char_Gen_foldable1NonEmpty()),
                                                                                                &&&LrcPtr::new(Data_NonEmpty_NonEmpty::Data_NonEmpty_NonEmptyusd_Ctor(Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Char_Gen::Data_Char_Gen_genAlphaLowercase(),
                                                                                                                                                                                                       dictMonadGen),
                                                                                                                                                                      &new_array(&[Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Char_Gen::Data_Char_Gen_genAlphaUppercase(),
                                                                                                                                                                                                                    dictMonadGen)]))))))
    }
}
