pub mod PureScript_Data_Map_Gen {
    use super::*;
    use fable_library_rust::Map_::find;
    use fable_library_rust::Native_::Any;
    use fable_library_rust::Native_::Func1;
    use fable_library_rust::Native_::LrcPtr;
    use fable_library_rust::Native_::MutCell;
    use fable_library_rust::String_::string;
    use crate::module_bb42e836::PureScript_Control_Apply;
    use crate::module_6c4d46c3::PureScript_Control_Bind;
    use crate::module_851afbc9::PureScript_Control_Monad_Gen_Class;
    use crate::module_e72de349::PureScript_Control_Monad_Gen;
    use crate::module_6e7709b7::PureScript_Data_Function;
    use crate::module_b38d0a2::PureScript_Data_Functor;
    use crate::module_d662adf2::PureScript_Data_List_Types;
    use crate::module_ed2bf3e0::PureScript_Data_Map_Internal;
    use crate::module_e7bd458d::PureScript_Data_Tuple::Data_Tuple_Tuple;
    use crate::module_aa21d1e7::Sharpurs_Prelude;
    pub fn Data_Map_Gen_genMap() -> &dyn Any {
        static Data_Map_Gen_genMap: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Map_Gen_genMap.get_or_init(||
                                            &Func1::new(move |dictMonadRec|
                                                            &Func1::new({
                                                                            let dictMonadRec
                                                                                =
                                                                                dictMonadRec.clone();
                                                                            move
                                                                                |dictMonadGen|
                                                                                {
                                                                                    let Monad0 =
                                                                                        Sharpurs_Prelude::sharpurs_apply(&&find(string("Monad0"),
                                                                                                                                Sharpurs_Prelude::unbox(dictMonadGen)),
                                                                                                                         &&&Sharpurs_Prelude::Prim_undefined());
                                                                                    let Bind1 =
                                                                                        Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                Sharpurs_Prelude::unbox(&&Monad0)),
                                                                                                                         &&&Sharpurs_Prelude::Prim_undefined());
                                                                                    let Bind11 =
                                                                                        Sharpurs_Prelude::sharpurs_apply(&&find(string("Bind1"),
                                                                                                                                Sharpurs_Prelude::unbox(&&Monad0)),
                                                                                                                         &&&Sharpurs_Prelude::Prim_undefined());
                                                                                    let Functor0 =
                                                                                        Sharpurs_Prelude::sharpurs_apply(&&find(string("Functor0"),
                                                                                                                                Sharpurs_Prelude::unbox(&Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                                                                                 Sharpurs_Prelude::unbox(&&Bind11)),
                                                                                                                                                                                          &&&Sharpurs_Prelude::Prim_undefined()))),
                                                                                                                         &&&Sharpurs_Prelude::Prim_undefined());
                                                                                    let Apply0 =
                                                                                        Sharpurs_Prelude::sharpurs_apply(&&find(string("Apply0"),
                                                                                                                                Sharpurs_Prelude::unbox(&&Bind11)),
                                                                                                                         &&&Sharpurs_Prelude::Prim_undefined());
                                                                                    &Func1::new({
                                                                                                    let Apply0
                                                                                                        =
                                                                                                        Apply0.clone();
                                                                                                    let Bind1
                                                                                                        =
                                                                                                        Bind1.clone();
                                                                                                    let Functor0
                                                                                                        =
                                                                                                        Functor0.clone();
                                                                                                    let dictMonadGen
                                                                                                        =
                                                                                                        dictMonadGen.clone();
                                                                                                    move
                                                                                                        |dictOrd|
                                                                                                        {
                                                                                                            let fromFoldable =
                                                                                                                Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Map_Internal::Data_Map_Internal_fromFoldable(),
                                                                                                                                                                                    dictOrd),
                                                                                                                                                 &&&PureScript_Data_List_Types::Data_List_Types_foldableList());
                                                                                                            &Func1::new({
                                                                                                                            let fromFoldable
                                                                                                                                =
                                                                                                                                fromFoldable.clone();
                                                                                                                            move
                                                                                                                                |genKey|
                                                                                                                                &Func1::new({
                                                                                                                                                let genKey
                                                                                                                                                    =
                                                                                                                                                    genKey.clone();
                                                                                                                                                move
                                                                                                                                                    |genValue|
                                                                                                                                                    Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_sized(),
                                                                                                                                                                                                                        &&&dictMonadGen),
                                                                                                                                                                                     &&&Func1::new({
                                                                                                                                                                                                       let genValue
                                                                                                                                                                                                           =
                                                                                                                                                                                                           genValue.clone();
                                                                                                                                                                                                       move
                                                                                                                                                                                                           |size|
                                                                                                                                                                                                           Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Bind::Control_Bind_bind(),
                                                                                                                                                                                                                                                                                                                  &&&Bind1),
                                                                                                                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_chooseInt(),
                                                                                                                                                                                                                                                                                                                                                                                        &&&dictMonadGen),
                                                                                                                                                                                                                                                                                                                                                     &&&0_i32),
                                                                                                                                                                                                                                                                                                                  size)),
                                                                                                                                                                                                                                            &&&Func1::new(move
                                                                                                                                                                                                                                                              |newSize|
                                                                                                                                                                                                                                                              Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Function::Data_Function_apply(),
                                                                                                                                                                                                                                                                                                                                  &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen_Class::Control_Monad_Gen_Class_resize(),
                                                                                                                                                                                                                                                                                                                                                                                                        &&&dictMonadGen),
                                                                                                                                                                                                                                                                                                                                                                     &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Function::Data_Function_const(),
                                                                                                                                                                                                                                                                                                                                                                                                        newSize))),
                                                                                                                                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                                                                                                                                                                                                                                                        &&&Functor0),
                                                                                                                                                                                                                                                                                                                                                                     &&&fromFoldable),
                                                                                                                                                                                                                                                                                                                                  &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Monad_Gen::Control_Monad_Gen_unfoldable(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              &&&dictMonadRec),
                                                                                                                                                                                                                                                                                                                                                                                                                                           &&&dictMonadGen),
                                                                                                                                                                                                                                                                                                                                                                                                        &&&PureScript_Data_List_Types::Data_List_Types_unfoldableList()),
                                                                                                                                                                                                                                                                                                                                                                     &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Apply::Control_Apply_apply(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              &&&Apply0),
                                                                                                                                                                                                                                                                                                                                                                                                                                           &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Functor::Data_Functor_map(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    &&&Functor0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 &&&Func1::new(move
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |usd__arg1|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Func1::new({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  let usd__arg1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      usd__arg1.clone();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  move
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |usd__arg2|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      &LrcPtr::new(Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(usd__arg1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              usd__arg2.clone()))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              &&&genKey)),
                                                                                                                                                                                                                                                                                                                                                                                                        &&&genValue))))))
                                                                                                                                                                                                   }))
                                                                                                                                            })
                                                                                                                        })
                                                                                                        }
                                                                                                })
                                                                                }
                                                                        })))
    }
}
