pub mod PureScript_Data_Divide {
    use super::*;
    use fable_library_rust::Map_::add;
    use fable_library_rust::Map_::empty;
    use fable_library_rust::Map_::find;
    use fable_library_rust::Native_::Any;
    use fable_library_rust::Native_::Func1;
    use fable_library_rust::Native_::LrcPtr;
    use fable_library_rust::Native_::MutCell;
    use fable_library_rust::String_::string;
    use crate::module_86d6df2::PureScript_Control_Category;
    use crate::module_18b8108c::PureScript_Data_Comparison;
    use crate::module_59dcd94b::PureScript_Data_Equivalence;
    use crate::module_c0687feb::PureScript_Data_HeytingAlgebra;
    use crate::module_851c93ca::PureScript_Data_Op;
    use crate::module_5f769efb::PureScript_Data_Ordering;
    use crate::module_d23c04ec::PureScript_Data_Predicate;
    use crate::module_ab5378f8::PureScript_Data_Semigroup;
    use crate::module_e7bd458d::PureScript_Data_Tuple::Data_Tuple_Tuple;
    use crate::module_aa21d1e7::Sharpurs_Prelude;
    pub fn Data_Divide_identity() -> &dyn Any {
        static Data_Divide_identity: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Divide_identity.get_or_init(||
                                             Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Category::Control_Category_identity(),
                                                                              &&&PureScript_Control_Category::Control_Category_categoryFn()))
    }
    pub fn Data_Divide_Divideusd_Dict() -> &dyn Any {
        static Data_Divide_Divideusd_Dict: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Divide_Divideusd_Dict.get_or_init(||
                                                   &Func1::new(move |x|
                                                                   x.clone()))
    }
    pub fn Data_Divide_dividePredicate() -> &dyn Any {
        static Data_Divide_dividePredicate: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Divide_dividePredicate.get_or_init(||
                                                    Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Divide::Data_Divide_Divideusd_Dict(),
                                                                                     &&&add(string("divide"),
                                                                                            &&Func1::new(move
                                                                                                             |f|
                                                                                                             &Func1::new({
                                                                                                                             let f
                                                                                                                                 =
                                                                                                                                 f.clone();
                                                                                                                             move
                                                                                                                                 |v|
                                                                                                                                 &Func1::new({
                                                                                                                                                 let v
                                                                                                                                                     =
                                                                                                                                                     v.clone();
                                                                                                                                                 move
                                                                                                                                                     |v1|
                                                                                                                                                     {
                                                                                                                                                         let matchValue =
                                                                                                                                                             Sharpurs_Prelude::unbox(&&f);
                                                                                                                                                         let matchValue_1 =
                                                                                                                                                             Sharpurs_Prelude::unbox(&&v);
                                                                                                                                                         let matchValue_2 =
                                                                                                                                                             Sharpurs_Prelude::unbox(v1);
                                                                                                                                                         Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Predicate::Data_Predicate_Predicate(),
                                                                                                                                                                                          &&&Func1::new({
                                                                                                                                                                                                            let matchValue_1
                                                                                                                                                                                                                =
                                                                                                                                                                                                                matchValue_1.clone();
                                                                                                                                                                                                            let matchValue_2
                                                                                                                                                                                                                =
                                                                                                                                                                                                                matchValue_2.clone();
                                                                                                                                                                                                            move
                                                                                                                                                                                                                |a|
                                                                                                                                                                                                                {
                                                                                                                                                                                                                    let matchValue_4:
                                                                                                                                                                                                                            LrcPtr<Data_Tuple_Tuple> =
                                                                                                                                                                                                                        Sharpurs_Prelude::unbox(&&Sharpurs_Prelude::sharpurs_apply(&&&matchValue,
                                                                                                                                                                                                                                                                                   a));
                                                                                                                                                                                                                    Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_HeytingAlgebra::Data_HeytingAlgebra_conj(),
                                                                                                                                                                                                                                                                                                                           &&&PureScript_Data_HeytingAlgebra::Data_HeytingAlgebra_heytingAlgebraBoolean()),
                                                                                                                                                                                                                                                                                        &&Sharpurs_Prelude::sharpurs_apply(&&&matchValue_1,
                                                                                                                                                                                                                                                                                                                           &&&match matchValue_4.as_ref()
                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                  Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(x,
                                                                                                                                                                                                                                                                                                                                                                             _)
                                                                                                                                                                                                                                                                                                                                  =>
                                                                                                                                                                                                                                                                                                                                  x.clone(),
                                                                                                                                                                                                                                                                                                                              })),
                                                                                                                                                                                                                                                     &&Sharpurs_Prelude::sharpurs_apply(&&&matchValue_2,
                                                                                                                                                                                                                                                                                        &&&match matchValue_4.as_ref()
                                                                                                                                                                                                                                                                                               {
                                                                                                                                                                                                                                                                                               Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(_,
                                                                                                                                                                                                                                                                                                                                          x)
                                                                                                                                                                                                                                                                                               =>
                                                                                                                                                                                                                                                                                               x.clone(),
                                                                                                                                                                                                                                                                                           }))
                                                                                                                                                                                                                }
                                                                                                                                                                                                        }))
                                                                                                                                                     }
                                                                                                                                             })
                                                                                                                         })),
                                                                                            add(string("Contravariant0"),
                                                                                                &&Func1::new(move
                                                                                                                 |usd__unused|
                                                                                                                 &PureScript_Data_Predicate::Data_Predicate_contravariantPredicate()),
                                                                                                empty::<string,
                                                                                                        &dyn Any>()))))
    }
    pub fn Data_Divide_divideOp() -> &dyn Any {
        static Data_Divide_divideOp: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Divide_divideOp.get_or_init(||
                                             &Func1::new(move |dictSemigroup|
                                                             Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Divide::Data_Divide_Divideusd_Dict(),
                                                                                              &&&add(string("divide"),
                                                                                                     &&Func1::new({
                                                                                                                      let dictSemigroup
                                                                                                                          =
                                                                                                                          dictSemigroup.clone();
                                                                                                                      move
                                                                                                                          |f|
                                                                                                                          &Func1::new({
                                                                                                                                          let f
                                                                                                                                              =
                                                                                                                                              f.clone();
                                                                                                                                          move
                                                                                                                                              |v|
                                                                                                                                              &Func1::new({
                                                                                                                                                              let v
                                                                                                                                                                  =
                                                                                                                                                                  v.clone();
                                                                                                                                                              move
                                                                                                                                                                  |v1|
                                                                                                                                                                  {
                                                                                                                                                                      let matchValue =
                                                                                                                                                                          Sharpurs_Prelude::unbox(&&f);
                                                                                                                                                                      let matchValue_1 =
                                                                                                                                                                          Sharpurs_Prelude::unbox(&&v);
                                                                                                                                                                      let matchValue_2 =
                                                                                                                                                                          Sharpurs_Prelude::unbox(v1);
                                                                                                                                                                      Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Op::Data_Op_Op(),
                                                                                                                                                                                                       &&&Func1::new({
                                                                                                                                                                                                                         let matchValue_1
                                                                                                                                                                                                                             =
                                                                                                                                                                                                                             matchValue_1.clone();
                                                                                                                                                                                                                         let matchValue_2
                                                                                                                                                                                                                             =
                                                                                                                                                                                                                             matchValue_2.clone();
                                                                                                                                                                                                                         move
                                                                                                                                                                                                                             |a|
                                                                                                                                                                                                                             {
                                                                                                                                                                                                                                 let matchValue_4:
                                                                                                                                                                                                                                         LrcPtr<Data_Tuple_Tuple> =
                                                                                                                                                                                                                                     Sharpurs_Prelude::unbox(&&Sharpurs_Prelude::sharpurs_apply(&&&matchValue,
                                                                                                                                                                                                                                                                                                a));
                                                                                                                                                                                                                                 Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Semigroup::Data_Semigroup_append(),
                                                                                                                                                                                                                                                                                                                                        &&&dictSemigroup),
                                                                                                                                                                                                                                                                                                     &&Sharpurs_Prelude::sharpurs_apply(&&&matchValue_1,
                                                                                                                                                                                                                                                                                                                                        &&&match matchValue_4.as_ref()
                                                                                                                                                                                                                                                                                                                                               {
                                                                                                                                                                                                                                                                                                                                               Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(x,
                                                                                                                                                                                                                                                                                                                                                                                          _)
                                                                                                                                                                                                                                                                                                                                               =>
                                                                                                                                                                                                                                                                                                                                               x.clone(),
                                                                                                                                                                                                                                                                                                                                           })),
                                                                                                                                                                                                                                                                  &&Sharpurs_Prelude::sharpurs_apply(&&&matchValue_2,
                                                                                                                                                                                                                                                                                                     &&&match matchValue_4.as_ref()
                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                            Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(_,
                                                                                                                                                                                                                                                                                                                                                       x)
                                                                                                                                                                                                                                                                                                            =>
                                                                                                                                                                                                                                                                                                            x.clone(),
                                                                                                                                                                                                                                                                                                        }))
                                                                                                                                                                                                                             }
                                                                                                                                                                                                                     }))
                                                                                                                                                                  }
                                                                                                                                                          })
                                                                                                                                      })
                                                                                                                  }),
                                                                                                     add(string("Contravariant0"),
                                                                                                         &&Func1::new(move
                                                                                                                          |usd__unused|
                                                                                                                          &PureScript_Data_Op::Data_Op_contravariantOp()),
                                                                                                         empty::<string,
                                                                                                                 &dyn Any>())))))
    }
    pub fn Data_Divide_divideEquivalence() -> &dyn Any {
        static Data_Divide_divideEquivalence: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Divide_divideEquivalence.get_or_init(||
                                                      Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Divide::Data_Divide_Divideusd_Dict(),
                                                                                       &&&add(string("divide"),
                                                                                              &&Func1::new(move
                                                                                                               |f|
                                                                                                               &Func1::new({
                                                                                                                               let f
                                                                                                                                   =
                                                                                                                                   f.clone();
                                                                                                                               move
                                                                                                                                   |v|
                                                                                                                                   &Func1::new({
                                                                                                                                                   let v
                                                                                                                                                       =
                                                                                                                                                       v.clone();
                                                                                                                                                   move
                                                                                                                                                       |v1|
                                                                                                                                                       {
                                                                                                                                                           let matchValue =
                                                                                                                                                               Sharpurs_Prelude::unbox(&&f);
                                                                                                                                                           let matchValue_1 =
                                                                                                                                                               Sharpurs_Prelude::unbox(&&v);
                                                                                                                                                           let matchValue_2 =
                                                                                                                                                               Sharpurs_Prelude::unbox(v1);
                                                                                                                                                           let f1 =
                                                                                                                                                               matchValue;
                                                                                                                                                           Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Equivalence::Data_Equivalence_Equivalence(),
                                                                                                                                                                                            &&&Func1::new({
                                                                                                                                                                                                              let f1
                                                                                                                                                                                                                  =
                                                                                                                                                                                                                  f1.clone();
                                                                                                                                                                                                              let matchValue_1
                                                                                                                                                                                                                  =
                                                                                                                                                                                                                  matchValue_1.clone();
                                                                                                                                                                                                              let matchValue_2
                                                                                                                                                                                                                  =
                                                                                                                                                                                                                  matchValue_2.clone();
                                                                                                                                                                                                              move
                                                                                                                                                                                                                  |a|
                                                                                                                                                                                                                  &Func1::new({
                                                                                                                                                                                                                                  let a
                                                                                                                                                                                                                                      =
                                                                                                                                                                                                                                      a.clone();
                                                                                                                                                                                                                                  move
                                                                                                                                                                                                                                      |b|
                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                          let matchValue_4:
                                                                                                                                                                                                                                                  LrcPtr<Data_Tuple_Tuple> =
                                                                                                                                                                                                                                              Sharpurs_Prelude::unbox(&&Sharpurs_Prelude::sharpurs_apply(&&&f1,
                                                                                                                                                                                                                                                                                                         &&&a));
                                                                                                                                                                                                                                          let matchValue_5:
                                                                                                                                                                                                                                                  LrcPtr<Data_Tuple_Tuple> =
                                                                                                                                                                                                                                              Sharpurs_Prelude::unbox(&&Sharpurs_Prelude::sharpurs_apply(&&&f1,
                                                                                                                                                                                                                                                                                                         b));
                                                                                                                                                                                                                                          Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_HeytingAlgebra::Data_HeytingAlgebra_conj(),
                                                                                                                                                                                                                                                                                                                                                 &&&PureScript_Data_HeytingAlgebra::Data_HeytingAlgebra_heytingAlgebraBoolean()),
                                                                                                                                                                                                                                                                                                              &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&matchValue_1,
                                                                                                                                                                                                                                                                                                                                                                                    &&&match matchValue_4.as_ref()
                                                                                                                                                                                                                                                                                                                                                                                           {
                                                                                                                                                                                                                                                                                                                                                                                           Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(x,
                                                                                                                                                                                                                                                                                                                                                                                                                                      _)
                                                                                                                                                                                                                                                                                                                                                                                           =>
                                                                                                                                                                                                                                                                                                                                                                                           x.clone(),
                                                                                                                                                                                                                                                                                                                                                                                       }),
                                                                                                                                                                                                                                                                                                                                                 &&&match matchValue_5.as_ref()
                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                        Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(x,
                                                                                                                                                                                                                                                                                                                                                                                                   _)
                                                                                                                                                                                                                                                                                                                                                        =>
                                                                                                                                                                                                                                                                                                                                                        x.clone(),
                                                                                                                                                                                                                                                                                                                                                    })),
                                                                                                                                                                                                                                                                           &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&matchValue_2,
                                                                                                                                                                                                                                                                                                                                                 &&&match matchValue_4.as_ref()
                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                        Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(_,
                                                                                                                                                                                                                                                                                                                                                                                                   x)
                                                                                                                                                                                                                                                                                                                                                        =>
                                                                                                                                                                                                                                                                                                                                                        x.clone(),
                                                                                                                                                                                                                                                                                                                                                    }),
                                                                                                                                                                                                                                                                                                              &&&match matchValue_5.as_ref()
                                                                                                                                                                                                                                                                                                                     {
                                                                                                                                                                                                                                                                                                                     Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(_,
                                                                                                                                                                                                                                                                                                                                                                x)
                                                                                                                                                                                                                                                                                                                     =>
                                                                                                                                                                                                                                                                                                                     x.clone(),
                                                                                                                                                                                                                                                                                                                 }))
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                              })
                                                                                                                                                                                                          }))
                                                                                                                                                       }
                                                                                                                                               })
                                                                                                                           })),
                                                                                              add(string("Contravariant0"),
                                                                                                  &&Func1::new(move
                                                                                                                   |usd__unused|
                                                                                                                   &PureScript_Data_Equivalence::Data_Equivalence_contravariantEquivalence()),
                                                                                                  empty::<string,
                                                                                                          &dyn Any>()))))
    }
    pub fn Data_Divide_divideComparison() -> &dyn Any {
        static Data_Divide_divideComparison: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Divide_divideComparison.get_or_init(||
                                                     Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Divide::Data_Divide_Divideusd_Dict(),
                                                                                      &&&add(string("divide"),
                                                                                             &&Func1::new(move
                                                                                                              |f|
                                                                                                              &Func1::new({
                                                                                                                              let f
                                                                                                                                  =
                                                                                                                                  f.clone();
                                                                                                                              move
                                                                                                                                  |v|
                                                                                                                                  &Func1::new({
                                                                                                                                                  let v
                                                                                                                                                      =
                                                                                                                                                      v.clone();
                                                                                                                                                  move
                                                                                                                                                      |v1|
                                                                                                                                                      {
                                                                                                                                                          let matchValue =
                                                                                                                                                              Sharpurs_Prelude::unbox(&&f);
                                                                                                                                                          let matchValue_1 =
                                                                                                                                                              Sharpurs_Prelude::unbox(&&v);
                                                                                                                                                          let matchValue_2 =
                                                                                                                                                              Sharpurs_Prelude::unbox(v1);
                                                                                                                                                          let f1 =
                                                                                                                                                              matchValue;
                                                                                                                                                          Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Comparison::Data_Comparison_Comparison(),
                                                                                                                                                                                           &&&Func1::new({
                                                                                                                                                                                                             let f1
                                                                                                                                                                                                                 =
                                                                                                                                                                                                                 f1.clone();
                                                                                                                                                                                                             let matchValue_1
                                                                                                                                                                                                                 =
                                                                                                                                                                                                                 matchValue_1.clone();
                                                                                                                                                                                                             let matchValue_2
                                                                                                                                                                                                                 =
                                                                                                                                                                                                                 matchValue_2.clone();
                                                                                                                                                                                                             move
                                                                                                                                                                                                                 |a|
                                                                                                                                                                                                                 &Func1::new({
                                                                                                                                                                                                                                 let a
                                                                                                                                                                                                                                     =
                                                                                                                                                                                                                                     a.clone();
                                                                                                                                                                                                                                 move
                                                                                                                                                                                                                                     |b|
                                                                                                                                                                                                                                     {
                                                                                                                                                                                                                                         let matchValue_4:
                                                                                                                                                                                                                                                 LrcPtr<Data_Tuple_Tuple> =
                                                                                                                                                                                                                                             Sharpurs_Prelude::unbox(&&Sharpurs_Prelude::sharpurs_apply(&&&f1,
                                                                                                                                                                                                                                                                                                        &&&a));
                                                                                                                                                                                                                                         let matchValue_5:
                                                                                                                                                                                                                                                 LrcPtr<Data_Tuple_Tuple> =
                                                                                                                                                                                                                                             Sharpurs_Prelude::unbox(&&Sharpurs_Prelude::sharpurs_apply(&&&f1,
                                                                                                                                                                                                                                                                                                        b));
                                                                                                                                                                                                                                         Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Semigroup::Data_Semigroup_append(),
                                                                                                                                                                                                                                                                                                                                                &&&PureScript_Data_Ordering::Data_Ordering_semigroupOrdering()),
                                                                                                                                                                                                                                                                                                             &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&matchValue_1,
                                                                                                                                                                                                                                                                                                                                                                                   &&&match matchValue_4.as_ref()
                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                          Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(x,
                                                                                                                                                                                                                                                                                                                                                                                                                                     _)
                                                                                                                                                                                                                                                                                                                                                                                          =>
                                                                                                                                                                                                                                                                                                                                                                                          x.clone(),
                                                                                                                                                                                                                                                                                                                                                                                      }),
                                                                                                                                                                                                                                                                                                                                                &&&match matchValue_5.as_ref()
                                                                                                                                                                                                                                                                                                                                                       {
                                                                                                                                                                                                                                                                                                                                                       Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(x,
                                                                                                                                                                                                                                                                                                                                                                                                  _)
                                                                                                                                                                                                                                                                                                                                                       =>
                                                                                                                                                                                                                                                                                                                                                       x.clone(),
                                                                                                                                                                                                                                                                                                                                                   })),
                                                                                                                                                                                                                                                                          &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&matchValue_2,
                                                                                                                                                                                                                                                                                                                                                &&&match matchValue_4.as_ref()
                                                                                                                                                                                                                                                                                                                                                       {
                                                                                                                                                                                                                                                                                                                                                       Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(_,
                                                                                                                                                                                                                                                                                                                                                                                                  x)
                                                                                                                                                                                                                                                                                                                                                       =>
                                                                                                                                                                                                                                                                                                                                                       x.clone(),
                                                                                                                                                                                                                                                                                                                                                   }),
                                                                                                                                                                                                                                                                                                             &&&match matchValue_5.as_ref()
                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                    Data_Tuple_Tuple::Data_Tuple_Tupleusd_Ctor(_,
                                                                                                                                                                                                                                                                                                                                                               x)
                                                                                                                                                                                                                                                                                                                    =>
                                                                                                                                                                                                                                                                                                                    x.clone(),
                                                                                                                                                                                                                                                                                                                }))
                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                             })
                                                                                                                                                                                                         }))
                                                                                                                                                      }
                                                                                                                                              })
                                                                                                                          })),
                                                                                             add(string("Contravariant0"),
                                                                                                 &&Func1::new(move
                                                                                                                  |usd__unused|
                                                                                                                  &PureScript_Data_Comparison::Data_Comparison_contravariantComparison()),
                                                                                                 empty::<string,
                                                                                                         &dyn Any>()))))
    }
    pub fn Data_Divide_divide() -> &dyn Any {
        static Data_Divide_divide: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Divide_divide.get_or_init(||
                                           &Func1::new(move |dict|
                                                           find(string("divide"),
                                                                Sharpurs_Prelude::unbox(&&Sharpurs_Prelude::unbox(dict)))))
    }
    pub fn Data_Divide_divided() -> &dyn Any {
        static Data_Divide_divided: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Data_Divide_divided.get_or_init(||
                                            &Func1::new(move |dictDivide|
                                                            Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Divide::Data_Divide_divide(),
                                                                                                                                dictDivide),
                                                                                             &&&PureScript_Data_Divide::Data_Divide_identity())))
    }
}
