pub mod PureScript_Effect_Aff_Compat {
    use super::*;
    use fable_library_rust::Native_::Any;
    use fable_library_rust::Native_::Func1;
    use fable_library_rust::Native_::LrcPtr;
    use fable_library_rust::Native_::MutCell;
    use crate::module_ce6bdf8a::PureScript_Control_Applicative;
    use crate::module_6c4d46c3::PureScript_Control_Bind;
    use crate::module_655da3ed::PureScript_Control_Semigroupoid;
    use crate::module_173929b2::PureScript_Data_Either::Data_Either_Either;
    use crate::module_6e7709b7::PureScript_Data_Function;
    use crate::module_361110b3::PureScript_Effect_Aff;
    use crate::module_edf44bb7::PureScript_Effect_Uncurried;
    use crate::module_5706e1fc::PureScript_Effect;
    use crate::module_aa21d1e7::Sharpurs_Prelude;
    pub fn Effect_Aff_Compat_pure() -> &dyn Any {
        static Effect_Aff_Compat_pure: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Effect_Aff_Compat_pure.get_or_init(||
                                               Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Applicative::Control_Applicative_pure(),
                                                                                &&&PureScript_Effect::Effect_applicativeEffect()))
    }
    pub fn Effect_Aff_Compat_EffectFnCanceler() -> &dyn Any {
        static Effect_Aff_Compat_EffectFnCanceler: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Effect_Aff_Compat_EffectFnCanceler.get_or_init(||
                                                           &Func1::new(move
                                                                           |x|
                                                                           x.clone()))
    }
    pub fn Effect_Aff_Compat_EffectFnAff() -> &dyn Any {
        static Effect_Aff_Compat_EffectFnAff: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Effect_Aff_Compat_EffectFnAff.get_or_init(||
                                                      &Func1::new(move |x|
                                                                      x.clone()))
    }
    pub fn Effect_Aff_Compat_fromEffectFnAff() -> &dyn Any {
        static Effect_Aff_Compat_fromEffectFnAff: MutCell<Option<&dyn Any>> =
            MutCell::new(None);
        Effect_Aff_Compat_fromEffectFnAff.get_or_init(||
                                                          &Func1::new(move |v|
                                                                          {
                                                                              let eff =
                                                                                  Sharpurs_Prelude::unbox(v);
                                                                              Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Aff::Effect_Aff_makeAff(),
                                                                                                               &&&Func1::new({
                                                                                                                                 let eff
                                                                                                                                     =
                                                                                                                                     eff.clone();
                                                                                                                                 move
                                                                                                                                     |k|
                                                                                                                                     Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Bind::Control_Bind_bind(),
                                                                                                                                                                                                                                            &&&PureScript_Effect::Effect_bindEffect()),
                                                                                                                                                                                                         &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Uncurried::Effect_Uncurried_runEffectFn2(),
                                                                                                                                                                                                                                                                                                                  &&&eff),
                                                                                                                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Uncurried::Effect_Uncurried_mkEffectFn1(),
                                                                                                                                                                                                                                                                                                                  &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Semigroupoid::Control_Semigroupoid_compose(),
                                                                                                                                                                                                                                                                                                                                                                                                                           &&&PureScript_Control_Semigroupoid::Control_Semigroupoid_semigroupoidFn()),
                                                                                                                                                                                                                                                                                                                                                                                        k),
                                                                                                                                                                                                                                                                                                                                                     &&&Func1::new(move
                                                                                                                                                                                                                                                                                                                                                                       |usd__arg1|
                                                                                                                                                                                                                                                                                                                                                                       &LrcPtr::new(Data_Either_Either::Data_Either_Leftusd_Ctor(usd__arg1.clone())))))),
                                                                                                                                                                                                                                            &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Uncurried::Effect_Uncurried_mkEffectFn1(),
                                                                                                                                                                                                                                                                               &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Semigroupoid::Control_Semigroupoid_compose(),
                                                                                                                                                                                                                                                                                                                                                                                        &&&PureScript_Control_Semigroupoid::Control_Semigroupoid_semigroupoidFn()),
                                                                                                                                                                                                                                                                                                                                                     k),
                                                                                                                                                                                                                                                                                                                  &&&Func1::new(move
                                                                                                                                                                                                                                                                                                                                    |usd__arg1_1|
                                                                                                                                                                                                                                                                                                                                    &LrcPtr::new(Data_Either_Either::Data_Either_Rightusd_Ctor(usd__arg1_1.clone()))))))),
                                                                                                                                                                      &&&Func1::new(move
                                                                                                                                                                                        |v1|
                                                                                                                                                                                        {
                                                                                                                                                                                            let canceler =
                                                                                                                                                                                                Sharpurs_Prelude::unbox(v1);
                                                                                                                                                                                            Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Data_Function::Data_Function_apply(),
                                                                                                                                                                                                                                                                &&&PureScript_Effect_Aff_Compat::Effect_Aff_Compat_pure()),
                                                                                                                                                                                                                             &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Aff::Effect_Aff_Canceler(),
                                                                                                                                                                                                                                                                &&&Func1::new({
                                                                                                                                                                                                                                                                                  let canceler
                                                                                                                                                                                                                                                                                      =
                                                                                                                                                                                                                                                                                      canceler.clone();
                                                                                                                                                                                                                                                                                  move
                                                                                                                                                                                                                                                                                      |e|
                                                                                                                                                                                                                                                                                      Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Aff::Effect_Aff_makeAff(),
                                                                                                                                                                                                                                                                                                                       &&&Func1::new({
                                                                                                                                                                                                                                                                                                                                         let e
                                                                                                                                                                                                                                                                                                                                             =
                                                                                                                                                                                                                                                                                                                                             e.clone();
                                                                                                                                                                                                                                                                                                                                         move
                                                                                                                                                                                                                                                                                                                                             |k2|
                                                                                                                                                                                                                                                                                                                                             Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Bind::Control_Bind_discard(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       &&&PureScript_Control_Bind::Control_Bind_discardUnit()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    &&&PureScript_Effect::Effect_bindEffect()),
                                                                                                                                                                                                                                                                                                                                                                                                                 &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Uncurried::Effect_Uncurried_runEffectFn3(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             &&&canceler),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          &&&e),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Uncurried::Effect_Uncurried_mkEffectFn1(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Semigroupoid::Control_Semigroupoid_compose(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   &&&PureScript_Control_Semigroupoid::Control_Semigroupoid_semigroupoidFn()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                k2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             &&&Func1::new(move
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |usd__arg1_2|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               &LrcPtr::new(Data_Either_Either::Data_Either_Leftusd_Ctor(usd__arg1_2.clone())))))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    &&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Effect_Uncurried::Effect_Uncurried_mkEffectFn1(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       &&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Semigroupoid::Control_Semigroupoid_compose(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                &&&PureScript_Control_Semigroupoid::Control_Semigroupoid_semigroupoidFn()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             k2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          &&&Func1::new(move
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |usd__arg1_3|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            &LrcPtr::new(Data_Either_Either::Data_Either_Rightusd_Ctor(usd__arg1_3.clone()))))))),
                                                                                                                                                                                                                                                                                                                                                                              &&&Func1::new(move
                                                                                                                                                                                                                                                                                                                                                                                                |usd__unused|
                                                                                                                                                                                                                                                                                                                                                                                                Sharpurs_Prelude::sharpurs_apply(&&Sharpurs_Prelude::sharpurs_apply(&&&PureScript_Control_Applicative::Control_Applicative_pure(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    &&&PureScript_Effect::Effect_applicativeEffect()),
                                                                                                                                                                                                                                                                                                                                                                                                                                 &&&PureScript_Effect_Aff::Effect_Aff_nonCanceler())))
                                                                                                                                                                                                                                                                                                                                     }))
                                                                                                                                                                                                                                                                              })))
                                                                                                                                                                                        }))
                                                                                                                             }))
                                                                          }))
    }
}
