public class Effect_Aff_Compat {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object EffectFnCanceler = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object EffectFnAff = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object fromEffectFnAff = (java.util.function.Function<Object, Object>) (v_0) -> ((java.util.function.Function<Object, Object>) (Effect_Aff.makeAff)).apply((java.util.function.Function<Object, Object>) (k_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object v1_2 = ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_0)).apply((java.util.function.Function<Object, Object>) (__local_var_2) -> ((java.util.function.Function<Object, Object>) (k_1)).apply(new Data_Either.Left(__local_var_2))))).apply((java.util.function.Function<Object, Object>) (__local_var_2) -> ((java.util.function.Function<Object, Object>) (k_1)).apply(new Data_Either.Right(__local_var_2))))).get(); return (java.util.function.Function<Object, Object>) (e_3) -> ((java.util.function.Function<Object, Object>) (Effect_Aff.makeAff)).apply((java.util.function.Function<Object, Object>) (k2_4) -> (new java.util.function.Supplier<Object>() { public Object get() { Object _dollar___unused_5 = ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v1_2)).apply(e_3))).apply((java.util.function.Function<Object, Object>) (__local_var_5) -> ((java.util.function.Function<Object, Object>) (k2_4)).apply(new Data_Either.Left(__local_var_5))))).apply((java.util.function.Function<Object, Object>) (__local_var_5) -> ((java.util.function.Function<Object, Object>) (k2_4)).apply(new Data_Either.Right(__local_var_5))))).get(); return Effect_Aff.nonCanceler; } })); } }));
}
