public class Test_LazyEvaluation {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Lazy = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object force = (java.util.function.Function<Object, Object>) (v_0) -> ((java.util.function.Function<Object, Object>) (v_0)).apply(Data_Unit.unit);
public static final Object describe = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Lazy Evaluation (1M Thunks Forced, 1k Depth):");
public static final Object defer = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object buildThunks = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; Object __tco_v1_1 = v1_1; while(true) { final Object __final_v_0 = __tco_v_0; final Object __final_v1_1 = __tco_v1_1; try { return ( ((Boolean) (java.util.Objects.equals(__final_v_0, 0))) ? __final_v1_1 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_LazyEvaluation.buildThunks)).apply((((Integer) (__final_v_0)) - ((Integer) (1)))))).apply((java.util.function.Function<Object, Object>) (v2_2) -> (((Integer) (((java.util.function.Function<Object, Object>) (v1_1)).apply(Data_Unit.unit))) + ((Integer) (1))))); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; __tco_v1_1 = __tco_ex.args[1]; } } } }).get();
public static final Object runManyTimes = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; Object __tco_v1_1 = v1_1; while(true) { final Object __final_v_0 = __tco_v_0; final Object __final_v1_1 = __tco_v1_1; try { return ( ((Boolean) (java.util.Objects.equals(__final_v_0, 0))) ? __final_v1_1 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_LazyEvaluation.runManyTimes)).apply((((Integer) (__final_v_0)) - ((Integer) (1)))))).apply((((Integer) (__final_v1_1)) + ((Integer) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_LazyEvaluation.buildThunks)).apply(1000))).apply((java.util.function.Function<Object, Object>) (v2_2) -> 0))).apply(Data_Unit.unit)))))); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; __tco_v1_1 = __tco_ex.args[1]; } } } }).get();
public static final Object act = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Bench.opaque)).apply(1000); Object dummy_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_LazyEvaluation.runManyTimes)).apply(dummy_1))).apply(0))))).get(); } });
}
