public class Test_Primes {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final class Nil {
            
            public Nil() {
                
            }
        }
public static final class Cons {
            public final Object value0;
            public final Object value1;
            public Cons(Object value0, Object value1) {
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object Nil = new Test_Primes.Nil();
public static final Object Cons = (java.util.function.Function<Object, Object>) (value0) -> (java.util.function.Function<Object, Object>) (value1) -> new Test_Primes.Cons(value0, value1);
public static final Object sumList = (java.util.function.Function<Object, Object>) (lst_0) -> { Object go__go_1 = (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_2 = v_2; Object __tco_v1_3 = v1_3; while(true) { final Object __final_v_2 = __tco_v_2; final Object __final_v1_3 = __tco_v1_3; try { return ( ((Boolean) ((__final_v_2 instanceof Test_Primes.Nil))) ? __final_v1_3 : ( ((Boolean) ((__final_v_2 instanceof Test_Primes.Cons))) ? (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_1", new Object[]{((Test_Primes.Cons) (Object)(__final_v_2)).value1, (((Integer) (__final_v1_3)) + ((Integer) (((Test_Primes.Cons) (Object)(__final_v_2)).value0)))}); } }).get() : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } catch (TcoLoop __tco_ex) { __tco_v_2 = __tco_ex.args[0]; __tco_v1_3 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_1)).apply(lst_0))).apply(0); };
public static final Object reverse = (java.util.function.Function<Object, Object>) (lst_0) -> { Object go__go_1 = (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_2 = v_2; Object __tco_v1_3 = v1_3; while(true) { final Object __final_v_2 = __tco_v_2; final Object __final_v1_3 = __tco_v1_3; try { return ( ((Boolean) ((__final_v_2 instanceof Test_Primes.Nil))) ? __final_v1_3 : ( ((Boolean) ((__final_v_2 instanceof Test_Primes.Cons))) ? (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_1", new Object[]{((Test_Primes.Cons) (Object)(__final_v_2)).value1, new Test_Primes.Cons(((Test_Primes.Cons) (Object)(__final_v_2)).value0, __final_v1_3)}); } }).get() : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } catch (TcoLoop __tco_ex) { __tco_v_2 = __tco_ex.args[0]; __tco_v1_3 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_1)).apply(lst_0))).apply(new Test_Primes.Nil()); };
public static final Object range = (java.util.function.Function<Object, Object>) (start_0) -> (java.util.function.Function<Object, Object>) (end_1) -> { Object go__go_2 = (java.util.function.Function<Object, Object>) (curr_3) -> (java.util.function.Function<Object, Object>) (acc_4) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_curr_3 = curr_3; Object __tco_acc_4 = acc_4; while(true) { final Object __final_curr_3 = __tco_curr_3; final Object __final_acc_4 = __tco_acc_4; try { return ( ((Boolean) ((((Integer) (__final_curr_3)) < ((Integer) (start_0))))) ? __final_acc_4 : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_2", new Object[]{(((Integer) (__final_curr_3)) - ((Integer) (1))), new Test_Primes.Cons(__final_curr_3, __final_acc_4)}); } }).get()); } catch (TcoLoop __tco_ex) { __tco_curr_3 = __tco_ex.args[0]; __tco_acc_4 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_2)).apply(end_1))).apply(new Test_Primes.Nil()); };
public static final Object filter = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (lst_1) -> { Object go__go_2 = (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_3 = v_3; Object __tco_v1_4 = v1_4; while(true) { final Object __final_v_3 = __tco_v_3; final Object __final_v1_4 = __tco_v1_4; try { return (new java.util.function.Supplier<Object>() { public Object get() {  return ( ((Boolean) ((__final_v_3 instanceof Test_Primes.Nil))) ? (new java.util.function.Supplier<Object>() { public Object get() { Object go__go_5 = (java.util.function.Function<Object, Object>) (v_6) -> (java.util.function.Function<Object, Object>) (v1_7) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_6 = v_6; Object __tco_v1_7 = v1_7; while(true) { final Object __final_v_6 = __tco_v_6; final Object __final_v1_7 = __tco_v1_7; try { return ( ((Boolean) ((__final_v_6 instanceof Test_Primes.Nil))) ? __final_v1_7 : ( ((Boolean) ((__final_v_6 instanceof Test_Primes.Cons))) ? (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_5", new Object[]{((Test_Primes.Cons) (Object)(__final_v_6)).value1, new Test_Primes.Cons(((Test_Primes.Cons) (Object)(__final_v_6)).value0, __final_v1_7)}); } }).get() : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } catch (TcoLoop __tco_ex) { __tco_v_6 = __tco_ex.args[0]; __tco_v1_7 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_5)).apply(__final_v1_4))).apply(new Test_Primes.Nil()); } }).get() : ( ((Boolean) ((__final_v_3 instanceof Test_Primes.Cons))) ? ( ((Boolean) (((java.util.function.Function<Object, Object>) (p_0)).apply(((Test_Primes.Cons) (Object)(__final_v_3)).value0))) ? (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_2", new Object[]{((Test_Primes.Cons) (Object)(__final_v_3)).value1, new Test_Primes.Cons(((Test_Primes.Cons) (Object)(__final_v_3)).value0, __final_v1_4)}); } }).get() : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_2", new Object[]{((Test_Primes.Cons) (Object)(__final_v_3)).value1, __final_v1_4}); } }).get()) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } }).get(); } catch (TcoLoop __tco_ex) { __tco_v_3 = __tco_ex.args[0]; __tco_v1_4 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_2)).apply(lst_1))).apply(new Test_Primes.Nil()); };
public static final Object sieve = (java.util.function.Function<Object, Object>) (v_0) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; while(true) { final Object __final_v_0 = __tco_v_0; try { return ( ((Boolean) ((__final_v_0 instanceof Test_Primes.Nil))) ? new Test_Primes.Nil() : (new java.util.function.Supplier<Object>() { public Object get() {  return ( ((Boolean) ((__final_v_0 instanceof Test_Primes.Cons))) ? (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((Test_Primes.Cons) (Object)(__final_v_0)).value0; return new Test_Primes.Cons(__local_var_1, ((java.util.function.Function<Object, Object>) (Test_Primes.sieve)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Primes.filter)).apply((java.util.function.Function<Object, Object>) (x_2) -> !(((Boolean) (java.util.Objects.equals(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.intMod)).apply(x_2))).apply(__local_var_1), 0))))))).apply(((Test_Primes.Cons) (Object)(__final_v_0)).value1))); } }).get() : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); } }).get()); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; } } } }).get();
public static final Object describe = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Prime Sieve (sum primes up to 500):");
public static final Object act = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Bench.opaque)).apply(500); Object dummy_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object go__go_2 = (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_3 = v_3; Object __tco_v1_4 = v1_4; while(true) { final Object __final_v_3 = __tco_v_3; final Object __final_v1_4 = __tco_v1_4; try { return ( ((Boolean) ((__final_v_3 instanceof Test_Primes.Nil))) ? __final_v1_4 : ( ((Boolean) ((__final_v_3 instanceof Test_Primes.Cons))) ? (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_2", new Object[]{((Test_Primes.Cons) (Object)(__final_v_3)).value1, (((Integer) (__final_v1_4)) + ((Integer) (((Test_Primes.Cons) (Object)(__final_v_3)).value0)))}); } }).get() : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } catch (TcoLoop __tco_ex) { __tco_v_3 = __tco_ex.args[0]; __tco_v1_4 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_2)).apply(((java.util.function.Function<Object, Object>) (Test_Primes.sieve)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object go__go_3 = (java.util.function.Function<Object, Object>) (curr_4) -> (java.util.function.Function<Object, Object>) (acc_5) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_curr_4 = curr_4; Object __tco_acc_5 = acc_5; while(true) { final Object __final_curr_4 = __tco_curr_4; final Object __final_acc_5 = __tco_acc_5; try { return ( ((Boolean) ((((Integer) (__final_curr_4)) < ((Integer) (2))))) ? __final_acc_5 : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_3", new Object[]{(((Integer) (__final_curr_4)) - ((Integer) (1))), new Test_Primes.Cons(__final_curr_4, __final_acc_5)}); } }).get()); } catch (TcoLoop __tco_ex) { __tco_curr_4 = __tco_ex.args[0]; __tco_acc_5 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_3)).apply(dummy_1))).apply(new Test_Primes.Nil()); } }).get())))).apply(0); } }).get())))).get(); } });
}
