public class Test_ArrayOps {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object range = (java.util.function.Function<Object, Object>) (start_0) -> (java.util.function.Function<Object, Object>) (end_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array.rangeImpl)).apply(start_0))).apply(end_1);
public static final Object filterEvens = (java.util.function.Function<Object, Object>) (arr_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array.filterImpl)).apply((java.util.function.Function<Object, Object>) (x_1) -> java.util.Objects.equals(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.intMod)).apply(x_1))).apply(2), 0)))).apply(arr_0);
public static final Object sumEvens = (java.util.function.Function<Object, Object>) (n_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Foldable.foldlArray)).apply(Data_Semiring.intAdd))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array.filterImpl)).apply((java.util.function.Function<Object, Object>) (x_1) -> java.util.Objects.equals(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.intMod)).apply(x_1))).apply(2), 0)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array.rangeImpl)).apply(1))).apply(n_0)));
public static final Object describe = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Array Processing (900 elements):");
public static final Object act = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Bench.opaque)).apply(900); Object dummy_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(((java.util.function.Function<Object, Object>) (Test_ArrayOps.sumEvens)).apply(dummy_1))))).get(); } });
}
