public class Test_Records {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object updateRec = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; Object __tco_v1_1 = v1_1; while(true) { final Object __final_v_0 = __tco_v_0; final Object __final_v1_1 = __tco_v1_1; try { return ( ((Boolean) (java.util.Objects.equals(__final_v_0, 0))) ? __final_v1_1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("updateRec", new Object[]{(((Integer) (__final_v_0)) - ((Integer) (1))), (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>((java.util.LinkedHashMap<String, Object>) __final_v1_1); __map.put("a", (((Integer) (((java.util.LinkedHashMap<String, Object>) __final_v1_1).get("a"))) + ((Integer) (1)))); __map.put("b", (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) __final_v1_1).get("b")); __map.put("c", (((Integer) (((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) __final_v1_1).get("b")).get("c"))) + ((Integer) (2)))); __map.put("d", (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) __final_v1_1).get("b")).get("d")); __map.put("e", (((Integer) (((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) __final_v1_1).get("b")).get("d")).get("e"))) + ((Integer) (3)))); __map.put("f", (((Integer) (((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) __final_v1_1).get("b")).get("d")).get("f"))) + ((Integer) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.intMod)).apply(__final_v_0))).apply(5)))));  return __map; } }).get());  return __map; } }).get());  return __map; } }).get()}); } }).get()); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; __tco_v1_1 = __tco_ex.args[1]; } } } }).get();
public static final Object initial = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("a", 0); __map.put("b", (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("c", 0); __map.put("d", (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("e", 0); __map.put("f", 0);  return __map; } }).get());  return __map; } }).get());  return __map; } }).get();
public static final Object describe = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Deep Record Updates (10k iterations):");
public static final Object act = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Bench.opaque)).apply(10000); Object dummy_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Records.updateRec)).apply(dummy_1))).apply(Test_Records.initial)).get("b")).get("d")).get("f"))))).get(); } });
}
