public class Test_Polymorphism {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object mempty_ = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("mempty_");
public static final Object mappend_ = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("mappend_");
public static final Object polyLoop = (java.util.function.Function<Object, Object>) (dictMonoidish_0) -> (java.util.function.Function<Object, Object>) (n_init_1) -> (java.util.function.Function<Object, Object>) (acc_init_2) -> { Object go__go_3 = (java.util.function.Function<Object, Object>) (v_4) -> (java.util.function.Function<Object, Object>) (v1_5) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_4 = v_4; Object __tco_v1_5 = v1_5; while(true) { final Object __final_v_4 = __tco_v_4; final Object __final_v1_5 = __tco_v1_5; try { return ( ((Boolean) (java.util.Objects.equals(__final_v_4, 0))) ? __final_v1_5 : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_3", new Object[]{(((Integer) (__final_v_4)) - ((Integer) (1))), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoidish_0).get("mappend_"))).apply(__final_v1_5))).apply(((java.util.LinkedHashMap<String, Object>) dictMonoidish_0).get("mempty_"))}); } }).get()); } catch (TcoLoop __tco_ex) { __tco_v_4 = __tco_ex.args[0]; __tco_v1_5 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_3)).apply(n_init_1))).apply(acc_init_2); };
public static final Object intMonoidish = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty_", 1); __map.put("mappend_", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (y_1) -> (((Integer) (x_0)) + ((Integer) (y_1))));  return __map; } }).get();
public static final Object describe = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Polymorphism (10M Type Class Dict Lookups):");
public static final Object act = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Bench.opaque)).apply(10000000); Object dummy_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object go__go_2 = (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_3 = v_3; Object __tco_v1_4 = v1_4; while(true) { final Object __final_v_3 = __tco_v_3; final Object __final_v1_4 = __tco_v1_4; try { return ( ((Boolean) (java.util.Objects.equals(__final_v_3, 0))) ? __final_v1_4 : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_2", new Object[]{(((Integer) (__final_v_3)) - ((Integer) (1))), (((Integer) (__final_v1_4)) + ((Integer) (1)))}); } }).get()); } catch (TcoLoop __tco_ex) { __tco_v_3 = __tco_ex.args[0]; __tco_v1_4 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_2)).apply(dummy_1))).apply(0); } }).get())))).get(); } });
}
