public class Test_StateMonad {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object State = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object runState = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (v_0)).apply(s_1);
public static final Object put = (java.util.function.Function<Object, Object>) (s_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("val", Data_Unit.unit); __map.put("state", s_0);  return __map; } }).get();
public static final Object pureState = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("val", a_0); __map.put("state", s_1);  return __map; } }).get();
public static final Object get = (java.util.function.Function<Object, Object>) (s_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("val", s_0); __map.put("state", s_0);  return __map; } }).get();
public static final Object describe = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("State Monad (1.2k Binds, 60 Stack Depth):");
public static final Object bindState = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (s_2) -> { Object r1_3 = ((java.util.function.Function<Object, Object>) (v_0)).apply(s_2); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (g_1)).apply(((java.util.LinkedHashMap<String, Object>) r1_3).get("val")))).apply(((java.util.LinkedHashMap<String, Object>) r1_3).get("state")); };
public static final Object modify = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("val", Data_Unit.unit); __map.put("state", ((java.util.function.Function<Object, Object>) (f_0)).apply(s_1));  return __map; } }).get();
public static final Object chainModifications = (java.util.function.Function<Object, Object>) (v_0) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; while(true) { final Object __final_v_0 = __tco_v_0; try { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Test_StateMonad.modify)).apply((java.util.function.Function<Object, Object>) (x_1) -> (((Integer) (x_1)) + ((Integer) (1)))); return ( ((Boolean) (java.util.Objects.equals(__final_v_0, 0))) ? (java.util.function.Function<Object, Object>) (s_1) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("val", Data_Unit.unit); __map.put("state", s_1);  return __map; } }).get() : (java.util.function.Function<Object, Object>) (s_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_StateMonad.chainModifications)).apply((((Integer) (v_0)) - ((Integer) (1)))))).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(s_2)).get("state"))); } }).get(); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; } } } }).get();
public static final Object runManyTimes = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; Object __tco_v1_1 = v1_1; while(true) { final Object __final_v_0 = __tco_v_0; final Object __final_v1_1 = __tco_v1_1; try { return ( ((Boolean) (java.util.Objects.equals(__final_v_0, 0))) ? __final_v1_1 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_StateMonad.runManyTimes)).apply((((Integer) (__final_v_0)) - ((Integer) (1)))))).apply((((Integer) (__final_v1_1)) + ((Integer) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_StateMonad.chainModifications)).apply(60))).apply(0)).get("state")))))); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; __tco_v1_1 = __tco_ex.args[1]; } } } }).get();
public static final Object act = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Bench.opaque)).apply(20); Object dummy_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_StateMonad.runManyTimes)).apply(dummy_1))).apply(0))))).get(); } });
}
