public class Test_ListOps {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final class Nil {
            
            public Nil() {
                
            }
        }
public static final class Cons {
            public final Object value0;
            public final Object value1;
            public Cons(Object value0, Object value1) {
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object Nil = new Test_ListOps.Nil();
public static final Object Cons = (java.util.function.Function<Object, Object>) (value0) -> (java.util.function.Function<Object, Object>) (value1) -> new Test_ListOps.Cons(value0, value1);
public static final Object range = (java.util.function.Function<Object, Object>) (start_0) -> (java.util.function.Function<Object, Object>) (end_1) -> { Object go__go_2 = (java.util.function.Function<Object, Object>) (curr_3) -> (java.util.function.Function<Object, Object>) (acc_4) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_curr_3 = curr_3; Object __tco_acc_4 = acc_4; while(true) { final Object __final_curr_3 = __tco_curr_3; final Object __final_acc_4 = __tco_acc_4; try { return ( ((Boolean) ((((Integer) (__final_curr_3)) < ((Integer) (start_0))))) ? __final_acc_4 : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_2", new Object[]{(((Integer) (__final_curr_3)) - ((Integer) (1))), new Test_ListOps.Cons(__final_curr_3, __final_acc_4)}); } }).get()); } catch (TcoLoop __tco_ex) { __tco_curr_3 = __tco_ex.args[0]; __tco_acc_4 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_2)).apply(end_1))).apply(new Test_ListOps.Nil()); };
public static final Object foldl = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (v2_2) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; Object __tco_v1_1 = v1_1; Object __tco_v2_2 = v2_2; while(true) { final Object __final_v_0 = __tco_v_0; final Object __final_v1_1 = __tco_v1_1; final Object __final_v2_2 = __tco_v2_2; try { return ( ((Boolean) ((__final_v2_2 instanceof Test_ListOps.Nil))) ? __final_v1_1 : ( ((Boolean) ((__final_v2_2 instanceof Test_ListOps.Cons))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_ListOps.foldl)).apply(__final_v_0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__final_v_0)).apply(__final_v1_1))).apply(((Test_ListOps.Cons) (Object)(__final_v2_2)).value0)))).apply(((Test_ListOps.Cons) (Object)(__final_v2_2)).value1) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; __tco_v1_1 = __tco_ex.args[1]; __tco_v2_2 = __tco_ex.args[2]; } } } }).get();
public static final Object filterEvens = (java.util.function.Function<Object, Object>) (lst_0) -> { Object go__go_1 = (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_2 = v_2; Object __tco_v1_3 = v1_3; while(true) { final Object __final_v_2 = __tco_v_2; final Object __final_v1_3 = __tco_v1_3; try { return ( ((Boolean) ((__final_v_2 instanceof Test_ListOps.Nil))) ? __final_v1_3 : ( ((Boolean) ((__final_v_2 instanceof Test_ListOps.Cons))) ? ( ((Boolean) (java.util.Objects.equals(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.intMod)).apply(((Test_ListOps.Cons) (Object)(__final_v_2)).value0))).apply(2), 0))) ? (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_1", new Object[]{((Test_ListOps.Cons) (Object)(__final_v_2)).value1, new Test_ListOps.Cons(((Test_ListOps.Cons) (Object)(__final_v_2)).value0, __final_v1_3)}); } }).get() : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_1", new Object[]{((Test_ListOps.Cons) (Object)(__final_v_2)).value1, __final_v1_3}); } }).get()) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } catch (TcoLoop __tco_ex) { __tco_v_2 = __tco_ex.args[0]; __tco_v1_3 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_1)).apply(lst_0))).apply(new Test_ListOps.Nil()); };
public static final Object sumEvens = (java.util.function.Function<Object, Object>) (n_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_ListOps.foldl)).apply(Data_Semiring.intAdd))).apply(0))).apply(((java.util.function.Function<Object, Object>) (Test_ListOps.filterEvens)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object go__go_1 = (java.util.function.Function<Object, Object>) (curr_2) -> (java.util.function.Function<Object, Object>) (acc_3) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_curr_2 = curr_2; Object __tco_acc_3 = acc_3; while(true) { final Object __final_curr_2 = __tco_curr_2; final Object __final_acc_3 = __tco_acc_3; try { return ( ((Boolean) ((((Integer) (__final_curr_2)) < ((Integer) (1))))) ? __final_acc_3 : (new java.util.function.Supplier<Object>() { public Object get() { throw new TcoLoop("go__go_1", new Object[]{(((Integer) (__final_curr_2)) - ((Integer) (1))), new Test_ListOps.Cons(__final_curr_2, __final_acc_3)}); } }).get()); } catch (TcoLoop __tco_ex) { __tco_curr_2 = __tco_ex.args[0]; __tco_acc_3 = __tco_ex.args[1]; } } } }).get(); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_1)).apply(n_0))).apply(new Test_ListOps.Nil()); } }).get()));
public static final Object describe = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("List Processing (900 elements):");
public static final Object act = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Bench.opaque)).apply(900); Object dummy_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(((java.util.function.Function<Object, Object>) (Test_ListOps.sumEvens)).apply(dummy_1))))).get(); } });
}
