public class Test_Church {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object zeroC = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (x_1) -> x_1;
public static final Object toInt = (java.util.function.Function<Object, Object>) (n_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (n_0)).apply((java.util.function.Function<Object, Object>) (x_1) -> (((Integer) (x_1)) + ((Integer) (1)))))).apply(0);
public static final Object succC = (java.util.function.Function<Object, Object>) (n_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (f_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (n_0)).apply(f_1))).apply(x_2));
public static final Object mulC = (java.util.function.Function<Object, Object>) (m_0) -> (java.util.function.Function<Object, Object>) (n_1) -> (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (m_0)).apply(((java.util.function.Function<Object, Object>) (n_1)).apply(f_2)))).apply(x_3);
public static final Object fromInt = (java.util.function.Function<Object, Object>) (v_0) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; while(true) { final Object __final_v_0 = __tco_v_0; try { return ( ((Boolean) (java.util.Objects.equals(__final_v_0, 0))) ? Test_Church.zeroC : (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Test_Church.fromInt)).apply((((Integer) (__final_v_0)) - ((Integer) (1)))); return (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (f_2)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1)).apply(f_2))).apply(x_3)); } }).get()); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; } } } }).get();
public static final Object describe = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Church Numerals (100k Closure Applications):");
public static final Object c10 = (java.util.function.Function<Object, Object>) (n_0) -> ((java.util.function.Function<Object, Object>) (Test_Church.fromInt)).apply(n_0);
public static final Object c100 = (java.util.function.Function<Object, Object>) (n_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Test_Church.fromInt)).apply(n_0); Object __local_var_2 = ((java.util.function.Function<Object, Object>) (Test_Church.fromInt)).apply(n_0); return (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (x_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1)).apply(((java.util.function.Function<Object, Object>) (__local_var_2)).apply(f_3)))).apply(x_4); };
public static final Object c10k = (java.util.function.Function<Object, Object>) (n_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Test_Church.c100)).apply(n_0); Object __local_var_2 = ((java.util.function.Function<Object, Object>) (Test_Church.c100)).apply(n_0); return (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (x_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1)).apply(((java.util.function.Function<Object, Object>) (__local_var_2)).apply(f_3)))).apply(x_4); };
public static final Object c100k = (java.util.function.Function<Object, Object>) (n_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Test_Church.c10k)).apply(n_0); Object __local_var_2 = ((java.util.function.Function<Object, Object>) (Test_Church.fromInt)).apply(n_0); return (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (x_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1)).apply(((java.util.function.Function<Object, Object>) (__local_var_2)).apply(f_3)))).apply(x_4); };
public static final Object addC = (java.util.function.Function<Object, Object>) (m_0) -> (java.util.function.Function<Object, Object>) (n_1) -> (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (m_0)).apply(f_2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (n_1)).apply(f_2))).apply(x_3));
public static final Object act = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Bench.opaque)).apply(10); Object dummy_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Church.c100k)).apply(dummy_1))).apply((java.util.function.Function<Object, Object>) (x_2) -> (((Integer) (x_2)) + ((Integer) (1)))))).apply(0))))).get(); } });
}
