#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Bench::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Monad::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Boolean::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Monoid::*;
use Purs_Data_Ord::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Effect::*;
use Purs_Effect_Console::*;
use Purs_Record_Unsafe::*;
use Purs_Type_Proxy::*;
use Purs_Bench::*;
use Purs_Control_Applicative::*;
use Purs_Control_Bind::*;
use Purs_Data_Ring::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Unit::*;
use Purs_Effect::*;
use Purs_Effect_Console::*;
use Purs_Record_Unsafe::*;

// Code generated by purust for module Test_StateMonad



pub fn Test_StateMonad_State(mut a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Abs(..., Local(...)))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>| -> purust_core::Func1<crate::UnknownType, crate::UnknownType> {
    let mut purs_local_0 = _a0;
    purs_local_0
} as fn(purust_core::Func1<crate::UnknownType, crate::UnknownType>) -> purust_core::Func1<crate::UnknownType, crate::UnknownType>)).clone(); move |mut _a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut _a1: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}

pub fn Test_StateMonad_runState(mut purs_local_0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut purs_local_1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(App(Typed(Local(...))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_0)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1)
}

pub fn Test_StateMonad_put(mut purs_local_0: crate::UnknownType, mut purs_local_1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Abs(..., Typed(Lit))))))))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */purust_core::Value::Record_state_val(perceus_ptr::PerceusPtr::new(Record_state_val { val: Some(crate::mk_unit(/* Typed () <- () : Var(...) */Data_Unit_unit())), state: Some(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_0), ..Default::default() }))
}

pub fn Test_StateMonad_pureState(mut purs_local_0: crate::UnknownType, mut purs_local_1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Abs(..., Typed(Lit))))))))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */purust_core::Value::Record_state_val(perceus_ptr::PerceusPtr::new(Record_state_val { val: Some(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_0), state: Some(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1), ..Default::default() }))
}

pub fn Test_StateMonad_get(mut purs_local_0: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Typed(Typed(Abs(..., Typed(Lit))))))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */purust_core::Value::Record_state_val(perceus_ptr::PerceusPtr::new(Record_state_val { val: Some(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_0.clone()), state: Some(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_0), ..Default::default() }))
}

pub fn Test_StateMonad_describe() -> crate::UnknownType {
    // AST: Typed(Typed(App(Var(...))))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<crate::UnknownType> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Test_StateMonad_describe", || {
/* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */Effect_Console_log(/* Typed String <- String : Lit */String::from("State Monad (1.2k Binds, 60 Stack Depth):"))
}).clone())
}

pub fn Test_StateMonad_bindState(mut purs_local_0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut purs_local_1: purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType>, mut purs_local_2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Let(...))))))))))))
{
    let mut purs_local_3 = /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_0)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2);
    /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_1)(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */(purs_local_3.clone()).get_val(), /* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */(purs_local_3).get_state())
}
}

pub fn Test_StateMonad_modify(mut purs_local_0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut purs_local_1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Typed(Typed(Typed(Typed(Lit))))))))))))))
/* Typed crate::UnknownType <- crate::UnknownType : Lit */purust_core::Value::Record_state_val(perceus_ptr::PerceusPtr::new(Record_state_val { val: Some(crate::mk_unit(/* Typed () <- () : Var(...) */Data_Unit_unit())), state: Some(/* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_0)(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(App(Var(...))) */(Test_StateMonad_get(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1)).get_val())), ..Default::default() }))
}

pub fn Test_StateMonad_chainModifications(mut a0: i64, mut a1: i64) -> crate::UnknownType {
    // AST: Typed(Abs(..., Typed(Branch(...))))
    loop {
        break {
fn Test_StateMonad_chainModifications(mut purs_local_0: i64) -> purust_core::Func1<i64, crate::UnknownType> {
    loop {
        break /* Typed purust_core::Func1<i64, crate::UnknownType> <- purust_core::Func1<i64, crate::UnknownType> : Branch(...) */if (/* Typed i64 <- i64 : Local(...) */purs_local_0.clone() == 0) {
        /* Typed Abs */purust_core::Func1::Static(|mut _a0: i64| -> crate::UnknownType {
    let mut purs_local_1 = _a0;
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */purust_core::Value::Record_state_val(perceus_ptr::PerceusPtr::new(Record_state_val { val: Some(crate::mk_unit(/* Typed crate::UnknownType <- () : Var(...) */Data_Unit_unit())), state: Some(crate::mk_int(/* Typed i64 <- i64 : Local(...) */purs_local_1)), ..Default::default() }))
} as fn(i64) -> crate::UnknownType)
    } else {
        {
    let mut purs_local_1 = {
        let mut eval_arg_0 = purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Static(|mut _a0: i64| -> i64 {
    let mut purs_local_1 = _a0;
    /* Typed i64 <- i64 : PrimOp(...) */(purs_local_1 + 1)
} as fn(i64) -> i64)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { crate::mk_int(_f((_a0).unwrap_int())) } }));
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Test_StateMonad_modify(eval_arg_0, eta_0.clone())
}))
};
    /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: i64| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    /* Typed crate::UnknownType <- crate::UnknownType : App(Var(...)) */(Test_StateMonad_chainModifications(/* Typed i64 <- i64 : PrimOp(...) */(/* Typed i64 <- i64 : Local(...) */purs_local_0.clone() - /* Typed i64 <- i64 : Lit */1)))(/* Typed i64 <- crate::UnknownType : Accessor(App(Local(...))) */(((purs_local_1)(crate::mk_int(/* Typed i64 <- i64 : Local(...) */purs_local_2))).get_state()).unwrap_int())
}))
}
    };
    }
}
(Test_StateMonad_chainModifications(a0.clone()))(a1.clone())
};
    }
}

pub fn Test_StateMonad_runManyTimes(mut purs_local_0: i64, mut purs_local_1: i64) -> i64 {
    // AST: Typed(Abs(..., Typed(Abs(..., Typed(Branch(...))))))
    loop {
        break /* Typed i64 <- i64 : Branch(...) */if (/* Typed i64 <- i64 : Local(...) */purs_local_0.clone() == 0) {
        /* Typed i64 <- i64 : Local(...) */purs_local_1
    } else {
        {
        let _tco_temp_0 = /* Typed i64 <- i64 : PrimOp(...) */(/* Typed i64 <- i64 : Local(...) */purs_local_0 - /* Typed i64 <- i64 : Lit */1);
        let _tco_temp_1 = /* Typed i64 <- i64 : PrimOp(...) */(purs_local_1 + ((Test_StateMonad_chainModifications(/* Typed i64 <- i64 : Lit */60, /* Typed i64 <- i64 : Lit */0)).get_state()).unwrap_int());
        purs_local_0 = _tco_temp_0;
        purs_local_1 = _tco_temp_1;
        continue;
    }
    };
    }
}

pub fn Test_StateMonad_act() -> crate::UnknownType {
    // AST: Typed(Let(...))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<crate::UnknownType> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Test_StateMonad_act", || {
{
    purust_core::Value::Func1(purust_core::Func1::Static(|mut _u: crate::UnknownType| -> crate::UnknownType {
        {
    let mut purs_local_0 = Bench_opaque(crate::mk_int(/* Typed i64 <- i64 : Lit */20));
    /* Typed crate::UnknownType <- crate::UnknownType : EffectBind */{
    let mut purs_local_1 = {
        let _val_eval = purs_local_0;
        if let purust_core::Value::Func1(f) = &_val_eval {
            f(purust_core::Value::Unit)
        } else if let purust_core::Value::Record_a(r) = &_val_eval {
            if r.call.is_some() {
                r.call.clone().unwrap()(purust_core::Value::Unit)
            } else {
                _val_eval
            }
        } else {
            _val_eval
        }
    };
    /* Typed crate::UnknownType <- crate::UnknownType : EffectPure */purust_core::Value::String(Data_Show_showIntImpl(/* Typed i64 <- i64 : App(Var(...)) */Test_StateMonad_runManyTimes(/* Typed i64 <- crate::UnknownType : Local(...) */(purs_local_1).unwrap_int(), /* Typed i64 <- i64 : Lit */0)))
}
}
    } as fn(crate::UnknownType) -> crate::UnknownType))
}
}).clone())
}





