% Generated by purerl version 0.0.24
-module(data_predicate@ps).
-export(['Predicate'/0, newtypePredicate/0, heytingAlgebraPredicate/0, contravariantPredicate/0, booleanAlgebraPredicate/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./data_predicate.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Predicate.purs", 0).
-spec compose() -> any().
compose() -> (?MEMOIZE((control_semigroupoid@ps:compose((control_semigroupoid@ps:semigroupoidFn()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Predicate.purs", 0).
-spec compose(any(),any()) -> any().
compose(_@2,_@3) -> (((compose())(_@2))(_@3)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Predicate.purs", 9).
-spec 'Predicate'() -> any().
'Predicate'() -> fun (X) ->
  X
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Predicate.purs", 11).
-spec newtypePredicate() -> any().
newtypePredicate() -> #{'Coercible0'=>fun (_) ->
  undefined
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Predicate.purs", 13).
-spec heytingAlgebraPredicate() -> any().
heytingAlgebraPredicate() -> ((data_heytingAlgebra@ps:heytingAlgebraFunction())((data_heytingAlgebra@ps:heytingAlgebraBoolean()))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Predicate.purs", 17).
-spec contravariantPredicate() -> any().
contravariantPredicate() -> #{cmap=>fun (F) ->
  fun (V) ->
    case { F, V } of
      ({ _@4, _@5 }) -> (compose(_@5, _@4))
    end
  end
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/contravariant/ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38/src/Data/Predicate.purs", 15).
-spec booleanAlgebraPredicate() -> any().
booleanAlgebraPredicate() -> ((data_booleanAlgebra@ps:booleanAlgebraFn())((data_booleanAlgebra@ps:booleanAlgebraBoolean()))).
