[<AutoOpen>]
module PureScript_Control_Biapply

open System
open System.Collections.Generic

let Control_Biapply_Biapplyusd_Dict  = (box (fun (x: obj) -> (box x)))

let Control_Biapply_biapplyTuple  = (sharpurs_apply (box ((box Control_Biapply_Biapplyusd_Dict))) (box ((box ((Map.add "biapply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Tuple_Tupleusd_Ctor(f, g), Data_Tuple_Tupleusd_Ctor(a, b)) -> ((box (Data_Tuple_Tupleusd_Ctor((sharpurs_apply (box ((box f))) (box ((box a)))), (sharpurs_apply (box ((box g))) (box ((box b))))))))))))))) (Map.add "Bifunctor0" (box ((box (fun (usd__unused: obj) -> (box Data_Bifunctor_bifunctorTuple))))) Map.empty)))))))

let Control_Biapply_biapply  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "biapply" (unbox<Map<string, obj>> ((box v))))))))

let Control_Biapply_biapplyFirst  = (box (fun (dictBiapply: obj) -> (let Bifunctor0 = (sharpurs_apply (box ((Map.find "Bifunctor0" (unbox<Map<string, obj>> ((box dictBiapply)))))) (box ((box Prim_undefined)))) in (box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapply_biapply))) (box ((box dictBiapply)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box Bifunctor0)))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn)))))))))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))))))))))))) (box ((box a))))))))) (box ((box b)))))))))))

let Control_Biapply_biapplySecond  = (box (fun (dictBiapply: obj) -> (let Bifunctor0 = (sharpurs_apply (box ((Map.find "Bifunctor0" (unbox<Map<string, obj>> ((box dictBiapply)))))) (box ((box Prim_undefined)))) in (box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapply_biapply))) (box ((box dictBiapply)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box Bifunctor0)))))) (box ((box Data_Function_const)))))) (box ((box Data_Function_const))))))))) (box ((box a))))))))) (box ((box b)))))))))))

let Control_Biapply_bilift2  = (box (fun (dictBiapply: obj) -> (let Bifunctor0 = (sharpurs_apply (box ((Map.find "Bifunctor0" (unbox<Map<string, obj>> ((box dictBiapply)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapply_biapply))) (box ((box dictBiapply)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box Bifunctor0)))))) (box ((box f)))))) (box ((box g))))))))) (box ((box a))))))))) (box ((box b)))))))))))))))

let Control_Biapply_bilift3  = (box (fun (dictBiapply: obj) -> (let Bifunctor0 = (sharpurs_apply (box ((Map.find "Bifunctor0" (unbox<Map<string, obj>> ((box dictBiapply)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapply_biapply))) (box ((box dictBiapply)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapply_biapply))) (box ((box dictBiapply)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box Bifunctor0)))))) (box ((box f)))))) (box ((box g))))))))) (box ((box a))))))))) (box ((box b))))))))) (box ((box c)))))))))))))))))
