[<AutoOpen>]
module PureScript_Control_Monad_Rec_Class

open System
open System.Collections.Generic

type Control_Monad_Rec_Class_Step =
  | Control_Monad_Rec_Class_Loopusd_Ctor of obj
  | Control_Monad_Rec_Class_Doneusd_Ctor of obj

let Control_Monad_Rec_Class_Loop  = (box ((fun (usd__arg1: obj) -> (box (Control_Monad_Rec_Class_Loopusd_Ctor(usd__arg1))))))

let Control_Monad_Rec_Class_Done  = (box ((fun (usd__arg1: obj) -> (box (Control_Monad_Rec_Class_Doneusd_Ctor(usd__arg1))))))

let Control_Monad_Rec_Class_MonadRecusd_Dict  = (box (fun (x: obj) -> (box x)))

let Control_Monad_Rec_Class_tailRecM  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "tailRecM" (unbox<Map<string, obj>> ((box v))))))))

let Control_Monad_Rec_Class_tailRecM2  = (box (fun (dictMonadRec: obj) -> (box (fun (f: obj) -> (box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRecM))) (box ((box dictMonadRec)))))) (box ((box (fun (o: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((Map.find "a" (unbox<Map<string, obj>> ((box o))))))))) (box ((Map.find "b" (unbox<Map<string, obj>> ((box o)))))))))))))) (box ((box ((Map.add "a" (box ((box a))) (Map.add "b" (box ((box b))) Map.empty)))))))))))))))

let Control_Monad_Rec_Class_tailRecM3  = (box (fun (dictMonadRec: obj) -> (box (fun (f: obj) -> (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRecM))) (box ((box dictMonadRec)))))) (box ((box (fun (o: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((Map.find "a" (unbox<Map<string, obj>> ((box o))))))))) (box ((Map.find "b" (unbox<Map<string, obj>> ((box o))))))))) (box ((Map.find "c" (unbox<Map<string, obj>> ((box o)))))))))))))) (box ((box ((Map.add "a" (box ((box a))) (Map.add "b" (box ((box b))) (Map.add "c" (box ((box c))) Map.empty))))))))))))))))))

let Control_Monad_Rec_Class_untilJust  = (box (fun (dictMonadRec: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadRec)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_applyFlipped))) (box ((box Data_Unit_unit)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRecM))) (box ((box dictMonadRec)))))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_mapFlipped))) (box ((box Functor0)))))) (box ((box m)))))) (box ((box (fun (v1: obj) -> (match ((unbox ((box v1)))) with | Data_Maybe_Nothingusd_Ctor -> ((box (Control_Monad_Rec_Class_Loopusd_Ctor((box Data_Unit_unit))))) | Data_Maybe_Justusd_Ctor(x) -> ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box x))))))))))))))))))))))))

let Control_Monad_Rec_Class_whileJust  = (box (fun (dictMonoid: obj) -> (let Semigroup0 = (sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined)))) in (box (fun (dictMonadRec: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadRec)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (m: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_applyFlipped))) (box ((sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRecM))) (box ((box dictMonadRec)))))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_mapFlipped))) (box ((box Functor0)))))) (box ((box m)))))) (box ((box (fun (v1: obj) -> (match ((unbox ((box v1)))) with | Data_Maybe_Nothingusd_Ctor -> ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box v))))) | Data_Maybe_Justusd_Ctor(x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box ((fun (usd__arg1: obj) -> (box (Control_Monad_Rec_Class_Loopusd_Ctor(usd__arg1))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Semigroup0)))))) (box ((box v)))))) (box ((box x))))))))))))))))))))))))))))))

let Control_Monad_Rec_Class_tailRec  = (box (fun (f: obj) -> (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (v: obj) : obj = ((match ((unbox ((box v)))) with | Control_Monad_Rec_Class_Loopusd_Ctor(a) -> ((go_tco ((sharpurs_apply (box ((box f))) (box ((box a))))))) | Control_Monad_Rec_Class_Doneusd_Ctor(b) -> ((box b)))) 
                                                                                                                                                                                                        and go = box ((fun (v: obj) -> go_tco v)) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box go)))))) (box ((box f))))
                                                                                                                                                                                                        )))

let Control_Monad_Rec_Class_tailRec2  = (box (fun (f: obj) -> (box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRec))) (box ((box (fun (o: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((Map.find "a" (unbox<Map<string, obj>> ((box o))))))))) (box ((Map.find "b" (unbox<Map<string, obj>> ((box o)))))))))))))) (box ((box ((Map.add "a" (box ((box a))) (Map.add "b" (box ((box b))) Map.empty)))))))))))))

let Control_Monad_Rec_Class_tailRec3  = (box (fun (f: obj) -> (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRec))) (box ((box (fun (o: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((Map.find "a" (unbox<Map<string, obj>> ((box o))))))))) (box ((Map.find "b" (unbox<Map<string, obj>> ((box o))))))))) (box ((Map.find "c" (unbox<Map<string, obj>> ((box o)))))))))))))) (box ((box ((Map.add "a" (box ((box a))) (Map.add "b" (box ((box b))) (Map.add "c" (box ((box c))) Map.empty))))))))))))))))

let Control_Monad_Rec_Class_monadRecMaybe  = (sharpurs_apply (box ((box Control_Monad_Rec_Class_MonadRecusd_Dict))) (box ((box ((Map.add "tailRecM" (box ((box (fun (f: obj) -> (box (fun (a0: obj) -> (let g = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Maybe_Nothingusd_Ctor -> ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box Data_Maybe_Nothingusd_Ctor))))) | Data_Maybe_Justusd_Ctor(Unbox(Control_Monad_Rec_Class_Loopusd_Ctor(a))) -> ((box (Control_Monad_Rec_Class_Loopusd_Ctor((sharpurs_apply (box ((box f))) (box ((box a)))))))) | Data_Maybe_Justusd_Ctor(Unbox(Control_Monad_Rec_Class_Doneusd_Ctor(b))) -> ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box (Data_Maybe_Justusd_Ctor((box b))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRec))) (box ((box g)))))) (box ((sharpurs_apply (box ((box f))) (box ((box a0)))))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_monadMaybe))))) Map.empty)))))))

let Control_Monad_Rec_Class_monadRecIdentity  = (sharpurs_apply (box ((box Control_Monad_Rec_Class_MonadRecusd_Dict))) (box ((box ((Map.add "tailRecM" (box ((box (fun (f: obj) -> (let runIdentity = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | x -> ((box x))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Identity_Identity)))))) (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRec))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box runIdentity)))))) (box ((box f))))))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box Data_Identity_monadIdentity))))) Map.empty)))))))

let Control_Monad_Rec_Class_monadRecFunction  = (sharpurs_apply (box ((box Control_Monad_Rec_Class_MonadRecusd_Dict))) (box ((box ((Map.add "tailRecM" (box ((box (fun (f: obj) -> (box (fun (a0: obj) -> (box (fun (e: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRec))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box a)))))) (box ((box e))))))))))) (box ((box a0)))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box Control_Monad_monadFn))))) Map.empty)))))))

let Control_Monad_Rec_Class_monadRecEither  = (sharpurs_apply (box ((box Control_Monad_Rec_Class_MonadRecusd_Dict))) (box ((box ((Map.add "tailRecM" (box ((box (fun (f: obj) -> (box (fun (a0: obj) -> (let g = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Either_Leftusd_Ctor(e) -> ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box (Data_Either_Leftusd_Ctor((box e)))))))) | Data_Either_Rightusd_Ctor(Unbox(Control_Monad_Rec_Class_Loopusd_Ctor(a))) -> ((box (Control_Monad_Rec_Class_Loopusd_Ctor((sharpurs_apply (box ((box f))) (box ((box a)))))))) | Data_Either_Rightusd_Ctor(Unbox(Control_Monad_Rec_Class_Doneusd_Ctor(b))) -> ((box (Control_Monad_Rec_Class_Doneusd_Ctor((box (Data_Either_Rightusd_Ctor((box b))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRec))) (box ((box g)))))) (box ((sharpurs_apply (box ((box f))) (box ((box a0)))))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box Data_Either_monadEither))))) Map.empty)))))))

let Control_Monad_Rec_Class_monadRecEffect  = (sharpurs_apply (box ((box Control_Monad_Rec_Class_MonadRecusd_Dict))) (box ((box ((Map.add "tailRecM" (box ((box (fun (f: obj) -> (box (fun (a: obj) -> (let fromDone = (sharpurs_apply (box ((box Partial_Unsafe_unsafePartial))) (box ((box (fun (usd__unused: obj) -> (box (fun (v: obj) -> (sharpurs_apply (box ((box (fun (usd__unused: obj) -> (match ((unbox ((box v)))) with | Control_Monad_Rec_Class_Doneusd_Ctor(b) -> ((box b))))))) (box ((box Prim_undefined))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Effect_bindEffect)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bindFlipped))) (box ((box Effect_bindEffect)))))) (box ((box Effect_Ref_new)))))) (box ((sharpurs_apply (box ((box f))) (box ((box a)))))))))))) (box ((box (fun (r: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_discard))) (box ((box Control_Bind_discardUnit)))))) (box ((box Effect_bindEffect)))))) (box ((sharpurs_apply (box ((box Effect_untilE))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Effect_bindEffect)))))) (box ((sharpurs_apply (box ((box Effect_Ref_read))) (box ((box r))))))))) (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Control_Monad_Rec_Class_Loopusd_Ctor(a_prime) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Effect_bindEffect)))))) (box ((sharpurs_apply (box ((box f))) (box ((box a_prime))))))))) (box ((box (fun (e: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Effect_bindEffect)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Effect_Ref_write))) (box ((box e)))))) (box ((box r))))))))) (box ((box (fun (usd__unused: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Effect_applicativeEffect)))))) (box ((box false))))))))))))))) | Control_Monad_Rec_Class_Doneusd_Ctor(_) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Effect_applicativeEffect)))))) (box ((box true))))))))))))))))))) (box ((box (fun (usd__unused: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Effect_functorEffect)))))) (box ((box fromDone)))))) (box ((sharpurs_apply (box ((box Effect_Ref_read))) (box ((box r)))))))))))))))))))))))) (Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box Effect_monadEffect))))) Map.empty)))))))

let Control_Monad_Rec_Class_loop3  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (fun (c: obj) -> (box (Control_Monad_Rec_Class_Loopusd_Ctor((box ((Map.add "a" (box ((box a))) (Map.add "b" (box ((box b))) (Map.add "c" (box ((box c))) Map.empty))))))))))))))

let Control_Monad_Rec_Class_loop2  = (box (fun (a: obj) -> (box (fun (b: obj) -> (box (Control_Monad_Rec_Class_Loopusd_Ctor((box ((Map.add "a" (box ((box a))) (Map.add "b" (box ((box b))) Map.empty)))))))))))

let Control_Monad_Rec_Class_functorStep  = (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (m: obj) -> (match ((unbox ((box m)))) with | Control_Monad_Rec_Class_Loopusd_Ctor(v) -> ((box (Control_Monad_Rec_Class_Loopusd_Ctor((box v))))) | Control_Monad_Rec_Class_Doneusd_Ctor(v) -> ((box (Control_Monad_Rec_Class_Doneusd_Ctor((sharpurs_apply (box ((box f))) (box ((box v))))))))))))))) Map.empty))))))

let Control_Monad_Rec_Class_forever  = (box (fun (dictMonadRec: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadRec)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (ma: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRecM))) (box ((box dictMonadRec)))))) (box ((box (fun (u: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_voidRight))) (box ((box Functor0)))))) (box ((box (Control_Monad_Rec_Class_Loopusd_Ctor((box u))))))))) (box ((box ma))))))))))) (box ((box Data_Unit_unit)))))))))

let Control_Monad_Rec_Class_bifunctorStep  = (sharpurs_apply (box ((box Data_Bifunctor_Bifunctorusd_Dict))) (box ((box ((Map.add "bimap" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (box (fun (v2: obj) -> (match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))))) with | (f, _, Control_Monad_Rec_Class_Loopusd_Ctor(a)) -> ((box (Control_Monad_Rec_Class_Loopusd_Ctor((sharpurs_apply (box ((box f))) (box ((box a)))))))) | (_, g, Control_Monad_Rec_Class_Doneusd_Ctor(b)) -> ((box (Control_Monad_Rec_Class_Doneusd_Ctor((sharpurs_apply (box ((box g))) (box ((box b))))))))))))))))) Map.empty))))))
