[<AutoOpen>]
module PureScript_Data_Semiring_Generic

open System
open System.Collections.Generic

let Data_Semiring_Generic_GenericSemiringusd_Dict  = (box (fun (x: obj) -> (box x)))

let Data_Semiring_Generic_genericZero_prime  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "genericZero'" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semiring_Generic_genericZero  = (box (fun (dictGeneric: obj) -> (box (fun (dictGenericSemiring: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Generic_Rep_to))) (box ((box dictGeneric)))))) (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericZero_prime))) (box ((box dictGenericSemiring)))))))))))

let Data_Semiring_Generic_genericSemiringNoArguments  = (sharpurs_apply (box ((box Data_Semiring_Generic_GenericSemiringusd_Dict))) (box ((box ((Map.add "genericAdd'" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (box Data_Generic_Rep_NoArgumentsusd_Ctor))))))) (Map.add "genericZero'" (box ((box Data_Generic_Rep_NoArgumentsusd_Ctor))) (Map.add "genericMul'" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (box Data_Generic_Rep_NoArgumentsusd_Ctor))))))) (Map.add "genericOne'" (box ((box Data_Generic_Rep_NoArgumentsusd_Ctor))) Map.empty)))))))))

let Data_Semiring_Generic_genericSemiringArgument  = (box (fun (dictSemiring: obj) -> (sharpurs_apply (box ((box Data_Semiring_Generic_GenericSemiringusd_Dict))) (box ((box ((Map.add "genericAdd'" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (x, y) -> ((sharpurs_apply (box ((box Data_Generic_Rep_Argument))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_add))) (box ((box dictSemiring)))))) (box ((box x)))))) (box ((box y))))))))))))))) (Map.add "genericZero'" (box ((sharpurs_apply (box ((box Data_Generic_Rep_Argument))) (box ((sharpurs_apply (box ((box Data_Semiring_zero))) (box ((box dictSemiring))))))))) (Map.add "genericMul'" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (x, y) -> ((sharpurs_apply (box ((box Data_Generic_Rep_Argument))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_mul))) (box ((box dictSemiring)))))) (box ((box x)))))) (box ((box y))))))))))))))) (Map.add "genericOne'" (box ((sharpurs_apply (box ((box Data_Generic_Rep_Argument))) (box ((sharpurs_apply (box ((box Data_Semiring_one))) (box ((box dictSemiring))))))))) Map.empty)))))))))))

let Data_Semiring_Generic_genericOne_prime  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "genericOne'" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semiring_Generic_genericOne  = (box (fun (dictGeneric: obj) -> (box (fun (dictGenericSemiring: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Generic_Rep_to))) (box ((box dictGeneric)))))) (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericOne_prime))) (box ((box dictGenericSemiring)))))))))))

let Data_Semiring_Generic_genericMul_prime  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "genericMul'" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semiring_Generic_genericMul  = (box (fun (dictGeneric: obj) -> (let to_var = (sharpurs_apply (box ((box Data_Generic_Rep_to))) (box ((box dictGeneric)))) in (box (fun (dictGenericSemiring: obj) -> (box (fun (x: obj) -> (box (fun (y: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box to_var)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericMul_prime))) (box ((box dictGenericSemiring)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Generic_Rep_from))) (box ((box dictGeneric)))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Generic_Rep_from))) (box ((box dictGeneric)))))) (box ((box y)))))))))))))))))))

let Data_Semiring_Generic_genericAdd_prime  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "genericAdd'" (unbox<Map<string, obj>> ((box v))))))))

let Data_Semiring_Generic_genericSemiringConstructor  = (box (fun (dictGenericSemiring: obj) -> (sharpurs_apply (box ((box Data_Semiring_Generic_GenericSemiringusd_Dict))) (box ((box ((Map.add "genericAdd'" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (a1, a2) -> ((sharpurs_apply (box ((box Data_Generic_Rep_Constructor))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericAdd_prime))) (box ((box dictGenericSemiring)))))) (box ((box a1)))))) (box ((box a2))))))))))))))) (Map.add "genericZero'" (box ((sharpurs_apply (box ((box Data_Generic_Rep_Constructor))) (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericZero_prime))) (box ((box dictGenericSemiring))))))))) (Map.add "genericMul'" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (a1, a2) -> ((sharpurs_apply (box ((box Data_Generic_Rep_Constructor))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericMul_prime))) (box ((box dictGenericSemiring)))))) (box ((box a1)))))) (box ((box a2))))))))))))))) (Map.add "genericOne'" (box ((sharpurs_apply (box ((box Data_Generic_Rep_Constructor))) (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericOne_prime))) (box ((box dictGenericSemiring))))))))) Map.empty)))))))))))

let Data_Semiring_Generic_genericSemiringProduct  = (box (fun (dictGenericSemiring: obj) -> (box (fun (dictGenericSemiring1: obj) -> (sharpurs_apply (box ((box Data_Semiring_Generic_GenericSemiringusd_Dict))) (box ((box ((Map.add "genericAdd'" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Generic_Rep_Productusd_Ctor(a1, b1), Data_Generic_Rep_Productusd_Ctor(a2, b2)) -> ((box (Data_Generic_Rep_Productusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericAdd_prime))) (box ((box dictGenericSemiring)))))) (box ((box a1)))))) (box ((box a2)))), (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericAdd_prime))) (box ((box dictGenericSemiring1)))))) (box ((box b1)))))) (box ((box b2))))))))))))))) (Map.add "genericZero'" (box ((box (Data_Generic_Rep_Productusd_Ctor((sharpurs_apply (box ((box Data_Semiring_Generic_genericZero_prime))) (box ((box dictGenericSemiring)))), (sharpurs_apply (box ((box Data_Semiring_Generic_genericZero_prime))) (box ((box dictGenericSemiring1))))))))) (Map.add "genericMul'" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Generic_Rep_Productusd_Ctor(a1, b1), Data_Generic_Rep_Productusd_Ctor(a2, b2)) -> ((box (Data_Generic_Rep_Productusd_Ctor((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericMul_prime))) (box ((box dictGenericSemiring)))))) (box ((box a1)))))) (box ((box a2)))), (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericMul_prime))) (box ((box dictGenericSemiring1)))))) (box ((box b1)))))) (box ((box b2))))))))))))))) (Map.add "genericOne'" (box ((box (Data_Generic_Rep_Productusd_Ctor((sharpurs_apply (box ((box Data_Semiring_Generic_genericOne_prime))) (box ((box dictGenericSemiring)))), (sharpurs_apply (box ((box Data_Semiring_Generic_genericOne_prime))) (box ((box dictGenericSemiring1))))))))) Map.empty)))))))))))))

let Data_Semiring_Generic_genericAdd  = (box (fun (dictGeneric: obj) -> (let to_var = (sharpurs_apply (box ((box Data_Generic_Rep_to))) (box ((box dictGeneric)))) in (box (fun (dictGenericSemiring: obj) -> (box (fun (x: obj) -> (box (fun (y: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box to_var)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_Generic_genericAdd_prime))) (box ((box dictGenericSemiring)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Generic_Rep_from))) (box ((box dictGeneric)))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Generic_Rep_from))) (box ((box dictGeneric)))))) (box ((box y)))))))))))))))))))
