[<AutoOpen>]
module PureScript_Data_Functor_Product

open System
open System.Collections.Generic

let Data_Functor_Product_unwrap  = (sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined))))

let Data_Functor_Product_unwrap1  = (sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined))))

let Data_Functor_Product_Product  = (box (fun (x: obj) -> (box x)))

let Data_Functor_Product_showProduct  = (box (fun (dictShow: obj) -> (box (fun (dictShow1: obj) -> (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(fa, ga) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(product ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow)))))) (box ((box fa))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box " ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow1)))))) (box ((box ga))))))))) (box ((box ")"))))))))))))))))))) Map.empty))))))))))

let Data_Functor_Product_product  = (box (fun (fa: obj) -> (box (fun (ga: obj) -> (sharpurs_apply (box ((box Data_Functor_Product_Product))) (box ((box (Data_Tuple_Tupleusd_Ctor((box fa), (box ga)))))))))))

let Data_Functor_Product_newtypeProduct  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Data_Functor_Product_functorProduct  = (box (fun (dictFunctor: obj) -> (box (fun (dictFunctor1: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, fga) -> ((sharpurs_apply (box ((box Data_Functor_Product_Product))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box Data_Bifunctor_bifunctorTuple)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f1))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor1)))))) (box ((box f1))))))))) (box ((box fga))))))))))))))) Map.empty))))))))))

let Data_Functor_Product_eq1Product  = (box (fun (dictEq1: obj) -> (box (fun (dictEq11: obj) -> (sharpurs_apply (box ((box Data_Eq_Eq1usd_Dict))) (box ((box ((Map.add "eq1" (box ((box (fun (dictEq: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Tuple_Tupleusd_Ctor(l1, r1), Data_Tuple_Tupleusd_Ctor(l2, r2)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_HeytingAlgebra_conj))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq1))) (box ((box dictEq1)))))) (box ((box dictEq)))))) (box ((box l1)))))) (box ((box l2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq1))) (box ((box dictEq11)))))) (box ((box dictEq)))))) (box ((box r1)))))) (box ((box r2))))))))))))))))) Map.empty))))))))))

let Data_Functor_Product_eqProduct  = (box (fun (dictEq1: obj) -> (let eq1Product1 = (sharpurs_apply (box ((box Data_Functor_Product_eq1Product))) (box ((box dictEq1)))) in (box (fun (dictEq11: obj) -> (let eq1 = (sharpurs_apply (box ((box Data_Eq_eq1))) (box ((sharpurs_apply (box ((box eq1Product1))) (box ((box dictEq11))))))) in (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((sharpurs_apply (box ((box eq1))) (box ((box dictEq)))))) Map.empty))))))))))))))

let Data_Functor_Product_ord1Product  = (box (fun (dictOrd1: obj) -> (let eq1Product1 = (sharpurs_apply (box ((box Data_Functor_Product_eq1Product))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd1)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd11: obj) -> (let eq1Product2 = (sharpurs_apply (box ((box eq1Product1))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd11)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ord1usd_Dict))) (box ((box ((Map.add "compare1" (box ((box (fun (dictOrd: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Tuple_Tupleusd_Ctor(l1, r1), Data_Tuple_Tupleusd_Ctor(l2, r2)) -> ((let v2 = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare1))) (box ((box dictOrd1)))))) (box ((box dictOrd)))))) (box ((box l1)))))) (box ((box l2)))) in (match ((unbox ((box v2)))) with | Data_Ordering_EQusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare1))) (box ((box dictOrd11)))))) (box ((box dictOrd)))))) (box ((box r1)))))) (box ((box r2))))) | o -> ((box o)))))))))))))) (Map.add "Eq10" (box ((box (fun (usd__unused: obj) -> (box eq1Product2))))) Map.empty)))))))))))))

let Data_Functor_Product_ordProduct  = (box (fun (dictOrd1: obj) -> (let ord1Product1 = (sharpurs_apply (box ((box Data_Functor_Product_ord1Product))) (box ((box dictOrd1)))) in let eqProduct1 = (sharpurs_apply (box ((box Data_Functor_Product_eqProduct))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd1)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd11: obj) -> (let compare1 = (sharpurs_apply (box ((box Data_Ord_compare1))) (box ((sharpurs_apply (box ((box ord1Product1))) (box ((box dictOrd11))))))) in let eqProduct2 = (sharpurs_apply (box ((box eqProduct1))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd11)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd: obj) -> (let eqProduct3 = (sharpurs_apply (box ((box eqProduct2))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((sharpurs_apply (box ((box compare1))) (box ((box dictOrd)))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box eqProduct3))))) Map.empty))))))))))))))))

let Data_Functor_Product_bihoistProduct  = (box (fun (natF: obj) -> (box (fun (natG: obj) -> (box (fun (v: obj) -> (match (((unbox ((box natF))), (unbox ((box natG))), (unbox ((box v))))) with | (natF1, natG1, e) -> ((sharpurs_apply (box ((box Data_Functor_Product_Product))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box Data_Bifunctor_bifunctorTuple)))))) (box ((box natF1)))))) (box ((box natG1)))))) (box ((box e)))))))))))))))

let Data_Functor_Product_applyProduct  = (box (fun (dictApply: obj) -> (let functorProduct1 = (sharpurs_apply (box ((box Data_Functor_Product_functorProduct))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined))))))) in (box (fun (dictApply1: obj) -> (let functorProduct2 = (sharpurs_apply (box ((box functorProduct1))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Tuple_Tupleusd_Ctor(f, g), Data_Tuple_Tupleusd_Ctor(a, b)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box dictApply)))))) (box ((box f)))))) (box ((box a))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box dictApply1)))))) (box ((box g)))))) (box ((box b))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorProduct2))))) Map.empty)))))))))))))

let Data_Functor_Product_bindProduct  = (box (fun (dictBind: obj) -> (let applyProduct1 = (sharpurs_apply (box ((box Data_Functor_Product_applyProduct))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictBind)))))) (box ((box Prim_undefined))))))) in (box (fun (dictBind1: obj) -> (let applyProduct2 = (sharpurs_apply (box ((box applyProduct1))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictBind1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((box (fun (v: obj) -> (box (fun (f: obj) -> (match (((unbox ((box v))), (unbox ((box f))))) with | (Data_Tuple_Tupleusd_Ctor(fa, ga), f1) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box dictBind)))))) (box ((box fa)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Tuple_fst)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Functor_Product_unwrap)))))) (box ((box f1))))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box dictBind1)))))) (box ((box ga)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Tuple_snd)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Functor_Product_unwrap1)))))) (box ((box f1))))))))))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyProduct2))))) Map.empty)))))))))))))

let Data_Functor_Product_applicativeProduct  = (box (fun (dictApplicative: obj) -> (let applyProduct1 = (sharpurs_apply (box ((box Data_Functor_Product_applyProduct))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (box (fun (dictApplicative1: obj) -> (let applyProduct2 = (sharpurs_apply (box ((box applyProduct1))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Product_product))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))))) (box ((box a))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative1)))))) (box ((box a))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyProduct2))))) Map.empty)))))))))))))

let Data_Functor_Product_monadProduct  = (box (fun (dictMonad: obj) -> (let applicativeProduct1 = (sharpurs_apply (box ((box Data_Functor_Product_applicativeProduct))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in let bindProduct1 = (sharpurs_apply (box ((box Data_Functor_Product_bindProduct))) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in (box (fun (dictMonad1: obj) -> (let applicativeProduct2 = (sharpurs_apply (box ((box applicativeProduct1))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad1)))))) (box ((box Prim_undefined))))))) in let bindProduct2 = (sharpurs_apply (box ((box bindProduct1))) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box applicativeProduct2))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box bindProduct2))))) Map.empty)))))))))))))
