[<AutoOpen>]
module PureScript_Data_Either

open System
open System.Collections.Generic

type Data_Either_Either =
  | Data_Either_Leftusd_Ctor of obj
  | Data_Either_Rightusd_Ctor of obj

let Data_Either_Left  = (box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))

let Data_Either_Right  = (box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))

let Data_Either_showEither  = (box (fun (dictShow: obj) -> (box (fun (dictShow1: obj) -> (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Either_Leftusd_Ctor(x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(Left ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow)))))) (box ((box x))))))))) (box ((box ")")))))))) | Data_Either_Rightusd_Ctor(y) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(Right ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow1)))))) (box ((box y))))))))) (box ((box ")"))))))))))))) Map.empty))))))))))

let Data_Either_note_prime  = (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe_prime))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))) (box ((box f))))))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))))))

let Data_Either_note  = (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe))) (box ((box (Data_Either_Leftusd_Ctor((box a))))))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))))))

let Data_Either_genericEither  = (sharpurs_apply (box ((box Data_Generic_Rep_Genericusd_Dict))) (box ((box ((Map.add "to" (box ((box (fun (x: obj) -> (match ((unbox ((box x)))) with | Data_Generic_Rep_Inlusd_Ctor(arg) -> ((box (Data_Either_Leftusd_Ctor((box arg))))) | Data_Generic_Rep_Inrusd_Ctor(arg) -> ((box (Data_Either_Rightusd_Ctor((box arg)))))))))) (Map.add "from" (box ((box (fun (x: obj) -> (match ((unbox ((box x)))) with | Data_Either_Leftusd_Ctor(arg) -> ((box (Data_Generic_Rep_Inlusd_Ctor((sharpurs_apply (box ((box Data_Generic_Rep_Constructor))) (box ((sharpurs_apply (box ((box Data_Generic_Rep_Argument))) (box ((box arg))))))))))) | Data_Either_Rightusd_Ctor(arg) -> ((box (Data_Generic_Rep_Inrusd_Ctor((sharpurs_apply (box ((box Data_Generic_Rep_Constructor))) (box ((sharpurs_apply (box ((box Data_Generic_Rep_Argument))) (box ((box arg)))))))))))))))) Map.empty)))))))

let Data_Either_functorEither  = (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (m: obj) -> (match ((unbox ((box m)))) with | Data_Either_Leftusd_Ctor(v) -> ((box (Data_Either_Leftusd_Ctor((box v))))) | Data_Either_Rightusd_Ctor(v) -> ((box (Data_Either_Rightusd_Ctor((sharpurs_apply (box ((box f))) (box ((box v))))))))))))))) Map.empty))))))

let Data_Either_invariantEither  = (sharpurs_apply (box ((box Data_Functor_Invariant_Invariantusd_Dict))) (box ((box ((Map.add "imap" (box ((sharpurs_apply (box ((box Data_Functor_Invariant_imapF))) (box ((box Data_Either_functorEither)))))) Map.empty))))))

let Data_Either_fromRight_prime  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_Either_Rightusd_Ctor(b)) -> ((box b)) | (default_var, _) -> ((sharpurs_apply (box ((box default_var))) (box ((box Data_Unit_unit))))))))))

let Data_Either_fromRight  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_Either_Rightusd_Ctor(b)) -> ((box b)) | (default_var, _) -> ((box default_var)))))))

let Data_Either_fromLeft_prime  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_Either_Leftusd_Ctor(a)) -> ((box a)) | (default_var, _) -> ((sharpurs_apply (box ((box default_var))) (box ((box Data_Unit_unit))))))))))

let Data_Either_fromLeft  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_Either_Leftusd_Ctor(a)) -> ((box a)) | (default_var, _) -> ((box default_var)))))))

let Data_Either_extendEither  = (sharpurs_apply (box ((box Control_Extend_Extendusd_Dict))) (box ((box ((Map.add "extend" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_Either_Leftusd_Ctor(y)) -> ((box (Data_Either_Leftusd_Ctor((box y))))) | (f, x) -> ((box (Data_Either_Rightusd_Ctor((sharpurs_apply (box ((box f))) (box ((box x))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Either_functorEither))))) Map.empty)))))))

let Data_Either_eqEither  = (box (fun (dictEq: obj) -> (box (fun (dictEq1: obj) -> (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Either_Leftusd_Ctor(l), Data_Either_Leftusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((box l)))))) (box ((box r))))) | (Data_Either_Rightusd_Ctor(l), Data_Either_Rightusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq1)))))) (box ((box l)))))) (box ((box r))))) | (_, _) -> ((box false))))))))) Map.empty))))))))))

let Data_Either_ordEither  = (box (fun (dictOrd: obj) -> (let eqEither1 = (sharpurs_apply (box ((box Data_Either_eqEither))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd1: obj) -> (let eqEither2 = (sharpurs_apply (box ((box eqEither1))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Either_Leftusd_Ctor(l), Data_Either_Leftusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd)))))) (box ((box l)))))) (box ((box r))))) | (Data_Either_Leftusd_Ctor(_), _) -> ((box Data_Ordering_LTusd_Ctor)) | (_, Data_Either_Leftusd_Ctor(_)) -> ((box Data_Ordering_GTusd_Ctor)) | (Data_Either_Rightusd_Ctor(l), Data_Either_Rightusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd1)))))) (box ((box l)))))) (box ((box r)))))))))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box eqEither2))))) Map.empty)))))))))))))

let Data_Either_eq1Either  = (box (fun (dictEq: obj) -> (let eqEither1 = (sharpurs_apply (box ((box Data_Either_eqEither))) (box ((box dictEq)))) in (sharpurs_apply (box ((box Data_Eq_Eq1usd_Dict))) (box ((box ((Map.add "eq1" (box ((box (fun (dictEq1: obj) -> (sharpurs_apply (box ((box Data_Eq_eq))) (box ((sharpurs_apply (box ((box eqEither1))) (box ((box dictEq1))))))))))) Map.empty)))))))))

let Data_Either_ord1Either  = (box (fun (dictOrd: obj) -> (let ordEither1 = (sharpurs_apply (box ((box Data_Either_ordEither))) (box ((box dictOrd)))) in let eq1Either1 = (sharpurs_apply (box ((box Data_Either_eq1Either))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ord1usd_Dict))) (box ((box ((Map.add "compare1" (box ((box (fun (dictOrd1: obj) -> (sharpurs_apply (box ((box Data_Ord_compare))) (box ((sharpurs_apply (box ((box ordEither1))) (box ((box dictOrd1))))))))))) (Map.add "Eq10" (box ((box (fun (usd__unused: obj) -> (box eq1Either1))))) Map.empty))))))))))

let Data_Either_either  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (box (fun (v2: obj) -> (match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))))) with | (f, _, Data_Either_Leftusd_Ctor(a)) -> ((sharpurs_apply (box ((box f))) (box ((box a))))) | (_, g, Data_Either_Rightusd_Ctor(b)) -> ((sharpurs_apply (box ((box g))) (box ((box b))))))))))))

let Data_Either_hush  = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box Data_Maybe_Nothingusd_Ctor))))))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))))

let Data_Either_isLeft  = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box true))))))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box false)))))))

let Data_Either_isRight  = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box false))))))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box true)))))))

let Data_Either_choose  = (box (fun (dictAlt: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictAlt)))))) (box ((box Prim_undefined)))) in (box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Alt_alt))) (box ((box dictAlt)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))) (box ((box a))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))))) (box ((box b))))))))))))))

let Data_Either_boundedEither  = (box (fun (dictBounded: obj) -> (let ordEither1 = (sharpurs_apply (box ((box Data_Either_ordEither))) (box ((sharpurs_apply (box ((Map.find "Ord0" (unbox<Map<string, obj>> ((box dictBounded)))))) (box ((box Prim_undefined))))))) in (box (fun (dictBounded1: obj) -> (let ordEither2 = (sharpurs_apply (box ((box ordEither1))) (box ((sharpurs_apply (box ((Map.find "Ord0" (unbox<Map<string, obj>> ((box dictBounded1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Bounded_Boundedusd_Dict))) (box ((box ((Map.add "top" (box ((box (Data_Either_Rightusd_Ctor((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box dictBounded1))))))))) (Map.add "bottom" (box ((box (Data_Either_Leftusd_Ctor((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box dictBounded))))))))) (Map.add "Ord0" (box ((box (fun (usd__unused: obj) -> (box ordEither2))))) Map.empty))))))))))))))

let Data_Either_blush  = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box Data_Maybe_Nothingusd_Ctor)))))))

let Data_Either_applyEither  = (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Either_Leftusd_Ctor(e), _) -> ((box (Data_Either_Leftusd_Ctor((box e))))) | (Data_Either_Rightusd_Ctor(f), r) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Either_functorEither)))))) (box ((box f)))))) (box ((box r)))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Either_functorEither))))) Map.empty)))))))

let Data_Either_bindEither  = (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((box (fun (e: obj) -> (box (fun (v: obj) -> (box (Data_Either_Leftusd_Ctor((box e))))))))))))) (box ((box (fun (a: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((box f))) (box ((box a))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box Data_Either_applyEither))))) Map.empty)))))))

let Data_Either_semigroupEither  = (box (fun (dictSemigroup: obj) -> (let append = (sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))) in (sharpurs_apply (box ((box Data_Semigroup_Semigroupusd_Dict))) (box ((box ((Map.add "append" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Data_Either_applyEither)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Either_functorEither)))))) (box ((box append)))))) (box ((box x))))))))) (box ((box y)))))))))) Map.empty)))))))))

let Data_Either_applicativeEither  = (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box Data_Either_applyEither))))) Map.empty)))))))

let Data_Either_monadEither  = (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box Data_Either_applicativeEither))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box Data_Either_bindEither))))) Map.empty)))))))

let Data_Either_altEither  = (sharpurs_apply (box ((box Control_Alt_Altusd_Dict))) (box ((box ((Map.add "alt" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Either_Leftusd_Ctor(_), r) -> ((box r)) | (l, _) -> ((box l))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Either_functorEither))))) Map.empty)))))))
