[<AutoOpen>]
module PureScript_Data_Enum_Gen

open System
open System.Collections.Generic

let Data_Enum_Gen_foldable1NonEmpty  = (sharpurs_apply (box ((box Data_NonEmpty_foldable1NonEmpty))) (box ((box Data_Foldable_foldableArray))))

let Data_Enum_Gen_genBoundedEnum  = (box (fun (dictMonadGen: obj) -> (let Applicative0 = (sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (dictBoundedEnum: obj) -> (let Enum1 = (sharpurs_apply (box ((Map.find "Enum1" (unbox<Map<string, obj>> ((box dictBoundedEnum)))))) (box ((box Prim_undefined)))) in let Bounded0 = (sharpurs_apply (box ((Map.find "Bounded0" (unbox<Map<string, obj>> ((box dictBoundedEnum)))))) (box ((box Prim_undefined)))) in let v = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Enum_succ))) (box ((box Enum1)))))) (box ((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Bounded0))))))) in (match ((unbox ((box v)))) with | Data_Maybe_Justusd_Ctor(a) -> ((let possibilities = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Enum_enumFromTo))) (box ((box Enum1)))))) (box ((box Data_Unfoldable1_unfoldable1Array)))))) (box ((box a)))))) (box ((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box Bounded0))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_elements))) (box ((box dictMonadGen)))))) (box ((box Data_Enum_Gen_foldable1NonEmpty)))))) (box ((box (Data_NonEmpty_NonEmptyusd_Ctor((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Bounded0)))), (box possibilities))))))))) | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Applicative0)))))) (box ((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Bounded0)))))))))))))))
