[<AutoOpen>]
module PureScript_Data_Functor_Coproduct

open System
open System.Collections.Generic

let Data_Functor_Coproduct_Coproduct  = (box (fun (x: obj) -> (box x)))

let Data_Functor_Coproduct_showCoproduct  = (box (fun (dictShow: obj) -> (box (fun (dictShow1: obj) -> (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Either_Leftusd_Ctor(fa) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(left ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow)))))) (box ((box fa))))))))) (box ((box ")")))))))) | Data_Either_Rightusd_Ctor(ga) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(right ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow1)))))) (box ((box ga))))))))) (box ((box ")"))))))))))))) Map.empty))))))))))

let Data_Functor_Coproduct_right  = (box (fun (ga: obj) -> (sharpurs_apply (box ((box Data_Functor_Coproduct_Coproduct))) (box ((box (Data_Either_Rightusd_Ctor((box ga)))))))))

let Data_Functor_Coproduct_newtypeCoproduct  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Data_Functor_Coproduct_left  = (box (fun (fa: obj) -> (sharpurs_apply (box ((box Data_Functor_Coproduct_Coproduct))) (box ((box (Data_Either_Leftusd_Ctor((box fa)))))))))

let Data_Functor_Coproduct_functorCoproduct  = (box (fun (dictFunctor: obj) -> (box (fun (dictFunctor1: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, e) -> ((sharpurs_apply (box ((box Data_Functor_Coproduct_Coproduct))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box Data_Bifunctor_bifunctorEither)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f1))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor1)))))) (box ((box f1))))))))) (box ((box e))))))))))))))) Map.empty))))))))))

let Data_Functor_Coproduct_eq1Coproduct  = (box (fun (dictEq1: obj) -> (box (fun (dictEq11: obj) -> (sharpurs_apply (box ((box Data_Eq_Eq1usd_Dict))) (box ((box ((Map.add "eq1" (box ((box (fun (dictEq: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (x, y) -> ((match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Either_Leftusd_Ctor(fa), Data_Either_Leftusd_Ctor(ga)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq1))) (box ((box dictEq1)))))) (box ((box dictEq)))))) (box ((box fa)))))) (box ((box ga))))) | (Data_Either_Rightusd_Ctor(fa), Data_Either_Rightusd_Ctor(ga)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq1))) (box ((box dictEq11)))))) (box ((box dictEq)))))) (box ((box fa)))))) (box ((box ga))))) | (_, _) -> ((box false))))))))))))) Map.empty))))))))))

let Data_Functor_Coproduct_eqCoproduct  = (box (fun (dictEq1: obj) -> (let eq1Coproduct1 = (sharpurs_apply (box ((box Data_Functor_Coproduct_eq1Coproduct))) (box ((box dictEq1)))) in (box (fun (dictEq11: obj) -> (let eq1 = (sharpurs_apply (box ((box Data_Eq_eq1))) (box ((sharpurs_apply (box ((box eq1Coproduct1))) (box ((box dictEq11))))))) in (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((sharpurs_apply (box ((box eq1))) (box ((box dictEq)))))) Map.empty))))))))))))))

let Data_Functor_Coproduct_ord1Coproduct  = (box (fun (dictOrd1: obj) -> (let eq1Coproduct1 = (sharpurs_apply (box ((box Data_Functor_Coproduct_eq1Coproduct))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd1)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd11: obj) -> (let eq1Coproduct2 = (sharpurs_apply (box ((box eq1Coproduct1))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd11)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ord1usd_Dict))) (box ((box ((Map.add "compare1" (box ((box (fun (dictOrd: obj) -> (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (x, y) -> ((match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Either_Leftusd_Ctor(fa), Data_Either_Leftusd_Ctor(ga)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare1))) (box ((box dictOrd1)))))) (box ((box dictOrd)))))) (box ((box fa)))))) (box ((box ga))))) | (Data_Either_Leftusd_Ctor(_), _) -> ((box Data_Ordering_LTusd_Ctor)) | (_, Data_Either_Leftusd_Ctor(_)) -> ((box Data_Ordering_GTusd_Ctor)) | (Data_Either_Rightusd_Ctor(fa), Data_Either_Rightusd_Ctor(ga)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare1))) (box ((box dictOrd11)))))) (box ((box dictOrd)))))) (box ((box fa)))))) (box ((box ga)))))))))))))))) (Map.add "Eq10" (box ((box (fun (usd__unused: obj) -> (box eq1Coproduct2))))) Map.empty)))))))))))))

let Data_Functor_Coproduct_ordCoproduct  = (box (fun (dictOrd1: obj) -> (let ord1Coproduct1 = (sharpurs_apply (box ((box Data_Functor_Coproduct_ord1Coproduct))) (box ((box dictOrd1)))) in let eqCoproduct1 = (sharpurs_apply (box ((box Data_Functor_Coproduct_eqCoproduct))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd1)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd11: obj) -> (let compare1 = (sharpurs_apply (box ((box Data_Ord_compare1))) (box ((sharpurs_apply (box ((box ord1Coproduct1))) (box ((box dictOrd11))))))) in let eqCoproduct2 = (sharpurs_apply (box ((box eqCoproduct1))) (box ((sharpurs_apply (box ((Map.find "Eq10" (unbox<Map<string, obj>> ((box dictOrd11)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd: obj) -> (let eqCoproduct3 = (sharpurs_apply (box ((box eqCoproduct2))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((sharpurs_apply (box ((box compare1))) (box ((box dictOrd)))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box eqCoproduct3))))) Map.empty))))))))))))))))

let Data_Functor_Coproduct_coproduct  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (box (fun (v2: obj) -> (match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))))) with | (f, _, Data_Either_Leftusd_Ctor(a)) -> ((sharpurs_apply (box ((box f))) (box ((box a))))) | (_, g, Data_Either_Rightusd_Ctor(b)) -> ((sharpurs_apply (box ((box g))) (box ((box b))))))))))))

let Data_Functor_Coproduct_extendCoproduct  = (box (fun (dictExtend: obj) -> (let functorCoproduct1 = (sharpurs_apply (box ((box Data_Functor_Coproduct_functorCoproduct))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictExtend)))))) (box ((box Prim_undefined))))))) in (box (fun (dictExtend1: obj) -> (let functorCoproduct2 = (sharpurs_apply (box ((box functorCoproduct1))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictExtend1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Extend_Extendusd_Dict))) (box ((box ((Map.add "extend" (box ((box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Functor_Coproduct_Coproduct)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Coproduct_coproduct))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Extend_extend))) (box ((box dictExtend)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box f)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Functor_Coproduct_Coproduct)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Extend_extend))) (box ((box dictExtend1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box f)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Functor_Coproduct_Coproduct)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))))))))))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorCoproduct2))))) Map.empty)))))))))))))

let Data_Functor_Coproduct_comonadCoproduct  = (box (fun (dictComonad: obj) -> (let extract = (sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad)))) in let extendCoproduct1 = (sharpurs_apply (box ((box Data_Functor_Coproduct_extendCoproduct))) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((box dictComonad)))))) (box ((box Prim_undefined))))))) in (box (fun (dictComonad1: obj) -> (let extendCoproduct2 = (sharpurs_apply (box ((box extendCoproduct1))) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((box dictComonad1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Comonad_Comonadusd_Dict))) (box ((box ((Map.add "extract" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Coproduct_coproduct))) (box ((box extract)))))) (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad1))))))))) (Map.add "Extend0" (box ((box (fun (usd__unused: obj) -> (box extendCoproduct2))))) Map.empty)))))))))))))

let Data_Functor_Coproduct_bihoistCoproduct  = (box (fun (natF: obj) -> (box (fun (natG: obj) -> (box (fun (v: obj) -> (match (((unbox ((box natF))), (unbox ((box natG))), (unbox ((box v))))) with | (natF1, natG1, e) -> ((sharpurs_apply (box ((box Data_Functor_Coproduct_Coproduct))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box Data_Bifunctor_bifunctorEither)))))) (box ((box natF1)))))) (box ((box natG1)))))) (box ((box e)))))))))))))))
