[<AutoOpen>]
module PureScript_Data_Profunctor_Star

open System
open System.Collections.Generic

let Data_Profunctor_Star_Star  = (box (fun (x: obj) -> (box x)))

let Data_Profunctor_Star_semigroupoidStar  = (box (fun (dictBind: obj) -> (sharpurs_apply (box ((box Control_Semigroupoid_Semigroupoidusd_Dict))) (box ((box ((Map.add "compose" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, g) -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box dictBind)))))) (box ((sharpurs_apply (box ((box g))) (box ((box x))))))))) (box ((box f))))))))))))))))) Map.empty))))))))

let Data_Profunctor_Star_profunctorStar  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Profunctor_Profunctorusd_Dict))) (box ((box ((Map.add "dimap" (box ((box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box v))))) with | (f1, g1, ft) -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box f1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box ft)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box g1))))))))))))))))))))))) Map.empty))))))))

let Data_Profunctor_Star_strongStar  = (box (fun (dictFunctor: obj) -> (let profunctorStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_profunctorStar))) (box ((box dictFunctor)))) in (sharpurs_apply (box ((box Data_Profunctor_Strong_Strongusd_Dict))) (box ((box ((Map.add "first" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (v1: obj) -> (match ((unbox ((box v1)))) with | Data_Tuple_Tupleusd_Ctor(s, x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box (fun (v2: obj) -> (box (Data_Tuple_Tupleusd_Ctor((box v2), (box x))))))))))) (box ((sharpurs_apply (box ((box f))) (box ((box s)))))))))))))))))))) (Map.add "second" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (v1: obj) -> (match ((unbox ((box v1)))) with | Data_Tuple_Tupleusd_Ctor(x, s) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((box f))) (box ((box s)))))))))))))))))))) (Map.add "Profunctor0" (box ((box (fun (usd__unused: obj) -> (box profunctorStar1))))) Map.empty)))))))))))

let Data_Profunctor_Star_newtypeStar  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Data_Profunctor_Star_invariantStar  = (box (fun (dictInvariant: obj) -> (sharpurs_apply (box ((box Data_Functor_Invariant_Invariantusd_Dict))) (box ((box ((Map.add "imap" (box ((box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box v))))) with | (f1, g1, h) -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Invariant_imap))) (box ((box dictInvariant)))))) (box ((box f1)))))) (box ((box g1))))))))) (box ((box h))))))))))))))))) Map.empty))))))))

let Data_Profunctor_Star_hoistStar  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, g) -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box f1)))))) (box ((box g)))))))))))))

let Data_Profunctor_Star_functorStar  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, g) -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f1))))))))) (box ((box g))))))))))))))) Map.empty))))))))

let rec Data_Profunctor_Star_distributiveStar_tco (dictDistributive: obj) : obj = ((let functorStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_functorStar))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictDistributive)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Distributive_Distributiveusd_Dict))) (box ((box ((Map.add "distribute" (box ((box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Distributive_collect))) (box ((box dictDistributive)))))) (box ((box dictFunctor)))))) (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | g -> ((sharpurs_apply (box ((box g))) (box ((box a))))))))))))) (box ((box f))))))))))))))) (Map.add "collect" (box ((box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Distributive_distribute))) (box ((Data_Profunctor_Star_distributiveStar_tco ((box dictDistributive)))))))) (box ((box dictFunctor))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorStar1))))) Map.empty))))))))))
and Data_Profunctor_Star_distributiveStar = box (fun (dictDistributive: obj) -> Data_Profunctor_Star_distributiveStar_tco dictDistributive)


let Data_Profunctor_Star_closedStar  = (box (fun (dictDistributive: obj) -> (let profunctorStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_profunctorStar))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictDistributive)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Profunctor_Closed_Closedusd_Dict))) (box ((box ((Map.add "closed" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (g: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Distributive_distribute))) (box ((box dictDistributive)))))) (box ((box Data_Functor_functorFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box f)))))) (box ((box g)))))))))))))))))) (Map.add "Profunctor0" (box ((box (fun (usd__unused: obj) -> (box profunctorStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_choiceStar  = (box (fun (dictApplicative: obj) -> (let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box Apply0)))))) (box ((box Prim_undefined)))) in let pure_var = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))) in let pure1 = (sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))) in let profunctorStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_profunctorStar))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box Apply0)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Profunctor_Choice_Choiceusd_Dict))) (box ((box ((Map.add "left" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Profunctor_Star_Star)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))))))))) (box ((box f))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box pure_var)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))))))))))))))) (Map.add "right" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Data_Profunctor_Star_Star)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Either_either))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box pure1)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))))))))) (box ((box f)))))))))))))))) (Map.add "Profunctor0" (box ((box (fun (usd__unused: obj) -> (box profunctorStar1))))) Map.empty)))))))))))

let Data_Profunctor_Star_categoryStar  = (box (fun (dictMonad: obj) -> (let semigroupoidStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_semigroupoidStar))) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Category_Categoryusd_Dict))) (box ((box ((Map.add "identity" (box ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))))))))))) (Map.add "Semigroupoid0" (box ((box (fun (usd__unused: obj) -> (box semigroupoidStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_applyStar  = (box (fun (dictApply: obj) -> (let functorStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_functorStar))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictApply)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, g) -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box dictApply)))))) (box ((sharpurs_apply (box ((box f))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box g))) (box ((box a)))))))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_bindStar  = (box (fun (dictBind: obj) -> (let applyStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_applyStar))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictBind)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((box (fun (v: obj) -> (box (fun (f: obj) -> (match (((unbox ((box v))), (unbox ((box f))))) with | (m, f1) -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box dictBind)))))) (box ((sharpurs_apply (box ((box m))) (box ((box x))))))))) (box ((box (fun (a: obj) -> (let v1 = (sharpurs_apply (box ((box f1))) (box ((box a)))) in (match ((unbox ((box v1)))) with | g -> ((sharpurs_apply (box ((box g))) (box ((box x))))))))))))))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_applicativeStar  = (box (fun (dictApplicative: obj) -> (let applyStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_applyStar))) (box ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box dictApplicative)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((box (fun (a: obj) -> (sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))))) (box ((box a))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box applyStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_monadStar  = (box (fun (dictMonad: obj) -> (let applicativeStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_applicativeStar))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in let bindStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_bindStar))) (box ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box applicativeStar1))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box bindStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_altStar  = (box (fun (dictAlt: obj) -> (let functorStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_functorStar))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictAlt)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Alt_Altusd_Dict))) (box ((box ((Map.add "alt" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, g) -> ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Alt_alt))) (box ((box dictAlt)))))) (box ((sharpurs_apply (box ((box f))) (box ((box a))))))))) (box ((sharpurs_apply (box ((box g))) (box ((box a)))))))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_plusStar  = (box (fun (dictPlus: obj) -> (let empty = (sharpurs_apply (box ((box Control_Plus_empty))) (box ((box dictPlus)))) in let altStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_altStar))) (box ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> ((box dictPlus)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Plus_Plususd_Dict))) (box ((box ((Map.add "empty" (box ((sharpurs_apply (box ((box Data_Profunctor_Star_Star))) (box ((box (fun (v: obj) -> (box empty)))))))) (Map.add "Alt0" (box ((box (fun (usd__unused: obj) -> (box altStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_alternativeStar  = (box (fun (dictAlternative: obj) -> (let applicativeStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_applicativeStar))) (box ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))) in let plusStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_plusStar))) (box ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Alternative_Alternativeusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box applicativeStar1))))) (Map.add "Plus1" (box ((box (fun (usd__unused: obj) -> (box plusStar1))))) Map.empty))))))))))

let Data_Profunctor_Star_monadPlusStar  = (box (fun (dictMonadPlus: obj) -> (let monadStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_monadStar))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadPlus)))))) (box ((box Prim_undefined))))))) in let alternativeStar1 = (sharpurs_apply (box ((box Data_Profunctor_Star_alternativeStar))) (box ((sharpurs_apply (box ((Map.find "Alternative1" (unbox<Map<string, obj>> ((box dictMonadPlus)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_MonadPlus_MonadPlususd_Dict))) (box ((box ((Map.add "Monad0" (box ((box (fun (usd__unused: obj) -> (box monadStar1))))) (Map.add "Alternative1" (box ((box (fun (usd__unused: obj) -> (box alternativeStar1))))) Map.empty))))))))))
