// Generated by purs version 0.15.16
var mempty_ = function (dict) {
    return dict.mempty_;
};
var mappend_ = function (dict) {
    return dict.mappend_;
};
var polyLoop = function (dictMonoidish) {
    var mempty_1 = mempty_(dictMonoidish);
    return function (v) {
        return function (v1) {
            if (v === 0) {
                return v1;
            };
            return polyLoop(dictMonoidish)(v - 1 | 0)(mappend_(dictMonoidish)(v1)(mempty_1));
        };
    };
};
var intMonoidish = {
    mempty_: 0,
    mappend_: function (a) {
        return function (b) {
            return a + b | 0;
        };
    }
};
var test = /* #__PURE__ */ polyLoop(intMonoidish)(10000000)(0);
export {
    mappend_,
    mempty_,
    polyLoop,
    test,
    intMonoidish
};
//# sourceMappingURL=index.js.map
