// Generated by purs version 0.15.16
import * as Effect_Console from "../Effect.Console/index.js";
import * as Test_AstTree from "../Test.AstTree/index.js";
import * as Test_Fib from "../Test.Fib/index.js";
var main = function __do() {
    Effect_Console.log(Test_AstTree.description + ":")();
    Test_AstTree.act();
    Effect_Console.log(Test_Fib.description + ":")();
    return Test_Fib.act();
};
export {
    main
};
//# sourceMappingURL=index.js.map
