% Generated by purerl version 0.0.24
-module(data_functor_flip@ps).
-export(['Flip'/0, showFlip/0, semigroupoidFlip/1, semigroupoidFlip/0, ordFlip/0, newtypeFlip/0, functorFlip/0, eqFlip/0, contravariantFlip/0, categoryFlip/0, bifunctorFlip/1, bifunctorFlip/0, biapplyFlip/1, biapplyFlip/0, biapplicativeFlip/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./data_functor_flip.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 0).
-spec append() -> any().
append() -> (?MEMOIZE((data_semigroup@ps:append((data_semigroup@ps:semigroupString()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 0).
-spec append(any(),any()) -> any().
append(_@2,_@3) -> (((append())(_@2))(_@3)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 14).
-spec 'Flip'() -> any().
'Flip'() -> fun (X) ->
  X
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 22).
-spec showFlip() -> any().
showFlip() -> fun (DictShow) ->
  Show@29 = (?MEMOIZE((data_show@ps:show(DictShow)))),
  #{show=>fun (V) ->
    case V of
      (_@4) -> (append(<<"(Flip "/utf8>>, (append((Show@29(_@4)), <<")"/utf8>>))))
    end
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 40).
-spec semigroupoidFlip(any()) -> any().
semigroupoidFlip(_@7) -> 
  Compose@30 = (?MEMOIZE((control_semigroupoid@ps:compose(_@7)))),
  #{compose=>fun (V) ->
    fun (V1) ->
      case { V, V1 } of
        ({ _@8, _@9 }) -> ((Compose@30(_@9))(_@8))
      end
    end
  end}
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 40).
-spec semigroupoidFlip() -> any().
semigroupoidFlip() -> fun (_@10) ->
  (semigroupoidFlip(_@10))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 20).
-spec ordFlip() -> any().
ordFlip() -> fun (DictOrd) ->
  DictOrd
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 16).
-spec newtypeFlip() -> any().
newtypeFlip() -> #{'Coercible0'=>fun (_) ->
  undefined
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 25).
-spec functorFlip() -> any().
functorFlip() -> fun (DictBifunctor) ->
  Lmap@31 = (?MEMOIZE((data_bifunctor@ps:lmap(DictBifunctor)))),
  #{map=>fun (F) ->
    fun (V) ->
      case { F, V } of
        ({ _@11, _@12 }) -> ((Lmap@31(_@11))(_@12))
      end
    end
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 18).
-spec eqFlip() -> any().
eqFlip() -> fun (DictEq) ->
  DictEq
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 37).
-spec contravariantFlip() -> any().
contravariantFlip() -> fun (DictProfunctor) ->
  Lcmap@32 = (?MEMOIZE((data_profunctor@ps:lcmap(DictProfunctor)))),
  #{cmap=>fun (F) ->
    fun (V) ->
      case { F, V } of
        ({ _@13, _@14 }) -> ((Lcmap@32(_@13))(_@14))
      end
    end
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 43).
-spec categoryFlip() -> any().
categoryFlip() -> fun (DictCategory) ->
  SemigroupoidFlip1@33 = (?MEMOIZE((semigroupoidFlip(((maps:get('Semigroupoid0', DictCategory))(undefined)))))),
  #{identity=>(?MEMOIZE((control_category@ps:identity(DictCategory)))), 'Semigroupoid0'=>fun (_) ->
    SemigroupoidFlip1@33
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 28).
-spec bifunctorFlip(any()) -> any().
bifunctorFlip(_@18) -> 
  Bimap@34 = (?MEMOIZE((data_bifunctor@ps:bimap(_@18)))),
  #{bimap=>fun (F) ->
    fun (G) ->
      fun (V) ->
        case { F, G, V } of
          ({ _@19, _@20, _@21 }) -> (((Bimap@34(_@20))(_@19))(_@21))
        end
      end
    end
  end}
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 28).
-spec bifunctorFlip() -> any().
bifunctorFlip() -> fun (_@22) ->
  (bifunctorFlip(_@22))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 31).
-spec biapplyFlip(any()) -> any().
biapplyFlip(_@25) -> 
  Biapply@35 = (?MEMOIZE((control_biapply@ps:biapply(_@25)))),
  BifunctorFlip1@36 = (?MEMOIZE((bifunctorFlip(((maps:get('Bifunctor0', _@25))(undefined)))))),
  #{biapply=>fun (V) ->
    fun (V1) ->
      case { V, V1 } of
        ({ _@26, _@27 }) -> ((Biapply@35(_@26))(_@27))
      end
    end
  end, 'Bifunctor0'=>fun (_) ->
    BifunctorFlip1@36
  end}
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 31).
-spec biapplyFlip() -> any().
biapplyFlip() -> fun (_@28) ->
  (biapplyFlip(_@28))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/functors/e936f7a8d2ec53a344c478ccada5add93273848c/src/Data/Functor/Flip.purs", 34).
-spec biapplicativeFlip() -> any().
biapplicativeFlip() -> fun (DictBiapplicative) ->
  Bipure@37 = (?MEMOIZE((control_biapplicative@ps:bipure(DictBiapplicative)))),
  BiapplyFlip1@38 = (?MEMOIZE((biapplyFlip(((maps:get('Biapply0', DictBiapplicative))(undefined)))))),
  #{bipure=>fun (A) ->
    fun (B) ->
      ((Bipure@37(B))(A))
    end
  end, 'Biapply0'=>fun (_) ->
    BiapplyFlip1@38
  end}
end.
