#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Alt::*;
use Purs_Control_Alternative::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Comonad::*;
use Purs_Control_Extend::*;
use Purs_Control_Lazy::*;
use Purs_Control_Monad::*;
use Purs_Control_MonadPlus::*;
use Purs_Control_Monad_Rec_Class::*;
use Purs_Control_Plus::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Bifunctor::*;
use Purs_Data_Boolean::*;
use Purs_Data_BooleanAlgebra::*;
use Purs_Data_Bounded::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Const::*;
use Purs_Data_Either::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Foldable::*;
use Purs_Data_FoldableWithIndex::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_FunctorWithIndex::*;
use Purs_Data_Functor_App::*;
use Purs_Data_Functor_Compose::*;
use Purs_Data_Functor_Coproduct::*;
use Purs_Data_Functor_Invariant::*;
use Purs_Data_Functor_Product::*;
use Purs_Data_Generic_Rep::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Identity::*;
use Purs_Data_Lazy::*;
use Purs_Data_List_Internal::*;
use Purs_Data_List_Lazy::*;
use Purs_Data_List_Lazy_Types::*;
use Purs_Data_List_Types::*;
use Purs_Data_Maybe::*;
use Purs_Data_Maybe_First::*;
use Purs_Data_Maybe_Last::*;
use Purs_Data_Monoid::*;
use Purs_Data_Monoid_Additive::*;
use Purs_Data_Monoid_Alternate::*;
use Purs_Data_Monoid_Conj::*;
use Purs_Data_Monoid_Disj::*;
use Purs_Data_Monoid_Dual::*;
use Purs_Data_Monoid_Endo::*;
use Purs_Data_Monoid_Multiplicative::*;
use Purs_Data_Newtype::*;
use Purs_Data_NonEmpty::*;
use Purs_Data_Ord::*;
use Purs_Data_Ord_Max::*;
use Purs_Data_Ord_Min::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semigroup_Foldable::*;
use Purs_Data_Semigroup_Traversable::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Traversable::*;
use Purs_Data_TraversableWithIndex::*;
use Purs_Data_Traversable_Accum_Internal::*;
use Purs_Data_Tuple::*;
use Purs_Data_Unfoldable::*;
use Purs_Data_Unfoldable1::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Effect::*;
use Purs_Effect_Ref::*;
use Purs_Partial::*;
use Purs_Partial_Unsafe::*;
use Purs_Record_Unsafe::*;
use Purs_Safe_Coerce::*;
use Purs_Type_Proxy::*;
use Purs_Unsafe_Coerce::*;
use Purs_Control_Alt::*;
use Purs_Control_Alternative::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Plus::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Function::*;
use Purs_Data_List_Lazy::*;
use Purs_Data_List_Lazy_Types::*;
use Purs_Data_Monoid::*;
use Purs_Data_Newtype::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Show::*;
use Purs_Partial_Unsafe::*;
use Purs_Data_Lazy::*;
use Purs_Data_Traversable::*;
use Purs_Data_Ord::*;
use Purs_Data_Functor::*;
use Purs_Data_Foldable::*;
use Purs_Data_Eq::*;

// Code generated by purust for module Data_List_ZipList



pub fn Data_List_ZipList_ZipList(mut purs_local_0: std::rc::Rc<Purs_Data_Lazy::Lazy>) -> std::rc::Rc<Purs_Data_Lazy::Lazy> {
    // AST: Typed(Abs(..., Local(...)))
purs_local_0
}

pub fn Data_List_ZipList_traversableZipList() -> std::rc::Rc<Purs_Data_Traversable::Traversable> {
    // AST: Typed(Var(...))
/* Typed std::rc::Rc<Purs_Data_Traversable::Traversable> <- std::rc::Rc<Purs_Data_Traversable::Traversable> : Var(...) */Data_List_Lazy_Types_traversableList()
}

pub fn Data_List_ZipList_showZipList(mut purs_local_0: std::rc::Rc<Purs_Data_Show::Show>) -> std::rc::Rc<Purs_Data_Show::Show> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Show::Show> <- std::rc::Rc<Purs_Data_Show::Show> : App(Var(...)) */Data_List_Lazy_Types_showList(purs_local_0);
    std::rc::Rc::new(Purs_Data_Show::Show { show: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: std::rc::Rc<Purs_Data_Lazy::Lazy>| -> String {
    let mut purs_local_2 = _a0;
    /* Typed String <- String : PrimOp(...) */format!("{}{}", format!("{}{}", String::from("(ZipList "), ((purs_local_1.clone()).show.clone())(purust_core::Value::Class(std::rc::Rc::new(/* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- std::rc::Rc<Purs_Data_Lazy::Lazy> : Local(...) */purs_local_2)))), String::from(")"))
}))).clone(); move |mut _a0: crate::UnknownType| -> String { _f((_a0).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone()) } })) })
}
}

pub fn Data_List_ZipList_semigroupZipList() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Var(...)))
/* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_List_Lazy_Types_semigroupList()
}

pub fn Data_List_ZipList_ordZipList(mut purs_local_0: std::rc::Rc<Purs_Data_Ord::Ord>) -> std::rc::Rc<Purs_Data_Ord::Ord> {
    // AST: Typed(Typed(Abs(..., Typed(App(Var(...))))))
/* Typed std::rc::Rc<Purs_Data_Ord::Ord> <- std::rc::Rc<Purs_Data_Ord::Ord> : App(Var(...)) */Data_List_Lazy_Types_ordList(purs_local_0)
}

pub fn Data_List_ZipList_newtypeZipList() -> std::rc::Rc<Purs_Data_Newtype::Newtype> {
    // AST: Typed(Typed(Typed(Lit)))
std::rc::Rc::new(Purs_Data_Newtype::Newtype { Coercible0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
} as fn(crate::UnknownType) -> crate::UnknownType) })
}

pub fn Data_List_ZipList_monoidZipList() -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Var(...)))
/* Typed std::rc::Rc<Purs_Data_Monoid::Monoid> <- std::rc::Rc<Purs_Data_Monoid::Monoid> : Var(...) */Data_List_Lazy_Types_monoidList()
}

pub fn Data_List_ZipList_functorZipList() -> std::rc::Rc<Purs_Data_Functor::Functor> {
    // AST: Typed(Var(...))
/* Typed std::rc::Rc<Purs_Data_Functor::Functor> <- std::rc::Rc<Purs_Data_Functor::Functor> : Var(...) */Data_List_Lazy_Types_functorList()
}

pub fn Data_List_ZipList_foldableZipList() -> std::rc::Rc<Purs_Data_Foldable::Foldable> {
    // AST: Typed(Var(...))
/* Typed std::rc::Rc<Purs_Data_Foldable::Foldable> <- std::rc::Rc<Purs_Data_Foldable::Foldable> : Var(...) */Data_List_Lazy_Types_foldableList()
}

pub fn Data_List_ZipList_eqZipList(mut purs_local_0: std::rc::Rc<Purs_Data_Eq::Eq>) -> std::rc::Rc<Purs_Data_Eq::Eq> {
    // AST: Typed(Typed(Abs(..., Typed(App(Var(...))))))
/* Typed std::rc::Rc<Purs_Data_Eq::Eq> <- std::rc::Rc<Purs_Data_Eq::Eq> : App(Var(...)) */Data_List_Lazy_Types_eqList(purs_local_0)
}

pub fn Data_List_ZipList_applyZipList() -> std::rc::Rc<Purs_Control_Apply::Apply> {
    // AST: Typed(Typed(Lit))
std::rc::Rc::new(Purs_Control_Apply::Apply { apply: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: std::rc::Rc<Purs_Data_Lazy::Lazy>, mut _a1: std::rc::Rc<Purs_Data_Lazy::Lazy>| -> std::rc::Rc<Purs_Data_Lazy::Lazy> {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- std::rc::Rc<Purs_Data_Lazy::Lazy> : App(TypeApp(TypeApp(TypeApp(Var(...))))) */Data_List_Lazy_zipWith(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<purust_core::Func1<crate::UnknownType, crate::UnknownType>, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<purust_core::Func1<crate::UnknownType, crate::UnknownType>, crate::UnknownType, crate::UnknownType> : Var(...) */purust_core::Func2::Static(Data_Function_apply)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { _f(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0).unwrap_func1(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } })), _a1) } })), /* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- std::rc::Rc<Purs_Data_Lazy::Lazy> : Local(...) */purs_local_0, /* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- std::rc::Rc<Purs_Data_Lazy::Lazy> : Local(...) */purs_local_1)
} as fn(std::rc::Rc<Purs_Data_Lazy::Lazy>, std::rc::Rc<Purs_Data_Lazy::Lazy>) -> std::rc::Rc<Purs_Data_Lazy::Lazy>)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone(), (_a1).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone()))) } })), Functor0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Functor::Functor> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Functor::Functor> <- std::rc::Rc<Purs_Data_Functor::Functor> : Var(...) */Data_List_Lazy_Types_functorList()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Functor::Functor>) })
}

pub fn Data_List_ZipList_zipListIsNotBind(mut purs_local_0: crate::UnknownType) -> std::rc::Rc<Purs_Control_Bind::Bind> {
    // AST: Typed(Abs(..., Typed(Typed(Lit))))
std::rc::Rc::new(Purs_Control_Bind::Bind { bind: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<std::rc::Rc<Purs_Data_Lazy::Lazy>, purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Lazy::Lazy>>, std::rc::Rc<Purs_Data_Lazy::Lazy>> <- crate::UnknownType : App(Var(...)) */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (Partial__crashWith(/* Typed String <- String : Lit */String::from("bind: unreachable"))).unwrap_func2(); move |mut _a0: std::rc::Rc<Purs_Data_Lazy::Lazy>, mut _a1: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Lazy::Lazy>>| -> std::rc::Rc<Purs_Data_Lazy::Lazy> { (_f(purust_core::Value::Class(std::rc::Rc::new(_a0)), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a1).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f(_a0))) } }))))).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone() } }))).clone(); move |mut _a0: crate::UnknownType, mut _a1: purust_core::Func1<crate::UnknownType, crate::UnknownType>| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone(), purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a1).clone(); move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Lazy::Lazy> { (_f(_a0)).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone() } }))))) } })), Apply0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Control_Apply::Apply> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Control_Apply::Apply> <- std::rc::Rc<Purs_Control_Apply::Apply> : Var(...) */Data_List_ZipList_applyZipList()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Control_Apply::Apply>) })
}

pub fn Data_List_ZipList_applicativeZipList() -> std::rc::Rc<Purs_Control_Applicative::Applicative> {
    // AST: Typed(Typed(Lit))
std::rc::Rc::new(Purs_Control_Applicative::Applicative { pure: purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Lazy::Lazy>> <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(TypeApp(TypeApp(Var(...))))))) */purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (Control_Semigroupoid_compose(/* Typed std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> <- std::rc::Rc<Purs_Control_Semigroupoid::Semigroupoid> : Var(...) */Control_Semigroupoid_semigroupoidFn(), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<std::rc::Rc<Purs_Data_Lazy::Lazy>, std::rc::Rc<Purs_Data_Lazy::Lazy>> <- purust_core::Func1<std::rc::Rc<Purs_Data_Lazy::Lazy>, std::rc::Rc<Purs_Data_Lazy::Lazy>> : Var(...) */purust_core::Func1::Static(Data_List_ZipList_ZipList)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone()))) } }))), purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Lazy::Lazy>> <- purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Lazy::Lazy>> : Var(...) */purust_core::Func1::Static(Data_List_Lazy_repeat)).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f(_a0))) } }))))).unwrap_func1(); move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Lazy::Lazy> { (_f(_a0)).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone() } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f(_a0))) } })), Apply0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Control_Apply::Apply> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Control_Apply::Apply> <- std::rc::Rc<Purs_Control_Apply::Apply> : Var(...) */Data_List_ZipList_applyZipList()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Control_Apply::Apply>) })
}

pub fn Data_List_ZipList_altZipList() -> std::rc::Rc<Purs_Control_Alt::Alt> {
    // AST: Typed(Typed(Lit))
std::rc::Rc::new(Purs_Control_Alt::Alt { alt: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: std::rc::Rc<Purs_Data_Lazy::Lazy>, mut _a1: std::rc::Rc<Purs_Data_Lazy::Lazy>| -> std::rc::Rc<Purs_Data_Lazy::Lazy> {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    /* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- crate::UnknownType : App(Accessor(Var(...))) */(((Data_List_Lazy_Types_semigroupList()).append.clone())(purust_core::Value::Class(std::rc::Rc::new(/* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- std::rc::Rc<Purs_Data_Lazy::Lazy> : Local(...) */purs_local_0.clone())), purust_core::Value::Class(std::rc::Rc::new(/* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- std::rc::Rc<Purs_Data_Lazy::Lazy> : App(TypeApp(Var(...))) */Data_List_Lazy_drop(/* Typed i64 <- i64 : App(TypeApp(Var(...))) */Data_List_Lazy_length(/* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- std::rc::Rc<Purs_Data_Lazy::Lazy> : Local(...) */purs_local_0), /* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- std::rc::Rc<Purs_Data_Lazy::Lazy> : Local(...) */purs_local_1))))).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone()
} as fn(std::rc::Rc<Purs_Data_Lazy::Lazy>, std::rc::Rc<Purs_Data_Lazy::Lazy>) -> std::rc::Rc<Purs_Data_Lazy::Lazy>)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone(), (_a1).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone()))) } })), Functor0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Functor::Functor> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Functor::Functor> <- std::rc::Rc<Purs_Data_Functor::Functor> : Var(...) */Data_List_Lazy_Types_functorList()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Functor::Functor>) })
}

pub fn Data_List_ZipList_plusZipList() -> std::rc::Rc<Purs_Control_Plus::Plus> {
    // AST: Typed(Typed(Lit))
std::rc::Rc::new(Purs_Control_Plus::Plus { empty: purust_core::Value::Class(std::rc::Rc::new(/* Typed std::rc::Rc<Purs_Data_Lazy::Lazy> <- crate::UnknownType : App(Var(...)) */(Data_Monoid_mempty(Data_List_ZipList_monoidZipList())).unwrap_class::<std::rc::Rc<Purs_Data_Lazy::Lazy>>().clone())), Alt0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Control_Alt::Alt> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Control_Alt::Alt> <- std::rc::Rc<Purs_Control_Alt::Alt> : Var(...) */Data_List_ZipList_altZipList()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Control_Alt::Alt>) })
}

pub fn Data_List_ZipList_alternativeZipList() -> std::rc::Rc<Purs_Control_Alternative::Alternative> {
    // AST: Typed(Typed(Lit))
std::rc::Rc::new(Purs_Control_Alternative::Alternative { Applicative0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Control_Applicative::Applicative> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Control_Applicative::Applicative> <- std::rc::Rc<Purs_Control_Applicative::Applicative> : Var(...) */Data_List_ZipList_applicativeZipList()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Control_Applicative::Applicative>), Plus1: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Control_Plus::Plus> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Control_Plus::Plus> <- std::rc::Rc<Purs_Control_Plus::Plus> : Var(...) */Data_List_ZipList_plusZipList()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Control_Plus::Plus>) })
}





