% Generated by purerl version 0.0.24
-module(safe_coerce@ps).
-export([coerce/0, coerce/2, coerce/1]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./safe_coerce.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/safe-coerce/e719defd227d932da067a1f0d62a60b3d3ff3637/src/Safe/Coerce.purs", 26).
-spec coerce() -> fun((any()) -> fun((any()) -> any())).
coerce() -> fun (_) ->
  fun unsafe_coerce@ps:unsafeCoerce/1
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/safe-coerce/e719defd227d932da067a1f0d62a60b3d3ff3637/src/Safe/Coerce.purs", 26).
-spec coerce(any(),any()) -> any().
coerce(_@2,_@3) -> (((coerce())(_@2))(_@3)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/safe-coerce/e719defd227d932da067a1f0d62a60b3d3ff3637/src/Safe/Coerce.purs", 26).
-spec coerce(any()) -> any().
coerce(_@0) -> fun unsafe_coerce@ps:unsafeCoerce/1.
