% Generated by purerl version 0.0.24
-module(test_fileOps@ps).
-export([loopIO/1, loopIO/0, describe/0, act/0, writeFileSync/0, writeFileSync/2, readFileSync/0, readFileSync/1, loopE/0, loopE/2]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./test_fileOps.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/FileOps/FileOps.purs", 11).
-spec loopIO(integer()) -> fun(() -> any()).
loopIO(_@10) -> (loopE(_@10, fun
  __do() -> 
  ((writeFileSync(<<"var/iotest.txt"/utf8>>, <<"Hello IO Benchmarks!"/utf8>>))()),
  ((test_fileOps@foreign:readFileSync(<<"var/iotest.txt"/utf8>>))()),
  unit
end)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/FileOps/FileOps.purs", 11).
-spec loopIO() -> fun((integer()) -> fun(() -> any())).
loopIO() -> fun (_@11) ->
  (loopIO(_@11))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/FileOps/FileOps.purs", 17).
-spec describe() -> fun(() -> any()).
describe() -> (effect_console@ps:log(<<"File I/O (10k writes/reads):"/utf8>>)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/FileOps/FileOps.purs", 20).
-spec act() -> fun(() -> any()).
act() -> (loopIO(10000)).
-spec writeFileSync() -> fun((binary()) -> fun((binary()) -> fun(() -> any()))).
writeFileSync() -> fun (_@12) ->
  fun (_@13) ->
    ((test_fileOps@foreign:writeFileSync(_@12))(_@13))
  end
end.
-spec writeFileSync(binary(),binary()) -> fun(() -> any()).
writeFileSync(_@17,_@18) -> (((writeFileSync())(_@17))(_@18)).
-spec readFileSync() -> fun((binary()) -> fun(() -> binary())).
readFileSync() -> fun (_@19) ->
  (test_fileOps@foreign:readFileSync(_@19))
end.
-spec readFileSync(binary()) -> fun(() -> binary()).
readFileSync(_@22) -> ((readFileSync())(_@22)).
-spec loopE() -> fun((integer()) -> fun((fun(() -> any())) -> fun(() -> any()))).
loopE() -> fun (_@23) ->
  fun (_@24) ->
    ((test_fileOps@foreign:loopE(_@23))(_@24))
  end
end.
-spec loopE(integer(),fun(() -> any())) -> fun(() -> any()).
loopE(_@28,_@29) -> (((loopE())(_@28))(_@29)).
