#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Unsafe_Coerce::*;
use Purs_Unsafe_Coerce::*;

// Code generated by purust for module Safe_Coerce



pub fn Safe_Coerce_coerce(mut a0: crate::UnknownType, mut a1: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Typed(Var(...)))))
(/* Typed Abs */purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> purust_core::Func1<crate::UnknownType, crate::UnknownType> {
    drop(_a0);
    /* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Var(...) */purust_core::Func1::Static(Unsafe_Coerce_unsafeCoerce)
} as fn(crate::UnknownType) -> purust_core::Func1<crate::UnknownType, crate::UnknownType>)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone()) } })))(a0.clone(), a1.clone())
}





