% Generated by purerl version 0.0.24
-module(effect_class_console@ps).
-export([warnShow/0, warnShow/3, warnShow/2, warn/0, warn/2, warn/1, timeLog/0, timeLog/2, timeLog/1, timeEnd/0, timeEnd/2, timeEnd/1, time/0, time/2, time/1, logShow/0, logShow/3, logShow/2, log/0, log/2, log/1, infoShow/0, infoShow/3, infoShow/2, info/0, info/2, info/1, errorShow/0, errorShow/3, errorShow/2, error/0, error/2, error/1, clear/1, clear/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./effect_class_console.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 0).
-spec compose() -> any().
compose() -> (?MEMOIZE((control_semigroupoid@ps:compose((control_semigroupoid@ps:semigroupoidFn()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 0).
-spec compose(any(),any()) -> any().
compose(_@2,_@3) -> (((compose())(_@2))(_@3)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 18).
-spec warnShow() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
warnShow() -> fun (DictMonadEffect) ->
  LiftEffect@58 = (?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))),
  fun (DictShow) ->
    (compose(LiftEffect@58, (?MEMOIZE((effect_console@ps:warnShow(DictShow))))))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 18).
-spec warnShow(any(),any(),any()) -> any().
warnShow(_@7,_@8,_@9) -> ((((warnShow())(_@7))(_@8))(_@9)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 18).
-spec warnShow(any(),any()) -> any().
warnShow(_@4,_@5) -> 
  LiftEffect@59 = (?MEMOIZE((effect_class@ps:liftEffect(_@4)))),
  (compose(LiftEffect@59, (?MEMOIZE((effect_console@ps:warnShow(_@5))))))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 15).
-spec warn() -> fun((any()) -> fun((binary()) -> any())).
warn() -> fun (DictMonadEffect) ->
  (compose((?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))), fun effect_console@ps:warn/1))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 15).
-spec warn(any(),binary()) -> any().
warn(_@12,_@13) -> (((warn())(_@12))(_@13)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 15).
-spec warn(any()) -> any().
warn(_@10) -> (compose((?MEMOIZE((effect_class@ps:liftEffect(_@10)))), fun effect_console@ps:warn/1)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 36).
-spec timeLog() -> fun((any()) -> fun((binary()) -> any())).
timeLog() -> fun (DictMonadEffect) ->
  (compose((?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))), fun effect_console@ps:timeLog/1))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 36).
-spec timeLog(any(),binary()) -> any().
timeLog(_@16,_@17) -> (((timeLog())(_@16))(_@17)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 36).
-spec timeLog(any()) -> any().
timeLog(_@14) -> (compose((?MEMOIZE((effect_class@ps:liftEffect(_@14)))), fun effect_console@ps:timeLog/1)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 39).
-spec timeEnd() -> fun((any()) -> fun((binary()) -> any())).
timeEnd() -> fun (DictMonadEffect) ->
  (compose((?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))), fun effect_console@ps:timeEnd/1))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 39).
-spec timeEnd(any(),binary()) -> any().
timeEnd(_@20,_@21) -> (((timeEnd())(_@20))(_@21)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 39).
-spec timeEnd(any()) -> any().
timeEnd(_@18) -> (compose((?MEMOIZE((effect_class@ps:liftEffect(_@18)))), fun effect_console@ps:timeEnd/1)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 33).
-spec time() -> fun((any()) -> fun((binary()) -> any())).
time() -> fun (DictMonadEffect) ->
  (compose((?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))), fun effect_console@ps:time/1))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 33).
-spec time(any(),binary()) -> any().
time(_@24,_@25) -> (((time())(_@24))(_@25)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 33).
-spec time(any()) -> any().
time(_@22) -> (compose((?MEMOIZE((effect_class@ps:liftEffect(_@22)))), fun effect_console@ps:time/1)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 12).
-spec logShow() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
logShow() -> fun (DictMonadEffect) ->
  LiftEffect@60 = (?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))),
  fun (DictShow) ->
    (compose(LiftEffect@60, (?MEMOIZE((effect_console@ps:logShow(DictShow))))))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 12).
-spec logShow(any(),any(),any()) -> any().
logShow(_@29,_@30,_@31) -> ((((logShow())(_@29))(_@30))(_@31)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 12).
-spec logShow(any(),any()) -> any().
logShow(_@26,_@27) -> 
  LiftEffect@61 = (?MEMOIZE((effect_class@ps:liftEffect(_@26)))),
  (compose(LiftEffect@61, (?MEMOIZE((effect_console@ps:logShow(_@27))))))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 9).
-spec log() -> fun((any()) -> fun((binary()) -> any())).
log() -> fun (DictMonadEffect) ->
  (compose((?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))), fun effect_console@ps:log/1))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 9).
-spec log(any(),binary()) -> any().
log(_@34,_@35) -> (((log())(_@34))(_@35)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 9).
-spec log(any()) -> any().
log(_@32) -> (compose((?MEMOIZE((effect_class@ps:liftEffect(_@32)))), fun effect_console@ps:log/1)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 30).
-spec infoShow() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
infoShow() -> fun (DictMonadEffect) ->
  LiftEffect@62 = (?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))),
  fun (DictShow) ->
    (compose(LiftEffect@62, (?MEMOIZE((effect_console@ps:infoShow(DictShow))))))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 30).
-spec infoShow(any(),any(),any()) -> any().
infoShow(_@39,_@40,_@41) -> ((((infoShow())(_@39))(_@40))(_@41)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 30).
-spec infoShow(any(),any()) -> any().
infoShow(_@36,_@37) -> 
  LiftEffect@63 = (?MEMOIZE((effect_class@ps:liftEffect(_@36)))),
  (compose(LiftEffect@63, (?MEMOIZE((effect_console@ps:infoShow(_@37))))))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 27).
-spec info() -> fun((any()) -> fun((binary()) -> any())).
info() -> fun (DictMonadEffect) ->
  (compose((?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))), fun effect_console@ps:info/1))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 27).
-spec info(any(),binary()) -> any().
info(_@44,_@45) -> (((info())(_@44))(_@45)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 27).
-spec info(any()) -> any().
info(_@42) -> (compose((?MEMOIZE((effect_class@ps:liftEffect(_@42)))), fun effect_console@ps:info/1)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 24).
-spec errorShow() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
errorShow() -> fun (DictMonadEffect) ->
  LiftEffect@64 = (?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))),
  fun (DictShow) ->
    (compose(LiftEffect@64, (?MEMOIZE((effect_console@ps:errorShow(DictShow))))))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 24).
-spec errorShow(any(),any(),any()) -> any().
errorShow(_@49,_@50,_@51) -> ((((errorShow())(_@49))(_@50))(_@51)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 24).
-spec errorShow(any(),any()) -> any().
errorShow(_@46,_@47) -> 
  LiftEffect@65 = (?MEMOIZE((effect_class@ps:liftEffect(_@46)))),
  (compose(LiftEffect@65, (?MEMOIZE((effect_console@ps:errorShow(_@47))))))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 21).
-spec error() -> fun((any()) -> fun((binary()) -> any())).
error() -> fun (DictMonadEffect) ->
  (compose((?MEMOIZE((effect_class@ps:liftEffect(DictMonadEffect)))), fun effect_console@ps:error/1))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 21).
-spec error(any(),binary()) -> any().
error(_@54,_@55) -> (((error())(_@54))(_@55)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 21).
-spec error(any()) -> any().
error(_@52) -> (compose((?MEMOIZE((effect_class@ps:liftEffect(_@52)))), fun effect_console@ps:error/1)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 42).
-spec clear(any()) -> any().
clear(_@56) -> (effect_class@ps:liftEffect(_@56, (effect_console@ps:clear()))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/console/56cfd5294acb79758cf30b357751f624650f18e3/src/Effect/Class/Console.purs", 42).
-spec clear() -> fun((any()) -> any()).
clear() -> fun (_@57) ->
  (clear(_@57))
end.
