// Generated by purs version 0.15.16
import * as Data_Array from "../Data.Array/index.js";
import * as Data_Either from "../Data.Either/index.js";
import * as Data_Show from "../Data.Show/index.js";
import * as Data_String_CodePoints from "../Data.String.CodePoints/index.js";
import * as Data_String_Common from "../Data.String.Common/index.js";
import * as Data_String_Regex from "../Data.String.Regex/index.js";
import * as Data_String_Regex_Flags from "../Data.String.Regex.Flags/index.js";
import * as Effect_Console from "../Effect.Console/index.js";
var show = /* #__PURE__ */ Data_Show.show(Data_Show.showInt);
var regexPattern = /* #__PURE__ */ (function () {
    var v = Data_String_Regex.regex("(hello|world)[0-9]+")(Data_String_Regex_Flags.noFlags);
    if (v instanceof Data_Either.Right) {
        return v.value0;
    };
    throw new Error("Failed pattern match at Test.StringOps (line 15, column 31 - line 15, column 89): " + [ v.constructor.name ]);
})();
var runStringOps = function (n) {
    var loop = function ($copy_v) {
        return function ($copy_v1) {
            return function ($copy_v2) {
                var $tco_var_v = $copy_v;
                var $tco_var_v1 = $copy_v1;
                var $tco_done = false;
                var $tco_result;
                function $tco_loop(v, v1, v2) {
                    if (v === 0) {
                        $tco_done = true;
                        return v2;
                    };
                    var concatted = v1 + (show(v) + ("world" + show(v + 1 | 0)));
                    var replaced = Data_String_Regex.replace(regexPattern)("matched")(concatted);
                    var splitted = Data_String_Common.split("e")(replaced);
                    $tco_var_v = v - 1 | 0;
                    $tco_var_v1 = Data_String_CodePoints.take(10)(concatted);
                    $copy_v2 = v2 + Data_Array.length(splitted) | 0;
                    return;
                };
                while (!$tco_done) {
                    $tco_result = $tco_loop($tco_var_v, $tco_var_v1, $copy_v2);
                };
                return $tco_result;
            };
        };
    };
    return loop(n)("hello")(0);
};
var describe = /* #__PURE__ */ Effect_Console.log("String Operations (1k Regex/Split):");
var act = /* #__PURE__ */ Effect_Console.logShow(Data_Show.showInt)(/* #__PURE__ */ runStringOps(1000));
export {
    regexPattern,
    runStringOps,
    describe,
    act
};
//# sourceMappingURL=index.js.map
