[<AutoOpen>]
module PureScript_Control_Monad_Gen_Common

open System
open System.Collections.Generic

let Control_Monad_Gen_Common_genTuple  = (box (fun (dictApply: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_lift2))) (box ((box dictApply)))))) (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))))))

let Control_Monad_Gen_Common_genNonEmpty  = (box (fun (dictMonadRec: obj) -> (box (fun (dictMonadGen: obj) -> (let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box Bind1)))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((box Bind1)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (dictUnfoldable: obj) -> (box (fun (gen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Apply0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2)))))))))))) (box ((box gen))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_resize))) (box ((box dictMonadGen)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_max))) (box ((box Data_Ord_ordInt)))))) (box ((box 0))))))))) (box ((box (fun (v: obj) -> (box ((unbox<int> (box ((box v)))) - (unbox<int> (box ((box 1)))))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_unfoldable))) (box ((box dictMonadRec)))))) (box ((box dictMonadGen)))))) (box ((box dictUnfoldable)))))) (box ((box gen)))))))))))))))))))

let Control_Monad_Gen_Common_genMaybe_prime  = (box (fun (dictMonadGen: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let Applicative0 = (sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in (box (fun (bias: obj) -> (box (fun (gen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseFloat))) (box ((box dictMonadGen)))))) (box ((box 0.0)))))) (box ((box 1.0))))))))) (box ((box (fun (n: obj) -> (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_lessThan))) (box ((box Data_Ord_ordNumber)))))) (box ((box n)))))) (box ((box bias))))))) with | LitBool true () -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))))) (box ((box gen))))) | _ -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Applicative0)))))) (box ((box Data_Maybe_Nothingusd_Ctor))))))))))))))))))

let Control_Monad_Gen_Common_genMaybe  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Common_genMaybe_prime))) (box ((box dictMonadGen)))))) (box ((box 0.75))))))

let Control_Monad_Gen_Common_genIdentity  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box Data_Identity_Identity))))))

let Control_Monad_Gen_Common_genEither_prime  = (box (fun (dictMonadGen: obj) -> (let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box Monad0)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (bias: obj) -> (box (fun (genA: obj) -> (box (fun (genB: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseFloat))) (box ((box dictMonadGen)))))) (box ((box 0.0)))))) (box ((box 1.0))))))))) (box ((box (fun (n: obj) -> (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_lessThan))) (box ((box Data_Ord_ordNumber)))))) (box ((box n)))))) (box ((box bias))))))) with | LitBool true () -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1))))))))))) (box ((box genA))))) | _ -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1))))))))))) (box ((box genB))))))))))))))))))))

let Control_Monad_Gen_Common_genEither  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Common_genEither_prime))) (box ((box dictMonadGen)))))) (box ((box 0.5))))))
