[<AutoOpen>]
module PureScript_Data_List_Lazy

open System
open System.Collections.Generic

let Data_List_Lazy_unwrap  = (sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined))))

let Data_List_Lazy_one  = (sharpurs_apply (box ((box Data_Semiring_one))) (box ((box Data_Semiring_semiringInt))))

let Data_List_Lazy_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_List_Lazy_Pattern  = (box (fun (x: obj) -> (box x)))

let rec Data_List_Lazy_zipWith_tco (f: obj) (xs: obj) (ys: obj) : obj = ((let go = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_List_Lazy_Types_Nilusd_Ctor, _) -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | (Data_List_Lazy_Types_Consusd_Ctor(a, as_var), Data_List_Lazy_Types_Consusd_Ctor(b, bs)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box a)))))) (box ((box b))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_zipWith))) (box ((box f)))))) (box ((box as_var)))))) (box ((box bs))))))))))))) in (sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Data_Lazy_applyLazy)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box xs)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box ys))))))))))))
and Data_List_Lazy_zipWith = box (fun (f: obj) ->  (fun (xs: obj) ->  (fun (ys: obj) -> Data_List_Lazy_zipWith_tco f xs ys)))


let Data_List_Lazy_zipWithA  = (box (fun (dictApplicative: obj) -> (box (fun (f: obj) -> (box (fun (xs: obj) -> (box (fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Traversable_sequence))) (box ((box Data_List_Lazy_Types_traversableList)))))) (box ((box dictApplicative)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_zipWith))) (box ((box f)))))) (box ((box xs)))))) (box ((box ys)))))))))))))))

let Data_List_Lazy_zip  = (sharpurs_apply (box ((box Data_List_Lazy_zipWith))) (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))))

let rec Data_List_Lazy_updateAt_tco (n: obj) (x: obj) (xs: obj) : obj = ((let go = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | (LitInt 0 (), Data_List_Lazy_Types_Consusd_Ctor(_, ys)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box ys))))) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(y, ys)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_updateAt))) (box ((box ((unbox<int> (box ((box n_prime)))) - (unbox<int> (box ((box 1))))))))))) (box ((box x)))))) (box ((box ys))))))))))))) in (sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((sharpurs_apply (box ((box go))) (box ((box n))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box xs))))))))))))
and Data_List_Lazy_updateAt = box (fun (n: obj) ->  (fun (x: obj) ->  (fun (xs: obj) -> Data_List_Lazy_updateAt_tco n x xs)))


let Data_List_Lazy_unzip  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldr))) (box ((box Data_List_Lazy_Types_foldableList)))))) (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(a, b) -> ((box (fun (v1: obj) -> (match ((unbox ((box v1)))) with | Data_Tuple_Tupleusd_Ctor(as_var, bs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box a)))))) (box ((box as_var))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box b)))))) (box ((box bs)))))))))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box Data_List_Lazy_Types_nil)))))) (box ((box Data_List_Lazy_Types_nil)))))))

let Data_List_Lazy_uncons  = (box (fun (xs: obj) -> (let v = (sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs)))) in (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((box Data_Maybe_Nothingusd_Ctor)) | Data_List_Lazy_Types_Consusd_Ctor(x, xs_prime) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box ((Map.add "head" (box ((box x))) (Map.add "tail" (box ((box xs_prime))) Map.empty))))))))))))

let Data_List_Lazy_toUnfoldable  = (box (fun (dictUnfoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Unfoldable_unfoldr))) (box ((box dictUnfoldable)))))) (box ((box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box (fun (rec_var: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((Map.find "head" (unbox<Map<string, obj>> ((box rec_var))))))))) (box ((Map.find "tail" (unbox<Map<string, obj>> ((box rec_var)))))))))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box xs))))))))))))))

let rec Data_List_Lazy_takeWhile_tco (p: obj) : obj = ((let go = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box ((box p))) (box ((box x))))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_takeWhile))) (box ((box p)))))) (box ((box xs)))))))) | _ -> ((box Data_List_Lazy_Types_Nilusd_Ctor))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_Types_List)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go))))))))) (box ((box Data_List_Lazy_unwrap)))))))))
and Data_List_Lazy_takeWhile = box (fun (p: obj) -> Data_List_Lazy_takeWhile_tco p)


let rec Data_List_Lazy_take_tco (n: obj) : obj = ((let go = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(x, xs)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_take))) (box ((box ((unbox<int> (box ((box n_prime)))) - (unbox<int> (box ((box 1))))))))))) (box ((box xs))))))))))))) in (match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_lessThanOrEq))) (box ((box Data_Ord_ordInt)))))) (box ((box n)))))) (box ((box 0))))))) with | LitBool true () -> ((sharpurs_apply (box ((box Data_Function_const))) (box ((box Data_List_Lazy_Types_nil))))) | _ -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_Types_List)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((sharpurs_apply (box ((box go))) (box ((box n)))))))))))) (box ((box Data_List_Lazy_unwrap)))))))))))
and Data_List_Lazy_take = box (fun (n: obj) -> Data_List_Lazy_take_tco n)


let Data_List_Lazy_tail  = (box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box (fun (v: obj) -> (Map.find "tail" (unbox<Map<string, obj>> ((box v))))))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box xs)))))))))

let Data_List_Lazy_stripPrefix  = (box (fun (dictEq: obj) -> (box (fun (v: obj) -> (box (fun (s: obj) -> (match (((unbox ((box v))), (unbox ((box s))))) with | (p_prime, s1) -> ((let go = (box (fun (prefix: obj) -> (box (fun (input: obj) -> (let v1 = (sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box prefix)))) in (match ((unbox ((box v1)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Control_Monad_Rec_Class_Doneusd_Ctor(usd__arg1)))))))) (box ((box input)))))))) | Data_List_Lazy_Types_Consusd_Ctor(p, ps) -> ((let v2 = (sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box input)))) in (match ((unbox ((box v2)))) with | Data_List_Lazy_Types_Consusd_Ctor(i, is) when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((box p)))))) (box ((box i))))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Control_Monad_Rec_Class_Loopusd_Ctor(usd__arg1)))))))) (box ((box ((Map.add "a" (box ((box ps))) (Map.add "b" (box ((box is))) Map.empty))))))))))) | _ -> ((box Data_Maybe_Nothingusd_Ctor))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Rec_Class_tailRecM2))) (box ((box Control_Monad_Rec_Class_monadRecMaybe)))))) (box ((box go)))))) (box ((box p_prime)))))) (box ((box s1)))))))))))))

let rec Data_List_Lazy_span_tco (p: obj) (xs: obj) : obj = ((let v = (sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box xs)))) in (match ((unbox ((box v)))) with | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (x) & HasProp "tail" (xs_prime)))) when (unbox (sharpurs_apply (box ((box p))) (box ((box x))))) -> ((let v1 = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_span))) (box ((box p)))))) (box ((box xs_prime)))) in (match ((unbox ((box v1)))) with | (HasProp "init" (ys) & HasProp "rest" (zs)) -> ((box ((Map.add "init" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((box ys)))))) (Map.add "rest" (box ((box zs))) Map.empty)))))))) | _ -> ((box ((Map.add "init" (box ((box Data_List_Lazy_Types_nil))) (Map.add "rest" (box ((box xs))) Map.empty))))))))
and Data_List_Lazy_span = box (fun (p: obj) ->  (fun (xs: obj) -> Data_List_Lazy_span_tco p xs))


let Data_List_Lazy_snoc  = (box (fun (xs: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldr))) (box ((box Data_List_Lazy_Types_foldableList)))))) (box ((box Data_List_Lazy_Types_cons)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((box Data_List_Lazy_Types_nil))))))))) (box ((box xs))))))))

let Data_List_Lazy_singleton  = (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box a)))))) (box ((box Data_List_Lazy_Types_nil))))))

let Data_List_Lazy_showPattern  = (box (fun (dictShow: obj) -> (let showList = (sharpurs_apply (box ((box Data_List_Lazy_Types_showList))) (box ((box dictShow)))) in (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | s -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(Pattern ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box showList)))))) (box ((box s))))))))) (box ((box ")"))))))))))))) Map.empty)))))))))

let rec Data_List_Lazy_scanlLazy_tco (f: obj) (acc: obj) (xs: obj) : obj = ((let go = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | Data_List_Lazy_Types_Consusd_Ctor(x, xs_prime) -> ((let acc_prime = (sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box acc)))))) (box ((box x)))) in (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box acc_prime))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_scanlLazy))) (box ((box f)))))) (box ((box acc_prime)))))) (box ((box xs_prime)))))))))))) in (sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box xs))))))))))))
and Data_List_Lazy_scanlLazy = box (fun (f: obj) ->  (fun (acc: obj) ->  (fun (xs: obj) -> Data_List_Lazy_scanlLazy_tco f acc xs)))


let Data_List_Lazy_reverse  = (box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Lazy_defer))) (box ((box Data_List_Lazy_Types_lazyList)))))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldl))) (box ((box Data_List_Lazy_Types_foldableList)))))) (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((box Data_List_Lazy_Types_cons))))))))) (box ((box Data_List_Lazy_Types_nil)))))) (box ((box xs)))))))))))

let rec Data_List_Lazy_replicateM_tco (dictMonad: obj) : obj = ((let Applicative0 = (sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))) in (box (fun (n: obj) -> (box (fun (m: obj) -> (match (((unbox ((box n))), (unbox ((box m))))) with | (n1, m1) when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_lessThan))) (box ((box Data_Ord_ordInt)))))) (box ((box n1)))))) (box ((box Data_List_Lazy_one))))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Applicative0)))))) (box ((box Data_List_Lazy_Types_nil))))) | (n1, m1) when (unbox (box Data_Boolean_otherwise)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((box m1)))))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_replicateM))) (box ((box dictMonad)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ring_sub))) (box ((box Data_Ring_ringInt)))))) (box ((box n1)))))) (box ((box Data_List_Lazy_one))))))))) (box ((box m1))))))))) (box ((box (fun (as_var: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Applicative0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box a)))))) (box ((box as_var)))))))))))))))))))))))))
and Data_List_Lazy_replicateM = box (fun (dictMonad: obj) -> Data_List_Lazy_replicateM_tco dictMonad)


let Data_List_Lazy_repeat  = (box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Lazy_fix))) (box ((box Data_List_Lazy_Types_lazyList)))))) (box ((box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((box xs)))))))))))

let Data_List_Lazy_replicate  = (box (fun (i: obj) -> (box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_take))) (box ((box i)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_repeat))) (box ((box xs)))))))))))

let Data_List_Lazy_range  = (box (fun (start: obj) -> (box (fun (end_var: obj) -> (match (((unbox ((box start))), (unbox ((box end_var))))) with | (start1, end1) when (unbox (box ((unbox<int> (box ((box start1)))) > (unbox<int> (box ((box end1))))))) -> ((let g = (box (fun (x: obj) -> (match ((unbox ((box x)))) with | x1 when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_greaterThanOrEq))) (box ((box Data_Ord_ordInt)))))) (box ((box x1)))))) (box ((box end1))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x1)))))) (box ((box ((unbox<int> (box ((box x1)))) - (unbox<int> (box ((box 1))))))))))))) | x1 when (unbox (box Data_Boolean_otherwise)) -> ((box Data_Maybe_Nothingusd_Ctor))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Unfoldable_unfoldr))) (box ((box Data_List_Lazy_Types_unfoldableList)))))) (box ((box g)))))) (box ((box start1)))))) | (start1, end1) when (unbox (box Data_Boolean_otherwise)) -> ((let f = (box (fun (x: obj) -> (match ((unbox ((box x)))) with | x1 when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_lessThanOrEq))) (box ((box Data_Ord_ordInt)))))) (box ((box x1)))))) (box ((box end1))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x1)))))) (box ((box ((unbox<int> (box ((box x1)))) + (unbox<int> (box ((box 1))))))))))))) | x1 when (unbox (box Data_Boolean_otherwise)) -> ((box Data_Maybe_Nothingusd_Ctor))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Unfoldable_unfoldr))) (box ((box Data_List_Lazy_Types_unfoldableList)))))) (box ((box f)))))) (box ((box start1)))))))))))

let Data_List_Lazy_partition  = (box (fun (f: obj) -> (let go = (box (fun (x: obj) -> (box (fun (v: obj) -> (match (((unbox ((box x))), (unbox ((box v))))) with | (x1, (HasProp "yes" (ys) & HasProp "no" (ns))) -> ((match ((unbox ((sharpurs_apply (box ((box f))) (box ((box x1))))))) with | LitBool true () -> ((box ((Map.add "yes" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x1)))))) (box ((box ys)))))) (Map.add "no" (box ((box ns))) Map.empty))))) | _ -> ((box ((Map.add "yes" (box ((box ys))) (Map.add "no" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x1)))))) (box ((box ns)))))) Map.empty)))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldr))) (box ((box Data_List_Lazy_Types_foldableList)))))) (box ((box go)))))) (box ((box ((Map.add "yes" (box ((box Data_List_Lazy_Types_nil))) (Map.add "no" (box ((box Data_List_Lazy_Types_nil))) Map.empty))))))))))

let Data_List_Lazy_null  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Maybe_isNothing)))))) (box ((box Data_List_Lazy_uncons))))

let Data_List_Lazy_nubBy  = (box (fun (p: obj) -> (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec goStep_tco (v: obj) (v1: obj) : obj = ((match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | (s, Data_List_Lazy_Types_Consusd_Ctor(a, as_var)) -> ((let v2 = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Internal_insertAndLookupBy))) (box ((box p)))))) (box ((box a)))))) (box ((box s)))) in (match ((unbox ((box v2)))) with | (HasProp "found" (found) & HasProp "result" (s_prime)) -> ((match ((unbox ((box found)))) with | LitBool true () -> ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((go_tco ((box s_prime)) ((box as_var))))))) | _ -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box a)))))) (box ((go_tco ((box s_prime)) ((box as_var)))))))))))))) 
                                                                                                                                                                                                        and goStep = box ((fun (v: obj) -> (fun (v1: obj) -> goStep_tco v v1))) 
                                                                                                                                                                                                        and go_tco (s: obj) (v: obj) : obj = ((match (((unbox ((box s))), (unbox ((box v))))) with | (s1, l) -> ((sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((sharpurs_apply (box ((box goStep))) (box ((box s1))))))))) (box ((box l)))))))))) 
                                                                                                                                                                                                        and go = box ((fun (s: obj) -> (fun (v: obj) -> go_tco s v))) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((box go))) (box ((box Data_List_Internal_emptySet))))
                                                                                                                                                                                                        )))

let Data_List_Lazy_nub  = (box (fun (dictOrd: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_nubBy))) (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd)))))))))

let Data_List_Lazy_newtypePattern  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let rec Data_List_Lazy_mapMaybe_tco (f: obj) : obj = ((
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (v: obj) : obj = ((match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) -> ((let v1 = (sharpurs_apply (box ((box f))) (box ((box x)))) in (match ((unbox ((box v1)))) with | Data_Maybe_Nothingusd_Ctor -> ((go_tco ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs))))))) | Data_Maybe_Justusd_Ctor(y) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_mapMaybe))) (box ((box f)))))) (box ((box xs))))))))))))) 
                                                                                                                                                                                                        and go = box ((fun (v: obj) -> go_tco v)) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_Types_List)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go))))))))) (box ((box Data_List_Lazy_unwrap)))))))
                                                                                                                                                                                                        ))
and Data_List_Lazy_mapMaybe = box (fun (f: obj) -> Data_List_Lazy_mapMaybe_tco f)


let rec Data_List_Lazy_some_tco (dictAlternative: obj) : obj = ((let Apply0 = (sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (dictLazy: obj) -> (box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Apply0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_List_Lazy_Types_cons)))))) (box ((box v))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Lazy_defer))) (box ((box dictLazy)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_many))) (box ((box dictAlternative)))))) (box ((box dictLazy)))))) (box ((box v))))))))))))))))))
and Data_List_Lazy_some = box (fun (dictAlternative: obj) -> Data_List_Lazy_some_tco dictAlternative)
 and Data_List_Lazy_many_tco (dictAlternative: obj) : obj = ((let Alt0 = (sharpurs_apply (box ((Map.find "Alt0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Plus1" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in let Applicative0 = (sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictAlternative)))))) (box ((box Prim_undefined)))) in (box (fun (dictLazy: obj) -> (box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Alt_alt))) (box ((box Alt0)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_some))) (box ((box dictAlternative)))))) (box ((box dictLazy)))))) (box ((box v))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Applicative0)))))) (box ((box Data_List_Lazy_Types_nil)))))))))))))
and Data_List_Lazy_many = box (fun (dictAlternative: obj) -> Data_List_Lazy_many_tco dictAlternative)


let Data_List_Lazy_length  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldl))) (box ((box Data_List_Lazy_Types_foldableList)))))) (box ((box (fun (l: obj) -> (box (fun (v: obj) -> (box ((unbox<int> (box ((box l)))) + (unbox<int> (box ((box 1))))))))))))))) (box ((box 0))))

let Data_List_Lazy_last  = (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (v: obj) : obj = ((match ((unbox ((box v)))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box ((box Data_List_Lazy_null))) (box ((box xs))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box x))))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (box Data_Boolean_otherwise)) -> ((go_tco ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs))))))) | _ -> ((box Data_Maybe_Nothingusd_Ctor)))) 
                                                                                                                                                                                                        and go = box ((fun (v: obj) -> go_tco v)) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box go)))))) (box ((box Data_List_Lazy_Types_step))))
                                                                                                                                                                                                        )

let Data_List_Lazy_iterate  = (box (fun (f: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Lazy_fix))) (box ((box Data_List_Lazy_Types_lazyList)))))) (box ((box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_List_Lazy_Types_functorList)))))) (box ((box f)))))) (box ((box xs))))))))))))))))

let rec Data_List_Lazy_insertAt_tco (v: obj) (v1: obj) (v2: obj) : obj = ((match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))))) with | (LitInt 0 (), x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((box xs))))) | (n, x, xs) -> ((let go = (box (fun (v3: obj) -> (match ((unbox ((box v3)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box Data_List_Lazy_Types_nil))))) | Data_List_Lazy_Types_Consusd_Ctor(y, ys) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_insertAt))) (box ((box ((unbox<int> (box ((box n)))) - (unbox<int> (box ((box 1))))))))))) (box ((box x)))))) (box ((box ys))))))))))) in (sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box xs))))))))))))))
and Data_List_Lazy_insertAt = box (fun (v: obj) ->  (fun (v1: obj) ->  (fun (v2: obj) -> Data_List_Lazy_insertAt_tco v v1 v2)))


let Data_List_Lazy_init  = (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (v: obj) : obj = ((match ((unbox ((box v)))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box ((box Data_List_Lazy_null))) (box ((box xs))))) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box Data_List_Lazy_Types_nil))))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (box Data_Boolean_otherwise)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x))))))))) (box ((go_tco ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs)))))))))) | _ -> ((box Data_Maybe_Nothingusd_Ctor)))) 
                                                                                                                                                                                                        and go = box ((fun (v: obj) -> go_tco v)) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box go)))))) (box ((box Data_List_Lazy_Types_step))))
                                                                                                                                                                                                        )

let Data_List_Lazy_index  = (box (fun (xs: obj) -> (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (v: obj) (v1: obj) : obj = ((match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_List_Lazy_Types_Nilusd_Ctor, _) -> ((box Data_Maybe_Nothingusd_Ctor)) | (Data_List_Lazy_Types_Consusd_Ctor(a, _), LitInt 0 ()) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box a))))) | (Data_List_Lazy_Types_Consusd_Ctor(_, as_var), i) -> ((go_tco ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box as_var))))) ((box ((unbox<int> (box ((box i)))) - (unbox<int> (box ((box 1))))))))))) 
                                                                                                                                                                                                        and go = box ((fun (v: obj) -> (fun (v1: obj) -> go_tco v v1))) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((box go))) (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs)))))))
                                                                                                                                                                                                        )))

let Data_List_Lazy_head  = (box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box (fun (v: obj) -> (Map.find "head" (unbox<Map<string, obj>> ((box v))))))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box xs)))))))))

let rec Data_List_Lazy_transpose_tco (xs: obj) : obj = ((let v = (sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box xs)))) in (match ((unbox ((box v)))) with | Data_Maybe_Nothingusd_Ctor -> ((box xs)) | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (h) & HasProp "tail" (xss)))) -> ((let v1 = (sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box h)))) in (match ((unbox ((box v1)))) with | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((box Data_List_Lazy_transpose))) (box ((box xss))))) | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (x) & HasProp "tail" (xs_prime)))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_mapMaybe))) (box ((box Data_List_Lazy_head)))))) (box ((box xss)))))))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_transpose))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box xs_prime)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_mapMaybe))) (box ((box Data_List_Lazy_tail)))))) (box ((box xss))))))))))))))))))))
and Data_List_Lazy_transpose = box (fun (xs: obj) -> Data_List_Lazy_transpose_tco xs)


let rec Data_List_Lazy_groupBy_tco (eq: obj) : obj = ((let go = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) -> ((let v1 = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_span))) (box ((sharpurs_apply (box ((box eq))) (box ((box x))))))))) (box ((box xs)))) in (match ((unbox ((box v1)))) with | (HasProp "init" (ys) & HasProp "rest" (zs)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_NonEmptyList))) (box ((sharpurs_apply (box ((box Data_Lazy_defer))) (box ((box (fun (v2: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box ys))))))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_groupBy))) (box ((box eq)))))) (box ((box zs)))))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_Types_List)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go))))))))) (box ((box Data_List_Lazy_unwrap)))))))))
and Data_List_Lazy_groupBy = box (fun (eq: obj) -> Data_List_Lazy_groupBy_tco eq)


let Data_List_Lazy_group  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_groupBy))) (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))))))

let Data_List_Lazy_fromStep  = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_Types_List)))))) (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Data_Lazy_applicativeLazy)))))))

let rec Data_List_Lazy_insertBy_tco (cmp: obj) (x: obj) (xs: obj) : obj = ((let go = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((box Data_List_Lazy_Types_nil))))) | (Data_List_Lazy_Types_Consusd_Ctor(y, ys_prime) as ys) -> ((let v1 = (sharpurs_apply (box ((sharpurs_apply (box ((box cmp))) (box ((box x)))))) (box ((box y)))) in (match ((unbox ((box v1)))) with | Data_Ordering_GTusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_insertBy))) (box ((box cmp)))))) (box ((box x)))))) (box ((box ys_prime)))))))) | _ -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_fromStep))) (box ((box ys)))))))))))))) in (sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box xs))))))))))))
and Data_List_Lazy_insertBy = box (fun (cmp: obj) ->  (fun (x: obj) ->  (fun (xs: obj) -> Data_List_Lazy_insertBy_tco cmp x xs)))


let Data_List_Lazy_insert  = (box (fun (dictOrd: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_insertBy))) (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd)))))))))

let Data_List_Lazy_fromFoldable  = (box (fun (dictFoldable: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldr))) (box ((box dictFoldable)))))) (box ((box Data_List_Lazy_Types_cons)))))) (box ((box Data_List_Lazy_Types_nil))))))

let Data_List_Lazy_foldrLazy  = (box (fun (dictLazy: obj) -> (box (fun (op: obj) -> (box (fun (z: obj) -> (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (xs: obj) : obj = ((let v = (sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs)))) in (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs_prime) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Lazy_defer))) (box ((box dictLazy)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box op))) (box ((box x)))))) (box ((go_tco ((box xs_prime)))))))))))) | Data_List_Lazy_Types_Nilusd_Ctor -> ((box z))))) 
                                                                                                                                                                                                        and go = box ((fun (xs: obj) -> go_tco xs)) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (box go)
                                                                                                                                                                                                        )))))))

let rec Data_List_Lazy_foldM_tco (dictMonad: obj) : obj = ((let Applicative0 = (sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))) in (box (fun (f: obj) -> (box (fun (b: obj) -> (box (fun (xs: obj) -> (let v = (sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box xs)))) in (match ((unbox ((box v)))) with | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Applicative0)))))) (box ((box b))))) | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (a) & HasProp "tail" (as_var)))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box b)))))) (box ((box a))))))))) (box ((box (fun (b_prime: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_foldM))) (box ((box dictMonad)))))) (box ((box f)))))) (box ((box b_prime)))))) (box ((box as_var))))))))))))))))))))
and Data_List_Lazy_foldM = box (fun (dictMonad: obj) -> Data_List_Lazy_foldM_tco dictMonad)


let Data_List_Lazy_findIndex  = (box (fun (fn: obj) -> (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (n: obj) (list: obj) : obj = ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Data_Maybe_bindMaybe)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box list))))))))) (box ((box (fun (o: obj) -> (match ((unbox ((sharpurs_apply (box ((box fn))) (box ((Map.find "head" (unbox<Map<string, obj>> ((box o)))))))))) with | LitBool true () -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Data_Maybe_applicativeMaybe)))))) (box ((box n))))) | _ -> ((go_tco ((box ((unbox<int> (box ((box n)))) + (unbox<int> (box ((box 1))))))) ((Map.find "tail" (unbox<Map<string, obj>> ((box o)))))))))))))) 
                                                                                                                                                                                                        and go = box ((fun (n: obj) -> (fun (list: obj) -> go_tco n list))) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((box go))) (box ((box 0))))
                                                                                                                                                                                                        )))

let Data_List_Lazy_findLastIndex  = (box (fun (fn: obj) -> (box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box (fun (v: obj) -> (box ((unbox<int> (box ((box ((unbox<int> (box ((sharpurs_apply (box ((box Data_List_Lazy_length))) (box ((box xs))))))) - (unbox<int> (box ((box 1))))))))) - (unbox<int> (box ((box v))))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_findIndex))) (box ((box fn)))))) (box ((sharpurs_apply (box ((box Data_List_Lazy_reverse))) (box ((box xs))))))))))))))

let rec Data_List_Lazy_filterM_tco (dictMonad: obj) : obj = ((let Applicative0 = (sharpurs_apply (box ((Map.find "Applicative0" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))) in let Bind1 = (sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((box dictMonad)))))) (box ((box Prim_undefined)))) in (box (fun (p: obj) -> (box (fun (list: obj) -> (let v = (sharpurs_apply (box ((box Data_List_Lazy_uncons))) (box ((box list)))) in (match ((unbox ((box v)))) with | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Applicative0)))))) (box ((box Data_List_Lazy_Types_nil))))) | Data_Maybe_Justusd_Ctor(Unbox((HasProp "head" (x) & HasProp "tail" (xs)))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((box p))) (box ((box x))))))))) (box ((box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Bind1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_filterM))) (box ((box dictMonad)))))) (box ((box p)))))) (box ((box xs))))))))) (box ((box (fun (xs_prime: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Applicative0)))))) (box ((match ((unbox ((box b)))) with | LitBool true () -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_Types_cons))) (box ((box x)))))) (box ((box xs_prime))))) | _ -> ((box xs_prime)))))))))))))))))))))))))
and Data_List_Lazy_filterM = box (fun (dictMonad: obj) -> Data_List_Lazy_filterM_tco dictMonad)


let rec Data_List_Lazy_filter_tco (p: obj) : obj = ((
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (v: obj) : obj = ((match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box ((box p))) (box ((box x))))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_filter))) (box ((box p)))))) (box ((box xs)))))))) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (box Data_Boolean_otherwise)) -> ((go_tco ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs))))))))) 
                                                                                                                                                                                                        and go = box ((fun (v: obj) -> go_tco v)) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_Types_List)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go))))))))) (box ((box Data_List_Lazy_unwrap)))))))
                                                                                                                                                                                                        ))
and Data_List_Lazy_filter = box (fun (p: obj) -> Data_List_Lazy_filter_tco p)


let Data_List_Lazy_intersectBy  = (box (fun (eq: obj) -> (box (fun (xs: obj) -> (box (fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_filter))) (box ((box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_any))) (box ((box Data_List_Lazy_Types_foldableList)))))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean)))))) (box ((sharpurs_apply (box ((box eq))) (box ((box x))))))))) (box ((box ys))))))))))) (box ((box xs))))))))))

let Data_List_Lazy_intersect  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_intersectBy))) (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))))))

let rec Data_List_Lazy_nubByEq_tco (eq: obj) : obj = ((let go = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | Data_List_Lazy_Types_Consusd_Ctor(x, xs) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box x)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_nubByEq))) (box ((box eq)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_filter))) (box ((box (fun (y: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_HeytingAlgebra_not))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box eq))) (box ((box x)))))) (box ((box y)))))))))))))) (box ((box xs)))))))))))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_Types_List)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go))))))))) (box ((box Data_List_Lazy_unwrap)))))))))
and Data_List_Lazy_nubByEq = box (fun (eq: obj) -> Data_List_Lazy_nubByEq_tco eq)


let Data_List_Lazy_nubEq  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_nubByEq))) (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))))))

let Data_List_Lazy_eqPattern  = (box (fun (dictEq: obj) -> (let eqList = (sharpurs_apply (box ((box Data_List_Lazy_Types_eqList))) (box ((box dictEq)))) in (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (l, r) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box eqList)))))) (box ((box l)))))) (box ((box r)))))))))))) Map.empty)))))))))

let Data_List_Lazy_ordPattern  = (box (fun (dictOrd: obj) -> (let ordList = (sharpurs_apply (box ((box Data_List_Lazy_Types_ordList))) (box ((box dictOrd)))) in let eqPattern1 = (sharpurs_apply (box ((box Data_List_Lazy_eqPattern))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (l, r) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box ordList)))))) (box ((box l)))))) (box ((box r)))))))))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box eqPattern1))))) Map.empty))))))))))

let Data_List_Lazy_elemLastIndex  = (box (fun (dictEq: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_findLastIndex))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((box v)))))) (box ((box x)))))))))))))

let Data_List_Lazy_elemIndex  = (box (fun (dictEq: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_findIndex))) (box ((box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((box v)))))) (box ((box x)))))))))))))

let Data_List_Lazy_dropWhile  = (box (fun (p: obj) -> (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (v: obj) : obj = ((match ((unbox ((box v)))) with | Data_List_Lazy_Types_Consusd_Ctor(x, xs) when (unbox (sharpurs_apply (box ((box p))) (box ((box x))))) -> ((go_tco ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs))))))) | xs -> ((sharpurs_apply (box ((box Data_List_Lazy_fromStep))) (box ((box xs))))))) 
                                                                                                                                                                                                        and go = box ((fun (v: obj) -> go_tco v)) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box go)))))) (box ((box Data_List_Lazy_Types_step))))
                                                                                                                                                                                                        )))

let Data_List_Lazy_drop  = (box (fun (n: obj) -> (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (v: obj) (v1: obj) : obj = ((match (((unbox ((box v))), (unbox ((box v1))))) with | (LitInt 0 (), xs) -> ((box xs)) | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(_, xs)) -> ((go_tco ((box ((unbox<int> (box ((box n_prime)))) - (unbox<int> (box ((box 1))))))) ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box xs))))))))) 
                                                                                                                                                                                                        and go = box ((fun (v: obj) -> (fun (v1: obj) -> go_tco v v1))) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_List_Lazy_Types_List)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((sharpurs_apply (box ((box go))) (box ((box n)))))))))))) (box ((box Data_List_Lazy_unwrap)))))))
                                                                                                                                                                                                        )))

let Data_List_Lazy_slice  = (box (fun (start: obj) -> (box (fun (end_var: obj) -> (box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_take))) (box ((box ((unbox<int> (box ((box end_var)))) - (unbox<int> (box ((box start))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_drop))) (box ((box start)))))) (box ((box xs)))))))))))))

let rec Data_List_Lazy_deleteBy_tco (eq: obj) (x: obj) (xs: obj) : obj = ((let go = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_List_Lazy_Types_Nilusd_Ctor -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | Data_List_Lazy_Types_Consusd_Ctor(y, ys) when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((box eq))) (box ((box x)))))) (box ((box y))))) -> ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box ys))))) | Data_List_Lazy_Types_Consusd_Ctor(y, ys) when (unbox (box Data_Boolean_otherwise)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_deleteBy))) (box ((box eq)))))) (box ((box x)))))) (box ((box ys))))))))))) in (sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((box go)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box xs))))))))))))
and Data_List_Lazy_deleteBy = box (fun (eq: obj) ->  (fun (x: obj) ->  (fun (xs: obj) -> Data_List_Lazy_deleteBy_tco eq x xs)))


let Data_List_Lazy_unionBy  = (box (fun (eq: obj) -> (box (fun (xs: obj) -> (box (fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_List_Lazy_Types_semigroupList)))))) (box ((box xs)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldl))) (box ((box Data_List_Lazy_Types_foldableList)))))) (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((box Data_List_Lazy_deleteBy))) (box ((box eq)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_nubByEq))) (box ((box eq)))))) (box ((box ys))))))))) (box ((box xs)))))))))))))

let Data_List_Lazy_union  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_unionBy))) (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))))))

let rec Data_List_Lazy_deleteAt_tco (n: obj) (xs: obj) : obj = ((let go = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | (LitInt 0 (), Data_List_Lazy_Types_Consusd_Ctor(_, ys)) -> ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box ys))))) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(y, ys)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_deleteAt))) (box ((box ((unbox<int> (box ((box n_prime)))) - (unbox<int> (box ((box 1))))))))))) (box ((box ys))))))))))))) in (sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((sharpurs_apply (box ((box go))) (box ((box n))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box xs))))))))))))
and Data_List_Lazy_deleteAt = box (fun (n: obj) ->  (fun (xs: obj) -> Data_List_Lazy_deleteAt_tco n xs))


let Data_List_Lazy_delete  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_List_Lazy_deleteBy))) (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))))))

let Data_List_Lazy_difference  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldl))) (box ((box Data_List_Lazy_Types_foldableList)))))) (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((box Data_List_Lazy_delete))) (box ((box dictEq))))))))))))

let Data_List_Lazy_cycle  = (box (fun (xs: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Lazy_fix))) (box ((box Data_List_Lazy_Types_lazyList)))))) (box ((box (fun (ys: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_List_Lazy_Types_semigroupList)))))) (box ((box xs)))))) (box ((box ys)))))))))))

let Data_List_Lazy_concatMap  = (sharpurs_apply (box ((box Data_Function_flip))) (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Data_List_Lazy_Types_bindList)))))))

let Data_List_Lazy_concat  = (box (fun (v: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Bind_bind))) (box ((box Data_List_Lazy_Types_bindList)))))) (box ((box v)))))) (box ((box Data_List_Lazy_identity))))))

let Data_List_Lazy_catMaybes  = (sharpurs_apply (box ((box Data_List_Lazy_mapMaybe))) (box ((sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn)))))))

let rec Data_List_Lazy_alterAt_tco (n: obj) (f: obj) (xs: obj) : obj = ((let go = (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_List_Lazy_Types_Nilusd_Ctor) -> ((box Data_List_Lazy_Types_Nilusd_Ctor)) | (LitInt 0 (), Data_List_Lazy_Types_Consusd_Ctor(y, ys)) -> ((let v2 = (sharpurs_apply (box ((box f))) (box ((box y)))) in (match ((unbox ((box v2)))) with | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((box Data_List_Lazy_Types_step))) (box ((box ys))))) | Data_Maybe_Justusd_Ctor(y_prime) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y_prime)))))) (box ((box ys)))))))) | (n_prime, Data_List_Lazy_Types_Consusd_Ctor(y, ys)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_List_Lazy_Types_Consusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box y)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_alterAt))) (box ((box ((unbox<int> (box ((box n_prime)))) - (unbox<int> (box ((box 1))))))))))) (box ((box f)))))) (box ((box ys))))))))))))) in (sharpurs_apply (box ((box Data_List_Lazy_Types_List))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Lazy_functorLazy)))))) (box ((sharpurs_apply (box ((box go))) (box ((box n))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((box xs))))))))))))
and Data_List_Lazy_alterAt = box (fun (n: obj) ->  (fun (f: obj) ->  (fun (xs: obj) -> Data_List_Lazy_alterAt_tco n f xs)))


let Data_List_Lazy_modifyAt  = (box (fun (n: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_Lazy_alterAt))) (box ((box n)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))))) (box ((box f)))))))))))
