#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Data_Semiring::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Record_Unsafe::*;
use Purs_Type_Proxy::*;
use Purs_Data_Semiring::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Record_Unsafe::*;
use Purs_Type_Proxy::*;

// Code generated by purust for module Data_Ring


#[derive(Clone)]
pub struct RingRecord {
    pub SemiringRecord0: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Semiring::SemiringRecord>>,
    pub subRecord: purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType>
}

#[derive(Clone)]
pub struct Ring {
    pub Semiring0: purust_core::Func1<crate::UnknownType, std::rc::Rc<Purs_Data_Semiring::Semiring>>,
    pub sub: purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType>
}

pub fn Data_Ring_subRecord(mut a0: std::rc::Rc<crate::RingRecord>, mut a1: Purs_Type_Proxy::Proxy, mut a2: crate::UnknownType, mut a3: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func4::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::RingRecord>| -> purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_0).subRecord.clone()
} as fn(std::rc::Rc<crate::RingRecord>) -> purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType>)).clone(); move |mut _a0: std::rc::Rc<crate::RingRecord>, mut _a1: Purs_Type_Proxy::Proxy, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone(), _a3.clone()) } })))(a0.clone(), a1.clone(), a2.clone(), a3.clone())
}

pub fn Data_Ring_sub(mut a0: std::rc::Rc<crate::Ring>, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Abs(..., Typed(Accessor(Local(...)))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<crate::Ring>| -> purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_0).sub.clone()
} as fn(std::rc::Rc<crate::Ring>) -> purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType>)).clone(); move |mut _a0: std::rc::Rc<crate::Ring>, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Data_Ring_ringUnit() -> std::rc::Rc<crate::Ring> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ring>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ring_ringUnit", || {
std::rc::Rc::new(crate::Ring { sub: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: (), mut _a1: ()| -> () {
    drop(_a1);
    drop(_a0);
    /* Typed () <- () : Var(...) */Data_Unit_unit()
} as fn((), ()) -> ())).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_unit(_f((_a0).unwrap_unit(), (_a1).unwrap_unit())) } })), Semiring0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semiring::Semiring> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semiring::Semiring> <- std::rc::Rc<Purs_Data_Semiring::Semiring> : Var(...) */Data_Semiring_semiringUnit()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semiring::Semiring>) })
}).clone())
}

pub fn Data_Ring_ringRecordNil() -> std::rc::Rc<crate::RingRecord> {
    // AST: Typed(Typed(Typed(Typed(Lit))))
std::rc::Rc::new(crate::RingRecord { subRecord: /* Typed Abs */purust_core::Func3::Static(|mut _a0: Purs_Type_Proxy::Proxy, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType {
    drop(_a2);
    drop(_a1);
    drop(_a0);
    /* Typed crate::UnknownType <- crate::UnknownType : Lit */purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() }))
} as fn(Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType) -> crate::UnknownType), SemiringRecord0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semiring::SemiringRecord> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semiring::SemiringRecord> <- std::rc::Rc<Purs_Data_Semiring::SemiringRecord> : Var(...) */Data_Semiring_semiringRecordNil()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semiring::SemiringRecord>) })
}

pub fn Data_Ring_ringRecordCons(mut purs_local_0: std::rc::Rc<Purs_Data_Symbol::IsSymbol>, mut purs_local_1: crate::UnknownType, mut purs_local_2: std::rc::Rc<crate::RingRecord>, mut purs_local_4: std::rc::Rc<crate::Ring>) -> std::rc::Rc<crate::RingRecord> {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Typed(Abs(..., Let(...))))))))
{
    let mut purs_local_3 = {
        let mut eval_arg_0 = purs_local_0.clone();
        let mut eval_arg_1 = purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }));
        let mut eval_arg_2 = ((purs_local_2.clone()).SemiringRecord0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: std::rc::Rc<Purs_Data_Semiring::Semiring>| -> std::rc::Rc<Purs_Data_Semiring::SemiringRecord> {
    let mut eval_arg_0 = eval_arg_0.clone();
    let mut eval_arg_1 = eval_arg_1.clone();
    let mut eval_arg_2 = eval_arg_2.clone();
    Data_Semiring_semiringRecordCons(eval_arg_0, eval_arg_1, eval_arg_2, eta_0.clone())
}))
};
    {
    let mut purs_local_5 = /* Typed std::rc::Rc<Purs_Data_Semiring::SemiringRecord> <- std::rc::Rc<Purs_Data_Semiring::SemiringRecord> : App(Local(...)) */(purs_local_3)(((purs_local_4.clone()).Semiring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::RingRecord { subRecord: /* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new(move |mut _a0: Purs_Type_Proxy::Proxy, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_7 = _a1;
    let mut purs_local_8 = _a2;
    drop(_a0);
    {
    let mut purs_local_9 = /* Typed String <- String : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func1<Purs_Type_Proxy::Proxy, String> <- purust_core::Func1<Purs_Type_Proxy::Proxy, String> : Accessor(Local(...)) */(purs_local_0.clone()).reflectSymbol.clone())(/* Typed Purs_Type_Proxy::Proxy <- Purs_Type_Proxy::Proxy : CtorSaturated(...) */Purs_Type_Proxy::Proxy::Proxy);
    {
    let mut purs_local_10 = /* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : App(TypeApp(TypeApp(Var(...)))) */{
        let mut eval_arg_0 = /* Typed String <- String : Local(...) */purs_local_9.clone();
    purust_core::Func1::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType| -> crate::UnknownType {
    let mut eval_arg_0 = eval_arg_0.clone();
    Record_Unsafe_unsafeGet(eval_arg_0, eta_0.clone())
}))
};
    /* Typed crate::UnknownType <- crate::UnknownType : App(TypeApp(TypeApp(TypeApp(Var(...))))) */Record_Unsafe_unsafeSet(/* Typed String <- String : Local(...) */purs_local_9, /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_4.clone()).sub.clone())(/* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(purs_local_10)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_7.clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Local(...)) */(purs_local_10)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_8.clone())), /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_2.clone()).subRecord.clone())(/* Typed Purs_Type_Proxy::Proxy <- Purs_Type_Proxy::Proxy : CtorSaturated(...) */Purs_Type_Proxy::Proxy::Proxy, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_7, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_8))
}
}
})), SemiringRecord0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semiring::SemiringRecord> {
    drop(_a0);
    purs_local_5.clone()
})) })
}
}
}

pub fn Data_Ring_ringRecord(mut purs_local_0: crate::UnknownType, mut purs_local_1: std::rc::Rc<crate::RingRecord>) -> std::rc::Rc<crate::Ring> {
    // AST: Typed(Typed(Abs(..., Typed(Abs(..., Let(...))))))
{
    let mut purs_local_2 = /* Typed std::rc::Rc<Purs_Data_Semiring::Semiring> <- std::rc::Rc<Purs_Data_Semiring::Semiring> : App(Var(...)) */Data_Semiring_semiringRecord(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })), ((purs_local_1.clone()).SemiringRecord0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::Ring { sub: /* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : App(Typed(Accessor(Local(...)))) */{
        let mut _fn_eval = (/* Typed purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func3<Purs_Type_Proxy::Proxy, crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_1).subRecord.clone());
        let mut eval_arg_0 = /* Typed Purs_Type_Proxy::Proxy <- Purs_Type_Proxy::Proxy : CtorSaturated(...) */Purs_Type_Proxy::Proxy::Proxy;
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType, mut eta_1: crate::UnknownType| -> crate::UnknownType {
    let mut _fn_ptr = _fn_eval.clone();
    let mut eval_arg_0 = eval_arg_0.clone();
    _fn_ptr(eval_arg_0, eta_0.clone(), eta_1.clone())
}))
}, Semiring0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semiring::Semiring> {
    drop(_a0);
    purs_local_2.clone()
})) })
}
}

pub fn Data_Ring_ringProxy() -> std::rc::Rc<crate::Ring> {
    // AST: Typed(Typed(Typed(Typed(Lit))))
std::rc::Rc::new(crate::Ring { sub: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: Purs_Type_Proxy::Proxy, mut _a1: Purs_Type_Proxy::Proxy| -> Purs_Type_Proxy::Proxy {
    drop(_a1);
    drop(_a0);
    /* Typed Purs_Type_Proxy::Proxy <- Purs_Type_Proxy::Proxy : TypeApp(TypeApp(CtorSaturated(...))) */Purs_Type_Proxy::Proxy::Proxy
} as fn(Purs_Type_Proxy::Proxy, Purs_Type_Proxy::Proxy) -> Purs_Type_Proxy::Proxy)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Class(std::rc::Rc::new(_f((_a0).unwrap_class::<Purs_Type_Proxy::Proxy>().clone(), (_a1).unwrap_class::<Purs_Type_Proxy::Proxy>().clone()))) } })), Semiring0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semiring::Semiring> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semiring::Semiring> <- std::rc::Rc<Purs_Data_Semiring::Semiring> : Var(...) */Data_Semiring_semiringProxy()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semiring::Semiring>) })
}

pub fn Data_Ring_ringNumber() -> std::rc::Rc<crate::Ring> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ring>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ring_ringNumber", || {
std::rc::Rc::new(crate::Ring { sub: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<f64, f64, f64> <- purust_core::Func2<f64, f64, f64> : Var(...) */purust_core::Func2::Static(Data_Ring_numSub)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_number(_f((_a0).unwrap_number(), (_a1).unwrap_number())) } })), Semiring0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semiring::Semiring> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semiring::Semiring> <- std::rc::Rc<Purs_Data_Semiring::Semiring> : Var(...) */Data_Semiring_semiringNumber()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semiring::Semiring>) })
}).clone())
}

pub fn Data_Ring_ringInt() -> std::rc::Rc<crate::Ring> {
    // AST: Typed(Typed(Typed(Lit)))
std::thread_local! { static __PURUST_MODULE_VALUE: purust_core::module_values::Cell<std::rc::Rc<crate::Ring>> = const { purust_core::module_values::Cell::new() }; }
__PURUST_MODULE_VALUE.with(|slot| slot.get_or_init("Data_Ring_ringInt", || {
std::rc::Rc::new(crate::Ring { sub: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed purust_core::Func2<i64, i64, i64> <- purust_core::Func2<i64, i64, i64> : Var(...) */purust_core::Func2::Static(Data_Ring_intSub)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_int(_f((_a0).unwrap_int(), (_a1).unwrap_int())) } })), Semiring0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semiring::Semiring> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semiring::Semiring> <- std::rc::Rc<Purs_Data_Semiring::Semiring> : Var(...) */Data_Semiring_semiringInt()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semiring::Semiring>) })
}).clone())
}

pub fn Data_Ring_ringFn(mut purs_local_0: std::rc::Rc<crate::Ring>) -> std::rc::Rc<crate::Ring> {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semiring::Semiring> <- std::rc::Rc<Purs_Data_Semiring::Semiring> : App(Var(...)) */Data_Semiring_semiringFn(((purs_local_0.clone()).Semiring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))));
    std::rc::Rc::new(crate::Ring { sub: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new(move |mut _a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut _a1: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut _a2: crate::UnknownType| -> crate::UnknownType {
    let mut purs_local_2 = _a0;
    let mut purs_local_3 = _a1;
    let mut purs_local_4 = _a2;
    /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_0.clone()).sub.clone())(/* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_2)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_4.clone()), /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_3)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_4))
}))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Func1(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Shared(std::rc::Rc::new({ let _f2 = _f.clone(); let mut _a0 = _a0.clone(); let mut _a1 = _a1.clone(); move |mut _a2: crate::UnknownType| -> crate::UnknownType { _f2(purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a0.clone()).unwrap_func1(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } })), purust_core::Func1::Shared(std::rc::Rc::new({ let _f = (_a1.clone()).unwrap_func1(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } })), _a2.clone()) } }))).clone(); move |mut _a0: crate::UnknownType| -> crate::UnknownType { _f(_a0) } }))) } })), Semiring0: /* Typed Abs */purust_core::Func1::Shared(std::rc::Rc::new(move |mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semiring::Semiring> {
    drop(_a0);
    purs_local_1.clone()
})) })
}
}

pub fn Data_Ring_negate(mut purs_local_0: std::rc::Rc<crate::Ring>, mut purs_local_2: crate::UnknownType) -> crate::UnknownType {
    // AST: Typed(Typed(Abs(..., Let(...))))
{
    let mut purs_local_1 = /* Typed std::rc::Rc<Purs_Data_Semiring::Semiring> <- std::rc::Rc<Purs_Data_Semiring::Semiring> : App(Accessor(Local(...))) */((purs_local_0.clone()).Semiring0.clone())(purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })));
    /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Accessor(Local(...)))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, crate::UnknownType> : Accessor(Local(...)) */(purs_local_0).sub.clone())(/* Typed crate::UnknownType <- crate::UnknownType : Accessor(Local(...)) */(purs_local_1).zero.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2)
}
}



pub fn Data_Ring_intSub(mut a: i64, mut b: i64) -> i64 {
    a - b
}

pub fn Data_Ring_numSub(mut a: f64, mut b: f64) -> f64 {
    a - b
}




