#![allow(warnings)]
#![recursion_limit = "512"]
use perceus_ptr::PerceusPtr;
use purust_core::*;
use Purs_Control_Alt::*;
use Purs_Control_Alternative::*;
use Purs_Control_Applicative::*;
use Purs_Control_Apply::*;
use Purs_Control_Bind::*;
use Purs_Control_Category::*;
use Purs_Control_Comonad::*;
use Purs_Control_Extend::*;
use Purs_Control_Monad::*;
use Purs_Control_Plus::*;
use Purs_Control_Semigroupoid::*;
use Purs_Data_Boolean::*;
use Purs_Data_BooleanAlgebra::*;
use Purs_Data_Bounded::*;
use Purs_Data_CommutativeRing::*;
use Purs_Data_Comparison::*;
use Purs_Data_Const::*;
use Purs_Data_Eq::*;
use Purs_Data_EuclideanRing::*;
use Purs_Data_Function::*;
use Purs_Data_Functor::*;
use Purs_Data_Functor_Contravariant::*;
use Purs_Data_Functor_Invariant::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Monoid::*;
use Purs_Data_Monoid_Additive::*;
use Purs_Data_Monoid_Alternate::*;
use Purs_Data_Monoid_Conj::*;
use Purs_Data_Monoid_Disj::*;
use Purs_Data_Monoid_Dual::*;
use Purs_Data_Monoid_Endo::*;
use Purs_Data_Monoid_Multiplicative::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ord::*;
use Purs_Data_Ordering::*;
use Purs_Data_Ring::*;
use Purs_Data_Semigroup::*;
use Purs_Data_Semiring::*;
use Purs_Data_Show::*;
use Purs_Data_Symbol::*;
use Purs_Data_Unit::*;
use Purs_Data_Void::*;
use Purs_Record_Unsafe::*;
use Purs_Safe_Coerce::*;
use Purs_Type_Proxy::*;
use Purs_Unsafe_Coerce::*;
use Purs_Data_Comparison::*;
use Purs_Data_Eq::*;
use Purs_Data_Function::*;
use Purs_Data_Functor_Contravariant::*;
use Purs_Data_HeytingAlgebra::*;
use Purs_Data_Monoid::*;
use Purs_Data_Newtype::*;
use Purs_Data_Ordering::*;
use Purs_Data_Semigroup::*;

// Code generated by purust for module Data_Equivalence



pub fn Data_Equivalence_Equivalence(mut a0: purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> bool {
    // AST: Typed(Abs(..., Local(...)))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>| -> purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> {
    let mut purs_local_0 = _a0;
    purs_local_0
} as fn(purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>) -> purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>)).clone(); move |mut _a0: purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> bool { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Data_Equivalence_semigroupEquivalence() -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    // AST: Typed(Typed(Typed(Lit)))
std::rc::Rc::new(Purs_Data_Semigroup::Semigroup { append: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func4::Static(|mut _a0: purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>, mut _a1: purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> bool {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    let mut purs_local_2 = _a2;
    let mut purs_local_3 = _a3;
    /* Typed bool <- bool : PrimOp(...) */(/* Typed bool <- bool : App(Typed(Local(...))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> : Local(...) */purs_local_0)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2.clone(), /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3.clone()) && /* Typed bool <- bool : App(Typed(Local(...))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> : Local(...) */purs_local_1)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3))
} as fn(purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>, purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>, crate::UnknownType, crate::UnknownType) -> bool)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func2::Shared(std::rc::Rc::new({ let _f2 = _f.clone(); let mut _a0 = _a0.clone(); let mut _a1 = _a1.clone(); move |mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> bool { _f2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (_a0.clone()).unwrap_func2(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> bool { (_f(_a0, _a1)).unwrap_bool() } })), purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (_a1.clone()).unwrap_func2(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> bool { (_f(_a0, _a1)).unwrap_bool() } })), _a2.clone(), _a3.clone()) } }))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(_a0, _a1)) } }))) } })) })
}

pub fn Data_Equivalence_newtypeEquivalence() -> std::rc::Rc<Purs_Data_Newtype::Newtype> {
    // AST: Typed(Typed(Typed(Lit)))
std::rc::Rc::new(Purs_Data_Newtype::Newtype { Coercible0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> crate::UnknownType {
    drop(_a0);
    purust_core::Value::Record_a(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))
} as fn(crate::UnknownType) -> crate::UnknownType) })
}

pub fn Data_Equivalence_monoidEquivalence() -> std::rc::Rc<Purs_Data_Monoid::Monoid> {
    // AST: Typed(Typed(Typed(Lit)))
std::rc::Rc::new(Purs_Data_Monoid::Monoid { mempty: purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func2::Static(|mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> bool {
    drop(_a1);
    drop(_a0);
    /* Typed bool <- bool : Lit */true
} as fn(crate::UnknownType, crate::UnknownType) -> bool)).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(_a0, _a1)) } }))), Semigroup0: /* Typed Abs */purust_core::Func1::Static(|mut _a0: crate::UnknownType| -> std::rc::Rc<Purs_Data_Semigroup::Semigroup> {
    drop(_a0);
    /* Typed std::rc::Rc<Purs_Data_Semigroup::Semigroup> <- std::rc::Rc<Purs_Data_Semigroup::Semigroup> : Var(...) */Data_Equivalence_semigroupEquivalence()
} as fn(crate::UnknownType) -> std::rc::Rc<Purs_Data_Semigroup::Semigroup>) })
}

pub fn Data_Equivalence_defaultEquivalence(mut a0: std::rc::Rc<Purs_Data_Eq::Eq>, mut a1: crate::UnknownType, mut a2: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(App(Var(...))))))))
(/* Typed Abs */purust_core::Func3::Shared(std::rc::Rc::new({ let _f = (purust_core::Func1::Static(|mut _a0: std::rc::Rc<Purs_Data_Eq::Eq>| -> purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> {
    let mut purs_local_0 = _a0;
    /* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> : App(Var(...)) */{
        let mut eval_arg_0 = purs_local_0;
    purust_core::Func2::Shared(std::rc::Rc::new(move |mut eta_0: crate::UnknownType, mut eta_1: crate::UnknownType| -> bool {
    let mut eval_arg_0 = eval_arg_0.clone();
    Data_Eq_eq(eval_arg_0, eta_0.clone(), eta_1.clone())
}))
}
} as fn(std::rc::Rc<Purs_Data_Eq::Eq>) -> purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>)).clone(); move |mut _a0: std::rc::Rc<Purs_Data_Eq::Eq>, mut _a1: crate::UnknownType, mut _a2: crate::UnknownType| -> bool { ((_f)(_a0.clone()))(_a1.clone(), _a2.clone()) } })))(a0.clone(), a1.clone(), a2.clone())
}

pub fn Data_Equivalence_contravariantEquivalence() -> std::rc::Rc<Purs_Data_Functor_Contravariant::Contravariant> {
    // AST: Typed(Typed(Lit))
std::rc::Rc::new(Purs_Data_Functor_Contravariant::Contravariant { cmap: purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (/* Typed Abs */purust_core::Func4::Static(|mut _a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut _a1: purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>, mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> bool {
    let mut purs_local_0 = _a0;
    let mut purs_local_1 = _a1;
    let mut purs_local_2 = _a2;
    let mut purs_local_3 = _a3;
    /* Typed crate::UnknownType <- bool : App(Typed(Local(...))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, bool> : Local(...) */purs_local_1)(/* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_0)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2), /* Typed crate::UnknownType <- crate::UnknownType : App(Typed(Local(...))) */(/* Typed purust_core::Func1<crate::UnknownType, crate::UnknownType> <- purust_core::Func1<crate::UnknownType, crate::UnknownType> : Local(...) */purs_local_0)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_3))
} as fn(purust_core::Func1<crate::UnknownType, crate::UnknownType>, purust_core::Func2<crate::UnknownType, crate::UnknownType, bool>, crate::UnknownType, crate::UnknownType) -> bool)).clone(); move |mut _a0: purust_core::Func1<crate::UnknownType, crate::UnknownType>, mut _a1: crate::UnknownType| -> crate::UnknownType { purust_core::Value::Func2(purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (purust_core::Func2::Shared(std::rc::Rc::new({ let _f2 = _f.clone(); let mut _a0 = _a0.clone(); let mut _a1 = _a1.clone(); move |mut _a2: crate::UnknownType, mut _a3: crate::UnknownType| -> bool { _f2(_a0.clone(), purust_core::Func2::Shared(std::rc::Rc::new({ let _f = (_a1.clone()).unwrap_func2(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> bool { (_f(_a0, _a1)).unwrap_bool() } })), _a2.clone(), _a3.clone()) } }))).clone(); move |mut _a0: crate::UnknownType, mut _a1: crate::UnknownType| -> crate::UnknownType { crate::mk_bool(_f(_a0, _a1)) } }))) } })) })
}

pub fn Data_Equivalence_comparisonEquivalence(mut purs_local_0: purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering>, mut purs_local_1: crate::UnknownType, mut purs_local_2: crate::UnknownType) -> bool {
    // AST: Typed(Typed(Abs(..., Typed(Typed(Typed(Typed(Abs(..., Typed(Abs(..., Typed(Typed(Typed(PrimOp(...))))))))))))))
/* Typed bool <- bool : PrimOp(...) *//* OpIsTag Debug: Data_Ordering_EQ -> Other */ matches!((/* Typed Purs_Data_Ordering::Ordering <- Purs_Data_Ordering::Ordering : App(Typed(Local(...))) */(/* Typed purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> <- purust_core::Func2<crate::UnknownType, crate::UnknownType, Purs_Data_Ordering::Ordering> : Local(...) */purs_local_0)(/* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_1, /* Typed crate::UnknownType <- crate::UnknownType : Local(...) */purs_local_2)), Purs_Data_Ordering::Ordering::EQ)
}





