[<AutoOpen>]
module PureScript_Data_Interval_Duration_Iso

open System
open System.Collections.Generic

type Data_Interval_Duration_Iso_Error =
  | Data_Interval_Duration_Iso_IsEmptyusd_Ctor
  | Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor
  | Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor of obj
  | Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor of obj

let Data_Interval_Duration_Iso_empty  = (sharpurs_apply (box ((box Control_Plus_empty))) (box ((box Data_List_Types_plusList))))

let Data_Interval_Duration_Iso_foldMap  = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldMap))) (box ((box Data_List_Types_foldableList)))))) (box ((box Data_List_Types_monoidList))))

let Data_Interval_Duration_Iso_monoidAdditive  = (sharpurs_apply (box ((box Data_Monoid_Additive_monoidAdditive))) (box ((box Data_Semiring_semiringNumber))))

let Data_Interval_Duration_Iso_heytingAlgebraFunction  = (sharpurs_apply (box ((box Data_HeytingAlgebra_heytingAlgebraFunction))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean))))

let Data_Interval_Duration_Iso_monoidFn  = (sharpurs_apply (box ((box Data_Monoid_monoidFn))) (box ((box Data_List_Types_monoidList))))

let Data_Interval_Duration_Iso_IsoDuration  = (box (fun (x: obj) -> (box x)))

let Data_Interval_Duration_Iso_IsEmpty  = (box Data_Interval_Duration_Iso_IsEmptyusd_Ctor)

let Data_Interval_Duration_Iso_InvalidWeekComponentUsage  = (box Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor)

let Data_Interval_Duration_Iso_ContainsNegativeValue  = (box ((fun (usd__arg1: obj) -> (box (Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(usd__arg1))))))

let Data_Interval_Duration_Iso_InvalidFractionalUse  = (box ((fun (usd__arg1: obj) -> (box (Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor(usd__arg1))))))

let Data_Interval_Duration_Iso_unIsoDuration  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | a -> ((box a)))))

let Data_Interval_Duration_Iso_showIsoDuration  = (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | d -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(IsoDuration ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box Data_Interval_Duration_showDuration)))))) (box ((box d))))))))) (box ((box ")"))))))))))))) Map.empty))))))

let Data_Interval_Duration_Iso_showError  = (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Interval_Duration_Iso_IsEmptyusd_Ctor -> ((box "(IsEmpty)")) | Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor -> ((box "(InvalidWeekComponentUsage)")) | Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(c) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(ContainsNegativeValue ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box Data_Interval_Duration_showDurationComponent)))))) (box ((box c))))))))) (box ((box ")")))))))) | Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor(c) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(InvalidFractionalUse ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box Data_Interval_Duration_showDurationComponent)))))) (box ((box c))))))))) (box ((box ")"))))))))))))) Map.empty))))))

let Data_Interval_Duration_Iso_prettyError  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Interval_Duration_Iso_IsEmptyusd_Ctor -> ((box "Duration is empty (has no components)")) | Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor -> ((box "Week component of Duration is used with other components")) | Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(c) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "Component `")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box Data_Interval_Duration_showDurationComponent)))))) (box ((box c))))))))) (box ((box "` contains negative value")))))))) | Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor(c) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "Invalid usage of Fractional value at component `")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box Data_Interval_Duration_showDurationComponent)))))) (box ((box c))))))))) (box ((box "`")))))))))))

let Data_Interval_Duration_Iso_eqIsoDuration  = (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (l, r) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Interval_Duration_eqDuration)))))) (box ((box l)))))) (box ((box r)))))))))))) Map.empty))))))

let Data_Interval_Duration_Iso_ordIsoDuration  = (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (l, r) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box Data_Interval_Duration_ordDuration)))))) (box ((box l)))))) (box ((box r)))))))))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box Data_Interval_Duration_Iso_eqIsoDuration))))) Map.empty)))))))

let Data_Interval_Duration_Iso_eqError  = (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Interval_Duration_Iso_IsEmptyusd_Ctor, Data_Interval_Duration_Iso_IsEmptyusd_Ctor) -> ((box true)) | (Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor, Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor) -> ((box true)) | (Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(l), Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Interval_Duration_eqDurationComponent)))))) (box ((box l)))))) (box ((box r))))) | (Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor(l), Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Interval_Duration_eqDurationComponent)))))) (box ((box l)))))) (box ((box r))))) | (_, _) -> ((box false))))))))) Map.empty))))))

let Data_Interval_Duration_Iso_ordError  = (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Interval_Duration_Iso_IsEmptyusd_Ctor, Data_Interval_Duration_Iso_IsEmptyusd_Ctor) -> ((box Data_Ordering_EQusd_Ctor)) | (Data_Interval_Duration_Iso_IsEmptyusd_Ctor, _) -> ((box Data_Ordering_LTusd_Ctor)) | (_, Data_Interval_Duration_Iso_IsEmptyusd_Ctor) -> ((box Data_Ordering_GTusd_Ctor)) | (Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor, Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor) -> ((box Data_Ordering_EQusd_Ctor)) | (Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor, _) -> ((box Data_Ordering_LTusd_Ctor)) | (_, Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor) -> ((box Data_Ordering_GTusd_Ctor)) | (Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(l), Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box Data_Interval_Duration_ordDurationComponent)))))) (box ((box l)))))) (box ((box r))))) | (Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(_), _) -> ((box Data_Ordering_LTusd_Ctor)) | (_, Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor(_)) -> ((box Data_Ordering_GTusd_Ctor)) | (Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor(l), Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box Data_Interval_Duration_ordDurationComponent)))))) (box ((box l)))))) (box ((box r)))))))))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box Data_Interval_Duration_Iso_eqError))))) Map.empty)))))))

let Data_Interval_Duration_Iso_checkWeekUsage  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | (HasProp "asMap" (asMap)) -> ((match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_HeytingAlgebra_conj))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean)))))) (box ((sharpurs_apply (box ((box Data_Maybe_isJust))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Map_Internal_lookup))) (box ((box Data_Interval_Duration_ordDurationComponent)))))) (box ((box Data_Interval_Duration_Weekusd_Ctor)))))) (box ((box asMap)))))))))))) (box ((box ((unbox<int> (box ((sharpurs_apply (box ((box Data_Map_Internal_size))) (box ((box asMap))))))) > (unbox<int> (box ((box 1)))))))))))) with | LitBool true () -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Data_List_Types_applicativeList)))))) (box ((box Data_Interval_Duration_Iso_InvalidWeekComponentUsageusd_Ctor))))) | _ -> ((box Data_Interval_Duration_Iso_empty)))))))

let Data_Interval_Duration_Iso_checkNegativeValues  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | (HasProp "asList" (asList)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_flip))) (box ((box Data_Interval_Duration_Iso_foldMap)))))) (box ((box asList)))))) (box ((box (fun (v1: obj) -> (match ((unbox ((box v1)))) with | Data_Tuple_Tupleusd_Ctor(c, num) -> ((match ((unbox ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_greaterThanOrEq))) (box ((box Data_Ord_ordNumber)))))) (box ((box num)))))) (box ((box 0.0))))))) with | LitBool true () -> ((sharpurs_apply (box ((box Control_Plus_empty))) (box ((box Data_List_Types_plusList))))) | _ -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Data_List_Types_applicativeList)))))) (box ((box (Data_Interval_Duration_Iso_ContainsNegativeValueusd_Ctor((box c))))))))))))))))))))

let Data_Interval_Duration_Iso_checkFractionalUse  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | (HasProp "asList" (asList)) -> ((let isFractional = (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_notEq))) (box ((box Data_Eq_eqNumber)))))) (box ((sharpurs_apply (box ((box Data_Number_floor))) (box ((box a))))))))) (box ((box a)))))) in let checkRest = (box (fun (rest: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_greaterThan))) (box ((box Data_Ord_ordNumber)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Newtype_unwrap))) (box ((box Prim_undefined)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_foldMap))) (box ((box Data_List_Types_foldableList)))))) (box ((box Data_Interval_Duration_Iso_monoidAdditive)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Tuple_snd)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Number_abs)))))) (box ((box Data_Monoid_Additive_Additive)))))))))))) (box ((box rest)))))))))))) (box ((box 0.0)))))) in (let v1 = (sharpurs_apply (box ((box (fun (v2: obj) -> (Map.find "rest" (unbox<Map<string, obj>> ((box v2)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_List_span))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box Data_Tuple_snd)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_HeytingAlgebra_not))) (box ((box Data_Interval_Duration_Iso_heytingAlgebraFunction)))))) (box ((box isFractional)))))))))))) (box ((box asList))))))) in (match ((unbox ((box v1)))) with | Data_List_Types_Consusd_Ctor(Unbox(Data_Tuple_Tupleusd_Ctor(c, _)), rest) when (unbox (sharpurs_apply (box ((box checkRest))) (box ((box rest))))) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Data_List_Types_applicativeList)))))) (box ((box (Data_Interval_Duration_Iso_InvalidFractionalUseusd_Ctor((box c)))))))) | _ -> ((box Data_Interval_Duration_Iso_empty)))))))))

let Data_Interval_Duration_Iso_checkEmptiness  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | (HasProp "asList" (asList)) -> ((match ((unbox ((sharpurs_apply (box ((box Data_List_null))) (box ((box asList))))))) with | LitBool true () -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box Data_List_Types_applicativeList)))))) (box ((box Data_Interval_Duration_Iso_IsEmptyusd_Ctor))))) | _ -> ((box Data_Interval_Duration_Iso_empty)))))))

let Data_Interval_Duration_Iso_checkValidIsoDuration  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | asMap -> ((let check = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Foldable_fold))) (box ((box Data_Foldable_foldableArray)))))) (box ((box Data_Interval_Duration_Iso_monoidFn)))))) (box ((box [|(box Data_Interval_Duration_Iso_checkWeekUsage); (box Data_Interval_Duration_Iso_checkEmptiness); (box Data_Interval_Duration_Iso_checkFractionalUse); (box Data_Interval_Duration_Iso_checkNegativeValues)|])))) in let asList = (sharpurs_apply (box ((box Data_List_reverse))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Map_Internal_toUnfoldable))) (box ((box Data_List_Types_unfoldableList)))))) (box ((box asMap))))))) in (sharpurs_apply (box ((box check))) (box ((box ((Map.add "asList" (box ((box asList))) (Map.add "asMap" (box ((box asMap))) Map.empty))))))))))))

let Data_Interval_Duration_Iso_mkIsoDuration  = (box (fun (d: obj) -> (let v = (sharpurs_apply (box ((box Data_List_NonEmpty_fromList))) (box ((sharpurs_apply (box ((box Data_Interval_Duration_Iso_checkValidIsoDuration))) (box ((box d))))))) in (match ((unbox ((box v)))) with | Data_Maybe_Justusd_Ctor(errs) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Leftusd_Ctor(usd__arg1)))))))) (box ((box errs))))) | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Either_Rightusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_Interval_Duration_Iso_IsoDuration))) (box ((box d))))))))))))
