% Generated by purerl version 0.0.24
-module(data_generic_rep@ps).
-export(['Inl'/0, 'Inr'/0, 'Product'/0, 'NoArguments'/0, 'Constructor'/0, 'Argument'/0, to/0, to/2, to/1, showSum/0, showProduct/0, showNoArguments/0, showConstructor/0, showArgument/0, repOf/2, repOf/0, repOf/1, from/0, from/2, from/1]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./data_generic_rep.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 0).
-spec append() -> any().
append() -> (?MEMOIZE((data_semigroup@ps:append((data_semigroup@ps:semigroupString()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 0).
-spec append(any(),any()) -> any().
append(_@2,_@3) -> (((append())(_@2))(_@3)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 0).
-spec show() -> any().
show() -> (?MEMOIZE((data_show@ps:show((data_show@ps:showString()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 0).
-spec show(any()) -> any().
show(_@5) -> ((show())(_@5)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 29).
-spec 'Inl'() -> any().
'Inl'() -> fun (Value0) ->
  { inl, Value0 }
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 29).
-spec 'Inr'() -> any().
'Inr'() -> fun (Value0) ->
  { inr, Value0 }
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 36).
-spec 'Product'() -> any().
'Product'() -> fun (Value0) ->
  fun (Value1) ->
    { product, Value0, Value1 }
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 23).
-spec 'NoArguments'() -> any().
'NoArguments'() -> { noArguments }.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 43).
-spec 'Constructor'() -> any().
'Constructor'() -> fun (X) ->
  X
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 49).
-spec 'Argument'() -> any().
'Argument'() -> fun (X) ->
  X
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 57).
-spec to() -> fun((any()) -> fun((any()) -> any())).
to() -> fun (Dict) ->
  case Dict of
    (_@6) -> (maps:get(to, _@6))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 57).
-spec to(any(),any()) -> any().
to(_@10,_@11) -> (((to())(_@10))(_@11)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 57).
-spec to(any()) -> any().
to(_@7) -> case _@7 of
  (_@9) -> (maps:get(to, _@9))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 31).
-spec showSum() -> any().
showSum() -> fun (DictShow) ->
  Show1@28 = (?MEMOIZE((data_show@ps:show(DictShow)))),
  fun (DictShow1) ->
    Show2@29 = (?MEMOIZE((data_show@ps:show(DictShow1)))),
    #{show=>fun (V) ->
      case V of
        ({ inl, _@12 }) -> (append(<<"(Inl "/utf8>>, (append((Show1@28(_@12)), <<")"/utf8>>))));
        ({ inr, _@13 }) -> (append(<<"(Inr "/utf8>>, (append((Show2@29(_@13)), <<")"/utf8>>))))
      end
    end}
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 38).
-spec showProduct() -> any().
showProduct() -> fun (DictShow) ->
  Show1@30 = (?MEMOIZE((data_show@ps:show(DictShow)))),
  fun (DictShow1) ->
    Show2@31 = (?MEMOIZE((data_show@ps:show(DictShow1)))),
    #{show=>fun (V) ->
      case V of
        ({ product, _@14, _@15 }) -> (append(<<"(Product "/utf8>>, (append((Show1@30(_@14)), (append(<<" "/utf8>>, (append((Show2@31(_@15)), <<")"/utf8>>))))))))
      end
    end}
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 25).
-spec showNoArguments() -> any().
showNoArguments() -> #{show=>fun (V) ->
  <<"NoArguments"/utf8>>
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 45).
-spec showConstructor() -> any().
showConstructor() -> fun (DictIsSymbol) ->
  ReflectSymbol@32 = (?MEMOIZE((data_symbol@ps:reflectSymbol(DictIsSymbol)))),
  fun (DictShow) ->
    Show1@33 = (?MEMOIZE((data_show@ps:show(DictShow)))),
    #{show=>fun (V) ->
      case V of
        (_@16) -> (append(<<"(Constructor @"/utf8>>, (append((show((ReflectSymbol@32({ proxy })))), (append(<<" "/utf8>>, (append((Show1@33(_@16)), <<")"/utf8>>))))))))
      end
    end}
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 51).
-spec showArgument() -> any().
showArgument() -> fun (DictShow) ->
  Show1@34 = (?MEMOIZE((data_show@ps:show(DictShow)))),
  #{show=>fun (V) ->
    case V of
      (_@17) -> (append(<<"(Argument "/utf8>>, (append((Show1@34(_@17)), <<")"/utf8>>))))
    end
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 60).
-spec repOf(any(),any()) -> any().
repOf(_@18,_@19) -> { proxy }.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 60).
-spec repOf() -> fun((any()) -> fun((any()) -> any())).
repOf() -> fun (_@20) ->
  fun (_@21) ->
    (repOf(_@20, _@21))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 60).
-spec repOf(any()) -> any().
repOf(_@18) -> fun (V) ->
  { proxy }
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 58).
-spec from() -> fun((any()) -> fun((any()) -> any())).
from() -> fun (Dict) ->
  case Dict of
    (_@22) -> (maps:get(from, _@22))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 58).
-spec from(any(),any()) -> any().
from(_@26,_@27) -> (((from())(_@26))(_@27)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/prelude/75a86f361270985ae983b59d4a69c0513b7f1cb1/src/Data/Generic/Rep.purs", 58).
-spec from(any()) -> any().
from(_@23) -> case _@23 of
  (_@25) -> (maps:get(from, _@25))
end.
