[<AutoOpen>]
module PureScript_Control_Comonad_Store_Trans

open System
open System.Collections.Generic

let Control_Comonad_Store_Trans_StoreT  = (box (fun (x: obj) -> (box x)))

let Control_Comonad_Store_Trans_runStoreT  = (box (fun (v: obj) -> (match ((unbox ((box v)))) with | s -> ((box s)))))

let Control_Comonad_Store_Trans_newtypeStoreT  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Control_Comonad_Store_Trans_functorStoreT  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_Tuple_Tupleusd_Ctor(w, s)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Control_Comonad_Store_Trans_StoreT)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box (fun (h: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box h)))))) (box ((box f1))))))))))) (box ((box w))))))))) (box ((box s))))))))))))))) Map.empty))))))))

let Control_Comonad_Store_Trans_extendStoreT  = (box (fun (dictExtend: obj) -> (let functorStoreT1 = (sharpurs_apply (box ((box Control_Comonad_Store_Trans_functorStoreT))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictExtend)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Extend_Extendusd_Dict))) (box ((box ((Map.add "extend" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_Tuple_Tupleusd_Ctor(w, s)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Control_Comonad_Store_Trans_StoreT)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Extend_extend))) (box ((box dictExtend)))))) (box ((box (fun (w_prime: obj) -> (box (fun (s_prime: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box f1)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box Control_Comonad_Store_Trans_StoreT)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((box w_prime)))))) (box ((box s_prime))))))))))))))))))) (box ((box w))))))))) (box ((box s))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box functorStoreT1))))) Map.empty))))))))))

let Control_Comonad_Store_Trans_comonadTransStoreT  = (sharpurs_apply (box ((box Control_Comonad_Trans_Class_ComonadTransusd_Dict))) (box ((box ((Map.add "lower" (box ((box (fun (dictComonad: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((box dictComonad)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined)))) in (box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(w, s) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box v1)))))) (box ((box s))))))))))) (box ((box w))))))))))))) Map.empty))))))

let Control_Comonad_Store_Trans_comonadStoreT  = (box (fun (dictComonad: obj) -> (let extendStoreT1 = (sharpurs_apply (box ((box Control_Comonad_Store_Trans_extendStoreT))) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((box dictComonad)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Comonad_Comonadusd_Dict))) (box ((box ((Map.add "extract" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Tuple_Tupleusd_Ctor(w, s) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad)))))) (box ((box w)))))) (box ((box s)))))))))) (Map.add "Extend0" (box ((box (fun (usd__unused: obj) -> (box extendStoreT1))))) Map.empty))))))))))
