[<AutoOpen>]
module PureScript_Data_Maybe

open System
open System.Collections.Generic

type Data_Maybe_Maybe =
  | Data_Maybe_Nothingusd_Ctor
  | Data_Maybe_Justusd_Ctor of obj

let Data_Maybe_identity  = (sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn))))

let Data_Maybe_Nothing  = (box Data_Maybe_Nothingusd_Ctor)

let Data_Maybe_Just  = (box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))

let Data_Maybe_showMaybe  = (box (fun (dictShow: obj) -> (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Maybe_Justusd_Ctor(x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(Just ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow)))))) (box ((box x))))))))) (box ((box ")")))))))) | Data_Maybe_Nothingusd_Ctor -> ((box "Nothing"))))))) Map.empty))))))))

let Data_Maybe_semigroupMaybe  = (box (fun (dictSemigroup: obj) -> (sharpurs_apply (box ((box Data_Semigroup_Semigroupusd_Dict))) (box ((box ((Map.add "append" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Maybe_Nothingusd_Ctor, y) -> ((box y)) | (x, Data_Maybe_Nothingusd_Ctor) -> ((box x)) | (Data_Maybe_Justusd_Ctor(x), Data_Maybe_Justusd_Ctor(y)) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box dictSemigroup)))))) (box ((box x)))))) (box ((box y))))))))))))))) Map.empty))))))))

let Data_Maybe_optional  = (box (fun (dictAlt: obj) -> (let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box dictAlt)))))) (box ((box Prim_undefined)))) in (box (fun (dictApplicative: obj) -> (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Alt_alt))) (box ((box dictAlt)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1))))))))))) (box ((box a))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Applicative_pure))) (box ((box dictApplicative)))))) (box ((box Data_Maybe_Nothingusd_Ctor))))))))))))))

let Data_Maybe_monoidMaybe  = (box (fun (dictSemigroup: obj) -> (let semigroupMaybe1 = (sharpurs_apply (box ((box Data_Maybe_semigroupMaybe))) (box ((box dictSemigroup)))) in (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((box Data_Maybe_Nothingusd_Ctor))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box semigroupMaybe1))))) Map.empty))))))))))

let Data_Maybe_maybe_prime  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (box (fun (v2: obj) -> (match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))))) with | (g, _, Data_Maybe_Nothingusd_Ctor) -> ((sharpurs_apply (box ((box g))) (box ((box Data_Unit_unit))))) | (_, f, Data_Maybe_Justusd_Ctor(a)) -> ((sharpurs_apply (box ((box f))) (box ((box a))))))))))))

let Data_Maybe_maybe  = (box (fun (v: obj) -> (box (fun (v1: obj) -> (box (fun (v2: obj) -> (match (((unbox ((box v))), (unbox ((box v1))), (unbox ((box v2))))) with | (b, _, Data_Maybe_Nothingusd_Ctor) -> ((box b)) | (_, f, Data_Maybe_Justusd_Ctor(a)) -> ((sharpurs_apply (box ((box f))) (box ((box a))))))))))))

let Data_Maybe_isNothing  = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe))) (box ((box true)))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box false)))))))

let Data_Maybe_isJust  = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe))) (box ((box false)))))) (box ((sharpurs_apply (box ((box Data_Function_const))) (box ((box true)))))))

let Data_Maybe_genericMaybe  = (sharpurs_apply (box ((box Data_Generic_Rep_Genericusd_Dict))) (box ((box ((Map.add "to" (box ((box (fun (x: obj) -> (match ((unbox ((box x)))) with | Data_Generic_Rep_Inlusd_Ctor(_) -> ((box Data_Maybe_Nothingusd_Ctor)) | Data_Generic_Rep_Inrusd_Ctor(arg) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((box arg)))))))))) (Map.add "from" (box ((box (fun (x: obj) -> (match ((unbox ((box x)))) with | Data_Maybe_Nothingusd_Ctor -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Generic_Rep_Inlusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_Generic_Rep_Constructor))) (box ((box Data_Generic_Rep_NoArgumentsusd_Ctor)))))))) | Data_Maybe_Justusd_Ctor(arg) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Generic_Rep_Inrusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_Generic_Rep_Constructor))) (box ((sharpurs_apply (box ((box Data_Generic_Rep_Argument))) (box ((box arg)))))))))))))))) Map.empty)))))))

let Data_Maybe_functorMaybe  = (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (fn, Data_Maybe_Justusd_Ctor(x)) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box fn))) (box ((box x)))))))) | (_, _) -> ((box Data_Maybe_Nothingusd_Ctor))))))))) Map.empty))))))

let Data_Maybe_invariantMaybe  = (sharpurs_apply (box ((box Data_Functor_Invariant_Invariantusd_Dict))) (box ((box ((Map.add "imap" (box ((sharpurs_apply (box ((box Data_Functor_Invariant_imapF))) (box ((box Data_Maybe_functorMaybe)))))) Map.empty))))))

let Data_Maybe_fromMaybe_prime  = (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe_prime))) (box ((box a)))))) (box ((box Data_Maybe_identity))))))

let Data_Maybe_fromMaybe  = (box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Maybe_maybe))) (box ((box a)))))) (box ((box Data_Maybe_identity))))))

let Data_Maybe_fromJust  = (box (fun (usd__unused: obj) -> (box (fun (v: obj) -> (sharpurs_apply (box ((box (fun (usd__unused: obj) -> (match ((unbox ((box v)))) with | Data_Maybe_Justusd_Ctor(x) -> ((box x))))))) (box ((box Prim_undefined))))))))

let Data_Maybe_extendMaybe  = (sharpurs_apply (box ((box Control_Extend_Extendusd_Dict))) (box ((box ((Map.add "extend" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (_, Data_Maybe_Nothingusd_Ctor) -> ((box Data_Maybe_Nothingusd_Ctor)) | (f, x) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box f))) (box ((box x))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_functorMaybe))))) Map.empty)))))))

let Data_Maybe_eqMaybe  = (box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Maybe_Nothingusd_Ctor, Data_Maybe_Nothingusd_Ctor) -> ((box true)) | (Data_Maybe_Justusd_Ctor(l), Data_Maybe_Justusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((box l)))))) (box ((box r))))) | (_, _) -> ((box false))))))))) Map.empty))))))))

let Data_Maybe_ordMaybe  = (box (fun (dictOrd: obj) -> (let eqMaybe1 = (sharpurs_apply (box ((box Data_Maybe_eqMaybe))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Maybe_Nothingusd_Ctor, Data_Maybe_Nothingusd_Ctor) -> ((box Data_Ordering_EQusd_Ctor)) | (Data_Maybe_Nothingusd_Ctor, _) -> ((box Data_Ordering_LTusd_Ctor)) | (_, Data_Maybe_Nothingusd_Ctor) -> ((box Data_Ordering_GTusd_Ctor)) | (Data_Maybe_Justusd_Ctor(l), Data_Maybe_Justusd_Ctor(r)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd)))))) (box ((box l)))))) (box ((box r)))))))))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box eqMaybe1))))) Map.empty))))))))))

let Data_Maybe_eq1Maybe  = (sharpurs_apply (box ((box Data_Eq_Eq1usd_Dict))) (box ((box ((Map.add "eq1" (box ((box (fun (dictEq: obj) -> (sharpurs_apply (box ((box Data_Eq_eq))) (box ((sharpurs_apply (box ((box Data_Maybe_eqMaybe))) (box ((box dictEq))))))))))) Map.empty))))))

let Data_Maybe_ord1Maybe  = (sharpurs_apply (box ((box Data_Ord_Ord1usd_Dict))) (box ((box ((Map.add "compare1" (box ((box (fun (dictOrd: obj) -> (sharpurs_apply (box ((box Data_Ord_compare))) (box ((sharpurs_apply (box ((box Data_Maybe_ordMaybe))) (box ((box dictOrd))))))))))) (Map.add "Eq10" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_eq1Maybe))))) Map.empty)))))))

let Data_Maybe_boundedMaybe  = (box (fun (dictBounded: obj) -> (let ordMaybe1 = (sharpurs_apply (box ((box Data_Maybe_ordMaybe))) (box ((sharpurs_apply (box ((Map.find "Ord0" (unbox<Map<string, obj>> ((box dictBounded)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Bounded_Boundedusd_Dict))) (box ((box ((Map.add "top" (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box dictBounded))))))))) (Map.add "bottom" (box ((box Data_Maybe_Nothingusd_Ctor))) (Map.add "Ord0" (box ((box (fun (usd__unused: obj) -> (box ordMaybe1))))) Map.empty)))))))))))

let Data_Maybe_applyMaybe  = (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Maybe_Justusd_Ctor(fn), x) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box fn)))))) (box ((box x))))) | (Data_Maybe_Nothingusd_Ctor, _) -> ((box Data_Maybe_Nothingusd_Ctor))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_functorMaybe))))) Map.empty)))))))

let Data_Maybe_bindMaybe  = (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Maybe_Justusd_Ctor(x), k) -> ((sharpurs_apply (box ((box k))) (box ((box x))))) | (Data_Maybe_Nothingusd_Ctor, _) -> ((box Data_Maybe_Nothingusd_Ctor))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_applyMaybe))))) Map.empty)))))))

let Data_Maybe_semiringMaybe  = (box (fun (dictSemiring: obj) -> (let mul = (sharpurs_apply (box ((box Data_Semiring_mul))) (box ((box dictSemiring)))) in (sharpurs_apply (box ((box Data_Semiring_Semiringusd_Dict))) (box ((box ((Map.add "zero" (box ((box Data_Maybe_Nothingusd_Ctor))) (Map.add "one" (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((box Data_Semiring_one))) (box ((box dictSemiring))))))))) (Map.add "add" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Maybe_Nothingusd_Ctor, y) -> ((box y)) | (x, Data_Maybe_Nothingusd_Ctor) -> ((box x)) | (Data_Maybe_Justusd_Ctor(x), Data_Maybe_Justusd_Ctor(y)) -> ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semiring_add))) (box ((box dictSemiring)))))) (box ((box x)))))) (box ((box y))))))))))))))) (Map.add "mul" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Apply_apply))) (box ((box Data_Maybe_applyMaybe)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Data_Maybe_functorMaybe)))))) (box ((box mul)))))) (box ((box x))))))))) (box ((box y)))))))))) Map.empty))))))))))))

let Data_Maybe_applicativeMaybe  = (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((box ((fun (usd__arg1: obj) -> (box (Data_Maybe_Justusd_Ctor(usd__arg1)))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_applyMaybe))))) Map.empty)))))))

let Data_Maybe_monadMaybe  = (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_applicativeMaybe))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_bindMaybe))))) Map.empty)))))))

let Data_Maybe_altMaybe  = (sharpurs_apply (box ((box Control_Alt_Altusd_Dict))) (box ((box ((Map.add "alt" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Maybe_Nothingusd_Ctor, r) -> ((box r)) | (l, _) -> ((box l))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_functorMaybe))))) Map.empty)))))))

let Data_Maybe_plusMaybe  = (sharpurs_apply (box ((box Control_Plus_Plususd_Dict))) (box ((box ((Map.add "empty" (box ((box Data_Maybe_Nothingusd_Ctor))) (Map.add "Alt0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_altMaybe))))) Map.empty)))))))

let Data_Maybe_alternativeMaybe  = (sharpurs_apply (box ((box Control_Alternative_Alternativeusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_applicativeMaybe))))) (Map.add "Plus1" (box ((box (fun (usd__unused: obj) -> (box Data_Maybe_plusMaybe))))) Map.empty)))))))
