[<AutoOpen>]
module PureScript_Data_Functor_Costar

open System
open System.Collections.Generic

let Data_Functor_Costar_Costar  = (box (fun (x: obj) -> (box x)))

let Data_Functor_Costar_semigroupoidCostar  = (box (fun (dictExtend: obj) -> (sharpurs_apply (box ((box Control_Semigroupoid_Semigroupoidusd_Dict))) (box ((box ((Map.add "compose" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, g) -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Extend_composeCoKleisliFlipped))) (box ((box dictExtend)))))) (box ((box f)))))) (box ((box g))))))))))))))) Map.empty))))))))

let Data_Functor_Costar_profunctorCostar  = (box (fun (dictFunctor: obj) -> (sharpurs_apply (box ((box Data_Profunctor_Profunctorusd_Dict))) (box ((box ((Map.add "dimap" (box ((box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box v))))) with | (f1, g1, h) -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f1))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box h)))))) (box ((box g1)))))))))))))))))))) Map.empty))))))))

let Data_Functor_Costar_strongCostar  = (box (fun (dictComonad: obj) -> (let Extend0 = (sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((box dictComonad)))))) (box ((box Prim_undefined)))) in let Functor0 = (sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box Extend0)))))) (box ((box Prim_undefined)))) in let profunctorCostar1 = (sharpurs_apply (box ((box Data_Functor_Costar_profunctorCostar))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((box Extend0)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Profunctor_Strong_Strongusd_Dict))) (box ((box ((Map.add "first" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_Tuple_fst)))))) (box ((box x)))))))))))) (box ((sharpurs_apply (box ((box Data_Tuple_snd))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad)))))) (box ((box x))))))))))))))))))))) (Map.add "second" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((box (fun (x: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Tuple_Tupleusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((box Data_Tuple_fst))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad)))))) (box ((box x)))))))))))) (box ((sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box Functor0)))))) (box ((box Data_Tuple_snd)))))) (box ((box x))))))))))))))))))))) (Map.add "Profunctor0" (box ((box (fun (usd__unused: obj) -> (box profunctorCostar1))))) Map.empty)))))))))))

let Data_Functor_Costar_newtypeCostar  = (sharpurs_apply (box ((box Data_Newtype_Newtypeusd_Dict))) (box ((box ((Map.add "Coercible0" (box ((box (fun (usd__unused: obj) -> (box Prim_undefined))))) Map.empty))))))

let Data_Functor_Costar_hoistCostar  = (box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, g) -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Profunctor_lcmap))) (box ((box Data_Profunctor_profunctorFn)))))) (box ((box f1)))))) (box ((box g)))))))))))))

let Data_Functor_Costar_functorCostar  = (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, g) -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box f1)))))) (box ((box g))))))))))))))) Map.empty))))))

let Data_Functor_Costar_invariantCostar  = (sharpurs_apply (box ((box Data_Functor_Invariant_Invariantusd_Dict))) (box ((box ((Map.add "imap" (box ((sharpurs_apply (box ((box Data_Functor_Invariant_imapF))) (box ((box Data_Functor_Costar_functorCostar)))))) Map.empty))))))

let rec Data_Functor_Costar_distributiveCostar : obj = ((sharpurs_apply (box ((box Data_Distributive_Distributiveusd_Dict))) (box ((box ((Map.add "distribute" (box ((box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | g -> ((sharpurs_apply (box ((box g))) (box ((box a))))))))))))) (box ((box f))))))))))))))) (Map.add "collect" (box ((box (fun (dictFunctor: obj) -> (box (fun (f: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Distributive_distribute))) (box ((box Data_Functor_Costar_distributiveCostar)))))) (box ((box dictFunctor))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Functor_Costar_functorCostar))))) Map.empty)))))))))


let Data_Functor_Costar_closedCostar  = (box (fun (dictFunctor: obj) -> (let profunctorCostar1 = (sharpurs_apply (box ((box Data_Functor_Costar_profunctorCostar))) (box ((box dictFunctor)))) in (sharpurs_apply (box ((box Data_Profunctor_Closed_Closedusd_Dict))) (box ((box ((Map.add "closed" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | f -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((box (fun (g: obj) -> (box (fun (x: obj) -> (sharpurs_apply (box ((box f))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box (fun (v1: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Function_apply))) (box ((box v1)))))) (box ((box x))))))))))) (box ((box g)))))))))))))))))))) (Map.add "Profunctor0" (box ((box (fun (usd__unused: obj) -> (box profunctorCostar1))))) Map.empty))))))))))

let Data_Functor_Costar_categoryCostar  = (box (fun (dictComonad: obj) -> (let semigroupoidCostar1 = (sharpurs_apply (box ((box Data_Functor_Costar_semigroupoidCostar))) (box ((sharpurs_apply (box ((Map.find "Extend0" (unbox<Map<string, obj>> ((box dictComonad)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Category_Categoryusd_Dict))) (box ((box ((Map.add "identity" (box ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((sharpurs_apply (box ((box Control_Comonad_extract))) (box ((box dictComonad))))))))) (Map.add "Semigroupoid0" (box ((box (fun (usd__unused: obj) -> (box semigroupoidCostar1))))) Map.empty))))))))))

let Data_Functor_Costar_bifunctorCostar  = (box (fun (dictContravariant: obj) -> (sharpurs_apply (box ((box Data_Bifunctor_Bifunctorusd_Dict))) (box ((box ((Map.add "bimap" (box ((box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box v))))) with | (f1, g1, h) -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_Contravariant_cmap))) (box ((box dictContravariant)))))) (box ((box f1))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_composeFlipped))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((box h)))))) (box ((box g1)))))))))))))))))))) Map.empty))))))))

let Data_Functor_Costar_applyCostar  = (sharpurs_apply (box ((box Control_Apply_Applyusd_Dict))) (box ((box ((Map.add "apply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (f, g) -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((box (fun (a: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box f))) (box ((box a)))))) (box ((sharpurs_apply (box ((box g))) (box ((box a)))))))))))))))))))) (Map.add "Functor0" (box ((box (fun (usd__unused: obj) -> (box Data_Functor_Costar_functorCostar))))) Map.empty)))))))

let Data_Functor_Costar_bindCostar  = (sharpurs_apply (box ((box Control_Bind_Bindusd_Dict))) (box ((box ((Map.add "bind" (box ((box (fun (v: obj) -> (box (fun (f: obj) -> (match (((unbox ((box v))), (unbox ((box f))))) with | (m, f1) -> ((sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((box (fun (x: obj) -> (let v1 = (sharpurs_apply (box ((box f1))) (box ((sharpurs_apply (box ((box m))) (box ((box x))))))) in (match ((unbox ((box v1)))) with | g -> ((sharpurs_apply (box ((box g))) (box ((box x)))))))))))))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box Data_Functor_Costar_applyCostar))))) Map.empty)))))))

let Data_Functor_Costar_applicativeCostar  = (sharpurs_apply (box ((box Control_Applicative_Applicativeusd_Dict))) (box ((box ((Map.add "pure" (box ((box (fun (a: obj) -> (sharpurs_apply (box ((box Data_Functor_Costar_Costar))) (box ((box (fun (v: obj) -> (box a)))))))))) (Map.add "Apply0" (box ((box (fun (usd__unused: obj) -> (box Data_Functor_Costar_applyCostar))))) Map.empty)))))))

let Data_Functor_Costar_monadCostar  = (sharpurs_apply (box ((box Control_Monad_Monadusd_Dict))) (box ((box ((Map.add "Applicative0" (box ((box (fun (usd__unused: obj) -> (box Data_Functor_Costar_applicativeCostar))))) (Map.add "Bind1" (box ((box (fun (usd__unused: obj) -> (box Data_Functor_Costar_bindCostar))))) Map.empty)))))))
