[<AutoOpen>]
module PureScript_Data_Functor_Product2

open System
open System.Collections.Generic

type Data_Functor_Product2_Product2 =
  | Data_Functor_Product2_Product2usd_Ctor of obj * obj

let Data_Functor_Product2_Product2  = (box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Functor_Product2_Product2usd_Ctor(usd__arg1, usd__arg2)))))))

let Data_Functor_Product2_showProduct2  = (box (fun (dictShow: obj) -> (box (fun (dictShow1: obj) -> (sharpurs_apply (box ((box Data_Show_Showusd_Dict))) (box ((box ((Map.add "show" (box ((box (fun (v: obj) -> (match ((unbox ((box v)))) with | Data_Functor_Product2_Product2usd_Ctor(x, y) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box "(Product2 ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow)))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((box " ")))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Data_Semigroup_semigroupString)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Show_show))) (box ((box dictShow1)))))) (box ((box y))))))))) (box ((box ")"))))))))))))))))))) Map.empty))))))))))

let Data_Functor_Product2_profunctorProduct2  = (box (fun (dictProfunctor: obj) -> (box (fun (dictProfunctor1: obj) -> (sharpurs_apply (box ((box Data_Profunctor_Profunctorusd_Dict))) (box ((box ((Map.add "dimap" (box ((box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box v))))) with | (f1, g1, Data_Functor_Product2_Product2usd_Ctor(x, y)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Functor_Product2_Product2usd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Profunctor_dimap))) (box ((box dictProfunctor)))))) (box ((box f1)))))) (box ((box g1)))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Profunctor_dimap))) (box ((box dictProfunctor1)))))) (box ((box f1)))))) (box ((box g1)))))) (box ((box y))))))))))))))))) Map.empty))))))))))

let Data_Functor_Product2_functorProduct2  = (box (fun (dictFunctor: obj) -> (box (fun (dictFunctor1: obj) -> (sharpurs_apply (box ((box Data_Functor_Functorusd_Dict))) (box ((box ((Map.add "map" (box ((box (fun (f: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box v))))) with | (f1, Data_Functor_Product2_Product2usd_Ctor(x, y)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Functor_Product2_Product2usd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor)))))) (box ((box f1)))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((box dictFunctor1)))))) (box ((box f1)))))) (box ((box y))))))))))))))) Map.empty))))))))))

let Data_Functor_Product2_eqProduct2  = (box (fun (dictEq: obj) -> (box (fun (dictEq1: obj) -> (sharpurs_apply (box ((box Data_Eq_Equsd_Dict))) (box ((box ((Map.add "eq" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Functor_Product2_Product2usd_Ctor(l, l1), Data_Functor_Product2_Product2usd_Ctor(r, r1)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_HeytingAlgebra_conj))) (box ((box Data_HeytingAlgebra_heytingAlgebraBoolean)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq)))))) (box ((box l)))))) (box ((box r))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box dictEq1)))))) (box ((box l1)))))) (box ((box r1))))))))))))))) Map.empty))))))))))

let Data_Functor_Product2_ordProduct2  = (box (fun (dictOrd: obj) -> (let eqProduct21 = (sharpurs_apply (box ((box Data_Functor_Product2_eqProduct2))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd)))))) (box ((box Prim_undefined))))))) in (box (fun (dictOrd1: obj) -> (let eqProduct22 = (sharpurs_apply (box ((box eqProduct21))) (box ((sharpurs_apply (box ((Map.find "Eq0" (unbox<Map<string, obj>> ((box dictOrd1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Ord_Ordusd_Dict))) (box ((box ((Map.add "compare" (box ((box (fun (x: obj) -> (box (fun (y: obj) -> (match (((unbox ((box x))), (unbox ((box y))))) with | (Data_Functor_Product2_Product2usd_Ctor(l, l1), Data_Functor_Product2_Product2usd_Ctor(r, r1)) -> ((let v = (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd)))))) (box ((box l)))))) (box ((box r)))) in (match ((unbox ((box v)))) with | Data_Ordering_LTusd_Ctor -> ((box Data_Ordering_LTusd_Ctor)) | Data_Ordering_GTusd_Ctor -> ((box Data_Ordering_GTusd_Ctor)) | _ -> ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_compare))) (box ((box dictOrd1)))))) (box ((box l1)))))) (box ((box r1))))))))))))))) (Map.add "Eq0" (box ((box (fun (usd__unused: obj) -> (box eqProduct22))))) Map.empty)))))))))))))

let Data_Functor_Product2_bifunctorProduct2  = (box (fun (dictBifunctor: obj) -> (box (fun (dictBifunctor1: obj) -> (sharpurs_apply (box ((box Data_Bifunctor_Bifunctorusd_Dict))) (box ((box ((Map.add "bimap" (box ((box (fun (f: obj) -> (box (fun (g: obj) -> (box (fun (v: obj) -> (match (((unbox ((box f))), (unbox ((box g))), (unbox ((box v))))) with | (f1, g1, Data_Functor_Product2_Product2usd_Ctor(x, y)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Functor_Product2_Product2usd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box dictBifunctor)))))) (box ((box f1)))))) (box ((box g1)))))) (box ((box x))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Bifunctor_bimap))) (box ((box dictBifunctor1)))))) (box ((box f1)))))) (box ((box g1)))))) (box ((box y))))))))))))))))) Map.empty))))))))))

let Data_Functor_Product2_biapplyProduct2  = (box (fun (dictBiapply: obj) -> (let bifunctorProduct21 = (sharpurs_apply (box ((box Data_Functor_Product2_bifunctorProduct2))) (box ((sharpurs_apply (box ((Map.find "Bifunctor0" (unbox<Map<string, obj>> ((box dictBiapply)))))) (box ((box Prim_undefined))))))) in (box (fun (dictBiapply1: obj) -> (let bifunctorProduct22 = (sharpurs_apply (box ((box bifunctorProduct21))) (box ((sharpurs_apply (box ((Map.find "Bifunctor0" (unbox<Map<string, obj>> ((box dictBiapply1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Biapply_Biapplyusd_Dict))) (box ((box ((Map.add "biapply" (box ((box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (Data_Functor_Product2_Product2usd_Ctor(w, x), Data_Functor_Product2_Product2usd_Ctor(y, z)) -> ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Functor_Product2_Product2usd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapply_biapply))) (box ((box dictBiapply)))))) (box ((box w)))))) (box ((box y))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapply_biapply))) (box ((box dictBiapply1)))))) (box ((box x)))))) (box ((box z))))))))))))))) (Map.add "Bifunctor0" (box ((box (fun (usd__unused: obj) -> (box bifunctorProduct22))))) Map.empty)))))))))))))

let Data_Functor_Product2_biapplicativeProduct2  = (box (fun (dictBiapplicative: obj) -> (let biapplyProduct21 = (sharpurs_apply (box ((box Data_Functor_Product2_biapplyProduct2))) (box ((sharpurs_apply (box ((Map.find "Biapply0" (unbox<Map<string, obj>> ((box dictBiapplicative)))))) (box ((box Prim_undefined))))))) in (box (fun (dictBiapplicative1: obj) -> (let biapplyProduct22 = (sharpurs_apply (box ((box biapplyProduct21))) (box ((sharpurs_apply (box ((Map.find "Biapply0" (unbox<Map<string, obj>> ((box dictBiapplicative1)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Control_Biapplicative_Biapplicativeusd_Dict))) (box ((box ((Map.add "bipure" (box ((box (fun (a: obj) -> (box (fun (b: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_Functor_Product2_Product2usd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapplicative_bipure))) (box ((box dictBiapplicative)))))) (box ((box a)))))) (box ((box b))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Biapplicative_bipure))) (box ((box dictBiapplicative1)))))) (box ((box a)))))) (box ((box b))))))))))))) (Map.add "Biapply0" (box ((box (fun (usd__unused: obj) -> (box biapplyProduct22))))) Map.empty)))))))))))))
