[<AutoOpen>]
module PureScript_Data_Monoid

open System
open System.Collections.Generic

let Data_Monoid_semigroupRecord  = (sharpurs_apply (box ((box Data_Semigroup_semigroupRecord))) (box ((box Prim_undefined))))

let Data_Monoid_MonoidRecordusd_Dict  = (box (fun (x: obj) -> (box x)))

let Data_Monoid_Monoidusd_Dict  = (box (fun (x: obj) -> (box x)))

let Data_Monoid_monoidUnit  = (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((box Data_Unit_unit))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box Data_Semigroup_semigroupUnit))))) Map.empty)))))))

let Data_Monoid_monoidString  = (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((box ""))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box Data_Semigroup_semigroupString))))) Map.empty)))))))

let Data_Monoid_monoidRecordNil  = (sharpurs_apply (box ((box Data_Monoid_MonoidRecordusd_Dict))) (box ((box ((Map.add "memptyRecord" (box ((box (fun (v: obj) -> (box (Map.empty)))))) (Map.add "SemigroupRecord0" (box ((box (fun (usd__unused: obj) -> (box Data_Semigroup_semigroupRecordNil))))) Map.empty)))))))

let Data_Monoid_monoidOrdering  = (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((box Data_Ordering_EQusd_Ctor))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box Data_Ordering_semigroupOrdering))))) Map.empty)))))))

let Data_Monoid_monoidArray  = (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((box [||]))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box Data_Semigroup_semigroupArray))))) Map.empty)))))))

let Data_Monoid_memptyRecord  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "memptyRecord" (unbox<Map<string, obj>> ((box v))))))))

let Data_Monoid_monoidRecord  = (box (fun (usd__unused: obj) -> (box (fun (dictMonoidRecord: obj) -> (let semigroupRecord1 = (sharpurs_apply (box ((box Data_Monoid_semigroupRecord))) (box ((sharpurs_apply (box ((Map.find "SemigroupRecord0" (unbox<Map<string, obj>> ((box dictMonoidRecord)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Monoid_memptyRecord))) (box ((box dictMonoidRecord)))))) (box ((box Type_Proxy_Proxyusd_Ctor)))))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box semigroupRecord1))))) Map.empty))))))))))))

let Data_Monoid_mempty  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "mempty" (unbox<Map<string, obj>> ((box v))))))))

let Data_Monoid_monoidFn  = (box (fun (dictMonoid: obj) -> (let semigroupFn = (sharpurs_apply (box ((box Data_Semigroup_semigroupFn))) (box ((sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined))))))) in (sharpurs_apply (box ((box Data_Monoid_Monoidusd_Dict))) (box ((box ((Map.add "mempty" (box ((box (fun (v: obj) -> (sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid)))))))) (Map.add "Semigroup0" (box ((box (fun (usd__unused: obj) -> (box semigroupFn))))) Map.empty))))))))))

let Data_Monoid_monoidRecordCons  = (box (fun (dictIsSymbol: obj) -> (let semigroupRecordCons = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_semigroupRecordCons))) (box ((box dictIsSymbol)))))) (box ((box Prim_undefined)))) in (box (fun (dictMonoid: obj) -> (let mempty1 = (sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid)))) in let Semigroup0 = (sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined)))) in (box (fun (usd__unused: obj) -> (box (fun (dictMonoidRecord: obj) -> (let semigroupRecordCons1 = (sharpurs_apply (box ((sharpurs_apply (box ((box semigroupRecordCons))) (box ((sharpurs_apply (box ((Map.find "SemigroupRecord0" (unbox<Map<string, obj>> ((box dictMonoidRecord)))))) (box ((box Prim_undefined))))))))) (box ((box Semigroup0)))) in (sharpurs_apply (box ((box Data_Monoid_MonoidRecordusd_Dict))) (box ((box ((Map.add "memptyRecord" (box ((box (fun (v: obj) -> (let tail = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Monoid_memptyRecord))) (box ((box dictMonoidRecord)))))) (box ((box Type_Proxy_Proxyusd_Ctor)))) in let key = (sharpurs_apply (box ((sharpurs_apply (box ((box Data_Symbol_reflectSymbol))) (box ((box dictIsSymbol)))))) (box ((box Type_Proxy_Proxyusd_Ctor)))) in let insert = (sharpurs_apply (box ((box Record_Unsafe_unsafeSet))) (box ((box key)))) in (sharpurs_apply (box ((sharpurs_apply (box ((box insert))) (box ((box mempty1)))))) (box ((box tail))))))))) (Map.add "SemigroupRecord0" (box ((box (fun (usd__unused: obj) -> (box semigroupRecordCons1))))) Map.empty))))))))))))))))))

let Data_Monoid_power  = (box (fun (dictMonoid: obj) -> (let mempty1 = (sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid)))) in let Semigroup0 = (sharpurs_apply (box ((Map.find "Semigroup0" (unbox<Map<string, obj>> ((box dictMonoid)))))) (box ((box Prim_undefined)))) in (box (fun (x: obj) -> (
                                                                                                                                                                                                        
                                                                                                                                                                                                        let rec go_tco (p: obj) : obj = ((match ((unbox ((box p)))) with | p1 when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Ord_lessThanOrEq))) (box ((box Data_Ord_ordInt)))))) (box ((box p1)))))) (box ((box 0))))) -> ((box mempty1)) | p1 when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Eq_eqInt)))))) (box ((box p1)))))) (box ((box 1))))) -> ((box x)) | p1 when (unbox (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Eq_eq))) (box ((box Data_Eq_eqInt)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_EuclideanRing_mod))) (box ((box Data_EuclideanRing_euclideanRingInt)))))) (box ((box p1)))))) (box ((box 2))))))))) (box ((box 0))))) -> ((let x_prime = (go_tco ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_EuclideanRing_div))) (box ((box Data_EuclideanRing_euclideanRingInt)))))) (box ((box p1)))))) (box ((box 2)))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Semigroup0)))))) (box ((box x_prime)))))) (box ((box x_prime)))))) | p1 when (unbox (box Data_Boolean_otherwise)) -> ((let x_prime = (go_tco ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_EuclideanRing_div))) (box ((box Data_EuclideanRing_euclideanRingInt)))))) (box ((box p1)))))) (box ((box 2)))))) in (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Semigroup0)))))) (box ((box x_prime)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Semigroup_append))) (box ((box Semigroup0)))))) (box ((box x_prime)))))) (box ((box x))))))))))) 
                                                                                                                                                                                                        and go = box ((fun (p: obj) -> go_tco p)) 
                                                                                                                                                                                                        in
                                                                                                                                                                                                        (box go)
                                                                                                                                                                                                        ))))))

let Data_Monoid_guard  = (box (fun (dictMonoid: obj) -> (let mempty1 = (sharpurs_apply (box ((box Data_Monoid_mempty))) (box ((box dictMonoid)))) in (box (fun (v: obj) -> (box (fun (v1: obj) -> (match (((unbox ((box v))), (unbox ((box v1))))) with | (LitBool true (), a) -> ((box a)) | (LitBool false (), _) -> ((box mempty1))))))))))
