[<AutoOpen>]
module PureScript_Data_Char_Gen

open System
open System.Collections.Generic

let Data_Char_Gen_foldable1NonEmpty  = (sharpurs_apply (box ((box Data_NonEmpty_foldable1NonEmpty))) (box ((box Data_Foldable_foldableArray))))

let Data_Char_Gen_genUnicodeChar  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Enum_toEnumWithDefaults))) (box ((box Data_Enum_boundedEnumChar)))))) (box ((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Data_Bounded_boundedChar))))))))) (box ((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box Data_Bounded_boundedChar)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 0)))))) (box ((box 65536)))))))))

let Data_Char_Gen_genDigitChar  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Enum_toEnumWithDefaults))) (box ((box Data_Enum_boundedEnumChar)))))) (box ((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Data_Bounded_boundedChar))))))))) (box ((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box Data_Bounded_boundedChar)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 48)))))) (box ((box 57)))))))))

let Data_Char_Gen_genAsciiChar_prime  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Enum_toEnumWithDefaults))) (box ((box Data_Enum_boundedEnumChar)))))) (box ((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Data_Bounded_boundedChar))))))))) (box ((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box Data_Bounded_boundedChar)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 0)))))) (box ((box 127)))))))))

let Data_Char_Gen_genAsciiChar  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Enum_toEnumWithDefaults))) (box ((box Data_Enum_boundedEnumChar)))))) (box ((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Data_Bounded_boundedChar))))))))) (box ((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box Data_Bounded_boundedChar)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 32)))))) (box ((box 127)))))))))

let Data_Char_Gen_genAlphaUppercase  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Enum_toEnumWithDefaults))) (box ((box Data_Enum_boundedEnumChar)))))) (box ((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Data_Bounded_boundedChar))))))))) (box ((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box Data_Bounded_boundedChar)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 65)))))) (box ((box 90)))))))))

let Data_Char_Gen_genAlphaLowercase  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Functor_map))) (box ((sharpurs_apply (box ((Map.find "Functor0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Apply0" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Bind1" (unbox<Map<string, obj>> ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box dictMonadGen)))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((box Prim_undefined))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Data_Enum_toEnumWithDefaults))) (box ((box Data_Enum_boundedEnumChar)))))) (box ((sharpurs_apply (box ((box Data_Bounded_bottom))) (box ((box Data_Bounded_boundedChar))))))))) (box ((sharpurs_apply (box ((box Data_Bounded_top))) (box ((box Data_Bounded_boundedChar)))))))))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_Class_chooseInt))) (box ((box dictMonadGen)))))) (box ((box 97)))))) (box ((box 122)))))))))

let Data_Char_Gen_genAlpha  = (box (fun (dictMonadGen: obj) -> (sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Gen_oneOf))) (box ((box dictMonadGen)))))) (box ((box Data_Char_Gen_foldable1NonEmpty)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box ((fun (usd__arg1: obj) -> (fun (usd__arg2: obj) -> (box (Data_NonEmpty_NonEmptyusd_Ctor(usd__arg1, usd__arg2))))))))) (box ((sharpurs_apply (box ((box Data_Char_Gen_genAlphaLowercase))) (box ((box dictMonadGen))))))))) (box ((box [|(sharpurs_apply (box ((box Data_Char_Gen_genAlphaUppercase))) (box ((box dictMonadGen))))|])))))))))
