[<AutoOpen>]
module PureScript_Effect_Aff_Class

open System
open System.Collections.Generic

let Effect_Aff_Class_lift  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_Cont_Trans_monadTransContT))))

let Effect_Aff_Class_lift1  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_Except_Trans_monadTransExceptT))))

let Effect_Aff_Class_lift2  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_List_Trans_monadTransListT))))

let Effect_Aff_Class_lift3  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_Maybe_Trans_monadTransMaybeT))))

let Effect_Aff_Class_lift4  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_Reader_Trans_monadTransReaderT))))

let Effect_Aff_Class_lift5  = (sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((box Control_Monad_State_Trans_monadTransStateT))))

let Effect_Aff_Class_MonadAffusd_Dict  = (box (fun (x: obj) -> (box x)))

let Effect_Aff_Class_monadAffAff  = (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((box Control_Category_identity))) (box ((box Control_Category_categoryFn)))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box Effect_Aff_monadEffectAff))))) Map.empty)))))))

let Effect_Aff_Class_liftAff  = (box (fun (dict: obj) -> (match ((unbox ((box dict)))) with | v -> ((Map.find "liftAff" (unbox<Map<string, obj>> ((box v))))))))

let Effect_Aff_Class_monadAffContT  = (box (fun (dictMonadAff: obj) -> (let MonadEffect0 = (sharpurs_apply (box ((Map.find "MonadEffect0" (unbox<Map<string, obj>> ((box dictMonadAff)))))) (box ((box Prim_undefined)))) in let monadEffectContT = (sharpurs_apply (box ((box Control_Monad_Cont_Trans_monadEffectContT))) (box ((box MonadEffect0)))) in (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_lift))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadEffect0)))))) (box ((box Prim_undefined)))))))))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_liftAff))) (box ((box dictMonadAff))))))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box monadEffectContT))))) Map.empty))))))))))

let Effect_Aff_Class_monadAffExceptT  = (box (fun (dictMonadAff: obj) -> (let MonadEffect0 = (sharpurs_apply (box ((Map.find "MonadEffect0" (unbox<Map<string, obj>> ((box dictMonadAff)))))) (box ((box Prim_undefined)))) in let monadEffectExceptT = (sharpurs_apply (box ((box Control_Monad_Except_Trans_monadEffectExceptT))) (box ((box MonadEffect0)))) in (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_lift1))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadEffect0)))))) (box ((box Prim_undefined)))))))))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_liftAff))) (box ((box dictMonadAff))))))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box monadEffectExceptT))))) Map.empty))))))))))

let Effect_Aff_Class_monadAffListT  = (box (fun (dictMonadAff: obj) -> (let MonadEffect0 = (sharpurs_apply (box ((Map.find "MonadEffect0" (unbox<Map<string, obj>> ((box dictMonadAff)))))) (box ((box Prim_undefined)))) in let monadEffectListT = (sharpurs_apply (box ((box Control_Monad_List_Trans_monadEffectListT))) (box ((box MonadEffect0)))) in (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_lift2))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadEffect0)))))) (box ((box Prim_undefined)))))))))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_liftAff))) (box ((box dictMonadAff))))))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box monadEffectListT))))) Map.empty))))))))))

let Effect_Aff_Class_monadAffMaybe  = (box (fun (dictMonadAff: obj) -> (let MonadEffect0 = (sharpurs_apply (box ((Map.find "MonadEffect0" (unbox<Map<string, obj>> ((box dictMonadAff)))))) (box ((box Prim_undefined)))) in let monadEffectMaybe = (sharpurs_apply (box ((box Control_Monad_Maybe_Trans_monadEffectMaybe))) (box ((box MonadEffect0)))) in (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_lift3))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadEffect0)))))) (box ((box Prim_undefined)))))))))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_liftAff))) (box ((box dictMonadAff))))))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box monadEffectMaybe))))) Map.empty))))))))))

let Effect_Aff_Class_monadAffRWS  = (box (fun (dictMonadAff: obj) -> (let MonadEffect0 = (sharpurs_apply (box ((Map.find "MonadEffect0" (unbox<Map<string, obj>> ((box dictMonadAff)))))) (box ((box Prim_undefined)))) in let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadEffect0)))))) (box ((box Prim_undefined)))) in let liftAff1 = (sharpurs_apply (box ((box Effect_Aff_Class_liftAff))) (box ((box dictMonadAff)))) in (box (fun (dictMonoid: obj) -> (let monadEffectRWS = (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_RWS_Trans_monadEffectRWS))) (box ((box dictMonoid)))))) (box ((box MonadEffect0)))) in (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((sharpurs_apply (box ((box Control_Monad_RWS_Trans_monadTransRWST))) (box ((box dictMonoid))))))))) (box ((box Monad0))))))))) (box ((box liftAff1)))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box monadEffectRWS))))) Map.empty)))))))))))))

let Effect_Aff_Class_monadAffReader  = (box (fun (dictMonadAff: obj) -> (let MonadEffect0 = (sharpurs_apply (box ((Map.find "MonadEffect0" (unbox<Map<string, obj>> ((box dictMonadAff)))))) (box ((box Prim_undefined)))) in let monadEffectReader = (sharpurs_apply (box ((box Control_Monad_Reader_Trans_monadEffectReader))) (box ((box MonadEffect0)))) in (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_lift4))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadEffect0)))))) (box ((box Prim_undefined)))))))))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_liftAff))) (box ((box dictMonadAff))))))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box monadEffectReader))))) Map.empty))))))))))

let Effect_Aff_Class_monadAffState  = (box (fun (dictMonadAff: obj) -> (let MonadEffect0 = (sharpurs_apply (box ((Map.find "MonadEffect0" (unbox<Map<string, obj>> ((box dictMonadAff)))))) (box ((box Prim_undefined)))) in let monadEffectState = (sharpurs_apply (box ((box Control_Monad_State_Trans_monadEffectState))) (box ((box MonadEffect0)))) in (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_lift5))) (box ((sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadEffect0)))))) (box ((box Prim_undefined)))))))))))) (box ((sharpurs_apply (box ((box Effect_Aff_Class_liftAff))) (box ((box dictMonadAff))))))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box monadEffectState))))) Map.empty))))))))))

let Effect_Aff_Class_monadAffWriter  = (box (fun (dictMonadAff: obj) -> (let MonadEffect0 = (sharpurs_apply (box ((Map.find "MonadEffect0" (unbox<Map<string, obj>> ((box dictMonadAff)))))) (box ((box Prim_undefined)))) in let Monad0 = (sharpurs_apply (box ((Map.find "Monad0" (unbox<Map<string, obj>> ((box MonadEffect0)))))) (box ((box Prim_undefined)))) in let liftAff1 = (sharpurs_apply (box ((box Effect_Aff_Class_liftAff))) (box ((box dictMonadAff)))) in (box (fun (dictMonoid: obj) -> (let monadEffectWriter = (sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Writer_Trans_monadEffectWriter))) (box ((box dictMonoid)))))) (box ((box MonadEffect0)))) in (sharpurs_apply (box ((box Effect_Aff_Class_MonadAffusd_Dict))) (box ((box ((Map.add "liftAff" (box ((sharpurs_apply (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Semigroupoid_compose))) (box ((box Control_Semigroupoid_semigroupoidFn)))))) (box ((sharpurs_apply (box ((sharpurs_apply (box ((box Control_Monad_Trans_Class_lift))) (box ((sharpurs_apply (box ((box Control_Monad_Writer_Trans_monadTransWriterT))) (box ((box dictMonoid))))))))) (box ((box Monad0))))))))) (box ((box liftAff1)))))) (Map.add "MonadEffect0" (box ((box (fun (usd__unused: obj) -> (box monadEffectWriter))))) Map.empty)))))))))))))
