% Generated by purerl version 0.0.24
-module(data_maybe@ps).
-export(['Nothing'/0, 'Just'/0, showMaybe/0, semigroupMaybe/1, semigroupMaybe/0, optional/0, optional/3, optional/2, monoidMaybe/0, 'maybe\''/3, 'maybe\''/0, 'maybe'/3, 'maybe'/0, isNothing/0, isNothing/1, isJust/0, isJust/1, genericMaybe/0, functorMaybe/0, invariantMaybe/0, 'fromMaybe\''/0, 'fromMaybe\''/2, fromMaybe/0, fromMaybe/2, fromJust/2, fromJust/0, fromJust/1, extendMaybe/0, eqMaybe/1, eqMaybe/0, ordMaybe/1, ordMaybe/0, eq1Maybe/0, ord1Maybe/0, boundedMaybe/0, applyMaybe/0, bindMaybe/0, applicativeMaybe/0, monadMaybe/0, altMaybe/0, plusMaybe/0, alternativeMaybe/0, monadZeroMaybe/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./data_maybe.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 0).
-spec append() -> any().
append() -> (?MEMOIZE((data_semigroup@ps:append((data_semigroup@ps:semigroupString()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 0).
-spec append(any(),any()) -> any().
append(_@2,_@3) -> (((append())(_@2))(_@3)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 0).
-spec identity() -> any().
identity() -> (?MEMOIZE((control_category@ps:identity((control_category@ps:categoryFn()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 19).
-spec 'Nothing'() -> any().
'Nothing'() -> { nothing }.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 19).
-spec 'Just'() -> any().
'Just'() -> fun (Value0) ->
  { just, Value0 }
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 216).
-spec showMaybe() -> any().
showMaybe() -> fun (DictShow) ->
  Show@92 = (?MEMOIZE((data_show@ps:show(DictShow)))),
  #{show=>fun (V) ->
    case V of
      ({ just, _@4 }) -> (append(<<"(Just "/utf8>>, (append((Show@92(_@4)), <<")"/utf8>>))));
      ({ nothing }) -> <<"Nothing"/utf8>>
    end
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 185).
-spec semigroupMaybe(any()) -> any().
semigroupMaybe(_@9) -> 
  Append1@93 = (?MEMOIZE((data_semigroup@ps:append(_@9)))),
  #{append=>fun (V) ->
    fun (V1) ->
      case { V, V1 } of
        ({ { nothing }, _@10 }) -> _@10;
        ({ _@11, { nothing } }) -> _@11;
        ({ { just, _@12 }, { just, _@13 } }) -> { just, ((Append1@93(_@12))(_@13)) }
      end
    end
  end}
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 185).
-spec semigroupMaybe() -> any().
semigroupMaybe() -> fun (_@14) ->
  (semigroupMaybe(_@14))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 304).
-spec optional() -> fun((any()) -> fun((any()) -> fun((any()) -> any()))).
optional() -> fun (DictAlt) ->
  Alt@94 = (?MEMOIZE((control_alt@ps:alt(DictAlt)))),
  Map1@95 = (?MEMOIZE((data_functor@ps:map(((maps:get('Functor0', DictAlt))(undefined)))))),
  fun (DictApplicative) ->
    Pure@96 = (?MEMOIZE((control_applicative@ps:pure(DictApplicative)))),
    fun (A) ->
      ((Alt@94(((Map1@95(('Just'())))(A))))((Pure@96({ nothing }))))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 304).
-spec optional(any(),any(),any()) -> any().
optional(_@18,_@19,_@20) -> ((((optional())(_@18))(_@19))(_@20)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 304).
-spec optional(any(),any()) -> any().
optional(_@15,_@16) -> 
  Alt@98 = (?MEMOIZE((control_alt@ps:alt(_@15)))),
  Map1@99 = (?MEMOIZE((data_functor@ps:map(((maps:get('Functor0', _@15))(undefined)))))),
  Pure@97@100 = (?MEMOIZE((control_applicative@ps:pure(_@16)))),
  fun (A) ->
    ((Alt@98(((Map1@99(('Just'())))(A))))((Pure@97@100({ nothing }))))
  end
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 190).
-spec monoidMaybe() -> any().
monoidMaybe() -> fun (DictSemigroup) ->
  SemigroupMaybe1@101 = (?MEMOIZE((semigroupMaybe(DictSemigroup)))),
  #{mempty=>{ nothing }, 'Semigroup0'=>fun (_) ->
    SemigroupMaybe1@101
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 243).
-spec 'maybe\''(fun((any()) -> any()),fun((any()) -> any()),data_maybe_Maybe(any())) -> any().
'maybe\''(_@24,_@25,_@26) -> case { _@24, _@25, _@26 } of
  ({ _@27, _, { nothing } }) -> (_@27(unit));
  ({ _, _@28, { just, _@29 } }) -> (_@28(_@29))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 243).
-spec 'maybe\''() -> fun((fun((any()) -> any())) -> fun((fun((any()) -> any())) -> fun((data_maybe_Maybe(any())) -> any()))).
'maybe\''() -> fun (_@30) ->
  fun (_@31) ->
    fun (_@32) ->
      ('maybe\''(_@30, _@31, _@32))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 230).
-spec 'maybe'(any(),fun((any()) -> any()),data_maybe_Maybe(any())) -> any().
'maybe'(_@36,_@37,_@38) -> case { _@36, _@37, _@38 } of
  ({ _@39, _, { nothing } }) -> _@39;
  ({ _, _@40, { just, _@41 } }) -> (_@40(_@41))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 230).
-spec 'maybe'() -> fun((any()) -> fun((fun((any()) -> any())) -> fun((data_maybe_Maybe(any())) -> any()))).
'maybe'() -> fun (_@42) ->
  fun (_@43) ->
    fun (_@44) ->
      ('maybe'(_@42, _@43, _@44))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 275).
-spec isNothing() -> fun((data_maybe_Maybe(any())) -> boolean()).
isNothing() -> ((('maybe'())(true))(((data_function@ps:const())(false)))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 275).
-spec isNothing(data_maybe_Maybe(any())) -> boolean().
isNothing(_@46) -> ((isNothing())(_@46)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 271).
-spec isJust() -> fun((data_maybe_Maybe(any())) -> boolean()).
isJust() -> ((('maybe'())(false))(((data_function@ps:const())(true)))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 271).
-spec isJust(data_maybe_Maybe(any())) -> boolean().
isJust(_@48) -> ((isJust())(_@48)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 220).
-spec genericMaybe() -> any().
genericMaybe() -> #{to=>fun (X) ->
  case X of
    ({ inl, _ }) -> { nothing };
    ({ inr, _@49 }) -> { just, _@49 }
  end
end, from=>fun (X) ->
  case X of
    ({ nothing }) -> { inl, { noArguments } };
    ({ just, _@50 }) -> { inr, _@50 }
  end
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 33).
-spec functorMaybe() -> any().
functorMaybe() -> #{map=>fun (V) ->
  fun (V1) ->
    case { V, V1 } of
      ({ _@51, { just, _@52 } }) -> { just, (_@51(_@52)) };
      ({ _, _ }) -> { nothing }
    end
  end
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 0).
-spec map() -> any().
map() -> (?MEMOIZE((data_functor@ps:map((functorMaybe()))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 0).
-spec map(any(),any()) -> any().
map(_@55,_@56) -> (((map())(_@55))(_@56)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 171).
-spec invariantMaybe() -> any().
invariantMaybe() -> #{imap=>(?MEMOIZE((data_functor_invariant@ps:imapF((functorMaybe())))))}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 267).
-spec 'fromMaybe\''() -> fun((fun((any()) -> any())) -> fun((data_maybe_Maybe(any())) -> any())).
'fromMaybe\''() -> fun (A) ->
  ((('maybe\''())(A))((identity())))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 267).
-spec 'fromMaybe\''(fun((any()) -> any()),data_maybe_Maybe(any())) -> any().
'fromMaybe\''(_@59,_@60) -> ((('fromMaybe\''())(_@59))(_@60)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 255).
-spec fromMaybe() -> fun((any()) -> fun((data_maybe_Maybe(any())) -> any())).
fromMaybe() -> fun (A) ->
  ((('maybe'())(A))((identity())))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 255).
-spec fromMaybe(any(),data_maybe_Maybe(any())) -> any().
fromMaybe(_@63,_@64) -> (((fromMaybe())(_@63))(_@64)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 281).
-spec fromJust(any(),data_maybe_Maybe(any())) -> any().
fromJust(_@66,_@67) -> (fun (_) ->
  case _@67 of
    ({ just, _@69 }) -> _@69
  end
end(undefined)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 281).
-spec fromJust() -> fun((any()) -> fun((data_maybe_Maybe(any())) -> any())).
fromJust() -> fun (_@70) ->
  fun (_@71) ->
    (fromJust(_@70, _@71))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 281).
-spec fromJust(any()) -> any().
fromJust(_@66) -> fun (V) ->
  (fun (_) ->
    case V of
      ({ just, _@68 }) -> _@68
    end
  end(undefined))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 167).
-spec extendMaybe() -> any().
extendMaybe() -> #{extend=>fun (V) ->
  fun (V1) ->
    case { V, V1 } of
      ({ _, { nothing } }) -> { nothing };
      ({ _@72, _@73 }) -> { just, (_@72(_@73)) }
    end
  end
end, 'Functor0'=>fun (_) ->
  (functorMaybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 196).
-spec eqMaybe(any()) -> any().
eqMaybe(_@76) -> 
  Eq@102 = (?MEMOIZE((data_eq@ps:eq(_@76)))),
  #{eq=>fun (X) ->
    fun (Y) ->
      case { X, Y } of
        ({ { nothing }, { nothing } }) -> true;
        ({ { just, _@77 }, { just, _@78 } }) -> ((Eq@102(_@77))(_@78));
        ({ _, _ }) -> false
      end
    end
  end}
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 196).
-spec eqMaybe() -> any().
eqMaybe() -> fun (_@79) ->
  (eqMaybe(_@79))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 205).
-spec ordMaybe(any()) -> any().
ordMaybe(_@82) -> 
  Compare@103 = (?MEMOIZE((data_ord@ps:compare(_@82)))),
  EqMaybe1@104 = (?MEMOIZE((eqMaybe(((maps:get('Eq0', _@82))(undefined)))))),
  #{compare=>fun (X) ->
    fun (Y) ->
      case { X, Y } of
        ({ { nothing }, { nothing } }) -> { eQ };
        ({ { nothing }, _ }) -> { lT };
        ({ _, { nothing } }) -> { gT };
        ({ { just, _@83 }, { just, _@84 } }) -> ((Compare@103(_@83))(_@84))
      end
    end
  end, 'Eq0'=>fun (_) ->
    EqMaybe1@104
  end}
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 205).
-spec ordMaybe() -> any().
ordMaybe() -> fun (_@85) ->
  (ordMaybe(_@85))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 198).
-spec eq1Maybe() -> any().
eq1Maybe() -> #{eq1=>fun (DictEq) ->
  (?MEMOIZE((data_eq@ps:eq((?MEMOIZE((eqMaybe(DictEq))))))))
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 207).
-spec ord1Maybe() -> any().
ord1Maybe() -> #{compare1=>fun (DictOrd) ->
  (?MEMOIZE((data_ord@ps:compare((?MEMOIZE((ordMaybe(DictOrd))))))))
end, 'Eq10'=>fun (_) ->
  (eq1Maybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 209).
-spec boundedMaybe() -> any().
boundedMaybe() -> fun (DictBounded) ->
  OrdMaybe1@105 = (?MEMOIZE((ordMaybe(((maps:get('Ord0', DictBounded))(undefined)))))),
  #{top=>{ just, (?MEMOIZE((data_bounded@ps:top(DictBounded)))) }, bottom=>{ nothing }, 'Ord0'=>fun (_) ->
    OrdMaybe1@105
  end}
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 68).
-spec applyMaybe() -> any().
applyMaybe() -> #{apply=>fun (V) ->
  fun (V1) ->
    case { V, V1 } of
      ({ { just, _@86 }, _@87 }) -> (map(_@86, _@87));
      ({ { nothing }, _ }) -> { nothing }
    end
  end
end, 'Functor0'=>fun (_) ->
  (functorMaybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 126).
-spec bindMaybe() -> any().
bindMaybe() -> #{bind=>fun (V) ->
  fun (V1) ->
    case { V, V1 } of
      ({ { just, _@88 }, _@89 }) -> (_@89(_@88));
      ({ { nothing }, _ }) -> { nothing }
    end
  end
end, 'Apply0'=>fun (_) ->
  (applyMaybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 91).
-spec applicativeMaybe() -> any().
applicativeMaybe() -> #{pure=>('Just'()), 'Apply0'=>fun (_) ->
  (applyMaybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 155).
-spec monadMaybe() -> any().
monadMaybe() -> #{'Applicative0'=>fun (_) ->
  (applicativeMaybe())
end, 'Bind1'=>fun (_) ->
  (bindMaybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 103).
-spec altMaybe() -> any().
altMaybe() -> #{alt=>fun (V) ->
  fun (V1) ->
    case { V, V1 } of
      ({ { nothing }, _@90 }) -> _@90;
      ({ _@91, _ }) -> _@91
    end
  end
end, 'Functor0'=>fun (_) ->
  (functorMaybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 112).
-spec plusMaybe() -> any().
plusMaybe() -> #{empty=>{ nothing }, 'Alt0'=>fun (_) ->
  (altMaybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 117).
-spec alternativeMaybe() -> any().
alternativeMaybe() -> #{'Applicative0'=>fun (_) ->
  (applicativeMaybe())
end, 'Plus1'=>fun (_) ->
  (plusMaybe())
end}.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/.spago/p/maybe/8e96ca0187208e78e8df6a464c281850e5c9400c/src/Data/Maybe.purs", 157).
-spec monadZeroMaybe() -> any().
monadZeroMaybe() -> #{'Monad0'=>fun (_) ->
  (monadMaybe())
end, 'Alternative1'=>fun (_) ->
  (alternativeMaybe())
end, 'MonadZeroIsDeprecated2'=>fun (_) ->
  undefined
end}.
