// Generated by purs version 0.15.16
import * as Bench from "../Bench/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Effect from "../Effect/index.js";
import * as Test_Records from "../Test.Records/index.js";
var main = /* #__PURE__ */ Data_Functor["void"](Effect.functorEffect)(/* #__PURE__ */ Bench.runBench(Test_Records.describe)(Test_Records.act));
export {
    main
};
//# sourceMappingURL=index.js.map
